### ISSUE TITLE
Group config support

### ISSUE THREAD

**Issue by hgelpke** [danielwelch/hassio-zigbee2mqtt#100]
I'm sure I'm missing something simple, but what is the syntax to add groups to the hass.io addon?

I see this in the Zigbee2Mqtt documentation but with the added " in the hass.io addon, I'm missing something in the formatting:

groups:
  '1':
    friendly_name: group_1

How do I make this Hass.io friendly?

**Comment by danielwelch** [comment]
At the moment, configuring groups via the front end isn’t supported, but you can manually edit your configuration file. I’ll look to include support for front end configuration once it’s stabilized (maybe it already is? But I see the tracking issue is still open)

**Comment by danielwelch** [comment]
https://github.com/danielwelch/hassio-zigbee2mqtt/blob/master/README.md#modifying-zigbee2mqtts-configurationyaml
