### ISSUE TITLE
Xiaomi smoke voltage and linkquality not visible in HA

### ISSUE THREAD

**Issue by KoumaMisna** [danielwelch/hassio-zigbee2mqtt#102]
So got zigbee2mqtt working and my first device connected which is the Xiaomi/Honeywell smoke detector.

The log says that they are not supported but still it works:
`zigbee2mqtt:warn 2019-2-3 12:02:12 Device with modelID 'undefined' is not supported.`

Still I have the state and battery percentage visible in HA but not battery voltage and signal strength.

However I can see them in the zigbee2mqtt log:
`zigbee2mqtt:info 2019-2-3 13:43:49 MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":126}'`

And here is the log from pairing:
`zigbee2mqtt:info 2019-2-3 12:02:16 MQTT publish: topic 'homeassistant/sensor/0x00158d0002527271/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x00158d0002527271","json_attributes_topic":"zigbee2mqtt/0x00158d0002527271","name":"0x00158d0002527271_battery","unique_id":"0x00158d0002527271_battery_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d0002527271","name":"0x00158d0002527271","sw_version":"Zigbee2mqtt 1.1.0","model":"MiJia Honeywell smoke detector (JTYJ-GD-01LM/BW)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'`

**Comment by peppekerstens** [comment]
hassio: v0.84.6
mosquitto: v1.4.15
zigbee2mqtt: v1.1.0.1
CC2531 firmware: 20181024

Working just fine with above version(s) installed:
  zigbee2mqtt:info 2019-2-3 08:56:52 MQTT publish: topic 'homeassistant/binary_sensor/0x00158d0002xxxxxx/smoke/config', payload '{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.smoke }}","device_class":"smoke","state_topic":"zigbee2mqtt/0x00158d0002xxxxxx","json_attributes_topic":"zigbee2mqtt/0x00158d0002xxxxxx","name":"0x00158d0002xxxxxx_smoke","unique_id":"0x00158d0002xxxxxx_smoke_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d0002xxxxxx","name":"0x00158d0002xxxxxx","sw_version":"Zigbee2mqtt 1.1.0","model":"MiJia Honeywell smoke detector (JTYJ-GD-01LM/BW)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 2019-2-3 08:56:52 MQTT publish: topic 'homeassistant/sensor/0x00158d0002xxxxxx/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x00158d0002xxxxxx","json_attributes_topic":"zigbee2mqtt/0x00158d0002xxxxxx","name":"0x00158d0002xxxxxx_battery","unique_id":"0x00158d0002xxxxxx_battery_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d0002xxxxxx","name":"0x00158d0002xxxxxx","sw_version":"Zigbee2mqtt 1.1.0","model":"MiJia Honeywell smoke detector (JTYJ-GD-01LM/BW)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 2019-2-3 15:05:23 MQTT publish: topic 'zigbee2mqtt/0x00158d0002xxxxxx', payload '{"smoke":false,"linkquality":18,"battery":100,"voltage":3065}'

<img width="277" alt="2019-02-03 15_33_55-home assistant" src="https://user-images.githubusercontent.com/13161629/52178037-854f7e80-27c9-11e9-942b-957fa135d750.png">


Please check your versions and config...

**Comment by KoumaMisna** [comment]
Hi!

My versions:
hassio: v0.86.3
mosquitto: didn't find the version but the newest addon
zigbee2mqtt: v1.1.0
CC2531 firmware: 20181024

Zigbee2mqtt config:
`{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.10.21:1883",
  "serial_port": "/dev/ttyACM1",
  "devices": [],
  "network_key": [],
  "mqtt_user": "user",
  "mqtt_pass": "pass"
}`

**Comment by danielwelch** [comment]
Like the issue template and docs explain, this issue more than likely belongs in the zigbee2mqtt issue tracker

**Comment by KoumaMisna** [comment]
Hi!

Thanks this was a pairing issue and is now fixed.

But still I don't see battery voltage and signal strength in HA. Is it just a fault in MQTT autodiscovery? Should I generate the sensors manually in configuration.yaml?

**Comment by itobey** [comment]
@KoumaMisna 
I think you already figured it out, but for anyone else stumbling across this issue: I had the same problem with no values beeing shown in HA. The issue solved itself for me, after I set the sensitivity (which was unset when paired, at least according to the Zigbee2Mqtt UI). Just a simple click on "high" in the UI solved the issue for me.
