### ISSUE TITLE
Deleting entity

### ISSUE THREAD

**Issue by nick9one1** [danielwelch/hassio-zigbee2mqtt#107]
I dont seem to be able to delete a paired device, is this possible without wiping Zigbee2MQTT?

**Comment by cela96** [comment]
Yes, it is possible just use

`zigbee2mqtt/bridge/config/remove`
Allows you to remove devices from the network. Payload should be the friendly_name, e.g. `0x00158d0001b79111`. On successful remove a `device_removed` message is send.

In the services page select `mqtt.publish` and send
{
  "topic": "zigbee2mqtt/bridge/config/remove",
  "payload": "`your_code`"
}

https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html

**Comment by danielwelch** [comment]
I’ll close this as it’s been answered and probably belongs in zigbee2mqtt anyway
