### ISSUE TITLE
WXKG11LM Xiaomi Aqura clicks only reset after 10 minutes (possibly generic issue)

### ISSUE THREAD

**Issue by ekaats** [danielwelch/hassio-zigbee2mqtt#109]
Recently I have received some Xiaomi/Aquara buttons. These devices are registered as sensors where the amount of presses is send as data attribute, rather than a switch with only one state.
However, I noticed that the reported state is only reset after 10 minutes in Home Assistant. When imputing a different amount of keypresses, it changes to that state.

**So, current situation, when waiting:**
Press button once
-> button reports 'single' to HA
wait 10 minutes
-> button state changes to blank.

Press button three times:
-> button reports 'triple' to HA
Press button once after <10 minutes:
-> button reports 'single' to HA
wait 10 minutes
-> button state changes to blank.

From a zigbee2mqtt perspective, this is probably working as intended as it the switch is indeed pressed the reported amount of times, de-pressing the button is not part of the report as with a switch.

To me it seems the switch should report its state, after which the 'sensor' is reset (in home assistant). 

Press button three times:
-> button reports 'triple' to HA
-> button resets to blank in HA

This is probably true for all switches reporting as multi-state sensors. Is this something for this add-on or should this be done within HA?

**Comment by danielwelch** [comment]
Regardless of the answer to your question, this should be asked in the zigbee2mqtt issue tracker (the issue template gives you a link), rather than here.
