### ISSUE TITLE
Log_level debug doesn't work in edge commit #3d15129

### ISSUE THREAD

**Issue by drogfild** [danielwelch/hassio-zigbee2mqtt#113]
At least for me with Hassio addin edge commit #3d15129 log_level setting doesn't seem to have effect.
I set it to "debug" but debug messages aren't written to log.
Am I doing something wrong?

```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": true,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://homeassistant",
  "serial_port": "/dev/ttyACM1",
  "devices": [],
  "network_key": [],
  "log_level": "debug",
  "disable_led": true
}

```

PS. When is edge docker image updated? Waiting for newest version and old one is already 8 days old ;)

**Comment by deisi** [comment]
It works if you set it within the `configuration.yaml` file directly.

**Comment by drogfild** [comment]
Ok, thanks. So is this known thing in edge or a bug?

**Comment by danielwelch** [comment]
> PS. When is edge docker image updated? Waiting for newest version and old one is already 8 days old ;)

Currently working on a fix for this -- edge builds have been failing for the past week or so and I think it's due to an issue with `zigbee2mqtt`'s `npm-shwrinkwrap.json`, but still troubleshooting. After that, I'll look into this bug.

**Comment by paskyecijano** [comment]
I think the problem is that from the interface does not overwrite the configuration file.

If you modify the configuration file by hand if it takes the changes

Same issue: [https://github.com/danielwelch/hassio-zigbee2mqtt/issues/116](url)
