### ISSUE TITLE
simplify config

### ISSUE THREAD

**Issue by deisi** [danielwelch/hassio-zigbee2mqtt#114]
Another suggestion. Would you be willing to accept a PR, that is a breaking change but tries to simplify the settings.
The current approach makes use of a rather complicated `set_config.py` and parses arguments individually. E.g. `mqtt_base_topc: str` gets translated into: 
```
mqtt:
  base_topic: str
```

However, there is nothing stopping us from using this structure right away. I think of something like:
```
"options": {
    "data_path": "/share/zigbee2mqtt",
    "configuration": {
      "homeassistant": true,
      "permit_join": false,
      "mqtt": {
        "base_topic": "zigbee2mqtt",
        "server": "mqtt://homeassistant"
      }
      "serial": {
        "port": "/dev/ttyACM0"
      }
    }
  ...
}
```

The advantages are:
- `set_config.py` becomes content independent parser.
- easier to implement all options of z2m, because they only need to be defined in config.json of the addon
- clear relation between z2m options and there counterpart in the addonn. They have the same name.
- Future proof, because naming conflicts between the addon and z2m can be avoided

I think the disadvantages are:
- breaking change
- nested options (looks complicated, some people don't like it)

**Comment by danielwelch** [comment]
I much prefer the look of your proposed schema. The current setup is awkward and is mostly a remnant of a time when zigbee2mqtt configuration looked very different. Breaking change is a major drawback, but I think zigbee2mqtt is fast-moving and we make it very obvious in the changelog/release notes.

**Comment by deisi** [comment]
okay, then I will sit down and try to make a pr.

**Comment by deisi** [comment]
I'm making some progress. However the scheme I proposed can't be implemented. As can be seen [here](https://developers.home-assistant.io/docs/en/hassio_addon_config.html#options-schema) the maximum allowed depth of nested dicts is 2. What I proposed had a depth of 3 and is thus not possible. 

I therefore removed the `configuration` layer and have all zigbee2mqtt options right within the first layer. 
This makes parsing the config a little harder again, but I still think its the right way of doing it. The config parser would then just pop `data_path` and `devices` from the config and parse the rest into the configuration file.

**Comment by deisi** [comment]
okay, in general it seems to work. I have not found out how to easily pass the `pan_id` yet, since this is expected to be a hex, but maybe ints work as well. 

I was also aiming to remove the setup.py completely, but I don't know yet how to pop values from json files with jq or json2yaml. Python would be easy though. Maybe for now we stick to it and later try to get rid of unnecessary dependencies. Anyhow I'm tired. I make the pr tomorrow.

**Comment by deisi** [comment]
needs a little help on the z2m side https://github.com/Koenkk/zigbee2mqtt/issues/1148
If this is available, we should be able to get rid of `set_config.py`

**Comment by deisi** [comment]
And I put some thought into having all default options shown in the config setting vs, just show some. Pros:
- easy to find out what can be changed and how it should be changed


Cons:
- harder to manage for us, because default options cant be updated by addon after initial installation
- looks bloated for the user and might be confusing

I think by now setting all the default options is not a good idea.

**Comment by danielwelch** [comment]
@deisi would you mind testing the changes I've made to dev branch? I added a basic check for a config backup and, if one isn't found, `cp`s `$DATA_PATH/configuration.yaml`.

**Comment by deisi** [comment]
@danielwelch 
for some reason its not making a backup, but I don't find any error...
it seems any one of the two conditions is always false, even though there is a config file o.O

**Comment by deisi** [comment]
ah found the mistake
its the first test. Ther is a not too much xD

`if [[ ! -f $DATA_PATH/configuration.yaml ]]; then`

this should be 
`if [[ -f $DATA_PATH/configuration.yaml ]]; then`

because we want it to back up if there is a file and not if ther is no file.

**Comment by deisi** [comment]
@danielwelch there is a mini pr now with this.
https://github.com/danielwelch/hassio-zigbee2mqtt/pull/127

**Comment by danielwelch** [comment]
Nice, figured it was a dumb logic typo. I’ve merged this, if you could give it a test I’d appreciate it.

**Comment by deisi** [comment]
currently running. I tested if it backs up a file and does. Lights work from my point of view it is fine.

**Comment by danielwelch** [comment]
Great. I'll look to merge this in the next few days. Wondering what the best way to inform everyone about this breaking change is in addition to some README updates and the usual changelog. Despite the breaking changes, I think it's a much cleaner config interface for users and eliminating the python dependency is a huge plus.
