### ISSUE TITLE
Overwritting not working 

### ISSUE THREAD

**Issue by septeven** [danielwelch/hassio-zigbee2mqtt#116]
Hi,
I just started to use zigbee2mqtt, and the hassio addon obviously.

I'm dealing with a very annoying problem. Overwritting doesn't work - I mean anything I change in the frontend is not overwritten to the yaml file in zigbee2mqtt share folder.

I tried to add the overwrite to true in the frontend config  (even though it should be the default value), and same thing happens.

Hope someone can help to figure this out. Thanks

**Comment by danielwelch** [comment]
Sorry for the issue. Can you paste your full add-on config?

**Comment by rgruyters** [comment]
Same issue with me. I have `disable_led` set to true, but it is still on. When I view the config under `/share/zigbee2mqtt` folder I can see that `disable_led` is still false.

```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.10.193",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [
    8,
    ...,
  ],
  "log_level": "warn",
  "disable_led": true
}
```

**Comment by septeven** [comment]
```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.1.13:1883",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [ my-network-key ],
  "mqtt_user": "ggeorges_mqtt",
  "mqtt_pass": " my-mqtt-pass ",
  "last_seen": "ISO_8601"
}
```

note that I now set mqtt_server to mqtt://homeassistant.

**Comment by septeven** [comment]
```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://homeassistant",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [ my-network-key ],
  "mqtt_user": "my-mqtt_user",
  "mqtt_pass": " my-mqtt-pass ",
  "last_seen": "ISO_8601"
}
```
Note that I have now set mqtt_server to mqtt://homeassistant

**Comment by ema987** [comment]
Unfortunately I'm experiencing the same issue and I found this ticket when I was going to open one.

What you can do in the meantime is:

- stop the plugin from running
- go to _/share/zigbee2mqtt_ (the default _data_path_, or the _data_path_ you chose if you changed it) and delete the _configuration.yaml_ file.
- restart the plugin (a new _configuration.yaml_ will be created with the settings you have in the frontend)

It seems that _configuration.yaml_ is not overwritten with the new settings you put in the front-end. It seems previously undefined options are added to _configuration.yaml_, but already present ones are not overwritten.

**Comment by danielwelch** [comment]
Thanks for the workaround @ema987 . This is likely a bug in the implementation of the overwrite functionality in `set_config.py` and probably an easy fix, but unfortunately I'm traveling and haven't had time to look into it. I will try to fix it this weekend. 

Just so everyone is aware, we're looking at overhauling the configuration structure (see #117) to make things easier to maintain and simpler for users. This restructuring will probably remove the overwrite option altogether.

**Comment by timdj** [comment]
@danielwelch Might have to do with this
`./run.sh: line 10:    12 Segmentation fault      (core dumped) python3 set_config.py "$CONFIG_PATH" "$DATA_PATH"`

That's the first line of log after starting zigbee2mqtt in home assistant.

**Comment by paskyecijano** [comment]
I have the same error, the overwritten don't work in the frontend

Any solutions?

**Comment by Routout** [comment]
I have also this same error when trying to start zigbee2mqtt on hass.io and can't get it working, also zigbee2mqtt folder isn't created in /share on installation.

`./run.sh: line 10: 12 Segmentation fault (core dumped) python3 set_config.py "$CONFIG_PATH" "$DATA_PATH"`
