### ISSUE TITLE
Allow config to be in config folder

### ISSUE THREAD

**Issue by TheZoker** [danielwelch/hassio-zigbee2mqtt#119]
One thing I like about the ESPHome addon for hassio is, that it stores the config directly in the configuration folder. 

So my suggestions would be to also allow users to have their config in `config/zigbee2mqtt` instead of the `share` folder. That would combine all the configs within one place instead of many.

What do you guys think about that?

**Comment by danielwelch** [comment]
I addressed this in https://github.com/danielwelch/hassio-zigbee2mqtt/pull/144/commits/bbf2750f2c8c88a819002a624872d5a8505d95c3. Planning to merge in these changes with version 1.5.0.

**Comment by danielwelch** [comment]
`config` is now mapped into the add-on in read-write mode.
