### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by neerdoc** [danielwelch/hassio-zigbee2mqtt#121]
I'm running a Raspberry Pi 3 B+ 64-bit mode. Trying to run the "edge" version but I cannot get it to start. I have rebooted and reinstalled.

/app/run.sh: line 10:    10 Segmentation fault      (core dumped) python3 set_config.py "$CONFIG_PATH" "$DATA_PATH"

I also get lot's of node.js error after this, but this is the very first line in the log window every time.

**Comment by neerdoc** [comment]
Just tested the normal version and it yields exactly the same error. I am suspecting the 64/32-bit to be the culprit, but I do not have any issues with other plugins so far.

Is there anyway to see the logfiles from the docker build step? How does the plugin know which architecture it is on?

**Comment by neerdoc** [comment]
Eh, don't know if I'm missing something here. I assumed that this is the correct docker image:
`dwelch2101/zigbee2mqtt-edge-aarch64:latest`
So I pulled it down on my laptop and it states that is starts:
`2019-3-1 19:49:21 INFO Starting zigbee2mqtt version 0.1.1 (commit #738c31c)`
which is _really_ old... It's from July 27 2018.

What am I missing?

**Comment by danielwelch** [comment]
The correct image for the edge versions is that which is tagged test

**Comment by neerdoc** [comment]
Thanks.

The issue remains, but I am now inclined to believe it is because of python3 being broken on Alpine 3.9 for aarch64 architecture. I will post the issue there.

**Comment by neerdoc** [comment]
Issue is reported [here](https://bugs.alpinelinux.org/issues/9981).

**Comment by MichaelSadovsky** [comment]
I have the same problem with "stable" version zigbee2mqtt add-on. The first string in log after starting is - "/app/run.sh: line 10: 10 Segmentation fault (core dumped) python3 set_config.py "$CONFIG_PATH" "$DATA_PATH"". 
hardware : odroid c2, software : hassOS=2.10, hass.io=148, python=3.7.2   
Does anybody know any solution?

**Comment by neerdoc** [comment]
The upstream bug has not yet been fixed, just checked.
I "solved" it by installing the 32-bit version instead.

**Comment by MichaelSadovsky** [comment]
Thank you for answer, but unfortunately i don't know where to find the 32-bit image for odroid c2.

**Comment by neerdoc** [comment]
Oh, sorry. I assumed there was one available. I believe you should write an issue on the _hassos_ repo since that is where the images are built. [hassos on github](https://github.com/home-assistant/hassos) I suggest asking them to provide a 32-bit image if possible.
