### ISSUE TITLE
Can't pair/add devices properly anymore

### ISSUE THREAD

**Issue by lv-88** [danielwelch/hassio-zigbee2mqtt#122]
Hey!
For some reason I can't properly pair/add anything anymore, despite it working pretty flawlessly the past few months. I mostly use aqara motion and temp sensors, as well as some ikea tradfri spotlights, all of these have worked great, up until now when I noticed that one motion sensor wasn't updating so I decided to repair it, and all hell broke lose.

I keep getting the message
`Device with modelID 'undefined' is not supported.`

after I get the "device connected" etc, it just becomes a "unknown" device when restarting the addon. It doesn't properly pair it, even if it's literally next to the coordinator.

**What I tried doing to troubleshoot was:**
Tried basic restart of the addon/reset stick, plug stick in plug out and then restart etc, but it keeps giving same messages. I also removed the device with the mqtt command, removed it from database, but still same issues upon re-pairing.

**I then went the complete remove/reset route:**
- Remove devices/entities in hassio entity registry (even removed mqtt broker setup altogether after removing in entity registry) to get a clean slate, all traces of all my zigbee2mqtt devices were gone in hassio when fully rebooting the system.
- uninstalled addon as well and entirely deleted all traces off it like the folders etc, then re-installed it, and I tried with both regular and dev versions.

Running latest hassio as well.

But it keeps giving the same results, I get the "device connected" message with its device id number but it then spams with the _Device with modelID 'undefined' is not supported_. messages, even when just pairing one simple device such as the aqara motion sensor, a aqara temperature sensor, or a cc2531 router. I never had this issue before, after several pairings/re/pairings.

I don't know what to do or try now anymore, any suggestions/tips?
Thanks in advance!

**Comment by lv-88** [comment]
Well I went as far as reinstalling my entire hassos from scratch, and only adding zigbee2mqtt, starting simple with adding one device, and still same thing, devices gets "added/connected" quickly but not fully, the neverending _Device with modelID 'undefined' is not supported_ keeps spaming the log. Don't know what else I can do now :/

**Comment by FrankZZ** [comment]
Can you try reflashing the original coordinator stick?

**Comment by lv-88** [comment]
I'd try that next time there is a need to redo stuff, all the troubleshooting took pretty much entire day, and re pairing everything is a bit tedious, so I'd rather not touch anything for now since it's working :)

It was just weird since the original stick was flashed with the same firmware and had worked so well this far.

**Comment by ilsalgo** [comment]
I've the same problem only with Ikea Tradfri lamps, any other devices work.
Solution? 
I don't have the possibility of reflash the firmware...
