### ISSUE TITLE
Can't start addon after reinstalling it

### ISSUE THREAD

**Issue by marcor78** [danielwelch/hassio-zigbee2mqtt#123]
I had to re-flash my dongle CC2531 USB stick due to some connectivity problems. I assumed it would be better to start from scratch, therefore I uninstalled the addon and reinstalled, but now I can't start the addon anymore and the log says the following error:

**Can't start addon_7ad98f9c_zigbee2mqtt: 403 Client Error: Forbidden ("endpoint with name addon_7ad98f9c_zigbee2mqtt already exists in network hassio")**

How can I fix that?
I'm running Hassio 0.88.2

**Comment by marcor78** [comment]
getting worse.... after uninstalling again, now I can't even reinstall the addon anymore.... here's the log:

**19-03-08 23:43:39 ERROR (SyncWorker_3) [hassio.docker.interface] Can't install dwelch2101/zigbee2mqtt-armv7:1.1.1 -> 404 Client Error: Not Found ("pull access denied for dwelch2101/zigbee2mqtt-armv7, repository does not exist or may require 'docker login'").**

Really can't figure out how to fix this....

**Comment by danielwelch** [comment]
Sigh... it looks like something changed in the hassio version released yesterday, [146](https://github.com/home-assistant/hassio/releases/tag/146). `armv7` is a new architecture. Of course, the developer docs haven't been updated to reflect that (still lists armhf, aarch64, amd64, i386 as the supported architectures, which is what this add-on is currently built for). Out of curiosity, what device are you running Hassio on?

I use a build environment made by frenck in the earlier days of hassio add-ons to automate the release process and docker image creation. It's always worked very well for me, but this build environment isn't being updated anymore, so I'm not optimistic that I'll be able to use it anymore to support armv7 architecture. Therefore, addressing this will probably involve totally overhauling the build system and pipeline.

**Comment by marcor78** [comment]
Hi @danielwelch and thanks for the support! I'm running hassio on a Raspberry Pi3 B+
I will try frenck's fix for this, although actually I wouldn't even know where to put the code as long as I don't even have a folder with the config.json now (actually the addon is not installed and can't be installed).

> Sigh... it looks like something changed in the hassio version released yesterday, [146](https://github.com/home-assistant/hassio/releases/tag/146). `armv7` is a new architecture. Of course, the developer docs haven't been updated to reflect that (still lists armhf, aarch64, amd64, i386 as the supported architectures, which is what this add-on is currently built for). Out of curiosity, what device are you running Hassio on?
> 
> I use a build environment made by frenck in the earlier days of hassio add-ons to automate the release process and docker image creation. It's always worked very well for me, but this build environment isn't being updated anymore, so I'm not optimistic that I'll be able to use it anymore to support armv7 architecture. Therefore, addressing this will probably involve totally overhauling the build system and pipeline.

**Comment by danielwelch** [comment]
I’ll merge his changes and make a new release later today. Otherwise, you
could clone his branch and copy the folder (zigbee2mqtt or
zigbee2mqtt-edge) into your addons folder.

Thanks,
Danny Welch

**Comment by zico1234** [comment]
Anyone what I can do to get it working until this is merged? No idea how where the add-on folder on home assistant even is:)

Thank you.

**Comment by liads** [comment]
Couldn't wait, so I created a temporary repository with frenck's fix: https://github.com/liads/hassio-zigbee2mqtt
Adding it to hass.io enables installing zigbee2mqtt again on rpi.
