### ISSUE TITLE
update

### ISSUE THREAD

**Issue by filoor** [danielwelch/hassio-zigbee2mqtt#126]
Hi,

Have a quick question with the last update of the zigbee2mqqt it added the support for "TRUST ZYCT-202" when will the this updated on the "hassio add-on"

Thank you For the great work

**Comment by noxhirsch** [comment]
+1 for this request :)

**Comment by TheZoker** [comment]
Have a look here: https://github.com/danielwelch/hassio-zigbee2mqtt/pull/128

**Comment by filoor** [comment]
@TheZoker Thanks
