### ISSUE TITLE
After Hass.io 0.89.x no more discovery

### ISSUE THREAD

**Issue by gianky69** [danielwelch/hassio-zigbee2mqtt#129]
After the upgrade to Hass.io HA 0.89.x the action "allow device to join" as copied into zigbee2mqtt.yaml (into packages dir) no longer work. I see the switch, timer and bridge state in my Lovelace UI, but using the switch no longer start timer nor disocvery any new device.

**Comment by CMDR-Sloma** [comment]
I have the same problem, I'm trying to re-pair my devices but none of them are discovered by mqtt built-in add-on.

**Comment by gianky69** [comment]
I've just found a solution:
looking at Unused entities in Lovelace UI GUI I've found that 3 automations from zigbee2mqtt are not visible and also not active. These are: Enable Zigbee joining, Disable Zigbee joining by timer and Disable Zigbee joining. After adding them to my automation panel and then enabled, the pairing (and the timer) are working again.
