### ISSUE TITLE
Unable to install 1.21

### ISSUE THREAD

**Issue by TinusScheppers** [danielwelch/hassio-zigbee2mqtt#130]
Hi,

Sadly I'm currently unable to install version 1.2.1, Hassio gives me this error:

`19-03-10 21:04:37 ERROR (SyncWorker_9) [hassio.docker.interface] Can't install dwelch2101/zigbee2mqtt-amd64:1.2.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-amd64:1.2.1 not found").`

However the edge version does install. Seemingly this is also version 1.2.1.
I'm unable to verify if this is a working build as I'm still unable to pair a Tradfri remote (which might be a different issue).

EDIT:

Got the remote working, so this build seems to be working, however the non-edge version does not yet install.

Thanks for releasing!

**Comment by danielwelch** [comment]
Sorry for the issue, this is a problem with the Travis config file (deploy should occur on tags).

**Comment by DeliriousMetro** [comment]
I was able to install 1.2.1 and update the coordinator firmware using the suggested tin-foil approach and turning off all zigbee devices.

Everything is back up and running apart from the Phillips Hue lights which connect to the stick and show the states correctly but when performing any action on them (e.g. Brightness/Switch on/off) it does not perform that.

I do not have a dimmer to repair this but I am looking at reseting the usb, deleting devices from the database. Pan ID appears to remain the same with the same network key so I don't know yet what is the issue.

**Comment by FrankZZ** [comment]
> I was able to install 1.2.1 and update the coordinator firmware using the suggested tin-foil approach and turning off all zigbee devices.
> 
> Everything is back up and running apart from the Phillips Hue lights which connect to the stick and show the states correctly but when performing any action on them (e.g. Brightness/Switch on/off) it does not perform that.
> 
> I do not have a dimmer to repair this but I am looking at reseting the usb, deleting devices from the database. Pan ID appears to remain the same with the same network key so I don't know yet what is the issue.

If you flash version `20190225` or later you don't have to wrap it with tin-foil or turn off all devices anymore:
https://www.zigbee2mqtt.io/information/what_does_and_doesnt_require_repairing.html

Worked for me (Although I don't use Philips Hue but 10+ TRADFRI's)

**Comment by DeliriousMetro** [comment]
> > I was able to install 1.2.1 and update the coordinator firmware using the suggested tin-foil approach and turning off all zigbee devices.
> > Everything is back up and running apart from the Phillips Hue lights which connect to the stick and show the states correctly but when performing any action on them (e.g. Brightness/Switch on/off) it does not perform that.
> > I do not have a dimmer to repair this but I am looking at reseting the usb, deleting devices from the database. Pan ID appears to remain the same with the same network key so I don't know yet what is the issue.
> 
> If you flash version `20190215` or later you don't have to wrap it with tin-foil or turn off all devices anymore:
> https://www.zigbee2mqtt.io/information/what_does_and_doesnt_require_repairing.html
> 
> Worked for me (Although I don't use Philips Hue but 10+ TRADFRI's)

Yeah I believe it's an issue with the Phillips Hue A60 bulbs, this other person has the same 205 error after updating.

10+ Xiaomi devices (various sensors) all work fine without any intervention.

Probably worth a mention as will have to go out to buy a dimmer to repair the bulbs and return the dimmer.

**Comment by andyinno** [comment]
I have a similar problem with the HUE, after updating the lamps "sometimes" work. They just looks like really laggy. I mean... 1 minute lag...

How can you re-pair them with the dimmer? I have it but I know it's possible when the dimmer and the light are connected to the bridge. Is it possible also if they are not connected to the bridge but to zigbee2mqtt?

**Comment by TinusScheppers** [comment]
Installed and tested 1.21 without any issues now!

**Comment by DeliriousMetro** [comment]
> I have a similar problem with the HUE, after updating the lamps "sometimes" work. They just looks like really laggy. I mean... 1 minute lag...
> 
> How can you re-pair them with the dimmer? I have it but I know it's possible when the dimmer and the light are connected to the bridge. Is it possible also if they are not connected to the bridge but to zigbee2mqtt?

I did if by ensuring the permit join is true in the zigbee2mqtt configuration and then holding the on/off buttons until the bulb flashes for a couple of seconds and then it turns on with a transition which is when I let go of the dimmer.
