### ISSUE TITLE
All devices unavailable after updating to 1.2.1

### ISSUE THREAD

**Issue by Pjanssen** [danielwelch/hassio-zigbee2mqtt#132]
After updating the addon to v1.2.1, all my devices show up as unavailable. The zigbee2mqtt log itself shows the devices without any errors.
I've also updated the mosquitto mqtt broker to v4.1, not sure if that's related?

**Comment by marinoraffaele** [comment]
Hi,
I have installed the zigbee2mqtt Addon to my Hassio version 1.2.1 and Mosquitto broker (4.1) all working for some time.
It starts and runs normal but after a while it just turns off and stops working.

Here is my my configuration.yaml:


advanced:
  log_level: debug
devices:
  '0x00158d00027ac1f2':
    friendly_name: '0x00158d00027ac1f2'
    retain: false
  '0x00158d0002b5fa1a':
    friendly_name: '0x00158d0002b5fa1a'
    retain: false
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  password: password
  server: mqtt://my_ip:1883
  user: username
permit_join: false
serial:
  port: /dev/ttyACM0

This is my log I get:

zigbee2mqtt:debug 3/12/2019, 6:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 6:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 6:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 6:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:00:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:05:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:10:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:15:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:20:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:25:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:30:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:35:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:00:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:05:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:10:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:15:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:20:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:22:00 AM Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"65281":{"1":2955,"3":23,"4":5032,"5":31,"6":[0,1],"8":516,"10":0,"100":0}}}' of device 'lumi.sensor_wleak.aq1' (0x00158d00027ac1f2)
  zigbee2mqtt:info 3/12/2019, 8:22:00 AM MQTT publish: topic 'zigbee2mqtt/0x00158d00027ac1f2', payload '{"water_leak":false,"linkquality":70,"battery":74,"voltage":2955}'
  zigbee2mqtt:debug 3/12/2019, 8:22:00 AM Received zigbee message of type 'devChange' with data '{"cid":"genBasic","data":{"65281":[null,2955,null,23,5032,31,[0,1],null,516,null,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0]}}' of device 'lumi.sensor_wleak.aq1' (0x00158d00027ac1f2)
  zigbee2mqtt:debug 3/12/2019, 8:25:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:30:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:35:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:00:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:05:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:10:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:15:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:20:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:25:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:30:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:35:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:00:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:05:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:10:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:15:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:20:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:25:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:30:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:35:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 11:00:25 AM Saving state to file /share/zigbee2mqtt/state.json

**Comment by Pjanssen** [comment]
I've reverted the Mosquitto broker to 4.0, and now everything is working again. So it's not related to the zigbee2mqtt update.

https://community.home-assistant.io/t/mosquitto-mqtt-4-1-doesnt-work-after-update/104855
