### ISSUE TITLE
Question on installation of add-on

### ISSUE THREAD

**Issue by Muffo** [danielwelch/hassio-zigbee2mqtt#133]
Disclaimer: I am just getting started with Hass.io and Zigbee2mqtt.

Can you clarify if the installation of this add-on completely replaces the installation of Zigbee2mqtt? Or it must be done in addition to the steps described [here](https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html)?

**Comment by Scourger10** [comment]
Completely replaces the installation of zigbee2mqtt...

**Comment by Muffo** [comment]
Thanks for the clarification. I am going to close the ticket, but feel free to reopen it if you think the documentation should point this out explicitly.
