### ISSUE TITLE
CC2531 router reported as "disconnected" despite it's working properly

### ISSUE THREAD

**Issue by papperone** [danielwelch/hassio-zigbee2mqtt#134]
I have router CC2531 that despite it's connected (link_quality = 60 and it show as "online" in the zigbee2mqtt map) in Home Assistant its sensor reports "disconnected".
In the zigbee2mqtt github it's stated that the "state:false" is not referred to the connection status but rather the status of the "green light" on the router itself (which still I can't understand what means).
I think that the router status shoudl be reported as "Connected" as far as the linkquality > 0 and not relying on the flag which apparently has nothign to do with the connection status...

**Comment by michaeldbr** [comment]
Hi, I have the same problem... Zigbee2MQTT receives messages from all my zigbee devices. but when i start the timer the bridge stays offline... I also can't switch the bridge sensor at the states tab. i have no error logs in Hassio or Zigbee2MQTT and everything is online exept the bridge.... Home assistant also can't read the sensor values..

**Comment by papperone** [comment]
my problem is not the bridge but the routers....
bridge status is correctly shown in HA

**Comment by Kedryn** [comment]
Same here with router state:false
And my friend's too, same problem.
