### ISSUE TITLE
Cannot update the latest dev with hass.io installation

### ISSUE THREAD

**Issue by milakov** [danielwelch/hassio-zigbee2mqtt#136]
Hi,

I am following this guide, for updating dev z2m with hass.io installation, including removing and adding back the repository: https://github.com/danielwelch/hassio-zigbee2mqtt. It doesn't help I still have old z2m running.

Any ideas are appreciated!

**Comment by Koenkk** [comment]
It seems that somehow the edge image isn't pushed anymore: https://hub.docker.com/r/dwelch2101/zigbee2mqtt-edge-aarch64/tags (current latest update is 10 days ago).

**Comment by Koenkk** [comment]
@danielwelch this is probably the cause https://github.com/danielwelch/hassio-zigbee2mqtt/commit/27caa6ff9394dba4673440c6c7e2289d3d68e925 , not tag is present meaning that the images will build but not be published.

**Comment by Koenkk** [comment]
New edge images are available now.

**Comment by milakov** [comment]
@Koenkk Thanks! I successfully updated z2m to the latest dev.

**Comment by gewoonik** [comment]
the next thing to do is get rid of the if the network_key starts with the number 0
change - **0**87 to 87

after that also the "disable_led": "bool?" Change to "disable_led": false

configuration.yaml file
advanced:
  network_key:
  - 4
  - **0**87
  - **0**95
  - 106
  - 217
  - 15
  - **0**87
  - 244
  - 27
  - 177
  - 29
  - 107
  - 24
  - 203
  - 53
  - 174

######################
config.json file
######################
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.2.50",
    "user": "username",
    "password": "password"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": false
  },
  "advanced": {
    "network_key": [
	  8,
	  24,
	  80,
	  106,
	  217,
	  15,
	  45,
	  244,
	  27,
	  188,
	  77,
	  205,
	  27,
	  35,
	  187,
	  178
     ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
