### ISSUE TITLE
Addon wont install in the latest hassio 

### ISSUE THREAD

**Issue by riddertommie** [danielwelch/hassio-zigbee2mqtt#137]
Upgrade to the last version of Hassio and now the the addon is broken. I reinstall Hassio rpi3 compleet again, but stil not working.

PS i'm on the 64 bits Version. and Mosquitto MQTT Server bundled with Hivemq's web client.

_____________________________________ Error below this line____________________________________________

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-03-25T09_51_43_945Z-debug.log
2019-03-25T10:51:46: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-03-25T10:51:46: PM2 log: App [npm:0] starting in -fork mode-
2019-03-25T10:51:46: PM2 log: App [npm:0] online

zigbee2mqtt@1.2.1 start /app
node index.js
fs.js:115
throw err;
^
Error: ENOENT: no such file or directory, open '/share/zigbee2mqtt/configuration.yaml'
at Object.openSync (fs.js:439:3)
at Object.readFileSync (fs.js:344:35)
at Object.readYaml (/app/lib/util/fs.js:5:29)
at read (/app/lib/util/settings.js:116:18)
at getSettings (/app/lib/util/settings.js:80:21)
at Object.get (/app/lib/util/settings.js:286:52)
at Object. (/app/lib/util/logger.js:10:24)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
npm
ERR! code ELIFECYCLE
npm ERR! errno 1
npm
ERR! zigbee2mqtt@1.2.1 start: node index.js
npm ERR! Exit status 1
npm ERR!
npm
ERR! Failed at the zigbee2mqtt@1.2.1 start script.

**Comment by hernanjc** [comment]
Same here. New installation yesterday and same error. "/zigbee2mqtt" doesn't exist under "/share". I installed the addon and started it. I tried different configurations (with and without password...) but always the same. 

Also "/dev/ttyACM0" doesn't exist, though in Hassio - Hadware it is there.

Any suggestions/ideas? Thanks!

**Comment by hernanjc** [comment]
I've tried with a 64 bit clean installation (Rpi3 + Hassio 64 bits) and same problem.
I've tried with a 32 bit clean installation (Rpi3 + Hassio 32 bits) and it works.

I think this is the same propblem explained in  #121 by @neerdoc (thanks by the way). 

It is better to wait for a solution or to migrate everything to the 32bit version? Will it work if I just restore a 64 bit hass.io snapshot in a clean 32 bit hass.io version ?

**Comment by riddertommie** [comment]
Tried it also and i can confirm, clean installation (Rpi3 + Hassio 32 bits) and it work

**Comment by Teie** [comment]
Ok, same here... New 64bits installation and no Zigbee2mqtt. :(

**Comment by Teie** [comment]
Does anyone know if Zigbee2MQTT now works on HAssio64Bits?

**Comment by ciotlosm** [comment]
@Teie 

I'm using zigbee2mqtt on a raspberry pi 4 with boot from USB/m.2 ssd with zzh!:


arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 5.4
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.6
supervisor | 2020.10.1
timezone | Europe/Bucharest
version | 0.117.1
virtualenv | false

I'm running zigbee2mqtt from https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
