### ISSUE TITLE
Bridge don't report State

### ISSUE THREAD

**Issue by paskyecijano** [danielwelch/hassio-zigbee2mqtt#145]
I am using the addons and bridge (CC2531) with the official configuration don't report the STATE.

![image](https://user-images.githubusercontent.com/3083124/56023474-31539f80-5d0e-11e9-9624-f97761447098.png)

![image](https://user-images.githubusercontent.com/3083124/56023489-429cac00-5d0e-11e9-82da-48c676479b5a.png)

But in the log of zigbee2mqtt i see the state correctly

![image](https://user-images.githubusercontent.com/3083124/56023625-8f808280-5d0e-11e9-8b92-e8047c75e22a.png)

the sensor is this:
![image](https://user-images.githubusercontent.com/3083124/56026087-b8efdd00-5d13-11e9-8fc5-c9cb2557b703.png)

i am using the last firmware in the bridge and the last version of de addons.

Any help??

thanks

**Comment by Karvis81** [comment]
Hi,

I have the same issue.
Also any of my sensors are not shown at hassio/states.


Zigbee2mqtt:
![image](https://user-images.githubusercontent.com/49531493/56092004-386ddf80-5ebf-11e9-9177-326ed705c638.png)

Conf:
![image](https://user-images.githubusercontent.com/49531493/56092028-7b2fb780-5ebf-11e9-8f33-fcb72197bc1d.png)


MQTT log:
![image](https://user-images.githubusercontent.com/49531493/56091950-6acb0d00-5ebe-11e9-9852-943922bb8f7b.png)

Configuration.yaml:
![image](https://user-images.githubusercontent.com/49531493/56091979-c85f5980-5ebe-11e9-8e49-47620583cf00.png)

Hassio 0.91.3
zigbee2mqtt 1.3.0
MQTT 4.1

I have already reistalled mqtt and zigbee2mqtt add-ons without any progress.
My 2 other manually installed mqtt devices are showing the states.

**Comment by tradenet** [comment]
Yeah, this broke for me in Hassio 92.0. With docker warnings.

**Comment by AdighaLogic** [comment]
> Hi,
> 
> I have the same issue.
> Also any of my sensors are not shown at hassio/states.
> 
> Zigbee2mqtt:
> ![image](https://user-images.githubusercontent.com/49531493/56092004-386ddf80-5ebf-11e9-9177-326ed705c638.png)
> 
> Conf:
> ![image](https://user-images.githubusercontent.com/49531493/56092028-7b2fb780-5ebf-11e9-8f33-fcb72197bc1d.png)
> 
> MQTT log:
> ![image](https://user-images.githubusercontent.com/49531493/56091950-6acb0d00-5ebe-11e9-9852-943922bb8f7b.png)
> 
> Configuration.yaml:
> ![image](https://user-images.githubusercontent.com/49531493/56091979-c85f5980-5ebe-11e9-8e49-47620583cf00.png)
> 
> Hassio 0.91.3
> zigbee2mqtt 1.3.0
> MQTT 4.1
> 
> I have already reistalled mqtt and zigbee2mqtt add-ons without any progress.
> My 2 other manually installed mqtt devices are showing the states.

Looks like you're pointing to the wrong mqtt server
I can see from the log that you're using mosquitto but in your zigbee config file you're pointing to HA built in mqtt server. 
Update this line in your zigbee config file.
server: mqtt://core-mosquitto
if you have a user name and password, you need to add those as well.
