### ISSUE TITLE
Setting pan_id not working

### ISSUE THREAD

**Issue by Smiggel** [danielwelch/hassio-zigbee2mqtt#150]
I tried to set the pan id for my USB stick, This does however not work.
The config expects the pan_id to be a string. The MQTT broker expects it to be a number.

Setting the pan_id to string "0x162a" literally saves it as a string and does not convert it to int 6754. Setting the pan_id to 6754 will save it as a string. With single quotes around it. That is not working either.

**Comment by carldebilly** [comment]
There is a similar problem with `ext_pan_id`: this one will simply be ignored & removed from the configuration.

**Comment by ryanbeaton** [comment]
I not the` pan_id` string issue also
