### ISSUE TITLE
  "zigbee_shepherd_devices": "true"

### ISSUE THREAD

**Issue by mclaudiopt** [danielwelch/hassio-zigbee2mqtt#155]
Is your issue about a specific device? It probably belongs in the [zigbee2mqtt issue tracker](https://github.com/Koenkk/zigbee2mqtt). Consider posting your issue there first.

hi. i am trying to add the line:
  "zigbee_shepherd_devices": "true"
to the UI interface of setup, but when i added it the addon does not allow me to save the settings

i wish to try to add an unsupported device.
this is needed, rigjht?

**Comment by d0ugal** [comment]
Try `"zigbee_shepherd_devices": true` with no quotes around true

**Comment by mclaudiopt** [comment]
this is my ccurrent yaml file.
is it ok like this?

base_topic: zigbee2mqtt
cache_state: true
devices: devices.yaml
disable_led: true
groups: groups.yaml
homeassistant: true
include_device_information: true
mqtt:
  base_topic: zigbee2mqtt
  password: mosquitto
  server: mqtt://192.168.1.108:1883
  user: Mosquitto
password: mosquitto
permit_join: true
port: /dev/ttyACM0
reject_unauthorized: true
serial:
  port: /dev/ttyACM0
server: mqtt://192.168.1.108:1883
user: Mosquitto
zigbee_shepherd_devices: true
