### ISSUE TITLE
Error bo showing entities

### ISSUE THREAD

**Issue by cargial** [danielwelch/hassio-zigbee2mqtt#156]
Thank you for your gate job firs. 
I have hassio 0.91.4 and installed cc2531. I flashed it with your last firmaware. I have you last addon zigbee2mqtt. I also have mqtt installed and one user for zigbee.
The issue is that i try to pair a xiaomi binary switch. I look at the log of the addon and it seams that it is connected becase when i press the botton it is shown... however when i try to use the enttity is tis no avalie in the list. (Neither in entities not used). I hace restaeted many times. I have unpluged the xiaomi gateway and the switch wasn't attached to the xiaomi gateway.
Is ther a solution?? Any idea...it is diving me mad...
Thank you very much

ZIGBEE2MQTT LOG:
zigbee2mqtt:info 5/10/2019, 7:37:27 AM zigbee-shepherd started zigbee2mqtt:info 5/10/2019, 7:37:27 AM Coordinator firmware version: '20190223' zigbee2mqtt:info 5/10/2019, 7:37:27 AM Currently 0 devices are joined: zigbee2mqtt:warn 5/10/2019, 7:37:27 AM `permit_join` set to `true` in configuration.yaml. zigbee2mqtt:warn 5/10/2019, 7:37:27 AM Allowing new devices to join. zigbee2mqtt:warn 5/10/2019, 7:37:27 AM Set `permit_join` to `false` once you joined all devices. zigbee2mqtt:info 5/10/2019, 7:37:27 AM Zigbee: allowing new devices to join. zigbee2mqtt:info 5/10/2019, 7:37:27 AM Connecting to MQTT server at mqtt://XXX.XXX.X.X:1883 zigbee2mqtt:info 5/10/2019, 7:37:27 AM zigbee-shepherd ready zigbee2mqtt:info 5/10/2019, 7:37:28 AM Connected to MQTT server zigbee2mqtt:info 5/10/2019, 7:37:28 AM MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online' zigbee2mqtt:info 5/10/2019, 7:37:28 AM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.3.1","commit":"unknown","coordinator_firmware":20190223,"log_level":"info","permit_join":true}' zigbee2mqtt:error 5/10/2019, 7:39:15 AM Cannot get the Node Descriptor of the Device: 0x00158d00027b6d79 (Error: Timed out after 10000 ms) zigbee2mqtt:error 5/10/2019, 7:39:42 AM Cannot get the Node Descriptor of the Device: 0x00158d00027b6d79 (Error: Timed out after 10000 ms) zigbee2mqtt:warn 5/10/2019, 7:39:57 AM Device with modelID 'undefined' is not supported. zigbee2mqtt:warn 5/10/2019, 7:39:57 AM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html zigbee2mqtt:warn 5/10/2019, 7:39:58 AM Device with modelID 'undefined' is not supported. zigbee2mqtt:warn 5/10/2019, 7:39:58 AM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html zigbee2mqtt:info 5/10/2019, 7:40:08 AM MQTT publish: topic 'homeassistant/sensor/0x00158d00027b6d79/click/config', payload '{"icon":"mdi:toggle-switch","value_template":"{{ value_json.click }}","expire_after":1,"state_topic":"zigbee2mqtt/0x00158d00027b6d79","json_attributes_topic":"zigbee2mqtt/0x00158d00027b6d79","name":"0x00158d00027b6d79_click","unique_id":"0x00158d00027b6d79_click_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d00027b6d79","name":"0x00158d00027b6d79","sw_version":"Zigbee2mqtt 1.3.1","model":"MiJia wireless switch (WXKG01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}' zigbee2mqtt:info 5/10/2019, 7:40:08 AM MQTT publish: topic 'homeassistant/sensor/0x00158d00027b6d79/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x00158d00027b6d79","json_attributes_topic":"zigbee2mqtt/0x00158d00027b6d79","name":"0x00158d00027b6d79_battery","unique_id":"0x00158d00027b6d79_battery_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d00027b6d79","name":"0x00158d00027b6d79","sw_version":"Zigbee2mqtt 1.3.1","model":"MiJia wireless switch (WXKG01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}' zigbee2mqtt:info 5/10/2019, 7:40:08 AM MQTT publish: topic 'homeassistant/sensor/0x00158d00027b6d79/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00158d00027b6d79","json_attributes_topic":"zigbee2mqtt/0x00158d00027b6d79","name":"0x00158d00027b6d79_linkquality","unique_id":"0x00158d00027b6d79_linkquality_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d00027b6d79","name":"0x00158d00027b6d79","sw_version":"Zigbee2mqtt 1.3.1","model":"MiJia wireless switch (WXKG01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}' zigbee2mqtt:warn 5/10/2019, 7:40:18 AM Message without device! zigbee2mqtt:info 5/10/2019, 7:40:21 AM Device incoming... zigbee2mqtt:info 5/10/2019, 7:40:21 AM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}' zigbee2mqtt:warn 5/10/2019, 7:40:37 AM Device with modelID 'undefined' is not supported. zigbee2mqtt:warn 5/10/2019, 7:40:37 AM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html zigbee2mqtt:warn 5/10/2019, 7:40:38 AM Device with modelID 'undefined' is not supported. zigbee2mqtt:warn 5/10/2019, 7:40:38 AM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html zigbee2mqtt:info 5/10/2019, 7:41:09 AM MQTT publish: topic 'zigbee2mqtt/0x00158d00027b6d79', payload '{"linkquality":168,"duration":32365,"battery":100,"voltage":3002,"click":"single"}' zigbee2mqtt:info 5/10/2019, 7:41:17 AM MQTT publish: topic 'zigbee2mqtt/0x00158d00027b6d79', payload '{"linkquality":162,"duration":32365,"battery":100,"voltage":3002,"click":"double"}' zigbee2mqtt:info 5/10/2019, 7:41:34 AM Device incoming... zigbee2mqtt:info 5/10/2019, 7:41:34 AM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}' zigbee2mqtt:info 5/10/2019, 7:48:17 AM MQTT publish: topic 'zigbee2mqtt/0x00158d00027b6d79', payload '{"linkquality":86,"duration":32365,"battery":100,"voltage":3002,"click":"double"}' zigbee2mqtt:info 5/10/2019, 7:48:17 AM MQTT publish: topic 'zigbee2mqtt/0x00158d00027b6d79', payload '{"linkquality":94,"duration":32365,"battery":100,"voltage":3002,"click":"single"}' zigbee2mqtt:info 5/10/2019, 9:42:26 AM MQTT publish: topic 'zigbee2mqtt/0x00158d00027b6d79', payload '{"linkquality":86,"duration":32365,"battery":100,"voltage":3002}' zigbee2mqtt:info 5/10/2019, 10:42:43 AM MQTT publish: topic 'zigbee2mqtt/0x00158d00027b6d79', payload '{"linkquality":92,"duration":32365,"battery":100,"voltage":3002}'

ZIGBEE2MQTT config:
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": true,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://xxx.xxx.x.xxx:1883",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [],
  "mqtt_user": "xxxx",
  "mqtt_pass": "xxxxx"
}

MQTT config:
{
  "logins": [
    {
      "username": "xxxxx",
      "password": "xxxxx"
    }
  ],
  "anonymous": false,
  "quiet_logs": true,
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

**Comment by AdighaLogic** [comment]
Try changing "anonymous" to true in MQTT config.
