### ISSUE TITLE
error when I add zigbee-shepherd 

### ISSUE THREAD

**Issue by httpedo13** [danielwelch/hassio-zigbee2mqtt#157]
when I add zigbee shepherd in the add on configuration I have the following error:

<img width="1036" alt="Schermata 2019-05-11 alle 20 07 21" src="https://user-images.githubusercontent.com/40502451/57573486-6dbb0e00-7428-11e9-8825-94520233f6ef.png">

**Comment by shadow-fight** [comment]
Same problem happened to me, started today morning

**Comment by AdighaLogic** [comment]
Try a different USB port, also try upgrading your addon to the latest release.
