### ISSUE TITLE
Not auto release latest version from zigbee2mqtt

### ISSUE THREAD

**Issue by dzungpv** [danielwelch/hassio-zigbee2mqtt#159]
@danielwelch I read that you wrote script for auto build release version from zigbee2mqtt repos.
But 1.4.0 release about 15 hours ago but not  with hassio-zigbee2mqtt.

**Comment by danielwelch** [comment]
This is true only for the edge image, not for stable images. I’ll try to
put together a release soon.

Thanks,
Danny Welch

**Comment by dzungpv** [comment]
@danielwelch i am running stable version 1.3.1 but there is no update notification for the addon in hassio.

**Comment by james-fry** [comment]
Daniel did not update the addon yet. As soon as its updated you'll see it in hassio.
@danielwelch - will you be incorporating the breaking change PR thats been submitted (Restructure configuration #144)?

**Comment by danielwelch** [comment]
Thanks @james-fry. I would like to incorporate it. The concern over the breaking changes is what has stopped me from doing it so far, but I would like to do it on a major version update.

**Comment by james-fry** [comment]
I was thinking about how you could do this when I posted.
I _think_ if you put a readme.md markdown file in the repo (same place as config,json) it will display in HASSIO.
This way you can warn users that the _next_ release will be breaking.

**Comment by TinusScheppers** [comment]
It seems that even the edge version is not on 1.4.0, is this correct?
