### ISSUE TITLE
Cannot Start Add-on

### ISSUE THREAD

**Issue by thanhkeyi** [danielwelch/hassio-zigbee2mqtt#163]
When I want to start the add-on this is shown in the log. What can I do now?

Log:

> ./run.sh: line 10: 10 Illegal instruction (core dumped) python3 set_config.py "$CONFIG_PATH" "$DATA_PATH"
> ./run.sh: line 25: 11 Illegal instruction (core dumped) ZIGBEE2MQTT_DATA="$DATA_PATH" pm2-runtime start npm -- start

My Config:

> {
> "data_path": "/share/zigbee2mqtt",
> "homeassistant": true,
> "permit_join": true,
> "mqtt_base_topic": "zigbee2mqtt",
> "mqtt_server": "mqtt://homeassistant",
> "serial_port": "/dev/ttyACM0",
> "devices": [],
> "network_key": [],
> "mqtt_user": "...",
> "mqtt_pass": "..."

**Comment by AdighaLogic** [comment]
Take a look at your share folder, do you see zigbee2mqtt folder in there? if so, any files in that folder?

**Comment by thanhkeyi** [comment]
I don't see any files in share folder

**Comment by AdighaLogic** [comment]
You could try to add the zigbee2mqtt folder like this:
share/zigbee2mqtt

then install the addon after that.

**Comment by thanhkeyi** [comment]
Thanks for the reply. But it doesn't work

**Comment by AdighaLogic** [comment]
Ok, so now that you added the zigbee2mqtt folder to the share folder. we could try to add the files it needs to run.
I have the following in my zigbee2mqtt folder:

folders:
log

files:
configuration.yaml
database.db
state.json

I'm not sure we can create the database.db but one thing you can try is to add the **log** folder and the **configuration.yaml** file.

you need to add the addon setup in the configuration.yaml file you just created.
Here's what mine looks like

`mqtt:
  base_topic: zigbee2mqtt
  password: **********
  server: mqtt://core-mosquitto
  user: *********
permit_join: false
serial:
  port: /dev/ttyACM0`

This ismy setup in the addon details 

`{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": false,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://core-mosquitto",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": []
}`

If you're using HomeAssistant's built in mqtt then you can change 
`
"homeassistant": true,
  "mqtt_server": "mqtt://homeassistant",
`
