### ISSUE TITLE
1.4.0 very active mqtt messaging

### ISSUE THREAD

**Issue by james-fry** [danielwelch/hassio-zigbee2mqtt#165]
Since upgrading to 1.4.0 today I am now seeing mqtt messages pushed for config and logging every 5 seconds. These were not either sent or logged with previous version.

E.g. (truncated rows)

```
  zigbee2mqtt:info 5/21/2019, 8:11:45 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":{}}'
  zigbee2mqtt:info 5/21/2019, 8:11:45 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{
  zigbee2mqtt:info 5/21/2019, 8:11:50 PM MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":"
  zigbee2mqtt:info 5/21/2019, 8:11:50 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":{}}'
  zigbee2mqtt:info 5/21/2019, 8:11:50 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"
  zigbee2mqtt:info 5/21/2019, 8:11:55 PM MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":
  zigbee2mqtt:info 5/21/2019, 8:11:55 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":{}}'
  zigbee2mqtt:info 5/21/2019, 8:11:55 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{
  zigbee2mqtt:info 5/21/2019, 8:12:00 PM MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":
  zigbee2mqtt:info 5/21/2019, 8:12:00 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":{}}'
  zigbee2mqtt:info 5/21/2019, 8:12:00 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[
  zigbee2mqtt:info 5/21/2019, 8:12:05 PM MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":
  zigbee2mqtt:info 5/21/2019, 8:12:05 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":{}}'
  zigbee2mqtt:info 5/21/2019, 8:12:05 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{
  zigbee2mqtt:info 5/21/2019, 8:12:10 PM MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":"
  zigbee2mqtt:info 5/21/2019, 8:12:10 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":{}}'
  zigbee2mqtt:info 5/21/2019, 8:12:10 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{
  zigbee2mqtt:info 5/21/2019, 8:12:11 PM MQTT publish: topic 'zigbee2mqtt/CC2531 Router Kitchen', payload '{"state":false,"linkquality":10}'
  zigbee2mqtt:info 5/21/2019, 8:12:15 PM MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":
  zigbee2mqtt:info 5/21/2019, 8:12:15 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":{}}'
  zigbee2mqtt:info 5/21/2019, 8:12:15 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{
  zigbee2mqtt:info 5/21/2019, 8:12:20 PM MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":
  zigbee2mqtt:info 5/21/2019, 8:12:20 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":{}}'
  zigbee2mqtt:info 5/21/2019, 8:12:20 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{
```

**Comment by AdighaLogic** [comment]
I upgraded to 1.4 as well this morning but i'm not having the same issue you're having. My MQTT traffic and logs seem normal, just like before. Although i should mention that I only have one Zigbee device connected.

`zigbee2mqtt:info 5/21/2019, 2:40:32 PM Connected to MQTT server
  zigbee2mqtt:info 5/21/2019, 2:40:32 PM MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
  zigbee2mqtt:info 5/21/2019, 2:40:32 PM MQTT publish: topic 'zigbee2mqtt/0x00158d000279e17f', payload '{"battery":100,"voltage":3205,"linkquality":136,"smoke":false}'
  zigbee2mqtt:info 5/21/2019, 2:40:32 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.4.0","commit":"unknown","coordinator":20190223,"log_level":"info","permit_join":false}'
  zigbee2mqtt:info 5/21/2019, 3:10:00 PM MQTT publish: topic 'zigbee2mqtt/0x00158d000279e17f', payload '{"battery":100,"voltage":3205,"linkquality":136,"smoke":false}'
  zigbee2mqtt:info 5/21/2019, 4:08:33 PM MQTT publish: topic 'zigbee2mqtt/0x00158d000279e17f', payload '{"battery":100,"voltage":3205,"linkquality":139,"smoke":false}'
  zigbee2mqtt:info 5/21/2019, 4:59:06 PM MQTT publish: topic 'zigbee2mqtt/0x00158d000279e17f', payload '{"battery":100,"voltage":3205,"linkquality":139,"smoke":false}'
  zigbee2mqtt:info 5/21/2019, 5:49:24 PM MQTT publish: topic 'zigbee2mqtt/0x00158d000279e17f', payload '{"battery":100,"voltage":3205,"linkquality":136,"smoke":false}'
  zigbee2mqtt:info 5/21/2019, 6:44:42 PM MQTT publish: topic 'zigbee2mqtt/0x00158d000279e17f', payload '{"battery":100,"voltage":3205,"linkquality":136,"smoke":false}'`

**Comment by danielwelch** [comment]
Regardless, this is probably not an add-on issue, but a zigbee2mqtt issue (if it’s an issue at all). I’ll close it for now but reopen if I’m missing something and this is an add-on issue.

**Comment by james-fry** [comment]
Fair enough Daniel :) first of all I will try to reinstall the addon. If that fails I’ll raise an issue on the z2m gh.

**Comment by james-fry** [comment]
It was a false alarm. The additional mqtt messages logged seem to be related to the node red Z2M admin panel: https://flows.nodered.org/flow/1f1c0dde4ff193e5c14d5b99442a7d00
I disabled the flow in NR and redeployed and the issue was resolved. I guess some interaction between the admin panel and Z2M 1.4.0.
