### ISSUE TITLE
Devices stoped updating their values

### ISSUE THREAD

**Issue by macjex** [danielwelch/hassio-zigbee2mqtt#167]
After using Zigbee2mqtt without a problem one of my Xiaomi Aquara Tempsensors stopped working. 
It just does not update any of the values. 
After restarting the Addon -> erasing the entity from the database
= Its not possible to add/pair the device. 

Now even a second Tempsensor has stopped working. 

Is there a workaround to get them back aboard? 

Or do I need to get a Hub for this ? 

Best regards

![image](https://user-images.githubusercontent.com/31004875/58208010-25cb9f00-7ce4-11e9-9694-875c1581964d.png)

![image](https://user-images.githubusercontent.com/31004875/58208030-354ae800-7ce4-11e9-81f5-41b53217af22.png)

**Comment by danielwelch** [comment]
This should probably be in the zigbee2mqtt issue tracker, but feel free to re-open if it turns out to be an add-on issue.
