### ISSUE TITLE
Trying to change dimming configuration of a single light.

### ISSUE THREAD

**Issue by ericmiller777** [danielwelch/hassio-zigbee2mqtt#168]
Trying to get my tradfri bulb to transition, Koenkk said this code should help, but not sure where to add it using this addon:

devices:
    '0x84182600000e9afd': 
         friendly_name: '0x84182600000e9afd'
         retain: false 
        homeassistant:
             light: 
               transition: 2

Doesn't seem to be working by adding it to the /share/zigbee2mqtt/configuration.yaml(I'm doing it from configurator is there a different file if I ssh?) Do I add it to the addon setup "devices" object? If so could I get a example? Thank you.

**Comment by danielwelch** [comment]
This is directly addressed in the add-on README

**Comment by ericmiller777** [comment]
@danielwelch I put the above code (formatted) in /share/zigbee2mqtt/configuration.yaml (it was blank) and I set overwrite to false in the addon set up, am I missing something?

**Comment by danielwelch** [comment]
Ah, I see that because you have some deeply nested options, you'll have to modify `configuration.yaml` directly rather than using the Hassio configuration.

Your `configuration.yaml` should not be empty... are you able to run the add-on at all? Can you post your full add-on configuration?

**Comment by ericmiller777** [comment]
Oh this only one of my lights, I have many other lights that work fine, 1 sec, I think that the configuration.yaml I see is just a blank file that I may have created at some point, and that perhaps I need to use ssh to edit the real one anyway here is my config:

{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://homeassistant",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [],
  "mqtt_user": "***",
  "mqtt_pass": "***",
  "overwrite": false
}

**Comment by ericmiller777** [comment]
@danielwelch Okay, after a reset seems its populated now:

devices:
  '0x90fd9ffffe6e8ec3':
    friendly_name: Kitchen Light
    homeassistant:
      light:
        transition: 3
    retain: false
  '0x0017880104214792':
    friendly_name: '0x0017880104214792'
    retain: false
  '0x00178801045a3b9d':
    friendly_name: '0x00178801045a3b9d'
    retain: false
  '0x00178801049f4cef':
    friendly_name: '0x00178801049f4cef'
    retain: false
  '0x00178801049f9218':
    friendly_name: '0x00178801049f9218'
    retain: false
  '0x00178801041e3749':
    friendly_name: '0x00178801041e3749'
    retain: false
  '0x00178801049f9307':
    friendly_name: '0x00178801049f9307'
    retain: false
  '0x00178801046542a3':
    friendly_name: '0x00178801046542a3'
    retain: false
  '0x90fd9ffffe649adf':
    friendly_name: '0x90fd9ffffe649adf'
    retain: false
  '0x00178801045a20ca':
    friendly_name: '0x00178801045a20ca'
    retain: false
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  password: {censored}
  server: 'mqtt://homeassistant'
  user: {censored}
permit_join: false
serial:
  port: /dev/ttyACM0

**Comment by danielwelch** [comment]
Closing as this must now be in done in a separate devices.yaml file in version 1.5 and above
