### ISSUE TITLE
Runtime Pairing not working

### ISSUE THREAD

**Issue by alexvenom** [danielwelch/hassio-zigbee2mqtt#170]
I tried the Runtime Pairing via Lovelace using the process described in: https://github.com/danielwelch/hassio-zigbee2mqtt#pairing

But thought he "Allow devices to join" and timer works and I can set new devices correctly, the "Bridge State" remains "Unknown":

![image](https://user-images.githubusercontent.com/4620702/58434063-40a96500-8090-11e9-88da-809ca5ab9d34.png)

I copied the whole config from the tutorial on the link
Does anyone know what I am missing?

**Comment by bmtKIA6** [comment]
Make sure that the serial path is correct. Where is your dongle? lspci

If using Hass, go to hass.io, system, hardware

**Comment by alexvenom** [comment]
Turned out a full reinstall of HA solved the problem.
