### ISSUE TITLE
How to trigger hassio-zigbee2mqtt enable and disable device pairing from native mobile app (Android & iOS)?

### ISSUE THREAD

**Issue by jerrychong25** [danielwelch/hassio-zigbee2mqtt#175]
Hi all,

I am currently doing native mobile app (Android & iOS) integration with Home Assistant via https://developers.home-assistant.io/docs/en/app_integration_index.html.

Noting that official **hassio-zigbee2mqtt** allow us to enable and disable device pairing from the Home Assistant front end, as per below:
![](https://user-images.githubusercontent.com/7738048/40874668-bdd1645a-667a-11e8-88ff-03b78212910b.png)

Is there any ways we could trigger hassio-zigbee2mqtt to enable and disable device pairing from native mobile app (Android & iOS)? 

And support other features like below?
-Read Zigbee device list from hassio-zigbee2mqtt database
-Read Zigbee device adding status (Success or Failed) during new device pairing process, so that mobile app could react and display relevant app screen to users.

Thanks.

**Comment by danielwelch** [comment]
Admittedly, I haven’t been following the latest advances in the mobile app component for hass. But I assume the front end UI is made available by your app, unless you’re going for some other niche use. 

So there’s a few options:
1. Just let the user implement this on their own in their front end, as you include above, or however they want.
2. If you want to do it from the “native code” for some reason, you could interact with the home assistant API directly, and/or publish an MQTT message from homeassistant that interacts with zigbee2mqtt

There’s nothing unique about how the add-on suggests doing this, it’s just using things that are already intrinsic to homeassistant.

Regardless, this is out of scope and doesn’t have anything to do with the add-on, but rather zigbee2mqtt itself. I’d suggest continuing the discussion there if you have questions. I’ll close this for now.

**Comment by jerrychong25** [comment]
> Admittedly, I haven’t been following the latest advances in the mobile app component for hass. But I assume the front end UI is made available by your app, unless you’re going for some other niche use.
> 
> So there’s a few options:
> 
> 1. Just let the user implement this on their own in their front end, as you include above, or however they want.
> 2. If you want to do it from the “native code” for some reason, you could interact with the home assistant API directly, and/or publish an MQTT message from homeassistant that interacts with zigbee2mqtt
> 
> There’s nothing unique about how the add-on suggests doing this, it’s just using things that are already intrinsic to homeassistant.
> 
> Regardless, this is out of scope and doesn’t have anything to do with the add-on, but rather zigbee2mqtt itself. I’d suggest continuing the discussion there if you have questions. I’ll close this for now.

Noted and thanks.
