### ISSUE TITLE
Set "experimental" option in config

### ISSUE THREAD

**Issue by MiguelAngelLV** [danielwelch/hassio-zigbee2mqtt#176]
I need add 

```json
"expiremental" : {
    "livolo":true
}
```

in the configuration, but, the schema fail and remove these lines.

**Comment by MiguelAngelLV** [comment]
Any way to add livolo config?

When I edit the file in config/zigbee2mqtt, when restart the module overwritter my custom configuration, so... I can't get livolo works fine.

**Comment by danielwelch** [comment]
@MiguelAngelLV can you point me to any documentation of this config section? Or, if it's undocumented, the relevant source?
Also, are you using the edge version of the add-on?

**Comment by MiguelAngelLV** [comment]
The config is from this issue: https://github.com/Koenkk/zigbee2mqtt/issues/592

I use the 1.5.1.1 version

**Comment by Nosstrom** [comment]
> Any way to add livolo config?
> When I edit the file in config/zigbee2mqtt, when restart the module overwritter my custom configuration, so... I can't get livolo works fine.

mine too.... why is that?>

**Comment by Nosstrom** [comment]
I used the dev version (edge) and worked just fine ! I got state and linkquality. The feedback is really good though.

**Comment by MiguelAngelLV** [comment]
@Nosstrom did you add experimental option or with edge version it is not necessary?

**Comment by Nosstrom** [comment]
I run Hassio 0.99.3 . In the config experimental doesn’t work . Just use the edge (dev) version and you ll be fine .
