### ISSUE TITLE
Aqara ZNLDP12LM succesfully reenabled joining

### ISSUE THREAD

**Issue by hagazan** [danielwelch/hassio-zigbee2mqtt#178]
Hi All,

Please help me with my issue regarding light bulb Aqara ZNLDP12LM.

On Zigbee to MQTT Bridge i receive the following log lines:

`  zigbee2mqtt:info 7/7/2019, 11:25:41 AM Succesfully reenabled joining
  zigbee2mqtt:info 7/7/2019, 11:29:01 AM Succesfully reenabled joining
  zigbee2mqtt:info 7/7/2019, 11:29:29 AM MQTT publish: topic 'zigbee2mqtt/0x00158d0002d3a4d9', payload '{"state":"ON","brightness":255,"color_temp":153,"linkquality":44}'
  zigbee2mqtt:info 7/7/2019, 11:32:21 AM Succesfully reenabled `joining``

But if i have a look into the integrations page or dev page, i cannot find the founded light bulb.

`mqtt:
  broker: 192.168.0.5 
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'`

Could you please help me?

Thanks in advance!

Hagazan

**Comment by danielwelch** [comment]
This should be posted in the zigbee2mqtt repo
