### ISSUE TITLE
v1.5 not available on hassio

### ISSUE THREAD

**Issue by mclaudiopt** [danielwelch/hassio-zigbee2mqtt#181]
hello 1.5 is released can you please make it available on hassio?

**Comment by brent0np** [comment]
i suspect this is the 1.5 work here: https://github.com/danielwelch/hassio-zigbee2mqtt/pull/144#issue-268566002

**Comment by TheZoker** [comment]
@brent0np Actually the new version of the hassio addon will be 1.5, but that has nothing to do with the version of zigbee2mqtt. It's just a coincidence, that they both have version 1.5.
Maybe @danielwelch will include version 1.5 of zigbee2mqtt in version 1.5 of the hassio addon, but we'll see

**Comment by danielwelch** [comment]
This is incorrect, the add-on versioning is pinned to zigbee2mqtt versioning. It’s explained in the README. Version 1.5 will contain zigbee2mqtt 1.5, and the work from PR #144 (which contains breaking changes!). Sorry, been a busy week for me, but I should be able to have the new version up either later this week or this weekend.

**Comment by mclaudiopt** [comment]
@danielwelch thanks a lot for your effort ! i will wait for your update ! thanks a lot

**Comment by kentux** [comment]
Hi,

1.5.1 version is available and fixes 2 bugs present in 1.5.0

**Comment by mclaudiopt** [comment]
any news @danielwelch ?
thanks
