### ISSUE TITLE
Feature request: Run 2 or more instance on hassio

### ISSUE THREAD

**Issue by dzungpv** [danielwelch/hassio-zigbee2mqtt#182]
Now i could run two instance at the same time with edge and stable version, with set two port for 2 usb/zigbee.
Is there anyway running two instance of the stable version @danielwelch ?

**Comment by alex-savin** [comment]
+1
Really need this option

**Comment by danielwelch** [comment]
I don't know of any way that hassio allows you to run 2 instances of the same image. You could create your own "add-on" using this repository as a base image in your Dockerfile and run that. Would probably be easiest to do this as a local add-on that you just rebuild as needed.
