### ISSUE TITLE
Downgrading to fix the breaking change doesn't work

### ISSUE THREAD

**Issue by lancelon** [danielwelch/hassio-zigbee2mqtt#188]
1.4.0

Hass.io

I, like many others, was hit by the breaking change in 1.5.1. Due to my auto update settings I unwittingly fell victim to this change when I was woken in the middle of the night by various automations being triggered by my Zigbee sensors going offline.

Given that today is NOT a day I have to spend hours detaching sensors and repairing them, I thought I might be able to temporarily fix the problem by rolling back to 1.4.0 using a snapshot and doing a partial restore. This does not work as the add on log is filled with references to 1.5.1 !

HELP!

(thanks!)

e.g
```
errno 1
npm
 ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm 
ERR! Exit status 1
```

**Comment by RWGaMeR** [comment]
I have the same mistake, as you see from pastebin

https://pastebin.com/GVuFLjh9

**Comment by lancelon** [comment]
@RWGaMeR  - https://community.home-assistant.io/t/zigbee2mqtt-typeerror-net-precfgkey-should-be-an-array-with-16-uint8-integers/127477/12?u=daneboom

**Comment by RWGaMeR** [comment]
@lancelon thanks, I have resolve

**Comment by danielwelch** [comment]
closing for now, please re-open if you have more issues
