### ISSUE TITLE
Update docker image on any commit to zigbee2mqtt master branch

### ISSUE THREAD

**Issue by danielwelch** [danielwelch/hassio-zigbee2mqtt#19]
Currently, zigbee2mqtt is doesn’t seem to have any form of versioning, as the pace of development is pretty fast. As a result, we’re building the image by just cloning the master branch into our docker container.

In docker hub, a new image is built and pushed with every commit to this repository’s master branch. However, updates to the underlying zigbee2mqtt library are not reflected in images until a new one is built (via changes/commits in this add-on). So users aren’t able to update zigbee2mqtt library if they are using the add-on until a new build.

The most obvious way I’ve seen to handle this is to add a github webhook in the zigbee2mqtt repository that POSTs to a web service (which I’ll create), which in turn calls the Travis API to trigger a build.

@Koenkk would you be willing to add a webhook when the time comes?

**Comment by Koenkk** [comment]
@danielwelch yes I can setup a webhook

**Comment by ciotlosm** [comment]
@danielwelch one other easier fix if the webhook takes time is to add cron job on travis to rebuild the image daily for now.

**Comment by Koenkk** [comment]
How-to: https://hiddentao.com/archives/2016/08/29/triggering-travis-ci-build-from-another-projects-build/

@danielwelch can you provide me your **encrypted** Travis API token?

**Comment by danielwelch** [comment]
@Koenkk see my thoughts in #16 

Also, my understanding of encrypting environment variables for travis is that the encryption is tied to the repository, meaning that I would need to give you the *unencrypted* token, which you would then encrypt via the `travis` CLI tool so that you could store it safely in your `.travis.yml`. If it didn't work this way, anyone could start making calls to my project's API as the encrypted token will be shared in your source control. Am I wrong here?

**Comment by Koenkk** [comment]
@danielwelch ok that makes sense, we need to find another way to do this.

**Comment by Koenkk** [comment]
Maybe this is not needed at all! Because you gave me access I also see this repo in travis now, going to test if I can trigger it.

**Comment by danielwelch** [comment]
The zigbee2mqtt library now uses a Travis script to trigger a rebuild of this add on directly on each commit to master branch! 

I added a note to documentation about needing to uninstall/reinstall the add on to update. Obviously, it would eventually be nice to use the update functionality within the Hassio UI rather than requiring an install/uninstall, but this will require versioned releases.

**Comment by ciotlosm** [comment]
Sorry to comment on a closed issue. 

I think zigbee2mqtt is getting closer and closer to getting stable enough to start release cycles. There is no major functionality missing, it has support for many devices, it's pretty stable, just a few quirks around max devices and zigbee-shepherd bugs and it should be good.
