### ISSUE TITLE
 how do i remove and re-associate all devices?

### ISSUE THREAD

**Issue by RWGaMeR** [danielwelch/hassio-zigbee2mqtt#190]
How do i remove and reassign all the hassio devices for adding network_key?
@Koenkk

**Comment by Koenkk** [comment]
- Remove `database.db`
- Reflash sniffer

**Comment by asyscom** [comment]
I boight a usb key ready and i don't have cable to do it.. Work around?

**Comment by RWGaMeR** [comment]
> * Remove `database.db`
> * Reflash CC2531

if I don't want to do this? is required?

**Comment by RWGaMeR** [comment]
if i use this key?
1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13

**Comment by RWGaMeR** [comment]
@Koenkk

**Comment by Koenkk** [comment]
Yes this is required

**Comment by RWGaMeR** [comment]
thanks, I have resolve and during the week I do a guide on my blog
