### ISSUE TITLE
Option problem with "zigbee_shepherd_devices "

### ISSUE THREAD

**Issue by GuGu927** [danielwelch/hassio-zigbee2mqtt#191]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.5.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Hass.IO

**Description of problem:**

Hi. My Version of Zigbee2MQTT is 1.5.1 on Hass.IO Add-on.

I'm using custom devices.js  with option  ["zigbee_shepherd_devices": true]
but it now works after upgrade.(1.4.0 -> 1.5.1)
I checked out there are no option about zigbee_shepherd_devices.
(https://github.com/danielwelch/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/config.json)

**Your entire configuration from the frontend (with sensitive fields redacted)**:
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": false,
  "permit_join": true,
  "zigbee_shepherd_devices": true,  << this line removed when I restart zigbee2mqtt add-on.
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "userid",
    "password": "userpw"
  },
  "serial": {
    "port": "/dev/ttyACM1",
    "disable_led": true
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [~~~~]
  }
}

**Your logs from Hass.io**
./run.sh: line 13: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
2019-07-22T00:06:38: PM2 log: Launching in no daemon mode
2019-07-22T00:06:38: PM2 log: App [npm:0] starting in -fork mode-
2019-07-22T00:06:38: PM2 log: App [npm:0] online
> zigbee2mqtt@1.5.1 start /zigbee2mqtt-1.5.1
> node index.js
  zigbee2mqtt:info 7/22/2019, 12:06:43 AM Logging to directory: '/share/zigbee2mqtt/log/2019-07-22.00-06-41'
  zigbee2mqtt:info 7/22/2019, 12:06:43 AM Starting zigbee2mqtt version 1.5.1 (commit #unknown)
  zigbee2mqtt:info 7/22/2019, 12:06:43 AM Starting zigbee-shepherd
  zigbee2mqtt:info 7/22/2019, 12:06:45 AM zigbee-shepherd started
  zigbee2mqtt:info 7/22/2019, 12:06:45 AM Coordinator firmware version: '20190608'
  zigbee2mqtt:info 7/22/2019, 12:06:45 AM Currently 8 devices are joined:
  zigbee2mqtt:info 7/22/2019, 12:06:45 AM goqual_livingroom_toilet (0x00158d00021202a2): unkown - undefined unknown (Router)
  zigbee2mqtt:info 7/22/2019, 12:06:45 AM goqual_kitchen (0x00158d0002125512): unkown - undefined unknown (Router)

**Comment by danielwelch** [comment]
Thanks for pointing this out. We started on these 1.5.1 breaking changes a long time ago and things have changed since then. I've pushed a fix (f01602a) and will after CI will try and push a patch release, v1.5.1.1

**Comment by GuGu927** [comment]
@danielwelch Thank you for your reply.
