### ISSUE TITLE
Request add option "homeassistant.js", "utils.js"

### ISSUE THREAD

**Issue by GuGu927** [danielwelch/hassio-zigbee2mqtt#194]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.5.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Hass.io

**Description of problem:**

Problem with edit 2 file on docker system.
1. lib/extension/homeassistant.js
2. lib/util/utils.js

When I uses custom devices.js, I also need to edit above files. 

File no.1 for mapping devices to homeassistant.
In my case

```
const mapping =
  'GQSWITCH_1': [configurations.switch],
    'GQSWITCH_2': [switchWithPostfix('top'),switchWithPostfix('bottom')],
    'GQSWITCH_3': [switchWithPostfix('top'),switchWithPostfix('center'),switchWithPostfix('bottom')],
    'GQSWITCH_4': [switchWithPostfix('top_left'),switchWithPostfix('bottom_left'),switchWithPostfix('top_right'),switchWithPostfix('bottom_right')],
    'GQSWITCH_5': [switchWithPostfix('top_left'),switchWithPostfix('center_left'),switchWithPostfix('bottom_left'),switchWithPostfix('top_right'),switchWithPostfix('bottom_right')],
    'GQSWITCH_6': [switchWithPostfix('top_left'),switchWithPostfix('center_left'),switchWithPostfix('bottom_left'),switchWithPostfix('top_right'),switchWithPostfix('center_right'),switchWithPostfix('bottom_right')],
```

File no.2 for custom postfix.
In my case.
find  word  `bottom_` in `lib/util/utils.js`.
and add `center_left, center_right`

Can you add option for these, please?

**Your entire configuration from the frontend (with sensitive fields redacted)**

```json
// replace this line with your pasted configuration
```

**Your logs from Hass.io**

**Comment by james-fry** [comment]
+1

**Comment by jpoconn87** [comment]
+1

**Comment by ciotlosm** [comment]
I think this should be re-evaluated in the light of this support: https://github.com/Koenkk/zigbee-herdsman-converters/issues/1343

**Comment by ciotlosm** [comment]
Closing based on https://github.com/danielwelch/hassio-zigbee2mqtt/issues/373#issuecomment-695191755 as this is supported through `external_converters`.
