### ISSUE TITLE
Add-on starup error

### ISSUE THREAD

**Issue by sebibv** [danielwelch/hassio-zigbee2mqtt#196]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.5.1
**Operating environment
HassIo

**Description of problem:**
I can't start the addon. I tried all the combination that I found online.

I'don't know what should I do...I'm trying this from 3 days ago without success... Please help.

I created also an empty configuration.yaml file because I got an error also for that.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "hassio",
    "password": "hassio"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "log_directory": "data/log/%TIMESTAMP%",
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      8,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ]
  }
}
```

**Your logs from Hass.io**
`> zigbee2mqtt@1.5.1 start /zigbee2mqtt-1.5.1
> node index.js
/zigbee2mqtt-1.5.1/lib/util/settings.js:150
    if (typeof s.devices === 'string') {
                 ^
TypeError: Cannot read property 'devices' of undefined
    at read (/zigbee2mqtt-1.5.1/lib/util/settings.js:150:18)
    at getSettings (/zigbee2mqtt-1.5.1/lib/util/settings.js:111:21)
    at Object.get (/zigbee2mqtt-1.5.1/lib/util/settings.js:380:52)
    at Object.<anonymous> (/zigbee2mqtt-1.5.1/lib/util/logger.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
npm
 ERR! code
 ELIFECYCLE
npm
 ERR! errno
 1
npm
 ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm 
ERR! Exit status 1
npm 
ERR! 
npm ERR!
 Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-22T16_47_06_359Z-debug.log`

**Comment by zepixir** [comment]
Does it help if you change your number 8 with 0 after number 15 in network key?

**Comment by sebibv** [comment]
Yesssssssssssssss!!!!!!!!!!!!!!!!!!
Thank you.
