### ISSUE TITLE
1.5.1.1 Reset to defaults gives not a valid value for dictionary value @ data['options'].

### ISSUE THREAD

**Issue by thoj** [danielwelch/hassio-zigbee2mqtt#197]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.5.1.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
hassos

**Description of problem:**

The default options gives error on save. I press Reset To Defaults and save and get this error:

```
not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt', 'server': 'mqtt://homeassistant', 'user': 'my_user', 'password': 'my_password'}, 'serial': {'port': '/dev/ttyACM0', 'disable_led': 'bool?'}, 'advanced': {'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13], 'availability_blacklist': []}, 'ban': [], 'whitelist': [], 'queue': {}}
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "my_user",
    "password": "my_password"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": "bool?"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**Comment by JarnoNijboer** [comment]
The option `"disable_led": "bool?"` is not a valid thing. I had the same issue, removing it from config makes it work.

**Comment by thoj** [comment]
Yeah i figured it out. It's there in thee default config so i opened a pull request fixing it.

**Comment by tigroz** [comment]
I'm on Hassos,
just upgraded to 1.5.1.1 and now config says:

**not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt', 'server': 'mqtt://homeassistant:1883', 'user': 'xxxx', 'password': 'xxxxx'}, 'serial': {'port': '/dev/ttyACM0'}, 'advanced': {'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]}, 'ban': [], 'whitelist': [], 'queue': {}}**
my config it's:
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant:1883",
    "user": "xxxx",
    "password": "xxxx"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ]
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}

**Comment by harkoprinssen** [comment]
Same here :(

**Comment by tigroz** [comment]
> I'm on Hassos,
> just upgraded to 1.5.1.1 and now config says:
> 
> **not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt', 'server': 'mqtt://homeassistant:1883', 'user': 'xxxx', 'password': 'xxxxx'}, 'serial': {'port': '/dev/ttyACM0'}, 'advanced': {'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]}, 'ban': [], 'whitelist': [], 'queue': {}}**
> my config it's:
> {
> "data_path": "/share/zigbee2mqtt",
> "devices": "devices.yaml",
> "groups": "groups.yaml",
> "homeassistant": true,
> "permit_join": false,
> "mqtt": {
> "base_topic": "zigbee2mqtt",
> "server": "mqtt://homeassistant:1883",
> "user": "xxxx",
> "password": "xxxx"
> },
> "serial": {
> "port": "/dev/ttyACM0"
> },
> "advanced": {
> "pan_id": 6754,
> "channel": 11,
> "network_key": [
> 1,
> 3,
> 5,
> 7,
> 9,
> 11,
> 13,
> 15,
> 0,
> 2,
> 4,
> 6,
> 8,
> 10,
> 12,
> 13
> ]
> },
> "ban": [],
> "whitelist": [],
> "queue": {}
> }

found solution,
i had to reset to the default settings of the config, fill in the mqtt login and password, change : 
"disable_led": "bool?" 
to
"disable_led": "false"
now the add-on starts without errors...

**Comment by harkoprinssen** [comment]
Yep, also did that. seems there is some change we are overlooking, nonetheless it works again!

**Comment by KaiboshOz** [comment]
For anyone else that the above didn't work (or they have additional options beyond the defaults) - I reset to default, copied and pasted that elsewhere and then adjusted to match my old settings.. No matter what I did it would not save.
The only way I could get the addon config to save was to again reset to defaults, and then update within the addon page, 1 entry at a time, saving each time.  What I ended up with is virtually identical to what I was pasting in there and was refusing to save - but it saved now..

**Comment by SpuriousGer** [comment]
Adding `,"availability_blacklist": []` after the network key did the trick for me.

**Comment by adrianmihalko** [comment]
socat must be in config. :/
