### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by motoolfan** [danielwelch/hassio-zigbee2mqtt#20]
I'm getting the following error:

[Info] Configuration file found. Will overwrite configurable               fields with values from add-on configuration
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
> zigbee2mqtt@0.1.0 start /app
> node index.js
2018-5-28 06:25:50 INFO Starting zigbee-shepherd
2018-5-28 06:25:53 ERROR Error while starting zigbee-shepherd!
2018-5-28 06:25:53 ERROR Failed to start

Any ideas would be greatly appreciated.

**Comment by dzungpv** [comment]
There some reason:
1, Wrong usb port.
2, The CC2531 dongle hang, i face this some times, unplug it or turn off the pi and then turn on.

**Comment by ciotlosm** [comment]
@motoolfan You can try to start it in debug mode to see more messages, but probably zigbee-shepherd can't see the CC2531

@dzungpv Did you ever try pressing the button on the dongle to avoid a complete turn off / turn on of the pi?

**Comment by motoolfan** [comment]
Figured out the node/npm issues, Will be working on the port after work. Thanks for the help.
