### ISSUE TITLE
Problem with device pairing 1.5.1.1

### ISSUE THREAD

**Issue by GuGu927** [danielwelch/hassio-zigbee2mqtt#200]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.5.1.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Hass.io

**Description of problem:**
When i pair devices, error occurs often.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": false,
  "permit_join": true,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "~~",
    "password": "~~~~"
  },
  "serial": {
    "port": "/dev/ttyACM1",
    "disable_led": true
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [~~~~~~
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "zigbee_shepherd_devices": true
}

```

**Your logs from Hass.io**

  zigbee2mqtt:info 7/23/2019, 10:14:45 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d00023f4f88","meta":{"modelID":"lumi.weather"}}'
/zigbee2mqtt-1.5.1/lib/extension/deviceReceive.js:109
                if (c.cid === cid) {
                      ^
TypeError: Cannot read property 'cid' of undefined
    at mappedDevice.fromZigbee.filter (/zigbee2mqtt-1.5.1/lib/extension/deviceReceive.js:109:23)
    at Array.filter (<anonymous>)
    at DeviceReceive.onZigbeeMessage (/zigbee2mqtt-1.5.1/lib/extension/deviceReceive.js:105:52)
    at extensions.filter.forEach (/zigbee2mqtt-1.5.1/lib/controller.js:143:31)
    at Array.forEach (<anonymous>)
    at Controller.onZigbeeMessage (/zigbee2mqtt-1.5.1/lib/controller.js:143:14)
    at Zigbee.onMessage (/zigbee2mqtt-1.5.1/lib/zigbee.js:275:18)
    at ZShepherd.emit (events.js:198:13)
    at ZShepherd.<anonymous> (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/shepherd.js:148:14)
    at ZShepherd.emit (events.js:198:13)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.5.1 start script.
npm 
ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by GuGu927** [comment]
Um..
This error occurs not only pairing devices but also update status.

**Comment by GuGu927** [comment]
I found the reason.
I'm using  "WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor"
When sensor updates, it make problem.
It was not occurs  on version 1.5.1

Here's error code.

2019-07-23T13:39:47.983Z zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: {"groupid":0,"clusterid":0,"srcaddr":44059,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":39,"securityuse":0,"timestamp":13425816,"transseqnumber":0,"len":44,"data":{"0":24,"1":167,"2":10,"3":1,"4":255,"5":66,"6":37,"7":1,"8":33,"9":169,"10":11,"11":4,"12":33,"13":168,"14":19,"15":5,"16":33,"17":50,"18":0,"19":6,"20":36,"21":0,"22":0,"23":0,"24":0,"25":0,"26":100,"27":41,"28":77,"29":10,"30":101,"31":33,"32":93,"33":24,"34":102,"35":43,"36":182,"37":132,"38":1,"39":0,"40":10,"41":33,"42":39,"43":216},"zclMsg":{"frameCntl":{"frameType":0,"manufSpec":0,"direction":1,"disDefaultRsp":1},"manufCode":0,"seqNum":167,"cmdId":"report","payload":[{"attrId":65281,"dataType":66,"attrData":{"1":2985,"4":5032,"5":50,"6":[0,0],"10":55335,"100":2637,"101":6237,"102":99510}}]}}
  zigbee2mqtt:debug 7/23/2019, 10:39:47 PM Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"65281":{"1":2985,"4":5032,"5":50,"6":[0,0],"10":55335,"100":2637,"101":6237,"102":99510}}}' of device 'lumi.weather' (0x00158d00022728f7) of endpoint 1
  
  2019-07-23T13:40:40.203Z zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: {"groupid":0,"clusterid":0,"srcaddr":7743,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":76,"securityuse":0,"timestamp":13589125,"transseqnumber":0,"len":19,"data":{"0":24,"1":46,"2":10,"3":5,"4":0,"5":66,"6":12,"7":108,"8":117,"9":109,"10":105,"11":46,"12":119,"13":101,"14":97,"15":116,"16":104,"17":101,"18":114},"zclMsg":{"frameCntl":{"frameType":0,"manufSpec":0,"direction":1,"disDefaultRsp":1},"manufCode":0,"seqNum":46,"cmdId":"report","payload":[{"attrId":5,"dataType":66,"attrData":"lumi.weather"}]}}
  zigbee2mqtt:debug 7/23/2019, 10:40:40 PM Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"modelId":"lumi.weather"}}' of device 'lumi.weather'

**Comment by bmtKIA6** [comment]
I am unable to pair anything either. However, I get the following errors, when trying to pair:

7/23/2019, 5:42:04 PM - error: Cannot get the Node Descriptor of the Device: 0x00158d00036b7518 (Error: Timed out after 10000 ms)

**Comment by liutikas** [comment]
I'm in the same boat. After updating to 1.5.1 and later 1.5.1.1 I am unable to pair any of my Xiaomi sensors (door and presence sensor).

Here is my config:
```
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "foo",
    "password": "bar"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": true
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [...],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**Comment by GJ2019** [comment]
I had the same issues. Decided to update to 1.5.1, restore to defaults, and deleted my database file. Once done, I decided to re-pair all my devices. Luckily the device id’s are still the same , so don’t have to change my automations and Lovelace interface. After all this costs me 30 to 45 minutes. Most of the work was taking of the sensors from the walls :-)

**Comment by GuGu927** [comment]
I think zigbee shepherd makes problem

**Comment by bmtKIA6** [comment]
@liutikas I had solved my issue by enabling the shepherd debugging and restarting the add-on.

Once the debugging is on, you should be able to see more detailed zigbee debugging info and see if there is any traffic.

I think, "reenabling joining" is also not working properly, as I was able to re-pair the devices on the first/initial pairing enabled run. After, that I had to restart the add-on.

**Comment by liutikas** [comment]
@bmtKIA6 how do you enable the shepherd debugging? 

https://www.zigbee2mqtt.io/how_tos/how_to_debug.html does not really explain how to do so in hassio situation and 
```
advanced:
  log_level: debug
```
does not seem to give much details about what's happening.

**Comment by bmtKIA6** [comment]
@liutikas 
add the following to the json config:   "zigbee_shepherd_debug": true

ie

{
 "zigbee_shepherd_debug": true,
...
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "grou
...
}

**Comment by GuGu927** [comment]
@bmtKIA6 oh. Thx. I'll try

**Comment by GuGu927** [comment]
xiaomi temperature sensor    "undefined"
when update status, get erroe

**Comment by xppx99** [comment]
Hello! 
I also have this problem. Upgraded today from 1.4 to 1.5 and I cant pair the new xiaomi sensors: Aqara door sensor, and aqara occupancy sensor.

**Comment by panache67** [comment]
I got the same issue. Is there any option to re-install 1.4 ? Unfortunately I missed to backup the old addon :-(

**Comment by captaindaveman** [comment]
I have this issue also, not sure since when but I’m on version 1.5.1.2 and cannot pair any new devices

**Comment by panache67** [comment]
@captaindaveman I 'solved' the issue for now by going back to version 1.4. 
I removed the zigbee2mqtt repo, cloned the hassio-zigbee2mqtt/zigbee2mqtt/ with tag 1.4 into the /addon/ directory. Works like a charm.

**Comment by captaindaveman** [comment]
@panache76 sounds great, but I don’t follow exactly what you’ve done here, do you mean remove the share?

**Comment by panache67** [comment]
@captaindaveman 
sorry - in a bit more detail: 
- uninstall zigbee2mqtt in HA under Hass.io addons 
- remove the zigbee2mqtt repository under Hass.io add-on store
- clone or download this repo tagged with 1.4, e.g. https://github.com/danielwelch/hassio-zigbee2mqtt/archive/v1.4.0.zip
[- extract the archive]
- copy the zigbee2mqtt folder to /addon/ on your HA machine, e.g. via SCP or SMB. 
- reload Hass.io add-on store and under Local add-ons there should be an entry for zigbee2mqtt 
- install the zigbee2mqtt add on
