### ISSUE TITLE
addon config not correct in version 1.5.1.1 - UPDATE - FIX INSIDE

### ISSUE THREAD

**Issue by aaamoeder** [danielwelch/hassio-zigbee2mqtt#202]
**zigbee2mqtt add-on version (if edge, please report commit hash):1.5.1.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):HASSIO
linux distro running hassio

**Description of problem:**
after update to 1.5.1.1 addon won't start, uninstalled an reinstalled and now it seems my config is not getting accepted anymore ?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "[]",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "*****",
    "password": "*****",
    "client_id": "zigbee2mqtt"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": true
  },
  "advanced": {
    "log_level": "info",
    "availability_timeout": 60,
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ]
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

error I get is : not a valid value for dictionary value @ data['options'].

**Comment by aaamoeder** [comment]
Already fixed it, but keeping this as heads up for others..
seems that after the update to 1.5.1.1 I needed to add 
"availability_blacklist": []" as you can see in my new config here:
`{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "*****",
    "password": "*****",
    "client_id": "zigbee2mqtt"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": true
  },
  "advanced": {
    "log_level": "info",
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}`

**Comment by Chimerique** [comment]
Personnaly I had to create the old configuration.yaml file for the app to start

**Comment by danielwelch** [comment]
Yes, any time a new configuration option is added that is "required", it needs to be added to your config. Of course, `availability_blacklist` isn't required, but the empty list is unfortunately required due to hass.io's weird handling of nested configuration.
