### ISSUE TITLE
Networkmap issue

### ISSUE THREAD

**Issue by furiaceka87** [danielwelch/hassio-zigbee2mqtt#203]
When I try to use Networkmap command:

mosquitto_sub -h 192.168.1.xx -p 1883 -u xx -P yy -C 1 -t zigbee2mqtt/bridge/networkmap/raw

or

mosquitto_sub -h 192.168.1.xx -p 1883 -u xx -P yy -C 1 -t zigbee2mqtt/bridge/networkmap/graphviz

I always receive nothing as answer.
I need to ctrl+c to terminate the command. I wait one hour after reboot but still no lucky.

Do you have some issue with 1.5.1.1 version of the addon?

**Comment by SittingDuc** [comment]
Not quite. You need two commands, one mosquito_sub on -t 'zigbee2mqtt/bridge/#' or similar. The second command is mosquito_pub -t 'zigbee2mqtt/bridge/networkmap' -m 'raw'
Or -m 'graphviz'.
You are sending a message with payload "raw" or "graphviz" to the topic "zigbee2mqtt/bridge/networkmap", which the bridge is listening to. The bridge then replies with a json/graphviz to the same topic.

(Not at my computer, hope I got the punctuation right)

**Comment by furiaceka87** [comment]
It’s work on my iPhone I will show you result as soon as I can use a laptop.

**Comment by furiaceka87** [comment]
Seems that two sensors are directly connected to the Router as expected!
