### ISSUE TITLE
Fresh install of z2m addon doesn't work - restoring 1.4.x backup and updating to 1.5.x works

### ISSUE THREAD

**Issue by h4nc** [danielwelch/hassio-zigbee2mqtt#205]
I friend of mine has a strange issue. It looks like it's related to the newest version(1.5.1) of the addon.

On a fresh hassio install he is not able to install the z2m addon. 

If he restores an old backup (1.4.x) and updates z2m 1.5.1 works fine. 

We noticed that in the fresh installation of hassio the z2m doesn't create new files in the `share` folder. 
So it looks like it's only able to update, if these files/folders already exist.

Maybe this has something to to with the backup feature?

Unfortunately I only have picture of his log:

![IMG_0420-2](https://user-images.githubusercontent.com/25117255/62126590-54f82100-b2d0-11e9-9d18-f071c036ef81.jpeg)

**Comment by danielwelch** [comment]
Should be fixed by #204

**Comment by danielwelch** [comment]
Releasing v1.5.1.2, which includes the above fix. I'll close for now but re-open if you're still experiencing problems.

**Comment by h4nc** [comment]
1.5.1.2 doesn’t show up yet, can you tell when will it be available?

**Comment by h4nc** [comment]
@danielwelch 1.5.1.2 still doesn’t appear as an update.

**Comment by h4nc** [comment]
Just want to note that this update fixed the issue. Thanks
