### ISSUE TITLE
Hou to add transition length when the color changes?

### ISSUE THREAD

**Issue by kvvoff** [danielwelch/hassio-zigbee2mqtt#208]
I use light bulbs E27, E14 and a led controller GL-C-008 from Gledopto.
When I turn on the light - the transition length is present and the light turns on smoothly. 
When I turn off the light - it also turns off smoothly. 
**But when I change colors or change the temperature with the lights on**, everything happens at lightning speed and is unpleasant for the eyes. 
How to fix it? 
How to make the **transition** length work **not only when turned on and off**, but also **when the color changes**?

**Comment by danielwelch** [comment]
This belongs in the zigbee2mqtt repo, not here, as the issue template suggests.
