### ISSUE TITLE
Unable to add new device to devices.js

### ISSUE THREAD

**Issue by dpicts** [danielwelch/hassio-zigbee2mqtt#210]
**zigbee2mqtt add-on version (if edge, please report commit hash):
1.5.1.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
hassio running on ubuntu (latest version) on an AtomicPi
**Description of problem:**
I have a device which is not currently supported and needs to be added per [https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html).
I opened a bash shell in the container and used vi to add my device to the end of the file. (used cat devices.js afterwards to confirm the change was saved.)  then when I restart the addon, the change has been erased...
How do I add my change to addon?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "[]",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.2.50",
    "user": "myuser",
    "password": "mypass"
  },
  "serial": {
    "port": "/dev/ttyACM1"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "availability_blacklist": [],
    "network_key": [
      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
    ]
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**Your logs from Hass.io**
```
  zigbee2mqtt:warn 8/4/2019, 10:47:46 AM Device with modelID 'Connected A-19 60W Equivalent   ' is not supported.
  zigbee2mqtt:warn 8/4/2019, 10:47:46 AM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```

**Comment by freenetwork** [comment]
Copy https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js to /share/zigbee2mqtt. Add your device to devices.js (Read docs)

add "zigbee_shepherd_devices": true in configure and start
