### ISSUE TITLE
HASS' MQTT broker is deprecated, recommend to use Mosquitto addon

### ISSUE THREAD

**Issue by iBobik** [danielwelch/hassio-zigbee2mqtt#211]
It seems embeded broker is deprecated: https://www.home-assistant.io/docs/mqtt/broker#embedded-broker-deprecated

In Hass.io is is super simple to install Mosquitto. How about to rewrite default config to support it by default?
```
"mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto",
```

**Comment by ambarusa** [comment]
I have no experience with zigbee2mqtt, but I'm already using Mosquitto. @iBobik I tried this server address, which I suppose is referring to the Mosquitto running locally, but sadly I don't see my client_id in the Mosquitto log.

**Comment by iBobik** [comment]
And do dou see on client service that is connected to the broker?

Btw, I tried to restart zigbee2mqtt and this appeared in the broke’s log:
```
1565107350: Socket error on client mqttjs_f708684e, disconnecting.
1565107361: New connection from 172.30.33.0 on port 1883.
[INFO] found zigbee on Home Assistant
1565107362: New client connected from 172.30.33.0 as mqttjs_9d119010 (p2, c1, k60, u'zigbee').
```

**Comment by danielwelch** [comment]
I'm ok with updating the defaults here to something more sensible given the deprecation.
