### ISSUE TITLE
How to specify device_options in hass.io config?

### ISSUE THREAD

**Issue by milakov** [danielwelch/hassio-zigbee2mqtt#213]
Hi, whenever I add "device_options" section to hass.io config, it gets discraded when I start the plugin. What is the right way to do it now? Thanks!

**Comment by milakov** [comment]
This option is mentioned at https://www.zigbee2mqtt.io/configuration/device_specific_configuration.html and it have been working fine.

**Comment by danielwelch** [comment]
See the README, [section on configuration](https://github.com/danielwelch/hassio-zigbee2mqtt#configuration), number 3.

The way that the add-on set the configuration in version 1.5 changed, so that's the reason the way you mention is no longer possible. Sorry for the inconvenience.

**Comment by milakov** [comment]
But I am talking not about device-specific settings, but about global device settings specified with `device_options`, I think it should be defined in general config file, not in `devices.yaml`. Is there a way to enable the corresponding json section in the hass.io add-on config, which would be translated into `device_options`, the same way `serial` or `advanced` sections are enabled?

Thanks!

**Comment by danielwelch** [comment]
Sorry, I see what you mean now. So, is that option defined as a top level option in configuration.yaml? It’s not clear to me from the docs.

**Comment by milakov** [comment]
Docs for some reason forget to talk about this option at https://www.zigbee2mqtt.io/configuration/configuration.html, this option is mentioned only at https://www.zigbee2mqtt.io/configuration/device_specific_configuration.html. This one worked fine for me in z2m's configuration.yaml file:
```
device_options:
  occupancy_timeout: 120
  humidity_precision: 1
  pressure_precision: 1
  temperature_precision: 1
```

**Comment by danielwelch** [comment]
Is that the complete set of options allowed? And just to clarify again, this is a top-level option, correct? The docs don’t clearly spell this out, but I’d be happy to implement this.

**Comment by milakov** [comment]
I don't think this is a complete list. For example, https://www.zigbee2mqtt.io/devices/RTCGQ11LM suggests there could be `no_occupancy_since` parameter, there might be others as well.

**Comment by milakov** [comment]
@danielwelch Would translating ane unknown parameters from json to yaml be a solution?

**Comment by ciotlosm** [comment]
@milakov Can this issue be closed considering https://github.com/Koenkk/zigbee2mqtt/issues/1905 was also closed?

**Comment by milakov** [comment]
I am fine with closing it. For now I am just setting all the parameters on a per device basis, not a big overhead if number of devices is small.

**Comment by bbccdd** [comment]
Was this issue ever resolved? I've just reopened issue .. but perhaps a solution was found, for zigbee groups specifically. https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/356
