### ISSUE TITLE
 ZNMS12LM - Xiaomi Aqara S2 Lock 

### ISSUE THREAD

**Issue by Omerdagan** [danielwelch/hassio-zigbee2mqtt#214]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.5.1.2 

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

**Description of problem:**
door lock worked fine until the first reboot. id of the lock (fingerprint user or password) is no longer getting published to mqtt

**Your entire configuration from the frontend (with sensitive fields redacted)**:
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "[]",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "user",
    "password": "password"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}

**Your logs from Hass.io**

  zigbee2mqtt:info 8/13/2019, 9:23:03 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00029147c2', payload '{"user":null,"repeat":null,"linkquality":92,"state":"LOCK","reverse":"UNLOCK"}'
  zigbee2mqtt:info 8/13/2019, 9:23:03 PM MQTT publish: topic 'homeassistant/sensor/0x00158d00029147c2/action/config', payload '{"icon":"mdi:gesture-double-tap","value_template":"{{ value_json.action }}","state_topic":"zigbee2mqtt/0x00158d00029147c2","json_attributes_topic":"zigbee2mqtt/0x00158d00029147c2","name":"0x00158d00029147c2_action","unique_id":"0x00158d00029147c2_action_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00029147c2"],"name":"0x00158d00029147c2","sw_version":"Zigbee2mqtt 1.5.1","model":"Aqara S2 Lock (ZNMS12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/13/2019, 9:23:03 PM MQTT publish: topic 'homeassistant/binary_sensor/0x00158d00029147c2/lock/config', payload '{"payload_on":"UNLOCK","payload_off":"LOCK","value_template":"{{ value_json.state}}","device_class":"lock","state_topic":"zigbee2mqtt/0x00158d00029147c2","json_attributes_topic":"zigbee2mqtt/0x00158d00029147c2","name":"0x00158d00029147c2_lock","unique_id":"0x00158d00029147c2_lock_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00029147c2"],"name":"0x00158d00029147c2","sw_version":"Zigbee2mqtt 1.5.1","model":"Aqara S2 Lock (ZNMS12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/13/2019, 9:23:03 PM MQTT publish: topic 'homeassistant/binary_sensor/0x00158d00029147c2/lock_reverse/config', payload '{"payload_on":"UNLOCK","payload_off":"LOCK","value_template":"{{ value_json.reverse}}","device_class":"lock","state_topic":"zigbee2mqtt/0x00158d00029147c2","json_attributes_topic":"zigbee2mqtt/0x00158d00029147c2","name":"0x00158d00029147c2_lock_reverse","unique_id":"0x00158d00029147c2_lock_reverse_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00029147c2"],"name":"0x00158d00029147c2","sw_version":"Zigbee2mqtt 1.5.1","model":"Aqara S2 Lock (ZNMS12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/13/2019, 9:23:03 PM MQTT publish: topic 'homeassistant/sensor/0x00158d00029147c2/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00158d00029147c2","json_attributes_topic":"zigbee2mqtt/0x00158d00029147c2","name":"0x00158d00029147c2_linkquality","unique_id":"0x00158d00029147c2_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00029147c2"],"name":"0x00158d00029147c2","sw_version":"Zigbee2mqtt 1.5.1","model":"Aqara S2 Lock (ZNMS12LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/13/2019, 9:23:03 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.5.1","commit":"unknown","coordinator":20190608,"log_level":"info","permit_join":false}'
  zigbee2mqtt:info 8/13/2019, 9:56:52 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00029147c2', payload '{"user":null,"repeat":null,"linkquality":81,"state":"LOCK","reverse":"UNLOCK"}'
  zigbee2mqtt:info 8/13/2019, 10:25:41 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00029147c2', payload '{"user":null,"repeat":null,"linkquality":84,"state":"LOCK","reverse":"UNLOCK"}'
  zigbee2mqtt:info 8/13/2019, 10:26:23 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00029147c2', payload '{"user":null,"repeat":1,"linkquality":2,"state":"LOCK","reverse":"UNLOCK","action":"finger_not_match"}'
  zigbee2mqtt:info 8/13/2019, 10:26:23 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00029147c2', payload '{"user":null,"repeat":1,"linkquality":2,"state":"LOCK","reverse":"UNLOCK","action":""}'
  zigbee2mqtt:info 8/13/2019, 10:26:35 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00029147c2', payload '{"user":null,"repeat":null,"linkquality":94,"state":"LOCK","reverse":"UNLOCK"}'
  zigbee2mqtt:info 8/13/2019, 10:26:36 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00029147c2', payload '{"user":null,"repeat":null,"linkquality":86,"state":"LOCK","reverse":"UNLOCK","action":"locked"}'
  zigbee2mqtt:info 8/13/2019, 10:26:36 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00029147c2', payload '{"user":null,"repeat":null,"linkquality":86,"state":"LOCK","reverse":"UNLOCK","action":""}'

**Comment by danielwelch** [comment]
This should probably be posted in the zigbee2mqtt repo
