### ISSUE TITLE
Please add dev branch

### ISSUE THREAD

**Issue by freenetwork** [danielwelch/hassio-zigbee2mqtt#215]
Please add addon from dev branch https://github.com/Koenkk/zigbee2mqtt/tree/dev
It is need for test custom device at home assistant

**Comment by freenetwork** [comment]
zigbee2mqtt-edge it is dev?

**Comment by james-fry** [comment]
@danielwelch please can you confirm (or link to doc/issue) how the zigbee2mqtt-edge branch gets updated? 
Is it automatically updated nightly or udpated based on tracking version additionas in https://github.com/Koenkk/zigbee2mqtt/tree/dev?

**Comment by Koenkk** [comment]
It's automatically updated, edge = zigbee2mqtt-dev

**Comment by james-fry** [comment]
Thank for confirming.
