### ISSUE TITLE
zigbee2mqtt 1.5.1.2 -Heiman sensor "GAS_V15" is not supported 

### ISSUE THREAD

**Issue by vencakratky** [danielwelch/hassio-zigbee2mqtt#219]
Hello,
 i am only basic user with HA, but i have devices from Heiman (Smart Plug metering) and this Gas (zigbee) sensor. Smart Plug working well, but with Gas sensor is Problem.
[](http://www.heimantech.com/c/88/76.html

Please, it´s possible in next update add this device? 
I found some tutorials, how add new device, but i am really only "new user" and cannot this with docker and other :(
Many times thank you 

**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.5.1.2
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
Raspberry 4 - 32bit - Version 0.97.2

**Your logs from Hass.io**
zigbee2mqtt:warn 8/27/2019, 11:06:14 PM Device with modelID 'GAS_V15' is not supported.
  zigbee2mqtt:warn 8/27/2019, 11:06:14 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

**Comment by danielwelch** [comment]
this should be posted in the zigbee2mqtt repo, as the issue template suggests
