### ISSUE TITLE
Devices in config file

### ISSUE THREAD

**Issue by AlexBoosh** [danielwelch/hassio-zigbee2mqtt#220]
Hi.
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.5.1.2 
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
Armbian, Hass.io running on Rock64

**Description of problem:**
I want to give it a friendly-name.
I add in config this string:
` "devices": "{'0x00158d00025ee533': {'friendly_name': 'AqaraTemper', 'retain': False}}",`

Config is OK, zigbee2mqtt restart successfully, but my friendly-name does not applycated (
In logs I see:
`zigbee2mqtt:info 9/2/2019, 12:41:36 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00025ee533', payload '{"temperature":17.3,"linkquality":84,"humidity":67.78,"pressure":974.3,"battery":100,"voltage":3025}'`

If I add this code:
```
'0x00158d00025ee533':
  friendly_name: 'AqaraTemper'
 retain: false
```
in device.yaml file - all is OK, friendly_name is working.
But I want use configuration.yaml only. That I doing wrong?
Thanks

**Comment by danielwelch** [comment]
Device-specific configuration is only supported via a separate file as the README says. I'm surprised your configuration isn't rejected by the hassio schema validation. If you include your entire configuration, that would help.

**Comment by AlexBoosh** [comment]
Daniel, my zigbee2mqtt configuration file:

```
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "{'0x00158d00025ee533': {'friendly_name': 'AqaraTemper', 'retain': False}}",
  "groups": "groups.yaml",
  "homeassistant": false,
  "permit_join": true,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.1.67:1883",
    "user": "***",
    "password": "***"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": true
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": [],
    "log_level": "debug"
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```
It's work but without friendly-name )

**Comment by mason-xx** [comment]
Im just struggeling with the same, I have them in a seperated devices.yaml. But HA doesn't pick up on them. Where does the file need to be located? I the /share folder I guess? And does it need to be json or yaml? (Tried both without success anyway)

**Comment by AlexBoosh** [comment]
Hello.
My device.yaml located in /usr/share/hassio/share/zigbee2mqtt/
In yaml. My devices:

'0x00158d00025ee533':
  friendly_name: 'AqaraTemp'
  retain: false

**Comment by danielwelch** [comment]
Gotcha. So this passes the schema check because you've included the JSON as a string, but the string is just supposed to be a path to your device-specific configuration file. I'm going to close this now, as what you're trying to do isn't supported, but it may be in a future release if the schema restrictions from Hass.io change.
