### ISSUE TITLE
Give a simple way to remove device from mqtt broker + zigbee2mqtt + ha

### ISSUE THREAD

**Issue by kentux** [danielwelch/hassio-zigbee2mqtt#223]
zigbee2mqtt add-on version : 1.5.1.2 

Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io): HassOS on RPi3 B+

Hi,

When I search on multiple forum, I can see that a lot of people have problem to remove easily a device from MQTT broker, ZigBee2MQTT and HA.

Is it possible to add this feature into this add-on ?

Regards,

**Comment by kentux** [comment]
> 
> 
> Did you try using [Zigbee2MqttAssistant](https://github.com/yllibed/Zigbee2MqttAssistant)? It's not solving all problems, but it's less hassle than manually writing topics in your broker...

Thank you @carldebilly ! I will try it this afternoon ;-)

**Comment by danielwelch** [comment]
closing as this is not an add-on issue, although discussion welcome!
