### ISSUE TITLE
Please update to Zigbee2Mqtt v1.6

### ISSUE THREAD

**Issue by carldebilly** [danielwelch/hassio-zigbee2mqtt#224]
Zigbee2Mqtt version 1.6 is now available.

**Comment by james-fry** [comment]
Do you know: will the edge addon pull the latest z2m using zigbee-herdsman?

**Comment by Koenkk** [comment]
@james-fry yes, edge is in sync with zigbee2mqtt 1.6 dev

**Comment by james-fry** [comment]
Thanks for the clarification

**Comment by Swiftnesses** [comment]
Can we push this to Hass.io?

**Comment by carldebilly** [comment]
@Koenkk But what I want is the 1.6 _non-dev_ version... :-(

**Comment by dzungpv** [comment]
@Koenkk I think you must handle this, @danielwelch too busy for this project.
@danielwelch could you add Koen as maintainer/manager of this project so he can manage, example pull request when new version release?

**Comment by BarBaar44** [comment]
Just updated to 1.6.o Running hassio on Odroid c2. Seems to have an issue

`[Info] Searching for custom devices file in zigbee2mqtt data path...
2019-09-13T10:24:06: PM2 log: Launching in no daemon mode
2019-09-13T10:24:06: PM2 log: App [npm:0] starting in -fork mode-
2019-09-13T10:24:06: PM2 log: App [npm:0] online
> zigbee2mqtt@1.6.0 start /zigbee2mqtt-1.6.0
> node index.js
/zigbee2mqtt-1.6.0/lib/util/utils.js:44
        .map((mappedModel) => mappedModel.zigbeeModel));
                                          ^
TypeError: Cannot read property 'zigbeeModel' of undefined
    at flatten.map.map (/zigbee2mqtt-1.6.0/lib/util/utils.js:44:43)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/zigbee2mqtt-1.6.0/lib/util/utils.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR!
 Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by ademobile** [comment]
Did not go well for me, nothing is now connected to the network. Check all IDs etc and all seem correct. Did not expect to have to re-pair everything just for an update :-(

**Comment by dzungpv** [comment]
@ademobile you update from version 1.5? If you have snapshot try to revert back, remember things with home assistant: always backup before update

**Comment by ademobile** [comment]
Did not have a snapshot as I have been testing my devices as I had been having a lot of issues with Xiaomi switches just not working. These were using deCONZ before. Its not a big network of 16 devices, however these have been so stable using zigbe2mqtt! Obvouisly this is just my experience and want to know if others have had the same. I was running 1.5.1.2 before this.

**Comment by dzungpv** [comment]
@ademobile I am running network with 21 devices, Zigbee 3.0.2 . You can try to stop z2mqtt, unplug the CC2530/2531 leave it 30 seconds and then re plug it/start z2mqtt

**Comment by Koenkk** [comment]
@BarBaar44 did you map a custom `devices.js`/`zigbee-shepherd-converters`? if so, please remove it.

**Comment by ademobile** [comment]
@dzungpv tried as you suggested, however no change. I did catch this in the logs though:

zigbee2mqtt:error 9/13/2019, 9:51:06 AM Failed to mount the cieApp
  zigbee2mqtt:warn 9/13/2019, 9:51:07 AM Failed to configure 0x[address removed] (0x[address removed]) ('Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.') (attempt #1)
  zigbee2mqtt:warn 9/13/2019, 9:51:07 AM This can be ignored if the device is working properly
/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:155
                throw e;
                ^
TypeError: Cannot read property 'ieeeAddr' of undefined
    at Zigbee.getCoordinator (/zigbee2mqtt-1.6.0/lib/zigbee.js:294:42)
    at queue.push (/zigbee2mqtt-1.6.0/lib/extension/deviceConfigure.js:53:84)
    at Queue.start (/zigbee2mqtt-1.6.0/node_modules/queue/index.js:145:17)
    at next (/zigbee2mqtt-1.6.0/node_modules/queue/index.js:120:16)
    at mappedDevice.configure (/zigbee2mqtt-1.6.0/lib/extension/deviceConfigure.js:79:21)
    at setTimeout (/zigbee2mqtt-1.6.0/node_modules/zigbee-shepherd-converters/devices.js:127:21)
    at /zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:2059:17
    at runSingle (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:137:13)
    at flush (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm
 ERR! code ELIFECYCLE
npm ERR!
 errno 1
npm ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-13T08_51_07_059Z-debug.log
2019-09-13T09:51:07: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-09-13T09:51:07: PM2 log: App [npm:0] starting in -fork mode-
2019-09-13T09:51:07: PM2 log: App [npm:0] online

**Comment by dzungpv** [comment]
@ademobile try to change other usb port, i have this problem sometime, but strange it happen with you after update. The final solution with you is erase coordinator flash and then re-flash the stable firmware, your network will automatically restore by z2mqtt

**Comment by BarBaar44** [comment]
> @BarBaar44 did you map a custom `devices.js`/`zigbee-shepherd-converters`? if so, please remove it.

Yes, I did. Just removed it. But no luck :(

**Comment by ademobile** [comment]
@dzungpv tried all that and no joy, also tried to re-join devices and they won't. Really in a mess now as other half is going mad! Any way of getting 1.5.1.2 re-installed back in HASS?

**Comment by ericmiller777** [comment]
Sometimes it just needs a while for the network to rebuild, then you need to sometimes switch your devices on/off. Set it up and leave it alone for a while if you can.

**Comment by ademobile** [comment]
@ericmiller777 been off for ages and I should be able to re-pair a device (had done many times so far!). All devices in network have be switched off and on again. Cannot leave it as I am getting shouted at!

**Comment by ademobile** [comment]
After a lot of 'playing around', pairing started working again. Network is now back up and running. In the end I removed the add-on again. Deleted all folders and started again. A bit drastic, however when needs must!

**Comment by danielwelch** [comment]
Do you have enough disk space? At least in the past, there were reports of (very unhelpful) 500 error codes from Hassio when disk space was full. I’ve experienced the “image not found” error in the past when disk space was full, but not what you’re seeing.

**Comment by CMDR-Sloma** [comment]
What has changed in this version? Sorry for asking but there is no changelog since 1.4.

**Comment by Koenkk** [comment]
https://github.com/Koenkk/zigbee2mqtt/releases

**Comment by schumi2004** [comment]
I installed the update but for some reason it looks like it still is 1.5.1, also uninstalled addon but after re-installing it still gives me below errors.
Note: Installed via HAss.io addon store.

https://pastebin.com/FXDpXDrN
