### ISSUE TITLE
Update From 1.4 > 1.6

### ISSUE THREAD

**Issue by filoor** [danielwelch/hassio-zigbee2mqtt#227]
Hi,

Hi Could youe ples help. 
It wont start after updating.

`> zigbee2mqtt@1.6.0 start /zigbee2mqtt-1.6.0
> node index.js
  zigbee2mqtt:info 9/16/2019, 12:27:18 PM Logging to directory: '/share/zigbee2mqtt/log/2019-09-16.12-27-16'
  zigbee2mqtt:info 9/16/2019, 12:27:19 PM Starting zigbee2mqtt version 1.6.0 (commit #unknown)
  zigbee2mqtt:info 9/16/2019, 12:27:19 PM Starting zigbee-shepherd
  zigbee2mqtt:info 9/16/2019, 12:27:21 PM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: Cluster with key 'genGreenPowerProxy' does not exist)
  zigbee2mqtt:info 9/16/2019, 12:28:21 PM Starting zigbee-shepherd
  zigbee2mqtt:error 9/16/2019, 12:28:22 PM Error while starting zigbee-shepherd! (Error: dev exists, unregister it first.)
  zigbee2mqtt:error 9/16/2019, 12:28:22 PM Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 9/16/2019, 12:28:22 PM Failed to start
	{"message":"dev exists, unregister it first.","stack":"Error: dev exists, unregister it first.\n    at /zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/lib/shepherd.js:449:19\n    at Promise.apply (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:1185:26)\n    at Promise.promise.promiseDispatch (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:808:41)\n    at /zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:1411:14\n    at runSingle (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:137:13)\n    at flush (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/q/q.js:125:13)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"}
  zigbee2mqtt:error 9/16/2019, 12:28:22 PM Exiting...
npm
 ERR! code
 ELIFECYCLE
npm ERR!
 errno 1
npm
 ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm 
ERR! Exit status 1
npm ERR! 
npm 
ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR!
 This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-16T10_28_22_989Z-debug.log`

**Comment by sallazda** [comment]
I have the same issue. My solution :
Remove all your philips devices in database, restart and paire again

**Comment by filoor** [comment]
Thanks I will give it a try

**Comment by filoor** [comment]
I have romved "database.db" and now its tsarting up

Thanks
