### ISSUE TITLE
Hassio Docker installation failing on startup

### ISSUE THREAD

**Issue by iainsimons** [danielwelch/hassio-zigbee2mqtt#228]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.6.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Hassio 0.98.5
Running on Synology DS1813+
flashed cc2531 Zigbee dongle

**Description of problem:**
zigbee2mqtt failing on startup, which I *think* is something to do with symlinks, but I don't wholly understand how to fix. 
dongle is definitely present on system as : /dev/ttyACM0 
and also exposed in Hassio hardware as: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001xxxxxxxxxxx

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration

{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "192.168.1.57",
    "user": "xxxx",
    "password": "xxxx"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**Your logs from Hass.io**
```
19-09-16 14:15:20 INFO (SyncWorker_11) [hassio.docker.interface] Clean addon_7ad98f9c_zigbee2mqtt application
19-09-16 14:15:22 ERROR (SyncWorker_11) [hassio.docker] Can't start addon_7ad98f9c_zigbee2mqtt: 404 Client Error: Not Found ("linux runtime spec devices: error gathering device information while adding custom device "/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED29FD-if00": lstat /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED29FD-if00: no such file or directory")
```

**Comment by danielwelch** [comment]
Can you share the text that is listed for (or a screenshot of) your hassio hardware?

**Comment by EliBates** [comment]
I'm having the same problem with this. Running on a synology NAS, I believe this is an issue with docker container not seeing the usbport. I've had issues with this in the past and had to run the container via command line to link the usb to the docker container... not sure if this helps you in anyway but I would like to see this get resolved as well

**Comment by ciotlosm** [comment]
@EliBates @iainsimons Try looking at https://github.com/Koenkk/zigbee2mqtt/issues/2157 and see if you find information in there for your serial device. From what I was able to read, you don't need to use the long name, but can use `"port": "/dev/ttyACM0"` instead.
