### ISSUE TITLE
Addon refers to github picture, violating Content Security Policy.

### ISSUE THREAD

**Issue by middelink** [danielwelch/hassio-zigbee2mqtt#229]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.6.0 

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
rp4

**Description of problem:**
Added Content Security Policy to hassio and for most part addons are playing nice, except for zigbee2mqtt, although it is only cosmetic. It seems there is one picture which is directly taken from github. I think it should be included in the addon and served from there, no? (main page, 2nd card, just above **Zigbee2mqtt Hass.io Add-on**)
... And sure, I can add it to the CSP, but it seems bad precedent not including everything needed to function as a stand alone addon.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
&lt;irrelevant&gt;

**Your logs from Chrome**
Refused to load the image 'https://github.com/Koenkk/zigbee2mqtt/blob/master/images/logo.png?raw=true' because it violates the following Content Security Policy directive: "img-src ***".

**Comment by ciotlosm** [comment]
@middelink I've removed the image from that page and added logo.png that is automatically fetched and served locally. See #394
