### ISSUE TITLE
timeout error when starting

### ISSUE THREAD

**Issue by Sabuto** [danielwelch/hassio-zigbee2mqtt#232]
**zigbee2mqtt add-on version (if edge, please report commit hash): standard**

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):
Hassio in Docker
Old pc tower 2 core 8gb ram.**

I get this error when starting the normal version of zigbee2mqtt hassio plugin, this started from when i upgraded to 1.6.

I have also tried the edge version and this doesn't work, happy to post the error logs on this too but i think it is the same.

I'm not sure if this should be posted here or the official repo as i can't decide weather this is a hassio plugin problem or not.

I have also tried this with both ttyAMC0 and also the by id TexasInstrumentsxxxxxxxxxxxx

Thanks.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto",
    "user": "redacted",
    "password": "redacted"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**./run.sh: line 16: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
2019-09-25T10:37:20: PM2 log: Launching in no daemon mode
2019-09-25T10:37:20: PM2 log: App [npm:0] starting in -fork mode-
2019-09-25T10:37:20: PM2 log: App [npm:0] online
> zigbee2mqtt@1.6.0 start /zigbee2mqtt-1.6.0
> node index.js
  zigbee2mqtt:info 9/25/2019, 10:37:26 AM Logging to directory: '/share/zigbee2mqtt/log/2019-09-25.10-37-25'
  zigbee2mqtt:info 9/25/2019, 10:37:27 AM Starting zigbee2mqtt version 1.6.0 (commit #unknown)
  zigbee2mqtt:info 9/25/2019, 10:37:27 AM Starting zigbee-shepherd
  zigbee2mqtt:info 9/25/2019, 10:37:40 AM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: SRSP - SYS - osalNvRead after 6000ms)
  zigbee2mqtt:info 9/25/2019, 10:38:40 AM Starting zigbee-shepherd
  zigbee2mqtt:error 9/25/2019, 10:38:53 AM Error while starting zigbee-shepherd! (Error: SRSP - SYS - osalNvRead after 6000ms)
  zigbee2mqtt:error 9/25/2019, 10:38:53 AM Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 9/25/2019, 10:38:53 AM Failed to start
	{"message":"SRSP - SYS - osalNvRead after 6000ms","stack":"Error: SRSP - SYS - osalNvRead after 6000ms\n    at Timeout.object.timer.setTimeout [as _onTimeout] (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/znp/znp.js:227:24)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
  zigbee2mqtt:error 9/25/2019, 10:38:53 AM Exiting...
npm
 
ERR!
 
code
 ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.**

**Comment by vstoms** [comment]
Also have same problem, I can also see that my zigbee-stick is turning off  the green led when the addon starts (The led is not disabled).

**Comment by Sabuto** [comment]
@vstoms I managed to fix this  last night, i removed the usb stick and replugged it in, this now works with both the standard and the edge version of the plugin.
