### ISSUE TITLE
Timed permit_join?

### ISSUE THREAD

**Issue by ciotlosm** [danielwelch/hassio-zigbee2mqtt#24]
Hey, 

What do you think of doing "timed" permit_join? 

I can update documentation & gist to show this as I think would be more helpful for people as it's a bit more secure. We can start with something really high like 10 minutes which should be plenty of time for experiments. 

I already did something similar for `zha:` component here: https://gist.github.com/ciotlosm/3e074c4ba8b32ded32ef1da22b70a7f9 but this is using the already in-service timer, but not hard to produce. 

<img width="366" alt="screen shot 2018-06-01 at 11 51 42" src="https://user-images.githubusercontent.com/7738048/40862884-95830d98-65f6-11e8-8929-817d68a519b0.png">

The way it would work:
- User presses input_boolean which starts timer and sets the input_boolean to on
- Time is visible on interface 
- When timer ends (reaches 0) automation resets input_boolean to off and removes permit_join

**Comment by ciotlosm** [comment]
Implemented something: https://gist.github.com/ciotlosm/59d160ad49c695a801d9a940a2a387d2
<img width="503" alt="screen shot 2018-06-02 at 14 41 42" src="https://user-images.githubusercontent.com/7738048/40874058-1c681de0-6673-11e8-8689-10dc8b2c4a2f.png">

**Comment by danielwelch** [comment]
Sounds like a good suggestion!
