### ISSUE TITLE
Enable debug mode in the add-on

### ISSUE THREAD

**Issue by BigCabbage** [danielwelch/hassio-zigbee2mqtt#243]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
zigbee2mqtt-edge version 1.6.0 (commit #78824b48c090470d178c00da80c0d57c58eeccf2)

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
Raspberry PI4, 4GB, using Docker Hass.io images
Coordinator CC2531 firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190619}}'

**Description of problem:**
Currently running Zigbee2mqtt-Edge, When investigating issues, KKoen always mentions: "If it is with dev please provide the DEBUG=* npm start log for the various issues"
However, since the add-on starts/stops this, I think it should be the add-on which offers the option to just start npm or start it with the DEBUG option.
Can an additional option be added (next to 'Start on boot', 'Auto update' and 'Protection mode') called something like 'Enable Debug mode' ?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "redacted",
    "password": "redacted"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,,
      14
    ],
    "availability_timeout": 30,
    "availability_blacklist": [],
    "last_seen": "ISO_8601",
    "report": false
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1,
    "initialdelay": 1,
    "options": "-d -d",
    "log": false
  }
}
```

**Your logs from Hass.io**
Not applicable

**Comment by lejroberts** [comment]
You could use the add on - Zigbee2MqttAssistant available at this repo;

https://github.com/yllibed/hassio

Very handy.

**Comment by BigCabbage** [comment]
Thanks both!

I know about the log-level, and use it in the Lovelace interface as well. I just wasn't sure this is producing the level needed by KKoen.
Also, I recently started using the Zigbee2MqttAssistant and love it.
So, given the feedback it seems that I can already provide the debug-level needed, so I"ll close this ticket.

Thanks everyone for the great support on this fantastic project!
