### ISSUE TITLE
how to remove a single device?

### ISSUE THREAD

**Issue by vpomax** [danielwelch/hassio-zigbee2mqtt#244]
I have Hassio and I need to remove a single device from zigbee2mqtt 
I want to remove the device "0x00158d00019c82ee"
How do I do it?

**Comment by vpomax** [comment]
I removed unwanted devices using Zigbee2Mqtt Assistant add-on (https://github.com/yllibed/hassio).

**Comment by danielwelch** [comment]
I’ll close this since you’ve found a solution and because it is related to Zigbee2mqtt itself, and should be posted over there.
