### ISSUE TITLE
cp error when custom devices.js is set

### ISSUE THREAD

**Issue by DimsterTim** [danielwelch/hassio-zigbee2mqtt#246]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.6.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

**Description of problem:**
I am trying to add Konke device which is not fully supported, but I can not manage to use custom "devices.js" due to cp error.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": true,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.1.17",
    "user": "mqttclient",
    "password": "xxxxxxxxxx"
  },
  "serial": {
    "port": "/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0019430C17-if00"
  },
  "advanced": {
    "log_level": "debug",
    "pan_id": 6754,
    "channel": 15,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1,
    "initialdelay": 1,
    "options": "-d -d",
    "log": true
  },
  "zigbee_shepherd_devices": true
}
```

**Your logs from Hass.io**
./run.sh: line 16: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Searching for custom devices file in zigbee2mqtt data path...
cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory

**Comment by DimsterTim** [comment]
It is seems the same issue:
[https://github.com/danielwelch/hassio-zigbee2mqtt/pull/230/](url)

**Comment by jonasknoergaard** [comment]
@DimsterTim did you find a way to solve this issue? I'm having the same problem

**Comment by ciotlosm** [comment]
You can uninstall and reinstall the 'edge' version as you might have the version before the update.

**Comment by DimsterTim** [comment]
Yes, solved. I have installed Edge version of zigbee2mqtt add-on and updated Hass.io to the latest version.

**Comment by nexustp** [comment]
Hi i have same problem:
zigbee_shepherd_devices: true

devices.js in data_path: /share/zigbee2mqtt

logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[18:19:38] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[18:19:38] INFO: MQTT available, fetching server detail ...
[18:19:38] INFO: Previous config file found, checking backup
[18:19:38] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[18:19:38] INFO: File devices.js found, copying to ./node_modules/zigbee-herdsman-converters/
cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory
[cont-init.d] zigbee2mqtt.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by 26tajeen** [comment]
Any ideas how to resolve this? Need to use custom devices.js and it keeps saying
`cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory`
I **HAVE** got` zigbee_shepherd_devices: true` set

**Comment by 26tajeen** [comment]
@nexustp, @DimsterTim, @Sabuto, @jonasknoergaard, @ciotlosm, @danielwelch, @AHH4485
any of you guys figured this one out yet?!
Cheers

**Comment by LuisCanossa** [comment]
I have the same problem:
cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory

**Comment by danielszilagyi** [comment]
Same issue here, any workaround or idea how to get it fixed?
Thanks

**Comment by frafall** [comment]
I am experiencing this on both production and edge versions, put devices.js in /config/zigbee2mqtt/ and the message 
`cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory`
shows up in log while the plugin refuses to start. Not having devices.js here results in using the default file but without any custom devices.

Putting the devices.js in the /share/zigbee2mqtt/ doesn't do a thing.

The documentation is sparse or misleading (or plain hard to find) on how to add custom devices.

Best regards
Morten

**Comment by 26tajeen** [comment]
I’d recommend restoring selectively your Z2M from a snapshot if you can because there’s radio silence on this bug!

**Comment by frafall** [comment]
Ye, I noticed. There are issues with hassio-zigbee2mqtt/common/rootfs/etc/cont-init.d/zigbee2mqtt.sh:

```
if bashio::config.true 'zigbee_shepherd_devices'; then
    bashio::log.debug "Searching for custom devices.js file in zigbee2mqtt data path..."
    if bashio::fs.file_exists "$DATA_PATH/devices.js"; then
        bashio::log.info "File devices.js found, copying to ./node_modules/zigbee-herdsman-converters/"
        cp -f "$DATA_PATH"/devices.js ./node_modules/zigbee-herdsman-converters/devices.js
    else
        bashio::log.warning "No devices.js file found in data path, starting with default devices.js"
    fi
else
    bashio::log.debug "No devices.js file manipulation required"
fi
```

Seems it should be simple to address the node_modules directory correctly if some1 got around to looking into this?

The reference should probably be to /app/node_modules ...

This section was moved from the original run.sh (Pre S6 docker image), the original run.sh was running in the /app directory while the S6 cont-init.d scripts are not...

-morten

**Comment by ciotlosm** [comment]
We decided to stop supporting `devices.js` officially because it's too tied to the version of the z2m and can break during updates. The documented method for custom devices works better and it's more supported, please try to migrate to that one. 

Commenting on a closed issue will also not help very much. If you see a potential fix for this unsupported method, happy to accept a PR against `dev` branch.
