### ISSUE TITLE
Ikea Switch

### ISSUE THREAD

**Issue by legolas0802** [danielwelch/hassio-zigbee2mqtt#248]
I have correctly configured ikea switch e1734, but I do not receive any message when I press it

zigbee2mqtt:info  2019-11-01T19:13:39: Device '0x14b457fffe7f06bc' joined
zigbee2mqtt:info  2019-11-01T19:13:39: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x14b457fffe7f06bc"}}'
zigbee2mqtt:info  2019-11-01T19:13:39: Starting interview of '0x14b457fffe7f06bc'
zigbee2mqtt:info  2019-11-01T19:13:39: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x14b457fffe7f06bc"}}'
zigbee2mqtt:info  2019-11-01T19:14:00: Successfully interviewed '0x14b457fffe7f06bc', device has successfully been paired
zigbee2mqtt:info  2019-11-01T19:14:00: Device '0x14b457fffe7f06bc' is supported, identified as: IKEA TRADFRI ON/OFF switch (E1743)
zigbee2mqtt:info  2019-11-01T19:14:00: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x14b457fffe7f06bc","model":"E1743","vendor":"IKEA","description":"TRADFRI ON/OFF switch","supported":true}}'
zigbee2mqtt:info  2019-11-01T19:14:00: Configuring '0x14b457fffe7f06bc'
zigbee2mqtt:info  2019-11-01T19:14:04: Succesfully configured '0x14b457fffe7f06bc'

**Comment by danielwelch** [comment]
This probably belongs in the zigbee2mqtt repo first, as the issue template suggests
