### ISSUE TITLE
Additional debug information not ending up in log file

### ISSUE THREAD

**Issue by nanobra1n** [danielwelch/hassio-zigbee2mqtt#251]
- zigbee2mqtt add-on version: zigbee2mqtt-edge 36c7a27 
Operating environment: Hass.io in Docker on an Odroid N2 running Ubuntu 18.04.3

When running the add-on with 
`"zigbee_herdsman_debug" : true`

the debug output does not get written into the log, but appears only in the UI (at least that I know of). When troubleshooting part of the debug output tends to get lost as you need to press "Refresh" in the UI and a new chunk of output appears and the only way I see is to copy & paste the screen output.

**Comment by arjanvroege** [comment]
I've the same issue, is the information normally written to a log file?
