### ISSUE TITLE
Update 1.7.0

### ISSUE THREAD

**Issue by cjsteward** [danielwelch/hassio-zigbee2mqtt#253]
It looks like the long awaited 1.7.0 update has been released by Koenkk. How long does it typically take for the docker image to be created for new versions?

Thanks too for everything!

**Comment by bruvv** [comment]
If you make a pull request it could have been done already 😜 
Normally few days or switch to the edge stuff.

**Comment by Koenkk** [comment]
Done

**Comment by cjsteward** [comment]
Thanks dude!
