### ISSUE TITLE
feature request / minor bug only push images to docker on tagged release

### ISSUE THREAD

**Issue by Sabuto** [danielwelch/hassio-zigbee2mqtt#258]
**zigbee2mqtt add-on version (if edge, please report commit hash): 1.6.0**

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io): 
Ubuntu server, docker install

So this is a minor bug and i suppose a feature request, I have noticed in my hass.io addon store i get a notification to upgrade to 1.7.0 but the latest release is 1.6.0. We should make it so it only pushes a new image to docker if there is a tagged release? I could be completely off here.

I am happy to raise a pr if people think this is correct

**Comment by carldebilly** [comment]
As I described in #257, you also need to change the version number for an upgrade to be proposed by HASS.IO.

**Comment by Sabuto** [comment]
this is true, however there is a way to do it via the build.sh like i said i can raise a pr

**Comment by danielwelch** [comment]
I'd say the build script is kind of "in limbo" right now, as it uses an outdated, and actually deprecated, dockerized build system. This used to only push docker images for tagged commits (a "release"), but now this happens automatically when the config file `version` field is updated (for example, when the commit that updates that field to `1.7.0` is pushed, CI will build a docker image and push that image to docker hub with the appropriate tags). I don't really like this setup. It's opaque and relies on something that isn't really supported anymore. But it's working well and I haven't found the time to rework it. I'd definitely be interested in trying something else though (the official add-ons, last I checked, had switched to gitlab CI, which relied on long and complex configuration templates--too complicated for this simple add-on, but a viable alternative as an example).

**Comment by Sabuto** [comment]
@danielwelch in my addons i have adapted your buildscript to use the [new hassio builder](https://github.com/home-assistant/hassio-builder) i would be happy to raise a pr if you were interested. Mine work how yours used to with when a release is done it will build the new docker images.

**Comment by danielwelch** [comment]
Sounds good to me. We’ll need to make sure @Koenkk is on the same page before we merge any changes to the build and distribute scripts, but I think this would be a good change.
