### ISSUE TITLE
New device pairing succesfull, not shown in HA entities

### ISSUE THREAD

**Issue by NathanvanSeters** [danielwelch/hassio-zigbee2mqtt#264]
**1.7.1**

**Hass.io on RPi4 (4GB) **

**Description of problem:**
I want to add a new device. I have added the device in the devices.js (in share/zigbee2mqtt/)

    _{
        zigbeeModel: ['ROB_200-003-0'],
        model: 'ROB_200-003-0',
        vendor: 'ROBB',
        description: 'Zigbee 3.0 Switch',
        supports: 'on/off',
        fromZigbee: [fz.on_off, fz.ignore_genLevelCtrl_report],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
        },_

The pairing went succesfull (no errors or unknown device message in the log). In the log the device (Gang2) is also published to zigbee2mqtt. But this device is not published (?) to homeassistant (no messages in the log and not visible in the entities list of home assistent). All other devices went ok and are visible as entity in HA.

**log from Zigbee2mqtt add on**

_./run.sh: line 16: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Searching for custom devices file in zigbee2mqtt data path...
[Info] Socat is DISABLED and not started
2019-11-16T15:34:32: PM2 log: Launching in no daemon mode
2019-11-16T15:34:33: PM2 log: App [npm:0] starting in -fork mode-
2019-11-16T15:34:33: PM2 log: App [npm:0] online
> zigbee2mqtt@1.7.1 start /zigbee2mqtt-1.7.1
> node index.js
zigbee2mqtt:info  2019-11-16T14:34:36: Logging to directory: '/share/zigbee2mqtt/log/2019-11-16.15-34-35'
zigbee2mqtt:info  2019-11-16T14:34:36: Starting zigbee2mqtt version 1.7.1 (commit #unknown)
zigbee2mqtt:info  2019-11-16T14:34:36: Starting zigbee-herdsman...
zigbee2mqtt:info  2019-11-16T14:34:37: zigbee-herdsman started
zigbee2mqtt:info  2019-11-16T14:34:37: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
zigbee2mqtt:info  2019-11-16T14:34:37: Currently 4 devices are joined:
zigbee2mqtt:info  2019-11-16T14:34:37: Eetkamer2 (0x000b3cfffefeb096): E1603/E1702 - IKEA TRADFRI control outlet (Router)
zigbee2mqtt:info  2019-11-16T14:34:37: TV2 (0x14b457fffe4a5fc7): LED1842G3 - IKEA TRADFRI LED bulb E27 WW clear 250 lumen, dimmable (Router)
**zigbee2mqtt:info  2019-11-16T14:34:37: Gang2 (0x14b457fffec4d5d3): ROB_200-003-0 - ROBB Zigbee 3.0 Switch (Router)**
zigbee2mqtt:info  2019-11-16T14:34:37: 0xec1bbdfffe6be505 (0xec1bbdfffe6be505): ROB_200-004-0 - ROBB ZigBee AC phase-cut dimmer (Router)
zigbee2mqtt:info  2019-11-16T14:34:37: Zigbee: disabling joining new devices.
zigbee2mqtt:info  2019-11-16T14:34:37: Connecting to MQTT server at mqtt://core-mosquitto
zigbee2mqtt:info  2019-11-16T14:34:38: Connected to MQTT server
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'zigbee2mqtt/Eetkamer2', payload '{"state":"ON","linkquality":44}'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'zigbee2mqtt/TV2', payload '{"state":"OFF","brightness":224}'
**zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'zigbee2mqtt/Gang2', payload '{"state":"OFF","linkquality":47}'**
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe6be505', payload '{"state":"ON","linkquality":78,"brightness":254}'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.7.1","commit":"unknown","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":false}'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'homeassistant/switch/0x000b3cfffefeb096/switch/config', payload '{"payload_off":"OFF","payload_on":"ON","value_template":"{{ value_json.state }}","command_topic":"zigbee2mqtt/Eetkamer2/set","state_topic":"zigbee2mqtt/Eetkamer2","name":"Eetkamer2_switch","unique_id":"0x000b3cfffefeb096_switch_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x000b3cfffefeb096"],"name":"Eetkamer2","sw_version":"Zigbee2mqtt 1.7.1","model":"TRADFRI control outlet (E1603/E1702)","manufacturer":"IKEA"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'homeassistant/sensor/0x000b3cfffefeb096/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/Eetkamer2","json_attributes_topic":"zigbee2mqtt/Eetkamer2","name":"Eetkamer2_linkquality","unique_id":"0x000b3cfffefeb096_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x000b3cfffefeb096"],"name":"Eetkamer2","sw_version":"Zigbee2mqtt 1.7.1","model":"TRADFRI control outlet (E1603/E1702)","manufacturer":"IKEA"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'homeassistant/light/0x14b457fffe4a5fc7/light/config', payload '{"brightness":true,"schema":"json","command_topic":"zigbee2mqtt/TV2/set","state_topic":"zigbee2mqtt/TV2","name":"TV2_light","unique_id":"0x14b457fffe4a5fc7_light_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x14b457fffe4a5fc7"],"name":"TV2","sw_version":"Zigbee2mqtt 1.7.1","model":"TRADFRI LED bulb E27 WW clear 250 lumen, dimmable (LED1842G3)","manufacturer":"IKEA"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'homeassistant/sensor/0x14b457fffe4a5fc7/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/TV2","json_attributes_topic":"zigbee2mqtt/TV2","name":"TV2_linkquality","unique_id":"0x14b457fffe4a5fc7_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x14b457fffe4a5fc7"],"name":"TV2","sw_version":"Zigbee2mqtt 1.7.1","model":"TRADFRI LED bulb E27 WW clear 250 lumen, dimmable (LED1842G3)","manufacturer":"IKEA"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'homeassistant/light/0xec1bbdfffe6be505/light/config', payload '{"brightness":true,"schema":"json","command_topic":"zigbee2mqtt/0xec1bbdfffe6be505/set","state_topic":"zigbee2mqtt/0xec1bbdfffe6be505","name":"0xec1bbdfffe6be505_light","unique_id":"0xec1bbdfffe6be505_light_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0xec1bbdfffe6be505"],"name":"0xec1bbdfffe6be505","sw_version":"Zigbee2mqtt 1.7.1","model":"ZigBee AC phase-cut dimmer (ROB_200-004-0)","manufacturer":"ROBB"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2019-11-16T14:34:38: MQTT publish: topic 'homeassistant/sensor/0xec1bbdfffe6be505/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0xec1bbdfffe6be505","json_attributes_topic":"zigbee2mqtt/0xec1bbdfffe6be505","name":"0xec1bbdfffe6be505_linkquality","unique_id":"0xec1bbdfffe6be505_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0xec1bbdfffe6be505"],"name":"0xec1bbdfffe6be505","sw_version":"Zigbee2mqtt 1.7.1","model":"ZigBee AC phase-cut dimmer (ROB_200-004-0)","manufacturer":"ROBB"},"availability_topic":"zigbee2mqtt/bridge/state"}'_

**Comment by Quentintin** [comment]
Same issue ...

**Comment by michelantonides** [comment]
RPI 3B+, same Issue ...
version 1.7.1

**Comment by kalazzerx** [comment]
is this the issue of needed to add device to lib/extension/homeassistant.js.  I was struggling with the same issue and then realize I missed that last step.  Now I am trying to figure out how we submit back the change to that file - it is not part of this library that I can find.

**Comment by danielwelch** [comment]
Have you posted this in zigbee2mqtt issues? I don't see a reason why this is an add-on issue (you are using the add-on to add new device support, but the add-on side seems to be going smoothly). Let me know if I'm missing something.

**Comment by lymereJ** [comment]
@NathanvanSeters - I'm facing the same issue. What did you end up doing?

**Comment by ciotlosm** [comment]
@lymereJ please open a new issue with all details around version, including logs
