### ISSUE TITLE
adding not supported devices

### ISSUE THREAD

**Issue by Dramenia** [danielwelch/hassio-zigbee2mqtt#269]
in https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html, there is an explination to add new devices to zigbee2mqtt. in step 2, they mention node_modules/zigbee-herdsman-converters/devices.js. Where can i find this file/directory of the node modules in your addon, or do i need to switch to the normal zigbee2mqtt version?

**Comment by danielwelch** [comment]
See the zigbee_shepherd_devices option and this part of the run script: https://github.com/danielwelch/hassio-zigbee2mqtt/blob/f767b41955335d9ed56f3f0310059b25f7d80b26/zigbee2mqtt-edge/run.sh#L40

You can include your custom devices in your DATA_PATH, and it will be copied to where it needs to be on startup. I should add this into the README.

**Comment by redahb** [comment]
If I may hijack this: Koenkk has added support for a few bulbs I had as well: https://github.com/Koenkk/zigbee-herdsman-converters/pull/745. Are there any things I need to do to get these in the hassio-zigbee2mqtt repo?

**Comment by danielwelch** [comment]
If these have been merged into the dev branch, they are available now in the edge version of the add-on. When the next version of zigbee2mqtt is released, the stable branch of this add-on will update and they will be included there as well
