### ISSUE TITLE
Set state Timeout Danalock V3

### ISSUE THREAD

**Issue by lettore** [danielwelch/hassio-zigbee2mqtt#270]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.7.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Hassio running on RPI3 with CC2351

**Description of problem:**
When I send a Lock or Unlock command the lock react correctly but I can't get the status updated in Home Assistant, in the log appears an error about timeout in set state.
This error is happening from about 3 weeks, before it's always worked well with the same config, maybe I just installed a new version in the meanwhile.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.1.52:1883",
    "user": "**",
    "password": "**"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      *
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1,
    "initialdelay": 1,
    "options": "-d -d",
    "log": false
  }
}
```

**Your logs from Hass.io**
zigbee2mqtt:info  2019-11-30T20:00:17: MQTT publish: topic 'zigbee2mqtt/0x000b57fffe59e69d', payload '{"state":"UNLOCK","linkquality":15,"user":65535,"source":1,"battery":100,"battery_low":false}'
zigbee2mqtt:error 2019-11-30T20:01:45: Publish 'set' 'state' to '0x000b57fffe59e69d' failed: 'Error: Timeout - 7204 - 1 - 2 - 257 - 11 after 15000ms'
zigbee2mqtt:info  2019-11-30T20:01:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x000b57fffe59e69d' failed: 'Error: Timeout - 7204 - 1 - 2 - 257 - 11 after 15000ms'","meta":{"friendly_name":"0x000b57fffe59e69d"}}'
zigbee2mqtt:error 2019-11-30T20:02:33: Publish 'set' 'state' to '0x000b57fffe59e69d' failed: 'Error: Timeout - 7204 - 1 - 3 - 257 - 11 after 15000ms'
zigbee2mqtt:info  2019-11-30T20:02:33: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x000b57fffe59e69d' failed: 'Error: Timeout - 7204 - 1 - 3 - 257 - 11 after 15000ms'","meta":{"friendly_name":"0x000b57fffe59e69d"}}'
zigbee2mqtt:error 2019-11-30T20:02:57: Publish 'set' 'state' to '0x000b57fffe59e69d' failed: 'Error: Timeout - 7204 - 1 - 4 - 257 - 11 after 15000ms'
zigbee2mqtt:info  2019-11-30T20:02:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x000b57fffe59e69d' failed: 'Error: Timeout - 7204 - 1 - 4 - 257 - 11 after 15000ms'","meta":{"friendly_name":"0x000b57fffe59e69d"}}'

**Comment by danielwelch** [comment]
This probably belongs in the zigbee2mqtt issue tracker. If it ends up being a problem specific to the add-on, feel free to re-open.
