### ISSUE TITLE
Warning about unknown options

### ISSUE THREAD

**Issue by CodeFinder2** [danielwelch/hassio-zigbee2mqtt#272]
Hi,

during startup, I have the following in my system log:

> 19-12-11 12:51:49 WARNING (MainThread) [hassio.addons.validate] Unknown options baudrate
> 19-12-11 12:51:49 WARNING (MainThread) [hassio.addons.validate] Unknown options zigbee_herdsman_debug

What is causing this? Maybe there's a bug in the code that checks / validates such options? 🙈

**Comment by danielwelch** [comment]
Please use the issue template when posting an issue. 

I'm guessing you're on the stable version of the add on, which doesn't have a `zigbee_herdsman_debug` option, and that you're `baudrate` option isn't correctly nested under `advanced`, but I'm only guessing because I don't see your configuration.

**Comment by CodeFinder2** [comment]
Sorry and thanks for you quick reply, yes I am using the stable version. Ah okay, didn't know that. So, it's only in the -edge version of the addon?

I might have missed something but [here](https://www.zigbee2mqtt.io/information/debug.html) is just said that this is supported in the HassIO addon. Maybe we should add that it's only working in the -edge version?

Your guess was right: I put baudrate into serial, not advanced. Stupid mistake, sorry for the noise! 😊

**Comment by danielwelch** [comment]
In the stable version, the corresponding option is called `zigbee_shepherd_debug`. This is purely historical. The library used to be called `zigbee_shepherd_converters`. I'd like to move it to the new herdsman variant, but that will be a breaking change, so I'm waiting for a major update to do so. Alternatively, we could just support both `zigbee_shepherd_debug` and _zigbee_herdsman_debug` and have the 2 options do the same thing.

**Comment by CodeFinder2** [comment]
Ahhh thanks for clarifying! 🙈

(IIRC, I just 'blindly' replaced `zigbee_shepherd_debug` with `zigbee_herdsman_debug` but your consideration makes perfectly sense!)

I really like and appreciate the way you think about breaking changes and that you are respecting the users' setups! I think both of your suggestions are possible and you should follow the way that minimizes your efforts since you obviously already putting a lot of time in this project (thank you for this!). 😉 

If you ask me, supporting both options would allow for the
