### ISSUE TITLE
Mosquitto MQTT with zigbee2mqtt connection problem

### ISSUE THREAD

**Issue by fremut** [danielwelch/hassio-zigbee2mqtt#277]
I am using combination of mosquitto-mqtt offical add-on with zigbee2mqtt addon. Everything works fine till stops wifi connection or LAN network (home router turn off). It is possile to set up broker IP independent on LAN ? I tried to use internal docker (mosquitto containers) IP 172.30.33.0 but with same effect. After turning home wifi off. Zigbee devices doesnt function. Thanks for your help.

**Comment by danielwelch** [comment]
Probably need more information about how you’re running the add-ons, hardware, docker, etc. You can use docker internal networking, but this will depend on your setup (and to be honest I’m not an expert).

**Comment by fremut** [comment]
Hello Daniel, thanks for your response. I have standard HassIO (HassOS) official image running on RasPI3B+ on SD card. Nothing special. All plugins are installed via Add-on store. So I am connected via wifi to home network and after router is off (sometimes happen) zigbee2mqtt lost connection with mosquitto mqtt broker. I tried to use home assistant embedded mqtt broker and with this setup everything works also without lan (wifi) connection. But in home Assistant docs is written that embedded borker will not be supported anymore. So i try to find out how to operate it with official mosquitto mqtt broker add-on (which is recommended).

**Comment by danielwelch** [comment]
Could you share what you’re using for your MQTT url (both for the embedded broker and what you’ve tried for the new mosquito broker via the add-on).

**Comment by fremut** [comment]
Hello sorry, now I see (after some tests) that I am unable to set my MQTT (embedded or mosquitto) in a way i described. So every time I shut down the wifi home router and/or LAN connection Zigbee2Mqtt stops sending telegrams to mqtt server. Is there some known way how to setup it in a way to LAN/network independency?

**Comment by fremut** [comment]
I think that i was successfully only one times when i was clicking on a zigbee button many times during stoping the wifi connection.  But it could be only accident or mistake.

**Comment by CodeFinder2** [comment]
I guess it highly depends on your config. For instance, if your addons are given the MQTT broker as a hostname, thus require a DNS for resolving, and will (try to) ask your router to resolve the hostname, it will obviously fail. I am also not completely sure if the RPi uses the router as its default gateway and, if so, it may also fail (but again, not sure about this).

In principle, running a zigbee network without a router / wifi / lan network should be possible but it will most probably complicate your setup.
