### ISSUE TITLE
Ikea E1743 Battery Problem

### ISSUE THREAD

**Issue by wes1993** [danielwelch/hassio-zigbee2mqtt#278]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

Zigbee2MQTT 1.7.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Hassio on Ubuntu Server with Docker

**Description of problem:**

Ikea E1743 Button won't update the battery status.
I have one button with 16% battery, i have changed the battery but HA still see 16%

**Comment by danielwelch** [comment]
This belongs in the zigbee2mqtt repo as the issue template suggests.
