### ISSUE TITLE
Failed to interview but device reports properly

### ISSUE THREAD

**Issue by KevinRiordan** [danielwelch/hassio-zigbee2mqtt#281]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
zigbee2mqtt version 1.8.0 (commit #unknown)

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
ubuntu 16.04

**Description of problem:**
Device fails to interview and does not appear as an identity or a device in mqtt.

zigbee2mqtt addon connects to the mqtt mosquito and detects devices and appears to be publishing to mqtt when sensor is activated however I do not see the device listed anywhere. And nothing is appearing in the mosquito logs. 

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": true,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto:1883",
    "user": "admin",
    "password": "orland0"
  },
  "serial": {
    "port": "/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B000147708E-if00"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1,
    "initialdelay": 1,
    "options": "-d -d",
    "log": true
  }
}
```
`
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-01-06T16:00:46: PM2 log: Launching in no daemon mode
2020-01-06T16:00:46: PM2 log: App [npm:0] starting in -fork mode-
2020-01-06T16:00:46: PM2 log: App [npm:0] online
> zigbee2mqtt@1.8.0 start /zigbee2mqtt-1.8.0
> node index.js
zigbee2mqtt:info  2020-01-06 16:00:47: Logging to console and directory: '/share/zigbee2mqtt/log/2020-01-06.16-00-47'
zigbee2mqtt:info  2020-01-06 16:00:47: Starting zigbee2mqtt version 1.8.0 (commit #unknown)
zigbee2mqtt:info  2020-01-06 16:00:47: Starting zigbee-herdsman...
zigbee2mqtt:info  2020-01-06 16:00:48: zigbee-herdsman started
zigbee2mqtt:info  2020-01-06 16:00:48: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
zigbee2mqtt:info  2020-01-06 16:00:48: Currently 0 devices are joined:
zigbee2mqtt:warn  2020-01-06 16:00:48: `permit_join` set to  `true` in configuration.yaml.
zigbee2mqtt:warn  2020-01-06 16:00:48: Allowing new devices to join.
zigbee2mqtt:warn  2020-01-06 16:00:48: Set `permit_join` to `false` once you joined all devices.
zigbee2mqtt:info  2020-01-06 16:00:48: Zigbee: allowing new devices to join.
zigbee2mqtt:info  2020-01-06 16:00:48: Connecting to MQTT server at mqtt://core-mosquitto:1883
zigbee2mqtt:info  2020-01-06 16:00:49: Connected to MQTT server
zigbee2mqtt:info  2020-01-06 16:00:49: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
zigbee2mqtt:info  2020-01-06 16:00:49: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.8.0","commit":"unknown","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":true}'
zigbee2mqtt:info  2020-01-06 16:01:42: Device '0x000d6f00120b28fd' joined
zigbee2mqtt:info  2020-01-06 16:01:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x000d6f00120b28fd"}}'
zigbee2mqtt:info  2020-01-06 16:01:42: Starting interview of '0x000d6f00120b28fd'
zigbee2mqtt:info  2020-01-06 16:01:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x000d6f00120b28fd"}}'
zigbee2mqtt:info  2020-01-06 16:01:46: MQTT publish: topic 'homeassistant/binary_sensor/0x000d6f00120b28fd/water_leak/config', payload '{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.water_leak }}","device_class":"moisture","state_topic":"zigbee2mqtt/0x000d6f00120b28fd","json_attributes_topic":"zigbee2mqtt/0x000d6f00120b28fd","name":"0x000d6f00120b28fd_water_leak","unique_id":"0x000d6f00120b28fd_water_leak_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x000d6f00120b28fd"],"name":"0x000d6f00120b28fd","sw_version":"Zigbee2mqtt 1.8.0","model":"Water leakage sensor (HS1-WL-E)","manufacturer":"HEIMAN"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-01-06 16:01:46: MQTT publish: topic 'homeassistant/sensor/0x000d6f00120b28fd/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x000d6f00120b28fd","json_attributes_topic":"zigbee2mqtt/0x000d6f00120b28fd","name":"0x000d6f00120b28fd_linkquality","unique_id":"0x000d6f00120b28fd_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x000d6f00120b28fd"],"name":"0x000d6f00120b28fd","sw_version":"Zigbee2mqtt 1.8.0","model":"Water leakage sensor (HS1-WL-E)","manufacturer":"HEIMAN"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:error 2020-01-06 16:02:14: Failed to interview '0x000d6f00120b28fd', device has not successfully been paired
zigbee2mqtt:info  2020-01-06 16:02:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_failed","meta":{"friendly_name":"0x000d6f00120b28fd"}}'

`

**Your logs from Hass.io**
20-01-06 15:39:15 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-01-06 15:39:20 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
20-01-06 15:39:20 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
20-01-06 15:39:20 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-01-06 15:39:25 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
20-01-06 15:39:25 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
20-01-06 15:39:25 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
20-01-06 15:39:25 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
20-01-06 15:39:26 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
20-01-06 15:52:14 INFO (SyncWorker_9) [hassio.docker.interface] Stop addon_7ad98f9c_zigbee2mqtt application
20-01-06 15:52:14 INFO (SyncWorker_9) [hassio.docker.interface] Clean addon_7ad98f9c_zigbee2mqtt application
20-01-06 15:52:15 INFO (SyncWorker_19) [hassio.docker.addon] Start Docker add-on dwelch2101/zigbee2mqtt-amd64 with version 1.8.0
20-01-06 15:52:18 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for admin
20-01-06 15:52:19 INFO (MainThread) [hassio.auth] Success login from admin
20-01-06 15:53:47 INFO (MainThread) [hassio.host.control] Initialize host reboot over systemd
20-01-06 15:53:47 INFO (MainThread) [hassio.addons] Phase 'application' stop 2 add-ons
20-01-06 15:53:47 INFO (SyncWorker_6) [hassio.docker.interface] Stop addon_core_configurator application
20-01-06 15:53:47 INFO (SyncWorker_16) [hassio.docker.interface] Stop addon_a0d7b954_nodered application
20-01-06 15:53:47 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API connection is closed
20-01-06 15:53:48 INFO (SyncWorker_6) [hassio.docker.interface] Clean addon_core_configurator application
20-01-06 15:53:48 INFO (SyncWorker_16) [hassio.docker.interface] Clean addon_a0d7b954_nodered application
20-01-06 15:53:48 INFO (SyncWorker_0) [hassio.docker.interface] Stop homeassistant application
20-01-06 15:54:48 INFO (MainThread) [hassio.addons] Phase 'services' stop 1 add-ons
20-01-06 15:54:48 INFO (SyncWorker_19) [hassio.docker.interface] Stop addon_7ad98f9c_zigbee2mqtt application
20-01-06 15:54:48 INFO (SyncWorker_19) [hassio.docker.interface] Clean addon_7ad98f9c_zigbee2mqtt application
20-01-06 15:54:48 INFO (MainThread) [hassio.addons] Phase 'system' stop 1 add-ons
20-01-06 15:54:48 INFO (SyncWorker_15) [hassio.docker.interface] Stop addon_core_mosquitto application
20-01-06 15:54:49 INFO (SyncWorker_15) [hassio.docker.interface] Clean addon_core_mosquitto application
20-01-06 15:54:49 INFO (MainThread) [hassio.addons] Phase 'initialize' stop 0 add-ons
20-01-06 15:54:49 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.Reboot on /org/freedesktop/systemd1
20-01-06 15:55:29 INFO (MainThread) [__main__] Initialize Hass.io setup
20-01-06 15:55:29 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 193
20-01-06 15:55:29 INFO (MainThread) [__main__] Setup HassIO
20-01-06 15:55:29 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-01-06 15:55:29 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-01-06 15:55:29 WARNING (MainThread) [hassio.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
20-01-06 15:55:29 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-01-06 15:55:29 INFO (MainThread) [hassio.host.info] Update local host information
20-01-06 15:55:29 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-06 15:55:29 INFO (MainThread) [hassio.host.services] Update service information
20-01-06 15:55:29 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-06 15:55:30 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-06 15:55:30 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-06 15:55:30 ERROR (MainThread) [hassio.utils.gdbus] DBus return error: Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/DnsManager

20-01-06 15:55:30 WARNING (MainThread) [hassio.host.network] Can't update host DNS system information!
20-01-06 15:55:30 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-01-06 15:55:30 INFO (MainThread) [hassio.host.services] Reload local service hassio-apparmor.service
20-01-06 15:55:30 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-01-06 15:55:30 INFO (SyncWorker_1) [hassio.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 1
20-01-06 15:55:30 INFO (MainThread) [hassio.dns] Update resolv from Supervisor
20-01-06 15:55:30 INFO (MainThread) [hassio.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-01-06 15:55:30 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
20-01-06 15:55:30 INFO (SyncWorker_1) [hassio.docker.interface] Clean hassio_dns application
20-01-06 15:55:30 INFO (SyncWorker_1) [hassio.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1
20-01-06 15:55:30 INFO (SyncWorker_0) [hassio.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.103.5
20-01-06 15:55:31 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/7ad98f9c repository
20-01-06 15:55:31 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
20-01-06 15:55:31 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-01-06 15:55:31 INFO (MainThread) [hassio.store] Load add-ons from store: 64 all - 64 new - 0 remove
20-01-06 15:55:31 INFO (MainThread) [hassio.addons] Found 4 installed add-ons
20-01-06 15:55:31 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/amd64-addon-configurator with version 4.2
20-01-06 15:55:31 INFO (SyncWorker_1) [hassio.docker.interface] Attach to homeassistant/amd64-addon-mosquitto with version 5.1
20-01-06 15:55:31 INFO (SyncWorker_4) [hassio.docker.interface] Attach to hassioaddons/node-red-amd64 with version 5.0.7
20-01-06 15:55:31 INFO (SyncWorker_6) [hassio.docker.interface] Attach to dwelch2101/zigbee2mqtt-amd64 with version 1.8.0
20-01-06 15:55:31 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-06 15:55:31 INFO (MainThread) [hassio.snapshots] Found 0 snapshot files
20-01-06 15:55:31 INFO (MainThread) [hassio.discovery] Load 1 messages
20-01-06 15:55:31 INFO (MainThread) [hassio.ingress] Load 6 ingress session
20-01-06 15:55:31 INFO (MainThread) [hassio.secrets] Load Home Assistant secrets: 1
20-01-06 15:55:31 INFO (MainThread) [__main__] Run Hass.io
20-01-06 15:55:31 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
20-01-06 15:55:31 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons
20-01-06 15:55:31 INFO (MainThread) [hassio.addons] Phase 'system' start 1 add-ons
20-01-06 15:55:31 INFO (SyncWorker_1) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-mosquitto with version 5.1
20-01-06 15:55:32 INFO (MainThread) [hassio.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
20-01-06 15:55:36 INFO (MainThread) [hassio.addons] Phase 'services' start 1 add-ons
20-01-06 15:55:38 INFO (SyncWorker_13) [hassio.docker.addon] Start Docker add-on dwelch2101/zigbee2mqtt-amd64 with version 1.8.0
20-01-06 15:55:42 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for admin
20-01-06 15:55:42 ERROR (MainThread) [hassio.homeassistant] Error on call http://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-01-06 15:55:42 INFO (MainThread) [hassio.auth] Home Assistant not running, check cache
20-01-06 15:55:42 INFO (MainThread) [hassio.auth] Cache hit for admin
20-01-06 15:55:43 INFO (SyncWorker_10) [hassio.docker.interface] Start homeassistant/qemux86-64-homeassistant
20-01-06 15:55:58 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
20-01-06 15:55:58 INFO (MainThread) [hassio.addons] Phase 'application' start 2 add-ons
20-01-06 15:55:58 INFO (SyncWorker_15) [hassio.docker.addon] Start Docker add-on hassioaddons/node-red-amd64 with version 5.0.7
20-01-06 15:55:59 INFO (SyncWorker_10) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-configurator with version 4.2
20-01-06 15:55:59 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_nodered
20-01-06 15:56:00 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_nodered
20-01-06 15:56:04 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
20-01-06 15:56:04 INFO (MainThread) [hassio.core] Hass.io is up and running
20-01-06 15:56:10 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
20-01-06 15:56:10 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
20-01-06 15:56:10 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
20-01-06 15:56:10 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
20-01-06 16:00:44 INFO (SyncWorker_2) [hassio.docker.interface] Stop addon_7ad98f9c_zigbee2mqtt application
20-01-06 16:00:44 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_7ad98f9c_zigbee2mqtt application
20-01-06 16:00:45 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on dwelch2101/zigbee2mqtt-amd64 with version 1.8.0
20-01-06 16:00:49 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for admin
20-01-06 16:00:49 INFO (MainThread) [hassio.auth] Success login from admin

**Comment by CodeFinder2** [comment]
Seems that this issue is not related to this addon. It's therefore more appropriate to open it in the zigbee2mqtt repo.

Also, is seems the error is only related to this single device "Water leakage sensor (HS1-WL-E)" by "HEIMAN". It explicitly says `Failed to interview '0x000d6f00120b28fd', device has not successfully been paired`. You should consider re-configuring and, if that doesn't work, re-pairing it. Don't forget to (force_)deleting it if you intend to re-pair it, see the docs of zigbee2mqtt for more infos about all this:

https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html
