### ISSUE TITLE
Default path configuration file not work

### ISSUE THREAD

**Issue by davide-rhw** [danielwelch/hassio-zigbee2mqtt#292]
hi, I have correctly installed the plugin on hassio. I have explored all the hassio files, but the configuration files of this plugin are not present anywhere. Is there a path accessible from the web configurator where to find them?

**Comment by svenvbins** [comment]
> Is there a path accessible from the web configurator where to find them?

In the HA main screen, click Hass.io (on the left side of your screen), then under Add-ons you should see zigbee2mqtt. Click it. Scroll just a little bit down and you'll find the config file. I hope that's what you're looking for!

**Comment by danielwelch** [comment]
Assuming you’re not trying anything fancy, just configure via the front-end configuration like for any other Hassio add-on. No need to edit files directly for most use cases (some exceptions described in the README).
