### ISSUE TITLE
unable to update to 1.10

### ISSUE THREAD

**Issue by lechk82** [danielwelch/hassio-zigbee2mqtt#295]
I'm unable to update to 1.10 on HA 0.104.3
`20-02-05 21:42:03 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.10.0 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.10.0 not found: manifest unknown: manifest unknown").`

**Comment by bas89** [comment]
Can confirm this, same Home Assistant version. Maybe we just have to wait for the package to be uploaded.

**Comment by shirou93** [comment]
105 HA same issue.

**Comment by Polosa** [comment]
Looks like docker image isn't pushed.

**Comment by coolguymatt** [comment]
Fixed now

**Comment by roygbiv856** [comment]
What is the latest version exactly? I've read 1.17 was available to some people over a month ago, but here I'm still sitting at 1.16

**Comment by delta010** [comment]
Same Problem I am using hass.io version 0.105.3, Supervisor version 200 and HassOS 3.10

But I can't update Zigbee2mqtt from version 1.10.0 to 1.10.1 

error while updating :
  
20-02-13 02:52:11 ERROR (SyncWorker_17)   [hassio.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.10.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.10.1 not found: manifest unknown: manifest unknown").

**Comment by danielwelch** [comment]
@delta010 Your comment was posted before the images were pushed to docker hub. You can always check the Travis build for the current build status or docker hub to see what image tags are there.
