### ISSUE TITLE
Readme Pairing: hide_entity is deprecated

### ISSUE THREAD

**Issue by Samlof** [danielwelch/hassio-zigbee2mqtt#299]
From Home Assistant logs: `The 'hide_entity' option (with value 'True') is deprecated, please remove it from your configuration. This option will become invalid in version 0.107`
The README.md Pairing section has hide_entity: true in the automations. Can't find much about this googling, so no idea if there is a replacement or if it does nothing at all.

**Comment by danielwelch** [comment]
That section of the README was written before Lovelace was mainstream, so I think it’s just a legacy option from the old states UI (which is being deprecated). If that’s the case, it shouldn’t be impacting anything assuming you’re using Lovelace (most everyone is). But would still be nice to refresh this docs section.
