### ISSUE TITLE
Make addon read from configuration.yaml

### ISSUE THREAD

**Issue by timdonovanuk** [danielwelch/hassio-zigbee2mqtt#301]
It currently seems to do its own thing, like the config section is stored client side..if you edit the configuration.yaml manually (outside of HA) those changes aren't even showed in HA once you refresh.

**Comment by timdonovanuk** [comment]
Sorry, this is so bloody dumb. Trying to switch to the dev branch of the plugin totally hoses your zigbee network, because for whatever reason the addon doesn't read a copied over configuration.yaml and decides to start the addon with default settings, thus trashing your panID and controller. You have to then go repair every zigbee device because the controller will no longer join the network.

**Comment by danielwelch** [comment]
I’m not totally sure what you’re talking about so apologies in advance if this is a non-answer to your suggestion, but no, the add-on doesn’t support manually editing your zigbee2mqtt configuration.yaml. This is generated from the add-on configuration when the add-on starts. 

(Historically, we used to have manual editing of this file, but the general trend for Hass.io (now just home assistant i guess) was/is to have everything configurable from the front end only). 

I don’t know what you mean by client side. It’s Docker. The changes from manual edits won’t be shown in your HA front end, ever, because that’s not how home assistant works. They also won’t be persisted because they will be overwritten with your configuration from the front end on next startup.

**Comment by timdonovanuk** [comment]
Fair enough, thanks for clarifying. It makes switching to the -edge version full of danger though. Seems odd to even bother exposing the config files in a nice folder called "share" by default.

> The changes from manual edits won’t be shown in your HA front end, ever, because that’s not how home assistant works

Well, I beg to differ. I've been using HA for 3+ years and found everything is driven from config files, even if you go via the integrations page, stuff still ends up the .storage folder. 

There is a sizable chunk of people cautious about how HA is moving towards full UI config only, and this is a great example why people are cautious. 

I'm not even sure why its been architected in this way..to not configuration files at the backend. There is zero problem storing a config file at the backend, loading those changes into the front end, and allowing people to change them in the front end. This is actually the default design paradigm for 99% of applications...

>  you could always just run zigbee2mqtt in docker yourself and configure it however you want.

Done and done :)

Thanks for maintaining this repo though anyway!

**Comment by danielwelch** [comment]
>> Well, I beg to differ. I've been using HA for 3+ years and found everything is driven from config files, even if you go via the integrations page, stuff still ends up the .storage folder.

I get what you’re saying. What I meant was, literally, the JSON formatted add-on configuration that you input into the front end is stored separately and independently by Hassio, and there is no mechanism for add-ons to alter that configuration directly via an arbitrary file (although the configuration can be circumvented, overwritten, or ignored, as you’re suggesting). I was specifically talking about the HA front end.

Sorry about having to re-pair. The edge add-on is mostly intended for advanced users. But maybe adding a section to the docs or changing the default data path would be a nice easy way to prevent this from happening in the future.


On a tangent, I totally understand the move toward full UI configuration, and think they’ve done a nice job of keeping a balance between these efforts and supporting those of us who want/need more control. But I understand your argument. Personally, I roll my own Docker compose set up :)

**Comment by danielwelch** [comment]
> Well, I beg to differ. I've been using HA for 3+ years and found everything is driven from config files, even if you go via the integrations page, stuff still ends up the .storage folder.

I get what you’re saying. What I meant was, literally, the JSON formatted add-on configuration that you input into the front end is stored separately and independently by Hassio, and there is no mechanism for add-ons to alter that configuration directly via an arbitrary file (although the configuration can be circumvented, overwritten, or ignored, as you’re suggesting). I was specifically talking about the HA front end.

Sorry about having to re-pair. The edge add-on is mostly intended for advanced users. But maybe adding a section to the docs or changing the default data path would be a nice easy way to prevent this from happening in the future.


On a tangent, I totally understand the move toward full UI configuration, and think they’ve done a nice job of keeping a balance between these efforts and supporting those of us who want/need more control. But I understand your argument. Personally, I roll my own Docker compose set up :)
