### ISSUE TITLE
Question about Edge/Dev

### ISSUE THREAD

**Issue by mf-social** [danielwelch/hassio-zigbee2mqtt#306]
Hi, no bugs, just a couple of quick questions please... 

Instructions say there's an 'edge' addon when you add the repo to homeassistant, I've not got one, is this no longer available?

![Screenshot_20200310-195143](https://user-images.githubusercontent.com/14824890/76353512-c4bf9700-6308-11ea-9c88-d0052df733c7.png)

If it is available, and presuming I can find it, is it as easy as just stopping one and starting the other to flick between them (obviously configuring them both the same), or do I have to set up my network again? 

And finally, will it literally track the latest dev branch, or do you have to manually update the addon when the dev branch is updated and then we get the update? 

Thanks in advance :slightly_smiling_face:

**Comment by tomaae** [comment]
It got broken in commit 2 days ago
`20-03-10 21:57:18 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['experimental']['transmit_power']. Got 'int(-22,19)?'`

**Comment by onewaylifestreet** [comment]
I cannot find it too.

**Comment by mf-social** [comment]
@tomaae - thanks - whilst I wait for that to be fixed are you able to answer the other two questions please?

**Comment by tomaae** [comment]
Edge loads configuration from same directory. As long as there is no breaking change in configuration in edge, you can switch between them. No need to configure anything.

You will have to reinstall edge every time you want to update it. It does not track version at all.

**Comment by mf-social** [comment]
Ah OK - so once it reappears in my addons list I can just download it, make sure the configuration options are the same, stop the 'stable' one, start the edge one and crack on?

When you say I'll have to reinstall it every time, does it pull the latest dev image each time it's installed then?

Many thanks 🙂

**Comment by upwindanderl** [comment]
I'm a hass.io addon user and i'm also waiting on this fix 

Is it easy to pull back on the old commit in my hass.io environment do get this edge addon? I've a  Texas Instruments CC1352P-2  here and i can't use it without (i guess?!)

**Comment by tomaae** [comment]
Yes, it always pull latest master from z2m git. Just make sure you only have only one with enabled autostart. It wont delete config when you uninstall, so no need to worry about that.

CC1352P-2 works with regular version, I use it too.

**Comment by mf-social** [comment]
@tomaae - thanks - I'll give it a punt as soon as the addon repo issue is fixed 👍

**Comment by upwindanderl** [comment]
> Yes, it always pull latest master from z2m git. Just make sure you only have only one with enabled autostart. It wont delete config when you uninstall, so no need to worry about that.
> 
> CC1352P-2 works with regular version, I use it too.

i know its wrong here
but maybe you can help me than with my actual issue ^^

i flashed the cc1352p
connected to my device (ubuntu server machine with docker)
had a look at my hassio->system->hardware and found following:
`/dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.07__Embed_with_CMSIS-DAP_L43003AX-if00`
`/dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.07__Embed_with_CMSIS-DAP_L43003AX-if03`

i tried both and sherdsman isn't able to connect to the device
so this was the reason i thought that i need the EDGE rep

**Comment by tomaae** [comment]
yeah, there are 2 usb devices since it have both uart's available through single connection.
I'm using if00 like this:
`serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L43002YI-if00`
I'm using Z-Stack_3.x.0 version 20191106

It didnt connect for me on first try for some reason too. But afterwards it worked without a flaw.

**Comment by upwindanderl** [comment]
> yeah, there are 2 usb devices since it have both uart's available through single connection.
> I'm using if00 like this:
> `serial: port: >- /dev/serial/by-id/usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L43002YI-if00`
> I'm using Z-Stack_3.x.0 version 20191106
> 
> It didnt connect for me on first try for some reason too. But afterwards it worked without a flaw.

ok.... i tried the stable version  on a PI instead of the ubuntu server... than it was easy
now I'm able to start through 
but i stuck on switching on/off pairing over mqtt :'(((

no log is shown #https://github.com/danielwelch/hassio-zigbee2mqtt/issues/287#issuecomment-597760948.. 

haha over 2years cc2531 using beginner problems like hell 
but thanks for your help

**Comment by tomaae** [comment]
that log looks okey to me, 0 devices and disabled pairing. it have nothing to do after that.
create yourself a switch to enable pairing like this:
`switch:
  - platform: mqtt
    name: "Zigbee2mqtt Main join"
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"`

**Comment by upwindanderl** [comment]
Ok got it! 
Thanks... because you were answering and because i was shure it should be ok like this i did some steps again. 

At the moment i've three HA instances in the same network (as well with two z2m) because i'm on some migration period from 2531 to the powerful 
This was as well most of the problem of all my issues. 
I guess i had problems that one instance was listening on the other mqtt server - shame on me! 
Everything fine for me now! But of course this has nothing to do with the main issue at all - sorry @mf-social for spamming !

**Comment by mf-social** [comment]
Lol - spam away, we're all friends here :slightly_smiling_face:

**Comment by backcountrymountains** [comment]
As long as we're spamming...
Has anyone figured out how to run the z2m docker image on a Hassio device using the portainer add-on? That way we'd be able to just pull directly from z2m and not have to use the z2m add-on. 

I'm super appreciative of the work that has been done with the add-on, but it seems we could be on the bleeding edge of z2m more quickly if we could just use the z2m dev docker image.

Also, @mf-social, please put your configs back on github! They were so useful! I learned many things from them!

**Comment by mf-social** [comment]
Ha - thanks :relaxed: 

Maybe one day :slightly_smiling_face:

**Comment by danielwelch** [comment]
Woops! Sorry, I’ll  fix this.

**Comment by davemenkehorst** [comment]
> 20-03-13 22:46:28 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['experimental']['transmit_power']. Got 'int(-22,19)?'

Any news already? Would be great to use the edge version. Maybe my zigbee2mqtt stick will finally work! 

Thanks!

**Comment by danielwelch** [comment]
I adjusted the schema in https://github.com/danielwelch/hassio-zigbee2mqtt/commit/da1a8a78ad0d375a7475978602277d7277192d89. Let me know if that fixes the problem or not.

**Comment by davemenkehorst** [comment]
Running the ‘test’ version right now. Thanks!

**Comment by danielwelch** [comment]
Unless you're building it yourself, you'll need to wait for the docker image to build and push. You can check travis to follow the process (warning: it takes a stupid long time)

**Comment by mf-social** [comment]
Confirm it has (re-)appeared in my addons list.

Thanks 👍
