### ISSUE TITLE
Failed to call 'OTAUpdate'

### ISSUE THREAD

**Issue by quantummobile** [danielwelch/hassio-zigbee2mqtt#308]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Raspberry Pi 3 Model B+

**Description of problem:**
After publishing topic zigbee2mqtt/bridge/ota_update/update with payload sensor.0xccccccfffe2fb7b9 zigbee2mqtt addon log shows the following:

`zigbee2mqtt:error 2020-03-17 13:06:55: Failed to call 'OTAUpdate' 'onMQTTMessage' (AssertionError [ERR_ASSERTION]: Device not found or not a device
    at OTAUpdate.onMQTTMessage (/zigbee2mqtt-1.11.0/lib/extension/otaUpdate.js:64:9)
    at Controller.callExtensionMethod (/zigbee2mqtt-1.11.0/lib/controller.js:329:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5))`

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'xxx'
  user: xxx
  password: 'xxx'
serial:
  port: /dev/ttyACM0
  disable_led: true
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_shepherd_devices: true
```

**Your logs from Hass.io**

**Comment by PreferHardware** [comment]
Based on experience: drop the "sensor:"  The payload should only include the 0x....
