### ISSUE TITLE
Image dwelch2101/zigbee2mqtt-armhf:1.12.0 not found

### ISSUE THREAD

**Issue by mlettica** [danielwelch/hassio-zigbee2mqtt#310]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
Updating from 1.11.0 to 1.12.0 
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
HassOS on raspberry Pi 3 B+

**Description of problem:**
Can't update to 1.12.0, the image doesn't exist on docker hub

**Your logs from Hass.io**
20-03-19 08:42:19 INFO (SyncWorker_14) [supervisor.docker.interface] Update image dwelch2101/zigbee2mqtt-armhf:1.11.0 to dwelch2101/zigbee2mqtt-armhf:1.12.0
20-03-19 08:42:19 INFO (SyncWorker_14) [supervisor.docker.interface] Pull image dwelch2101/zigbee2mqtt-armhf tag 1.12.0.
20-03-19 08:42:20 ERROR (SyncWorker_14) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.12.0 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.12.0 not found: manifest unknown: manifest unknown").

**Comment by agsola** [comment]
Ssame error here in PI 4
20-03-19 09:10:41 ERROR (SyncWorker_11) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.12.0 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.12.0 not found: manifest unknown: manifest unknown").
