### ISSUE TITLE
Add advanced settting homeassistant_legacy_triggers

### ISSUE THREAD

**Issue by apeeters** [danielwelch/hassio-zigbee2mqtt#313]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.12.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Hass.io

**Description of problem:**
zigbee2mqtt 1.12 introduced a new advanced setting `homeassistant_legacy_triggers`. Please add support for this in hassio-zigbee2mqtt.

Reference:

```
# Optional: Home Assistant legacy triggers (default: shown below), when enabled:
# - Zigbee2mqt will send an empty 'action' or 'click' after one has been send
# - A 'sensor_action' and 'sensor_click' will be discoverd
homeassistant_legacy_triggers: true
```

Zigbee2mqtt issue: https://github.com/Koenkk/zigbee2mqtt/issues/3033

**Comment by artem-dudarev** [comment]
When I try to add this setting I get the following warning in the system log:

> WARNING (MainThread) [supervisor.addons.validate] Unknown options homeassistant_legacy_triggers

**Comment by artem-dudarev** [comment]
@danielwelch This issue is not resolved

**Comment by andriej** [comment]
+1

**Comment by apeeters** [comment]
I created a PR: https://github.com/danielwelch/hassio-zigbee2mqtt/pull/376
