### ISSUE TITLE
Add device option to Json for edge Version

### ISSUE THREAD

**Issue by Nailik** [danielwelch/hassio-zigbee2mqtt#315]
Hi,

in zigbee2mqtt they added 

```
serial:
  adapter: <z-stack|deconz>
  port: /dev/ttyS0
```

in dev branch so it works with deconz (conbee 2 stick) see:
https://github.com/Koenkk/zigbee-herdsman/issues/72

I tried to fork this project and add the Json by myself until it's done in this project, but it keeps removing the "adapter" part (i updated config.json in scheme).
So i hope you find some time to do this in the edge Version

Greetings

**Comment by EpicLPer** [comment]
Issue is not stale, Stalebot...
