### ISSUE TITLE
Device specific configuration in Config

### ISSUE THREAD

**Issue by ryanbeaton** [danielwelch/hassio-zigbee2mqtt#32]
Sorry if I have missed this somewhere but how do you put [Device specific configuration](https://github.com/Koenkk/zigbee2mqtt/wiki/Device-specific-configuration) into the config of the Hass.io add-on?

**Comment by ciotlosm** [comment]
You should be able to do this by editing configuration files in /share/zigbee2mqtt directly.

**Comment by ryanbeaton** [comment]
Thank you @ciotlosm
For others reading, if you install the SSH Server add-on you can ssh in to hassio.local, cd to /share/zigbee2mqtt and nano configuration.yaml

@danielwelch do you see this being exposed in the add-on Config box?

**Comment by ciotlosm** [comment]
@ryanbeaton we’ll update the docs with this information. Thanks for sharing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielwelch** [comment]
@ryanbeaton Another option that may be more beginner-friendly is using the official samba share add-on, which will let you edit files on your device using the text editor of your choice if uncomfortable on the command line.

I don't see this being exposed in the add-on frontend config any time soon, as the configuration file is dynamically rewritten during the lifetime of the application, whereas the add-on is generally only usable for setting options at startup. See previous (now closed) issues on this repository for similar discussions on handling config. That's not to say that it would be impossible (for ultimate overkill, the add-on could expose a web UI for editing `configuration.yaml` cleanly and during runtime), just maybe not worth the effort in the near-term when a simple alternative exists by editing a yaml file.

**Comment by ciotlosm** [comment]
@danielwelch I do think we need to add either samba, ssh or sshfs documentation to the addon readme.md to allow people to configure this. I'm currently away and with limited connectivity, but I'll try to add it at the end of the week.

**Comment by danielwelch** [comment]
@ciotlosm I've updated the docs with a section on modifying `configuration.yaml` with links to the official samba share and SSH add-ons, as well as the community SSH add-on.

**Comment by talondnb** [comment]
I believe you will always have the unknown values until next poll, triggered from the device itself.

**Comment by danielwelch** [comment]
No worries, I totally agree with your goal for how you want hassio to run and I think anything that can be done to move things toward a “set it and forget it” state is more than worth it. But am I right in saying that this particular problem is a separate issue, like talondb suggests? If so, I’ll close this.

**Comment by ryanbeaton** [comment]
@talndnb Setting retain true worked for me. Restarted hass.io and the values were there. Consumption on the sockets was unknown as I didn’t set them as retained so I know it worked.

@danielwelch no issue, was just giving you understanding what I was up to so you knew use case.

**Comment by danielwelch** [comment]
Awesome, thanks for reporting back

**Comment by talondnb** [comment]
Thanks for confirming, that’s good to know!

**Comment by ryanbeaton** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/139#issuecomment-399661976
