### ISSUE TITLE
zigbee2mqtt not strarting after update

### ISSUE THREAD

**Issue by ageurtse** [danielwelch/hassio-zigbee2mqtt#322]
ubuntu server 18.04.4 LTS
Hassio running in docker
Hassio version : 0.108.1
zigbee2mqtt: 1.12.2

**Description of problem:**
Hello, 

it seems that after updateing Hassio, zigbee2mqtt stopt working.
in the logs of hassio and the logs from zigbee2mqtt remains empty about zigbee2mqtt i cant find anything about zigbee2mqtt. 
why isn't my device started and why can't i find anything aboutt this in the log files. 
**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: '***********'
  user: ******
  password: '******'
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E32312-if00
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: true
```

*** Partial configfile hassio ***
```json
#Tuya devices
tuya:
  username: !secret tuya_usr
  password: !secret tuya_pwd
  country_code: +31

logger:
  default: info

utility_meter:
###### DSMR METER READINGS ######
  hourly_gas:
    source: sensor.gas_consumption
    cycle: hourly

remote:
  - platform: harmony
    name: Woonkamer
```

**zigbee2mqtt log:**
there is nothing in the log

**Comment by SpecialT131** [comment]
+1 Same Problem here

**Comment by wreality** [comment]
The supervisor logs have this error for me is this the case for others as well ?

> 20-04-09 19:54:08 ERROR (SyncWorker_11) [supervisor.docker] Can't create container from addon_7ad98f9c_zigbee2mqtt: 404 Client Error: Not Found ("No such image: dwelch2101/zigbee2mqtt-armhf:1.12.2")

**Comment by ageurtse** [comment]
yes, same error here. didn't look earlyer in the supervisor log.

**Comment by wreality** [comment]
Docker hub shows an image for 1.12.2 not sure why the supervisor isn’t grabbing it. I wonder if a remove and re-install would fix it. 

https://hub.docker.com/r/dwelch2101/zigbee2mqtt-armhf/tags

**Comment by urbatecte** [comment]
Hassio version : 0.108.1
zigbee2mqtt: 1.12.2  
Same here : Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
But ZHA do not find the ti_cc anymore since HA 108 update.

**Comment by ageurtse** [comment]
uninstall en reinstall did the job for me,

**Comment by matthewjporter** [comment]
Had the failed to connect errors with my CC1352P-2 adapter

Read the dev firmware fixes it so have it a go and the errors have gone

I also changed to using “port: null” in my config and now my network is rock solid

Homeassistant and Zigbee2mqtt on Ubuntu 18.04 as docker

**Comment by ageurtse** [comment]
> Had the failed to connect errors with my CC1352P-2 adapter
> 
> Read the dev firmware fixes it so have it a go and the errors have gone
> 
> I also changed to using “port: null” in my config and now my network is rock solid
> 
> Homeassistant and Zigbee2mqtt on Ubuntu 18.04 as docker

I think your error is different then we discuse here. oure error has nothing to do with not connecting the usb/serial adapter.

**Comment by fodi666** [comment]
I had the same problem with a missing image 1.12.2 but having a 1.12.1 image downloaded. Finally I did `ha su repair` through the CLI and then it came back to life. (running currently 1.106.4 with supervisor 214 as hassio on ubuntu server amd64)

**Comment by ronniebee** [comment]
same problem, reinstall (hassio) did the job.

**Comment by mprice43** [comment]
> I had the same problem with a missing image 1.12.2 but having a 1.12.1 image downloaded. Finally I did `ha su repair` through the CLI and then it came back to life. (running currently 1.106.4 with supervisor 214 as hassio on ubuntu server amd64)

I have the same issue.
I am running HA Core  version 0.107.7
Hass OS 3.1, Supervisor Version 214 on Raspberry Pi 3b hardware and TI_CC2531 Zigbee USB.
I ran 'ha su repair' in an SSH session as suggested. 
This solved the problem of Zigbee2MQTT not starting but I ended up with a new problem

zigbee2mqtt:info  2020-04-10 12:11:47: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-04-10 12:11:55: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-04-10 12:11:55: Failed to start zigbee
zigbee2mqtt:error 2020-04-10 12:11:55: Exiting...
zigbee2mqtt:error 2020-04-10 12:11:55: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.12.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:71:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.12.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.12.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.12.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-10T02_11_55_527Z-debug.log

I eventually fixed this problem by unpluggin and Re-pluging in my CC2531 USB

**Comment by oospat** [comment]
`ha su repair` did the job for me.

**Comment by urbatecte** [comment]
Uninstall/reinstall doesn't help for me but unplug/replug do the trick 👍

**Comment by casvanom** [comment]
installing the terminal&ssh addon, then running ha su repair did it for me. thanks guys.

**Comment by matthewjporter** [comment]
> > Had the failed to connect errors with my CC1352P-2 adapter
> > Read the dev firmware fixes it so have it a go and the errors have gone
> > I also changed to using “port: null” in my config and now my network is rock solid
> > Homeassistant and Zigbee2mqtt on Ubuntu 18.04 as docker
> 
> I think your error is different then we discuse here. oure error has nothing to do with not connecting the usb/serial adapter.
If you only want suggestions On specific issue then don’t post full logs

I was responding to the comment(s) with these errors in the event log of @urbatecte 

Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

**Comment by greynoO** [comment]
Had the same issue, reinstall fixed it!

**Comment by ageurtse** [comment]
because of the solution / workaround is already given i close this issue.
