### ISSUE TITLE
No update option for hassio addin

### ISSUE THREAD

**Issue by Johnyb62** [danielwelch/hassio-zigbee2mqtt#327]
V1.6.0
rPi2 HassIO 

Noticd the auto update was disabled which I corrected, but there's no update notification or option on the addin to update as per other apps.  

data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://x.x.x.x'
  user: xxx
  password: xxx
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
  availability_blacklist: []
ban: []
whitelist: []
queue: {}

**Comment by photonforge** [comment]
Same here. im at 1.11.0 version of the addon. there is no option to update on the gui.

**Comment by HydrelioxGitHub** [comment]
Same with version 1.10.1, no update available.

**Comment by HydrelioxGitHub** [comment]
I figure it out that the repository disappeared from Home Assistant. After re-enter it, the update is available.

**Comment by Johnyb62** [comment]
> I figure it out that the repository disappeared from Home Assistant. After re-enter it, the update is available.
Brilliant that was my problem, didn’t think to check it had somehow been removed. Much appreciated.
