### ISSUE TITLE
BT not working

### ISSUE THREAD

**Issue by paskyecijano** [danielwelch/hassio-zigbee2mqtt#33]
I have this device https://www.home-assistant.io/components/sensor.mitemp_bt/ but can not read the info.

i think that the problem is this

bcm43xx_init
Flash firmware /lib/firmware/brcm/BCM43430A1.hcd
Set BDADDR UART: b8:27:eb:aa:aa:aa
Set Controller UART speed to 921600 bit/s
Device setup complete

the number MAC not is correct. b8:27:eb:**aa:aa:aa**

**Comment by ciotlosm** [comment]
@paskyecijano You might have got the wrong repository. This is for zigbee type of devices using a CC2531 device from Texas Instruments. 

For bluetooth related questions & issues please use https://github.com/home-assistant/hassio/issues.
