### ISSUE TITLE
How to access the data directory?

### ISSUE THREAD

**Issue by swissbyte** [danielwelch/hassio-zigbee2mqtt#330]
Hi there

I would like to manually update my devices.js
How can i access the data directory? I have installe HA supervised. Therefore i have full access to the underlaying OS. 

Thanks

**Comment by coolguymatt** [comment]
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#hassio-addon

**Comment by danielwelch** [comment]
There's an officially supported way to do this listed in the README for this add-on: https://github.com/danielwelch/hassio-zigbee2mqtt#adding-support-for-new-devices
