### ISSUE TITLE
Can't get zigbee2mqtt to work

### ISSUE THREAD

**Issue by Duff78** [danielwelch/hassio-zigbee2mqtt#332]
**zigbee2mqtt add-on version 1.12.2**

**Operating environment Hass.io**

**I have been using zigbee2mqtt in the past and am a great fan of what you made.
That said I restarted on the same device Pi4 with latest hassio with zigbee2mqtt and a CC2531 and have the same problems as a few here, but I'm a novice and couldn't find enough information to solve the same issue. Hope I'm posting this in the right location. If not, sorry. In need of help, thanks**

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto",
    "user": "mqtt user",
    "password": "mqtt password"
  },
  "serial": {
    "port": "/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B000BE89D97-if00"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1,
    "initialdelay": 1,
    "options": "-d -d",
    "log": false
  }
}
```

**Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-04-27T23:36:56: PM2 log: Launching in no daemon mode
2020-04-27T23:36:56: PM2 log: App [npm:0] starting in -fork mode-
2020-04-27T23:36:56: PM2 log: App [npm:0] online
> zigbee2mqtt@1.12.2 start /zigbee2mqtt-1.12.2
> node index.js
zigbee2mqtt:info  2020-04-27 23:36:59: Logging to console and directory: '/share/zigbee2mqtt/log/2020-04-27.23-36-59' filename: log.txt
zigbee2mqtt:info  2020-04-27 23:37:00: Starting zigbee2mqtt version 1.12.2 (commit #unknown)
zigbee2mqtt:info  2020-04-27 23:37:00: Starting zigbee-herdsman...
(node:233) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - activeEpReq after 6000ms
    at Timeout._onTimeout (/zigbee2mqtt-1.12.2/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:233) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:233) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
zigbee2mqtt:error 2020-04-27 23:37:12: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-04-27 23:37:12: Failed to start zigbee
zigbee2mqtt:error 2020-04-27 23:37:12: Exiting...
zigbee2mqtt:error 2020-04-27 23:37:12: Error: AREQ - ZDO - activeEpRsp after 10000ms
    at Timeout._onTimeout (/zigbee2mqtt-1.12.2/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm
 ERR! code ELIFECYCLE
npm 
ERR! errno 1
npm ERR! zigbee2mqtt@1.12.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm 
ERR! Failed at the zigbee2mqtt@1.12.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-27T21_37_17_716Z-debug.log
2020-04-27T23:37:17: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-04-27T23:37:17: PM2 log: App [npm:0] starting in -fork mode-
2020-04-27T23:37:17: PM2 log: App [npm:0] online
> zigbee2mqtt@1.12.2 start /zigbee2mqtt-1.12.2
> node index.js
zigbee2mqtt:info  2020-04-27 23:37:20: Logging to console and directory: '/share/zigbee2mqtt/log/2020-04-27.23-37-20' filename: log.txt
zigbee2mqtt:info  2020-04-27 23:37:21: Starting zigbee2mqtt version 1.12.2 (commit #unknown)
zigbee2mqtt:info  2020-04-27 23:37:21: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-04-27 23:37:33: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-04-27 23:37:33: Failed to start zigbee
zigbee2mqtt:error 2020-04-27 23:37:33: Exiting...
zigbee2mqtt:error 2020-04-27 23:37:33: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.12.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:71:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.12.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm
 
ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.12.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.12.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-27T21_37_38_966Z-debug.log
2020-04-27T23:37:39: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-04-27T23:37:39: PM2 log: App [npm:0] starting in -fork mode-
2020-04-27T23:37:39: PM2 log: App [npm:0] online
> zigbee2mqtt@1.12.2 start /zigbee2mqtt-1.12.2
> node index.js
zigbee2mqtt:info  2020-04-27 23:37:42: Logging to console and directory: '/share/zigbee2mqtt/log/2020-04-27.23-37-42' filename: log.txt
zigbee2mqtt:info  2020-04-27 23:37:42: Starting zigbee2mqtt version 1.12.2 (commit #unknown)
zigbee2mqtt:info  2020-04-27 23:37:42: Starting zigbee-herdsman...**

**Comment by mperci** [comment]
Same issue I think:

zigbee2mqtt:info  2020-05-03 11:26:08: Starting zigbee2mqtt version 1.13.0 (commit #unknown)
zigbee2mqtt:info  2020-05-03 11:26:08: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-05-03 11:26:08: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-05-03 11:26:08: Failed to start zigbee
zigbee2mqtt:error 2020-05-03 11:26:08: Exiting...
zigbee2mqtt:error 2020-05-03 11:26:08: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:113:32)
    at Generator.next (<anonymous>)
    at /zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:4:12)
    at SerialPort.<anonymous> (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:111:49)
    at SerialPort._error (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm
 ERR! code ELIFECYCLE
npm ERR!
 
errno 1
npm ERR! zigbee2mqtt@1.13.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.13.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-03T15_26_08_512Z-debug.log
2020-05-03T11:26:09: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-05-03T11:26:09: PM2 log: App [npm:0] starting in -fork mode-
2020-05-03T11:26:09: PM2 log: App [npm:0] online
> zigbee2mqtt@1.13.0 start /zigbee2mqtt-1.13.0
> node index.js
