### ISSUE TITLE
new release(1.13.0) can't start on hassOS

### ISSUE THREAD

**Issue by jpalczewski** [danielwelch/hassio-zigbee2mqtt#334]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 1.13.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):** hassOS  on rpi3

**Description of problem:** After updating to 1.13.0 from 1.12.2 hassOS has problems with docker image - also portainer can't download it. 

**Your entire configuration from the frontend (with sensitive fields redacted)**: n/a

**Your logs from Hass.io**
```
20-05-01 14:31:58 ERROR (SyncWorker_14) [supervisor.docker] Can't create container from addon_7ad98f9c_zigbee2mqtt: 404 Client Error: Not Found ("No such image: dwelch2101/zigbee2mqtt-armhf:1.13.0")
```

**Comment by j-iglesias** [comment]
Hola, me pasó lo mismo pero lo solucioné desinstalando y volviendo a instalar el complemento, cabe destacar que actualicé hassio con la última versión, la 0.109.3

**Comment by jpalczewski** [comment]
@j-iglesias is right - reinstall solves the problem. My problem was also in the connectivity - I wasn't calm enough to wait, but dependent docker images have about 100mb. Downloading/updating the docker image in community ssh might be a better option for power users - it is a much more informative way than a WebUI.
