### ISSUE TITLE
Cannot enable option adapter: deconz

### ISSUE THREAD

**Issue by hutchinsane** [danielwelch/hassio-zigbee2mqtt#336]
Currently, it is not possible to add the entry 

adapter: deconz 

in the configuration file in order to enable raspbee/conbee support for z2m on hassio. Adding the entry simply has no effect, and it also doesn't appear in the configuration file

**Comment by And3rsL** [comment]
same here

**Comment by Dimand** [comment]
Would be great to get this fixed. Currently no way to test the new Zigbee herdsman support of the Conbee with hassio that I have found.

**Comment by joe540** [comment]
> 
> 1. Add `e2fsprogs-extra` to the list of `packages` in the config of the SSH add-on. This is so it it makes `chattr` available for use within the add-on
> 
@mdegat01 This may appear stupid, but I'm unable to build the SSH addon locally so I'm not able to add e2fsprogs-extra to requirements.txt

Would you be able to point me in the right direction? Without the immutable config file, the addon rewrite the file everytime it's restarted :(

Thanks a lot for that workaround!

**Comment by joe540** [comment]
OK, I was able to install it in the running container but didn't have the right to set the immutable flag.
I had to install it in the main docker container of Home Assistant and was able to set the flag.

Sorry for that!
