### ISSUE TITLE
1.13.1 not available for ARM

### ISSUE THREAD

**Issue by Kisty** [danielwelch/hassio-zigbee2mqtt#341]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 1.13.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

HassOS: 
Raspberry Pi 3 B

**Description of problem:**
Unable to update from 1.13.0 to 1.13.1.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
N/A

**Your logs from Hass.io**
Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.13.1 not found: manifest unknown: manifest unknown").

**Comment by noob4ik** [comment]
Unable to install plugin

It seems there is no image 1.13.1 in docker hub
https://hub.docker.com/r/dwelch2101/zigbee2mqtt-armhf/tags

**Comment by Kisty** [comment]
Oops dupe #340
