### ISSUE TITLE
After updating to 1.14.0 i can't assign new devices.

### ISSUE THREAD

**Issue by DiegoFoxy** [danielwelch/hassio-zigbee2mqtt#348]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
#1.14.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Raspberry pi 4 4GB
Hass.io on docker
HA 0.111.3

**Description of problem:**

Currently I have 5 devices connected to zigbee2mqtt and works fine.
But i can't assigned newone.
I trying with Aqara motion sensor, Aqara door window sensor, Mija door sensor, Ikea remote

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
//data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: *******
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false


**Your logs from Hass.io**

**Comment by tego1** [comment]
I have the same problem after v. 1.14 (main & edge)
Win 10 + vmware + Home Assistant 0.111.4
I had only 1 device ("MiJia wireless switch (WXKG01LM)") paired before the update.
But after the update I tried to pair another 2 -II- swithes, 3x MiJia temp&humi sensors and 2x MiJia magnetic door switches. But now everytime I manage to start pairing it fails with interview unsuccessful error. I tried USB extension cable, flashing my CC2351 with the 3.0 FW, changing zigbee channels, stop addon-unplug CC2531-replug-start addon. But after 100 attempts I managed to pair only 1 of the door switches - but next attempts with this door switch were unsuccessful. In every stage I also tried the remote switch I paired with older version then 1.14 and this switch pairs everytime. 

data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: *****
  client_id: zigbee2mqtt
serial:
  port: /dev/ttyACM0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true

**Comment by jhbcosta** [comment]
Same issue here. 
I cannot pair new device after pairing the 5th device.

**Comment by DiegoFoxy** [comment]
Problem was with wrong version of firmware on C2531.
