### ISSUE TITLE
Clean Zigbee2MQTT add-on install won't start (Failed to connect to the adapter)

### ISSUE THREAD

**Issue by husq101** [danielwelch/hassio-zigbee2mqtt#349]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.14.0 
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
RPI4, HASS.IO version 0.111.3 with Zigbee2MQTT add-on installed.

**Description of problem:**
Zigbee2MQTT won't start, tried things like rebooting the system, changing the config file, checking free-memory space, re-installing the add-on, checking if the port ttyACM0 is accesable etc.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: 
  password:
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

```

**Your logs from Hass.io**

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-06-17T18:59:52: PM2 log: Launching in no daemon mode
2020-06-17T18:59:52: PM2 log: App [npm:0] starting in -fork mode-
2020-06-17T18:59:52: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.0 start /zigbee2mqtt-1.14.0
> node index.js
zigbee2mqtt:info  2020-06-17 18:59:58: Logging to console and directory: '/share/zigbee2mqtt/log/2020-06-17.18-59-58' filename: log.txt
zigbee2mqtt:info  2020-06-17 18:59:59: Starting zigbee2mqtt version 1.14.0 (commit #unknown)
zigbee2mqtt:info  2020-06-17 18:59:59: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-06-17 19:00:07: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-06-17 19:00:07: Failed to start zigbee
zigbee2mqtt:error 2020-06-17 19:00:07: Exiting...
zigbee2mqtt:error 2020-06-17 19:00:07: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:72:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.14.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by niek1992** [comment]
What FW is on the CC2531 stick? Sounds like you have firmware that isn't loaded correctly and misbehaves a bit. Did you try removing the stick for a few minutes and reinsert it to see if that fixes your problem?

**Comment by korro1975** [comment]
Hi husq101. I had the same issue and the only way to be able to have zigbee2mqtt up and running was inserting the stick once the raspberry is powered on and running for a while. Try the suggestion of niek1992 and turn on the raspberry and after a few minutes insert the stick. Good luck!.

**Comment by niek1992** [comment]
To add to @korro1975, this can also be caused by the use of a underpowered power adapter. Do you use a correctly specced one?

**Comment by husq101** [comment]
Hi! @niek1992 @korro1975 
I used the latest version of KoenK for flashing. Checked the power adapter (original Raspberry adapter) which results in 5.1 Volts 2,5A. But will try nother adapter when I found one and see if that fixes the problem. Could be the issue perhaps.

Any ideas on what I can do more?

**Comment by korro1975** [comment]
Hi @husq101.
Unfortunately I'm completely junior in this matter and I only have followed links and public documentation so no more ideas on this matter I can provide, sorry.
Regards.

**Comment by korro1975** [comment]
Hi Team,
I still have the same issue. The only way to have z2mqtt service running is unplug and plug the stick. Were you able to solve this issue. I have trying with "uhubctl" commands but unstable behavior is obtained.
I would be very grateful if you have solved this issue in some way.
Thanks in advance.

**Comment by husq101** [comment]
> Hi Team,
> I still have the same issue. The only way to have z2mqtt service running is unplug and plug the stick. Were you able to solve this issue. I have trying with "uhubctl" commands but unstable behavior is obtained.
> I would be very grateful if you have solved this issue in some way.
> Thanks in advance.

Hi Korro1975, Are you running HASS on the Raspberry Pi? Which model Pi are you using?

**Comment by korro1975** [comment]
Hi Husq101.
I am using RBPI 4B (4GB RAM). In my case I execute a script on each reboot that turns off and on the USB ports (2.0) where my sitck is plugged and then execute "sudo npm start". I have had to fine tune the number of seconds because the behavior was unstable too but now it seems to work fine most of times.
I hope this help.
Regards.
    On Monday, August 10, 2020, 07:46:23 PM GMT+2, husq101 <notifications@github.com> wrote:  
 
 



Hi Team,
I still have the same issue. The only way to have z2mqtt service running is unplug and plug the stick. Were you able to solve this issue. I have trying with "uhubctl" commands but unstable behavior is obtained.
I would be very grateful if you have solved this issue in some way.
Thanks in advance.


Hi Korro1975, Are you running HASS on the Raspberry Pi? Which model Pi are you using?

**Comment by ciotlosm** [comment]
Have you tried pressing the button on the device as well? I'm using /dev/serial entry from hardware to connect to the device to avoid /dev/tty moving on reboot.

**Comment by ciotlosm** [comment]
As this is a problem with either the adapter or the firmware and nothing that this repo can fix, I recommend you open an issue in https://github.com/Koenkk/zigbee2mqtt.
