### ISSUE TITLE
external_converters option does not work

### ISSUE THREAD

**Issue by artem-dudarev** [danielwelch/hassio-zigbee2mqtt#351]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.14.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

HassOS

**Description of problem:**
external_converters option does not work.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```markdown
external_converters:
  - lonsonho.js
```

**Your logs from Hass.io**
```
WARNING (MainThread) [supervisor.addons.validate] Unknown options external_converters
```

**Comment by IronButterfly** [comment]
The same issue. Please add support for external converters.
Thanks.

**Comment by nurikk** [comment]
Bump

**Comment by tayanov** [comment]
+1

**Comment by nurikk** [comment]
this issue resolved in #353, kindly help to merge

**Comment by vring0** [comment]
+1

**Comment by klim123123** [comment]
+1
