### ISSUE TITLE
The Zigbee2mqtt add-on can't start later of 1.14.1 update

### ISSUE THREAD

**Issue by maruiz81** [danielwelch/hassio-zigbee2mqtt#352]
**zigbee2mqtt add-on version:**  1.14.1

**Rasberry Pi 3 B**
**Home Assistant version  0.111.4**

**Description of problem:**
The version 1.14.0 was working like a charm I have updated 5o 1.14.1 and them it can't start. I have tried to uninstall and install it again a not success. In the logs, I have the next message:

20-07-01 07:09:41 ERROR (SyncWorker_5) [supervisor.docker] Can't create container from addon_7ad98f9c_zigbee2mqtt: 404 Client Error: Not Found ("No such image: dwelch2101/zigbee2mqtt-armhf:1.14.1")

**Comment by Kisty** [comment]
Ah, this happened last time. See #340. The ARM image isn't being built when it's released. Glad I hadn't tried to install the update.

**Comment by maruiz81** [comment]
Thank you for the update, it is the first time it fails to me. I am gonna try with the edge version meanwhile

**Comment by formatBCE** [comment]
Same here. I don't think it's normal to post updates in this manner.

**Comment by marius-se** [comment]
Same here

**Comment by marius-se** [comment]
Nevermind: After restarting the host system zigbee2mqtt magically appeared in the add-ons panel...

**Comment by ciotlosm** [comment]
Closing this as there seems to be a problem somewhere. Multiple reports on "No such image" reference.
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/366
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/365
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/352
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/334
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/293

https://github.com/danielwelch/hassio-zigbee2mqtt/issues/267#issuecomment-558845125
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/340#issuecomment-631652864
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/340#issuecomment-638257269

https://github.com/danielwelch/hassio-zigbee2mqtt/issues/382
