### ISSUE TITLE
Zigbee2mqtt doesn't start after update to 1.14.1

### ISSUE THREAD

**Issue by smarti** [danielwelch/hassio-zigbee2mqtt#355]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.14.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
Raspberry PI 4 (4 GB model)
HassOS 4.10 / Supervisor version 228
Zigbee usb: usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2192166-if00

**Description of problem:**
Since the 1.14.1 update I am no longer able to start zigbee2mqtt.

The problem started on an x86 desktop running hassio, which I accidentally removed all the docker containers from when trying to find out why Zigbee stopped working.

Knowing I had to make a fresh start, I installled hassio on a Raspberry PI 4.
I have tried two different Zigby USB sticks and tried configuring the serial port with the serial id as well as /dev/ttyACM0. None of which have made any difference.
Even switching from the release addon to the edge version didn't make any difference for the errors I am getting.
I even tried reinstalling hassio on the pi to be sure I didn't misconfigure anything else.

Since I am all out of options, but would prefer to keep using this add-on, I am posting the issue here in the hope someone can help me out.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: zigbee2mqtt
  password: [Redacted]
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2192166-if00
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

```

**Your logs from Hass.io**
> zigbee2mqtt@1.14.1-dev start /app
> node index.js
zigbee2mqtt:info  2020-07-03 15:57:27: Logging to console and directory: '/share/zigbee2mqtt/log/2020-07-03.15-57-27' filename: log.txt
zigbee2mqtt:info  2020-07-03 15:57:27: Starting zigbee2mqtt version 1.14.1-dev (commit #)
zigbee2mqtt:info  2020-07-03 15:57:27: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-07-03 15:57:35: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-07-03 15:57:35: Failed to start zigbee
zigbee2mqtt:error 2020-07-03 15:57:35: Exiting...
zigbee2mqtt:error 2020-07-03 15:57:35: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:72:23)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.14.1-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.1-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-03T13_57_35_394Z-debug.log
2020-07-03T15:57:36: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-07-03T15:57:36: PM2 log: App [npm:0] starting in -fork mode-
2020-07-03T15:57:36: PM2 log: App [npm:0] online

**Comment by stefagi** [comment]
I have the same problem, restarting the host, sometimes zigbee works for a few minutes, then it returns in error.
My system runs on Virtualbox.

zigbee2mqtt:info  2020-07-06 10:45:41: Logging to console and directory: '/share/zigbee2mqtt.cc2531/log/2020-07-06.10-45-41' filename: log.txt
zigbee2mqtt:info  2020-07-06 10:45:42: Starting zigbee2mqtt version 1.14.1 (commit #unknown)
zigbee2mqtt:info  2020-07-06 10:45:42: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-07-06 10:45:42: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-07-06 10:45:42: Failed to start zigbee
zigbee2mqtt:error 2020-07-06 10:45:42: Exiting...
zigbee2mqtt:error 2020-07-06 10:45:42: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:123:32)
    at Generator.next (<anonymous>)
    at /zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:4:12)
    at SerialPort.<anonymous> (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:121:49)
    at SerialPort._error (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.14.1 start: `node index.js`
npm ERR! Exit status 1

**Comment by Tam-Lin** [comment]
I'm having the same problem.

**Comment by groenmarsmannetje** [comment]
I have this too. This requires an urgent fix because the whole add on is now useless.

**Comment by InvertedMinor** [comment]
Despite numerous restarts and reboots 1.14.2 does not start. the edge version does start...luckily

**Comment by isoinh** [comment]
> I have the same problem, restarting the host, sometimes zigbee works for a few minutes, then it returns in error.
> My system runs on Virtualbox.
> 
> zigbee2mqtt:info 2020-07-06 10:45:41: Logging to console and directory: '/share/zigbee2mqtt.cc2531/log/2020-07-06.10-45-41' filename: log.txt
> zigbee2mqtt:info 2020-07-06 10:45:42: Starting zigbee2mqtt version 1.14.1 (commit #unknown)
> zigbee2mqtt:info 2020-07-06 10:45:42: Starting zigbee-herdsman...
> zigbee2mqtt:error 2020-07-06 10:45:42: Error while starting zigbee-herdsman
> zigbee2mqtt:error 2020-07-06 10:45:42: Failed to start zigbee
> zigbee2mqtt:error 2020-07-06 10:45:42: Exiting...
> zigbee2mqtt:error 2020-07-06 10:45:42: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
> at Znp. (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:123:32)
> at Generator.next ()
> at /zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:8:71
> at new Promise ()
> at __awaiter (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:4:12)
> at SerialPort. (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:121:49)
> at SerialPort._error (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
> at /zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
> npm
> ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! zigbee2mqtt@1.14.1 start: `node index.js`
> npm ERR! Exit status 1

@stefagi Perhaps modifying the port in configuration would help here as per:
zigbee2mqtt:error 2020-07-06 10:45:42: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'

In my case the port is:
# ls -la /dev/ttyA*
crw-rw---- 1 root dialout 204, 64 Jul 22 10:24 /dev/ttyAMA0

**Comment by isoinh** [comment]
> > I have the same problem, restarting the host, sometimes zigbee works for a few minutes, then it returns in error.
> > My system runs on Virtualbox.
> > zigbee2mqtt:info 2020-07-06 10:45:41: Logging to console and directory: '/share/zigbee2mqtt.cc2531/log/2020-07-06.10-45-41' filename: log.txt
> > zigbee2mqtt:info 2020-07-06 10:45:42: Starting zigbee2mqtt version 1.14.1 (commit #unknown)
> > zigbee2mqtt:info 2020-07-06 10:45:42: Starting zigbee-herdsman...
> > zigbee2mqtt:error 2020-07-06 10:45:42: Error while starting zigbee-herdsman
> > zigbee2mqtt:error 2020-07-06 10:45:42: Failed to start zigbee
> > zigbee2mqtt:error 2020-07-06 10:45:42: Exiting...
> > zigbee2mqtt:error 2020-07-06 10:45:42: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
> > at Znp. (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:123:32)
> > at Generator.next ()
> > at /zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:8:71
> > at new Promise ()
> > at __awaiter (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:4:12)
> > at SerialPort. (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:121:49)
> > at SerialPort._error (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
> > at /zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
> > npm
> > ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! zigbee2mqtt@1.14.1 start: `node index.js`
> > npm ERR! Exit status 1
> 
> @stefagi Perhaps modifying the port in configuration would help here as per:
> zigbee2mqtt:error 2020-07-06 10:45:42: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
> 
> In my case the port is:
> ls -la /dev/ttyA*
> crw-rw---- 1 root dialout 204, 64 Jul 22 10:24 /dev/ttyAMA0

Well... wrongly advised from me, that is definitely not the correct tty device. My apologies.
In my case, I just flashed the dongle and everything worked right out of the box after that, only few variables needed to be changed to match my setup.

I used this as instructions "https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html" for the flashing procedure, only difference was that I needed to "update" those two drivers manually form windows device manager.

**Comment by oldfart101** [comment]
same problem with version 1.14.3

Operating environment (HassOS):
Raspberry PI 4 (4 GB model)
HassOS 4.12 / Supervisor version 235
Home Assistant 0.114.3

flashed CC2531 Zigbee Stick [Lumi]

serial:
/dev/ttyACM0
/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D956FC-if00
/dev/ttyAMA0

Zigbee working in homeassistant with /dev/serial/by-id/usb-Texas_Instruments...

zigbee2mqtt config:

data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: '192.168.1.10:1885' # mqtt broker running on Ubuntu VM on Unraid
  user: username
  password: password
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D956FC-if00
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

zigbee2mqtt error log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-08-26T09:35:54: PM2 log: Launching in no daemon mode
2020-08-26T09:35:54: PM2 log: App [npm:0] starting in -fork mode-
2020-08-26T09:35:54: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.3 start /zigbee2mqtt-1.14.3
> node index.js
Zigbee2MQTT:info  2020-08-26 09:35:57: Logging to console and directory: '/share/zigbee2mqtt/log/2020-08-26.09-35-57' filename: log.txt
Zigbee2MQTT:info  2020-08-26 09:35:58: Starting Zigbee2MQTT version 1.14.3 (commit #unknown)
Zigbee2MQTT:info  2020-08-26 09:35:58: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-08-26 09:36:17: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-08-26 09:36:17: Failed to start zigbee
Zigbee2MQTT:error 2020-08-26 09:36:17: Exiting...
Zigbee2MQTT:error 2020-08-26 09:36:17: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.14.3/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:87:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.14.3/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.14.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-26T08_36_17_880Z-debug.log
2020-08-26T09:36:18: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-08-26T09:36:18: PM2 log: App [npm:0] starting in -fork mode-
2020-08-26T09:36:18: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.3 start /zigbee2mqtt-1.14.3
> node index.js
Zigbee2MQTT:info  2020-08-26 09:36:21: Logging to console and directory: '/share/zigbee2mqtt/log/2020-08-26.09-36-21' filename: log.txt
Zigbee2MQTT:info  2020-08-26 09:36:22: Starting Zigbee2MQTT version 1.14.3 (commit #unknown)
Zigbee2MQTT:info  2020-08-26 09:36:22: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-08-26 09:36:42: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-08-26 09:36:42: Failed to start zigbee
Zigbee2MQTT:error 2020-08-26 09:36:42: Exiting...
Zigbee2MQTT:error 2020-08-26 09:36:42: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.14.3/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:87:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.14.3/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.14.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-26T08_36_42_264Z-debug.log
2020-08-26T09:36:43: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-08-26T09:36:43: PM2 log: App [npm:0] starting in -fork mode-
2020-08-26T09:36:43: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.3 start /zigbee2mqtt-1.14.3
> node index.js
Zigbee2MQTT:info  2020-08-26 09:36:45: Logging to console and directory: '/share/zigbee2mqtt/log/2020-08-26.09-36-45' filename: log.txt
Zigbee2MQTT:info  2020-08-26 09:36:46: Starting Zigbee2MQTT version 1.14.3 (commit #unknown)
Zigbee2MQTT:info  2020-08-26 09:36:46: Starting zigbee-herdsman...

**Comment by oldfart101** [comment]
as an aside, homeassistant (in supervisor - hardware) says the CC2531 Zigbee Stick is here:
/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D956FC-if00
there is no such file - HA is working and receives actions from the TICC2531
How do I determine where it is actually connected, since Zigbee2mqtt says it isn't there

**Comment by ciotlosm** [comment]
This is not a problem of the addon, but more of [zigbee2mqtt](http://github.com/koenkk/zigbee2mqtt). I'd recommend you open an issue there.

**Comment by invince** [comment]
in my case, I use virtualbox.
And you need add the usb device. Then you can find the /dev/ttyACM0

![image](https://user-images.githubusercontent.com/5184791/107130872-1b936f00-68d2-11eb-93f3-68d27b5fbeb6.png)

**Comment by xtrem16081987** [comment]
> in my case, I use virtualbox.
> And you need add the usb device. Then you can find the /dev/ttyACM0
> 
> ![image](https://user-images.githubusercontent.com/5184791/107130872-1b936f00-68d2-11eb-93f3-68d27b5fbeb6.png)

and it works ? 

what versions are you on !?
