### ISSUE TITLE
404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-amd64:1.14.2 not found").

### ISSUE THREAD

**Issue by bruvv** [danielwelch/hassio-zigbee2mqtt#360]
When updating I am getting the following error:
```
20-07-22 21:53:19 INFO (SyncWorker_0) [supervisor.docker.interface] Update image dwelch2101/zigbee2mqtt-amd64:1.14.1 to dwelch2101/zigbee2mqtt-amd64:1.14.2
20-07-22 21:53:19 INFO (SyncWorker_0) [supervisor.docker.interface] Pull image dwelch2101/zigbee2mqtt-amd64 tag 1.14.2.
20-07-22 21:53:20 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-amd64:1.14.2 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-amd64:1.14.2 not found").
```

Looks like it is going wrong at the azure pipeline and it's not being pushed to docker:
https://dev.azure.com/danielwelch2101/hassio-zigbee2mqtt/_build/results?buildId=207&view=logs&j=d822dde3-66a5-599f-9c9e-ed09ffe6609f&t=22f3bdd9-8b84-57c5-833f-5accb3b8a54d

**Comment by richard-scott** [comment]
I was just about to open an issue on the same thing :-)

**Comment by freman** [comment]
Is this why HA is like "can't install, unknown error, check logs"?
Cos if so I'll just go to work and try later lol

**Comment by rbron01** [comment]
The development version has been uploaded but not the production one.

**Comment by Koenkk** [comment]
Fixed
