### ISSUE TITLE
Startup delay in Home Assistant add-on

### ISSUE THREAD

**Issue by 0xygen8** [danielwelch/hassio-zigbee2mqtt#364]
**zigbee2mqtt add-on version 1.14.2
**Operating environment  homeassistant/intel-nuc-homeassistant:0.112.4
**Description of problem:**
When I restart the system (due to OS upgrades) the plugin never starts ok, (all states in HA stay Unknown) when I restart the plugin it works all right (race condition?)
This would could be a easy fix to start the container with a delay (configurable from frontend)

**Comment by fufar** [comment]
same problem, it will be nice

**Comment by ciotlosm** [comment]
Can you use the watchdog feature from Home Assistant to make sure addon is up?

**Comment by 0xygen8** [comment]
Today I retested this with watchdog enabled (on v1.14.4) and it started OK -- have to test more to see if it is magically resolved... @fufar can you retest also?

**Comment by ciotlosm** [comment]
I will close this for now. If something still not working after using `watchdog` please reopen.

**Comment by ciotlosm** [comment]
@0xygen8 @fufar I've also added https://github.com/danielwelch/hassio-zigbee2mqtt/pull/393 as this might improve things as well.

**Comment by 0xygen8** [comment]
That sounds like a real fix in opposite to the startup delay, thank you!
