### ISSUE TITLE
Aqara wireless switches (1st gen and 2nd gen) stop working after 1.14.3 update

### ISSUE THREAD

**Issue by SVhuMMer** [danielwelch/hassio-zigbee2mqtt#369]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

1.14.3

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

hass.io 0.113.3 in Docker on Ubunto 20.04 server

**Description of problem:**

After the latest update my 3 aqara wireless wall switches stopped working (two 86sw2 WXKG02LM and one remote.b286acn01 WXKG02LM) They do get back to normal work after manually rolling back to 1.14.2 via partial snapshot recovery.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration
```
**Your logs from Hass.io**

**Comment by thijselblaso** [comment]
I have the same problem!

**Comment by pznamenskii** [comment]
I had to change my automations from click to action (press, long_press, etc) to make them work again. aqara mini buttons are affected as well.

**Comment by pznamenskii** [comment]
in mqtt logs:

Zigbee2MQTT:info  2020-08-26 10:19:05: MQTT publish: topic 'zigbee2mqtt/wireless_switch_room_gold', payload '{"battery":100,"voltage":3035,"linkquality":57,"action":"single_right","click":"right"}'
Zigbee2MQTT:info  2020-08-26 10:19:05: MQTT publish: topic 'zigbee2mqtt/wireless_switch_room_gold', payload '{"battery":100,"voltage":3035,"linkquality":57,"action":""}'
Zigbee2MQTT:info  2020-08-26 10:19:05: MQTT publish: topic 'zigbee2mqtt/wireless_switch_room_gold/action', payload 'single_right'

though automations only react now to action payload and not to click - is the topic not published correctly?

**Comment by yaronbl** [comment]
I have the same problem. Going through system logs, it seems all devices (Aqara & Xiaomi buttons) that are 3+ feet a way from the receiver, gets a link quality 0, and are removed after a while. If I take one of the buttons closer to the receiver and press it, it will be discovered (device announced) and return to work for a few hours, till it drops down again. Tried 4 different buttons, all with full battery, and only 10 feet a way.

**Comment by ciotlosm** [comment]
This looks like a problem with zigbee2mqtt and should be reported on that repo. The add-on just wraps that functionality. Please report here: https://github.com/Koenkk/zigbee2mqtt.
