### ISSUE TITLE
no devices join 

### ISSUE THREAD

**Issue by Paddyirl** [danielwelch/hassio-zigbee2mqtt#37]
Hi I have hassio and have setup your hassio-zigbee2mqtt and have the following in the log 
> zigbee2mqtt@0.1.0 start /app
> node index.js
2018-7-20 10:41:00 INFO Starting zigbee2mqtt version 0.1.0 (commit #ae41b7b)
2018-7-20 10:41:00 INFO Starting zigbee-shepherd
2018-7-20 10:41:04 INFO zigbee-shepherd started
2018-7-20 10:41:04 INFO Currently 0 devices are joined:
2018-7-20 10:41:04 WARN `permit_join` set to  `true` in configuration.yaml.
2018-7-20 10:41:04 WARN Allowing new devices to join.
2018-7-20 10:41:04 WARN Set `permit_join` to `false` once you joined all devices.
2018-7-20 10:41:04 INFO Zigbee: allowing new devices to join.
2018-7-20 10:41:05 INFO Connecting to MQTT server at mqtt://homeassistant
2018-7-20 10:41:05 INFO zigbee-shepherd ready
2018-7-20 10:41:05 INFO Connected to MQTT server
2018-7-20 10:41:05 INFO MQTT publish, topic: 'zigbee2mqtt/bridge/state', payload: 'online'

I have reflashed the usb sniffer and uninstalled the hassio-zigbee addon and have installed the zigbee2mqtt-edge addon and get the same messages as above .I have put the ikea led 1622g12 e27 right beside the usb sniffer in rpi2 .Any help or suggestions would be much appreciated

**Comment by danielwelch** [comment]
I’d start with this issue in the zigbee2mqtt github repo unless we have a reason to believe the add on is the problem. Seems like it’s starting zigbee2mqtt fine, making it less likely to be a problem with the add-on (although it’s still possible).

**Comment by Paddyirl** [comment]
ok Thanks I will raise this in zigbee2mqtt github repo

**Comment by ciotlosm** [comment]
Seems raised here: https://github.com/Koenkk/zigbee2mqtt/issues/204
