### ISSUE TITLE
Enhancement request - addition of 'Jump to bottom' on log page

### ISSUE THREAD

**Issue by sym0nd0** [danielwelch/hassio-zigbee2mqtt#374]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.14.4
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

HassOS 4.12
RPi4 4Gb

**Description of enhancement request:**
Jump to bottom link/button on log page, especially for mobile, to allow for the latest log entry to be read quickly without the need to manually scroll.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
N/A

**Your logs from Hass.io**
N/A

**Comment by ciotlosm** [comment]
This functionality for log view management is done in Home Assistant. You should open an issue with the frontend there to add such support. The addon can't control the view.
