### ISSUE TITLE
Smart Smoke Sensor Heiman HS1SA - Zigbee2mqtt 1.14.4

### ISSUE THREAD

**Issue by eschefer** [danielwelch/hassio-zigbee2mqtt#377]
After update 1.14.4 my Smart Smoke Sensor (Heiman HS1SA) is not visable anymore in HA, and unable to find with automatic discovery.

**Comment by ciotlosm** [comment]
This looks like a problem with zigbee2mqtt and should be reported on that repo. The add-on just wraps that functionality. Please report here: https://github.com/Koenkk/zigbee2mqtt
