### ISSUE TITLE
Zigbee2MQTT addon 1.14.4: Xiaomi Honeywell smokedetectors doesn't work

### ISSUE THREAD

**Issue by Sandriekus** [danielwelch/hassio-zigbee2mqtt#379]
After upgrading Zigbee2MQTT official addon (master branch) to 1.14.4, my Xiaomi Honeywell Smoke detectors doesn't work anymore.

cannot set sensitivity:  no network route 205 error
cannot perform self-test: no network route 205 error
cannot repair the device, had to force-remove them and then repair

after restoring a back-up (Zigbee2MQTT 1.14.3) everything is working fine 

i'm running HA on a Raspberry Pi 4b with the slaesh’s CC2652RB stick

**Comment by ciotlosm** [comment]
@Sandriekus this looks like a problem with `zigbee2mqtt` and should be reported on that repo. The add-on just wraps that functionality. Please report here: https://github.com/Koenkk/zigbee2mqtt
