### ISSUE TITLE
CloudMQTT

### ISSUE THREAD

**Issue by arnonel** [danielwelch/hassio-zigbee2mqtt#38]
Hi there
Getting errors using CloudMQTT:

2018-7-23 09:33:13 INFO Connecting to MQTT server at mqtt://m21.cloudmqtt.com
2018-7-23 09:33:23 ERROR Not connected to MQTT server!

Relevant config:
  "mqtt_server": "mqtt://m21.cloudmqtt.com",
  "mqtt_user": "user",
  "mqtt_pass": "pass"

Question: How can I use CloudMQTT? Could it be because I need a port number that is not exposed by config?

**Comment by ciotlosm** [comment]
@arnonel how do you connect to CloudMQTT?

**Comment by arnonel** [comment]
Ignore. Found the issue. You can just append port to the MQTT URL.
