### ISSUE TITLE
Unable to edit fromZigbee.js

### ISSUE THREAD

**Issue by 7h0mas-R** [danielwelch/hassio-zigbee2mqtt#383]
Hi there,

I use HA with Zigbee2Mqtt for about 9 months and like how easy and fast I can expand it.
I am now working on integrating my first piece of new hardware (`Merten Wiser` roller-shutter controller).
I have most functionality working but would like to try adding a new `zigbee-herdsman-converter` to `fromZigbee.js`, to read a buffer from a `raw` message.

However, the instruction from the "How to add new devices (Hass-io add-on)" on the Zigbee2Mqtt documentation seems no longer to work for my installation - there is no docker installation anymore obviously.

How is Zigbee2Mqtt Add-on integrated into HA? Where/how can I find the `fromZigbee.js`? Or do I need to install Zigbee2Mqtt on a separate system to work on the converter files?

I'm on:
- OS 4.12
- HA core 0.114.3

Probably easy, but I just do not see it and did not find any hint searching the web. Happy if somebody can point me to the right spot...
Tom

**Comment by lovelylain** [comment]
Because hassio often re-creates the container and cannot custom the container parameters, it is not recommended to use the mapping method. It is recommended to use the new [external_converters](https://www.zigbee2mqtt.io/information/configuration.html#external-converters-configuration) option. Here is an example https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs /externalConvertersExample/dummy-converter.js

**Comment by ciotlosm** [comment]
@7h0mas-R thanks for reporting this. I agree with you docs will need a refresh and include this expicit. If you could try a PR after you complete your setup would be great (on this repo as it's very specific to this addon). 

Based on the docs:
> set the optional, top-level zigbee_shepherd_devices option to true in your configuration. When set, the add-on will scan your data_path for a devices.js file, and will run zigbee2mqtt using this custom file.

See https://www.zigbee2mqtt.io/information/configuration.html#external-converters-configuration for some details. You should be able to map custom files maybe in the /share section on HA and use a sftp with ssh addon to edit locally on your machine or something.

**Comment by ciotlosm** [comment]
After further review this requires changes in the add-on to allow such files to be updated.
