### ISSUE TITLE
Zigbee2MQTT addon 1.14.4: Xiaomi Honeywell smoke detectors refusing to  pair 

### ISSUE THREAD

**Issue by ardenking** [danielwelch/hassio-zigbee2mqtt#385]
was using 1.14.3 on openhab and my Xiaomi Honeywell smoke detectors were working fine 

migrating to Hassio installed the plugin all my devices except the smoke detectors will pair noting in the logs to say way 

tested them with the official hub and paired first go

**Comment by danielwelch** [comment]
You should first post this issue in the zigbee2mqtt page
