### ISSUE TITLE
both availability_blocklist and availability_passlist are required

### ISSUE THREAD

**Issue by GuusK** [danielwelch/hassio-zigbee2mqtt#386]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 1.14.4

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):** HassOS 4.13, home assistant 0.114.4

**Description of problem:**
I've had it working with a few Osram Smart+plugs on version 1.14.1. Updated to 1.14.4 and now it doesn't start. When it does start, it shows me the following:

```
Failed to start addon - configruation validation faled!
Missing option availability_passlist in advanced.
```
When I go to configuration and add ``availability_passlist: []`` to advanced, it isn't able to save with the following error ``Failed to save addon configuration, not a valid value for dictionary value @ data['options'].`` and then a listing of my settings. Changing ``availability_blacklist`` into ``availability_blocklist`` doesn't help. But having both (as empty lists) allows the addon to start and allowed my to have the smart plugs working again. This is against documentation as found on [zigbee2mqtt.io](https://www.zigbee2mqtt.io/information/configuration.html)

Please note that this is my working configuration. Deleting either ``availability_blocklist: []`` or ``  availability_passlist: []`` will not allow me to save the config. 
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user:   # Omitted for security
  password:   # Omitted for security
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  network_key:
  # Omitted for security
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
ban: []
whitelist: []
```

There are no logs for this in HassOS logs for Supervisor, Core or Host

**Comment by svenvbins** [comment]
Did you check the other issues? Sounds like it's the same issue as #384

**Comment by GuusK** [comment]
Depends on what you see as the issue, but I do agree that they seem to have the same origin. Let's continue the conversation there.
