### ISSUE TITLE
Migrate to a more stable add-on release workflow

### ISSUE THREAD

**Issue by ciotlosm** [danielwelch/hassio-zigbee2mqtt#399]
## Description of problem:
Currently when PRs are merge into `master`, any changes to `config.json` are automatically *seen* by Home Assistant installations. This is particularly visible when users are waiting for a release and constantly refreshing their Add-on Store. This has multiple implications:
- The build process for the new version is only kicked off after the PR was merged, so in some cases users see the "Update" button available but the image is **not yet** ready. 
- Any changes to `config.json` are visible automatically to older version of the add-on if the config changed, but the version was not incremented, and this can be forced by users doing Reload on Add-on Store and restarting the add-on

Another problem is that merges to `master` branch don't trigger a stable build automatically and you have to manually create a tag for the Azure Pipeline to run and this can cause further build delays. 

The above are causing multiple issues as seen in historical issues on this repo https://github.com/danielwelch/hassio-zigbee2mqtt/issues/366 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/365 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/352 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/334 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/293 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/267#issuecomment-558845125 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/340#issuecomment-631652864 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/340#issuecomment-638257269 #384

### (Option 1) Build from dev branch
- Introduction of a `dev` branch where all PRs are merged
- Only merge to `master` when a build is stable
- Image builds are triggered from `dev` branch

**Pros**
- Better stability for master branch `config.json` for Stable version

**Cons**
- Harder to do proper tag management and release tagging for github
  - Can drop the tag usage in `dev` and only auto-tag through clever logic when merges to master include version changes in `config.json` for Stable
- Many files would not require this type of strict branch separation (Readme, docs, change log, etc.)

### (Option 2) Move addons outside of the hassio-repository
- Move `zigbee2mqtt` and `zigbee2mqtt-edge` in separate repositories (Dockerfile, config.json, build details)
- Use `master` in the separate repositories (for z2m and z2m-edge)
- Build images out of the z2m and z2m-edge repos
- Keep Readme.md/ Changelog.md /Docs.md in the hassio-repository together with a version of `config.json`
- On releases, when we have an image we are happy with (Can be tested locally easier with full build) we just merge config.json with the right version in hassio-repo

**Pros**
- `master` workflow is maintained
- Clear separation of add-ons from repository

**Cons**
- Lots of duplication that has to be managed when merging to repository repo
- More complex to understand for people doing PRs if we have duplicate files between `hassio-zigbee2mqtt` repo and the other that contains the actual add-ons

### (Option 3) Use git submodules
- Move `zigbee2mqtt` and `zigbee2mqtt-edge` in separate repositories 
- Use `master` in the separate repositories (for z2m and z2m-edge) development
- Build images out of the z2m and z2m-edge repos
- In `hassio-zigbee2mqtt` link `zigbee2mqtt` and `zigbee2mqtt-edge` folders as git submodules tracking master
- Add workflow to update `hassio-zigbee2mqtt` on releases (tags) of `zigbee2mqtt` or on demand (for `zigbee2mqtt-edge` config.json changes)

**Pros**
- `master` workflow is maintained
- Clear separation of add-ons from repository
- Better stability for master branch `config.json` for Stable version

**Cons**
- More complex to manage, requires specific logic to properly update submodules
- More complex to understand for people doing PRs
- Checkout in pipelines to manage the git submodule update can't be a native pipeline task (must use bash)

**Comment by ciotlosm** [comment]
@Koenkk @danielwelch I am testing at the moment build speed improvements: https://dev.azure.com/zigbee2mqtt/Zigbee2mqtt%20Add-on/_build

Please ignore all the different naming, I've tried to avoid crashing anything existing, and I had no access to current pipelines. Speed improvement seems to be decent, around `10 minutes`. The job now auto-generates parallel jobs for each architecture and there are 4 pipelines: 2 for build and 2 for test.

**Comment by ciotlosm** [comment]
My recommendation is to use `dev` branch, and log any PRs against that branch

### What would need to be updated
- Azure Pipeline code must come from `dev` branch
- Azure Pipeline must track `dev` branch changes and PRs
- Stable & Edge build triggers should be done based on key folder file (Dockerfile, run.sh, socat.sh, config.json) only 
- Stable build should use config.json version value for builds and use the `--docker-hub-check` option to skip builds and uploads for existing version
  - Users must make sure that any change to `Dockerfile, run.sh, socat.sh and config.json` include a version bump
- Merging to `master` should be done for any change
- Master changes should not trigger any Pipelines with one exception: config.json version update for Stable
- If config.json contains a version change in the PR from `dev` to `master` a process should be started after merge to tag a release automatically and include text in the PR/commit as notes
- A validation script should be created to make sure that a version upgrade for z2m in Dockerfile (Stable) contains a correct *base* version in `config.json`

**Comment by danielwelch** [comment]
Hey @ciotlosm , sorry I've been gone since you started all this great work. I agree that option 1 is the way to go. I think all the goals can be accomplished with some simple scripts. Really like the changes you've made so far and agree with them all. We are in the middle of a serious network outage at our hospital, so I won't have much time to look at this or assist in the near future, but will follow along for now. Ping me if you need help with something specific. When things get a little more normal, I'll try and see where I can help out.

**Comment by ciotlosm** [comment]
@danielwelch no worries, hope things work out at your end. I will try to accomplish part of the setup. The only thing missing is access to your Azure Pipelines to update them for speed, and in order to keep images published in the right repos, probably access in DockerHub or for you to setup on the Azure side a Docker Hub connector (so we can move away from pipeline env variables.

**Comment by ciotlosm** [comment]
I tried to setup Azure Pipelines in the new organisation (zigbee2mqtt) but I don't have permissions to hook to this repo: `Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.`

I could probably push to the new zigbee2mqtt Docker Hub organisation, but this will probably reset downloads (I don't think a big problem). The CI links were invalid anyway for some time since the migration from Travic CI. 

Let me know how you want to proceed, if you want to use the new orgs (you're admin on both), or if you want to keep stuff setup differently and configure the hooks & pipelines by yourself. 

I will work on rest of changes on `dev` branch (mqtt integration) and probably use my repo to test out things on azure for now. `master` does not contain these changes, and things can always be reverted with no big impact.

**Comment by danielwelch** [comment]
I'm good with using the new orgs. I can't find a setting to give you the necessary permissions to set up that integration, so if you're aware let me know. Otherwise I'll keep looking.

**Comment by ciotlosm** [comment]
@danielwelch It seems I can't find a way to allow collaborators to use webhooks on personal projects. I will keep looking as well. 

Available other options:
- Move project and an org 
- You to setup pipelines

**Comment by ciotlosm** [comment]
- I setup Zigbee2mqtt org here: https://github.com/Zigbee2mqtt
- I forked the add-on (for now) here: https://github.com/Zigbee2mqtt/hassio-zigbee2mqtt
- Fork uses `dev` as default branch
- I setup new pipelines here: https://dev.azure.com/zigbee2mqtt/Zigbee2mqtt%20Add-on/_build
- I setup new docker hub repo here: https://hub.docker.com/orgs/zigbee2mqtt/repositories

Still TODO:
- [ ] Add back tag vs config version validation for stable builds
- [ ] Add stable build validation for base version between config and docker file

**Comment by danielwelch** [comment]
Looks great! I’m happy to do whatever you think is best re: transferring the project to the organization, personally it seems that’s the way to go to me.
