### ISSUE TITLE
Zigbee2mqtt, fresh install: Not connected to MQTT server!

### ISSUE THREAD

**Issue by cibernox** [danielwelch/hassio-zigbee2mqtt#400]
First, I've google this and saw a few kind of old issues and comments in the HA community but none seemed to apply to what I was seeing.

I apologise if this is not the right repo to report the issue, it's hard for a newby to know wether the issue lies in the addon or on zigbee2mqtt itself, but I'm happy to move it is this is not the right place.

I acquired a cc2531 and today flashed it on my mac following the instructions on the page. It all went well apparently.
I'm running home assistant on a RPi 3, completely updated to the latest and greatest as of today: 

```
HassOS 4.13
Home Assistant 0.115.2
Local IP: 192.168.1.133
```

After plugging in the cc2531, I installed zigbee2mqtt adding this repo and and configured it like this:

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://homeassistant'
  user: <SOMEUSER>
  password: <SOMEPASSWORD>
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 8
    - 198
    - 112
    - 233
    - 68
    - 153
    - 190
    - 54
    - 30
    - 199
    - 165
    - 116
    - 153
    - 121
    - 125
    - 36
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

Really the only thing I touched on the config was `server`,`user`, `password` and `network_key` as the tutorial I followed advices to not leave the default values. I did check that the serial port was correct and itwas.

When I start the server the boot process seems to go well but it never connects to the server.
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-09-22T15:53:53: PM2 log: Launching in no daemon mode
2020-09-22T15:53:53: PM2 log: App [npm:0] starting in -fork mode-
2020-09-22T15:53:53: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.4 start /zigbee2mqtt-1.14.4
> node index.js
Zigbee2MQTT:info  2020-09-22 15:54:05: Logging to console and directory: '/share/zigbee2mqtt/log/2020-09-22.15-54-04' filename: log.txt
Zigbee2MQTT:info  2020-09-22 15:54:08: Starting Zigbee2MQTT version 1.14.4 (commit #1.14.4)
Zigbee2MQTT:info  2020-09-22 15:54:08: Starting zigbee-herdsman...
Zigbee2MQTT:info  2020-09-22 15:54:11: zigbee-herdsman started
Zigbee2MQTT:info  2020-09-22 15:54:11: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
Zigbee2MQTT:info  2020-09-22 15:54:11: Currently 0 devices are joined:
Zigbee2MQTT:info  2020-09-22 15:54:11: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2020-09-22 15:54:11: Connecting to MQTT server at mqtt://homeassistant
Zigbee2MQTT:error 2020-09-22 15:54:21: Not connected to MQTT server!
```

I tried chaging server to `mqtt://192.168.1.133` (the static IP address of the RPi), `mqtt://192.168.1.133:1883`, `mqtt://192.168.1.133:8123`, `mqtt://homeassistant`, `mqtt://homeassistant.local`, `mqtt://homeassistant:1883` and everthing that came to mind, it never connects.

### Notes
- I do NOT have mosquitto nor any other mqtt addon installed. This is the first time ever I use mqtt in any form.
- When I was out of ideas, I did try to install mosquito despite the fact that the tutorials didn't mention it, just because many internet threads did. When I did I saw this on the logs: 
```
1550603281: New connection from 172.30.X.X on port 1883.
1550603281: Socket error on client , disconnecting.
```

The only thing that might be interfering that can come to mind is that I have **NGINX Home Assistant SSL proxy** and the DuckDNS addon installed, so when accessing my duckdns domain I use https but when using my local network I can use plain http and not get certificate errors.

Is there any configuration step that I'm missing?

**Comment by ciotlosm** [comment]
I'll be brief:

- You need Mosquitto add-on installed: `Supervisor` - `Add-on store` - `Official add-ons` - Mosquitto broker`
- You need Mosquitto integration configured (with auto discovery) `Configuration` - `Integrations`
- You need to setup a user/ password for the add-on (this might go away in the future): `Configuration` - `Users`
- You need to use the internal namespace for the configuration `server: 'mqtt://core-mosquitto'` in your zigbee2mqtt add-on

As a side note: zigbee2mqtt add-on runs in a container. Mosquitto (mqtt) add-on also runs in a container, but exploses the mqtt service in a clever way through the supervisor. You dont' need to expose ports on the host, as the container network is internal and the containers should have access between them.

I hope this helps.

**Comment by cibernox** [comment]
@ciotlosm It did work like a charm!

For some reason the tutorial I followed didn't mention AT ALL any of these steps. Are those relatively new? The tutorial I followed was barely 4 months old. I just want to report if in case it is outdated.

Thank you so much!

**Comment by ciotlosm** [comment]
Depends who maintains the tutorial. Ideally zigbee2mqtt should not contain in depth discussion about setting up mqtt. I do however think that at least a basic tutorial should exist of dependencies and most likely setup scenario. 

However next release will probably contain "auto-setup" for mqtt, without you needing to setup a user / password or finding out the URL, as long as you have the core one installed (or one compatible with supervisor services registration for mqtt).
