### ISSUE TITLE
Addon fails to start after update to 1.14.4.2

### ISSUE THREAD

**Issue by dunxd** [danielwelch/hassio-zigbee2mqtt#403]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

1.14.4.2

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

Home Assistant 0.115.2

**Description of problem:**
I resolved the issues with 1.14.4.1 by updating the config to the new block and passlist names.  On updating to 1.14.4.2 today, zigbee2mqtt add on fails to start.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://hassio.lan'
  user: *****
  password: *******
  version: 5
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E325A9-if00
  disable_led: true
advanced:
  report: true
  log_level: warn
  pan_id: 6754
  channel: 20
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
```
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-09-23T23:11:35: PM2 log: Launching in no daemon mode
2020-09-23T23:11:35: PM2 log: App [npm:0] starting in -fork mode-
2020-09-23T23:11:35: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.4 start /zigbee2mqtt-1.14.4
> node index.js
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.14.4 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-23T22_11_59_582Z-debug.log
2020-09-23T23:12:00: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-09-23T23:12:00: PM2 log: App [npm:0] starting in -fork mode-
2020-09-23T23:12:00: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.4 start /zigbee2mqtt-1.14.4
> node index.js
```

**Comment by ciotlosm** [comment]
@dunxd can you please change `log_level` to `debug` and restart the add-on? The trace provided is not very explicit.

**Comment by M1kk0H** [comment]
Hi, I have a same problem. Here is my log with debug level.  

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-09-24T12:43:37: PM2 log: Launching in no daemon mode
2020-09-24T12:43:37: PM2 log: App [npm:0] starting in -fork mode-
2020-09-24T12:43:37: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.4 start /zigbee2mqtt-1.14.4
> node index.js
Zigbee2MQTT:info  2020-09-24 12:43:39: Logging to console and directory: '/share/zigbee2mqtt/log/2020-09-24.12-43-39' filename: log.txt
Zigbee2MQTT:debug 2020-09-24 12:43:39: Removing old log directory '/share/zigbee2mqtt/log/2020-09-24.12-41-05'
Zigbee2MQTT:debug 2020-09-24 12:43:40: Loaded state from file /share/zigbee2mqtt/state.json
Zigbee2MQTT:info  2020-09-24 12:43:40: Starting Zigbee2MQTT version 1.14.4 (commit #1.14.4)
Zigbee2MQTT:info  2020-09-24 12:43:40: Starting zigbee-herdsman...
Zigbee2MQTT:debug 2020-09-24 12:43:40: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
(node:242) UnhandledPromiseRejectionWarning: Error: SREQ '--> ZDO - activeEpReq - {"dstaddr":0,"nwkaddrofinterest":0}' failed with status '(0xc2: NWK_INVALID_REQUEST)' (expected '(0x00: SUCCESS)')
    at Znp.<anonymous> (/zigbee2mqtt-1.14.4/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/zigbee2mqtt-1.14.4/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)
(node:242) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:242) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ciotlosm** [comment]
Your error `UnhandledPromiseRejectionWarning: Error: SREQ '--> ZDO - activeEpReq - ... failed with status '(0xc2: NWK_INVALID_REQUEST)' ...` points to a problem with your adapter. 

You can try a few steps:
- Remove and reinsert CC2531
- Press reset button on CC2531
- Change the `panId` ⚠️ unsure if this would require you to repair all your devices

If nothing works, try to re-flash the USB with the latest stable firmware

**Comment by M1kk0H** [comment]
Hi,
Thanks for help! In my case Press reset button on CC2531 helped and solved the problem. Remove and reinsert didn't work.

By the way what is easiest way to check  ZStack/Firmware on CC2531?

**Comment by ciotlosm** [comment]
@M1kk0H you can use Edge version of the add-on and that gives you a lot of debug messages on startup including that or if you want to use Stable and get the information, you can use for Stable:

**Configuration → Integrations → MQTT → Configure → Listen to a topic**
Topic to subscribe to: `zigbee2mqtt/bridge/config` → **Start Listening**

You should see a JSON like this:
```
{
    "commit": "1.14.4",
    "coordinator": {
        "meta": {
            "maintrel": 3,
            "majorrel": 2,
            "minorrel": 6,
            "product": 0,
            "revision": 20190619,
            "transportrev": 2
        },
        "type": "zStack12"
    },
    "log_level": "info",
    "network": {
        "channel": 11,
        "extendedPanID": "<redacted>",
        "panID": 6754
    },
    "permit_join": false,
    "version": "1.14.4"
}
```

**Comment by dunxd** [comment]
In my experience it wasn't necessary to do anything with my CC2531. After I changed log_level to debug and restarted zigbee2mqtt add-on things started working again.

I ended up restoring a backup with HA 1.115.0 and Zigbee2Mqtt add-on 1.14.2, and things started working again. I then brought zigbee2mqtt up to date (1.14.4) and things still worked, so I finally brought HA up to date (1.115.2) and still everything works. I don't know what was going wrong last night.

**Comment by ciotlosm** [comment]
I might have been that something kept the resource busy. Maybe the Supervisor didn't release the serial port resources from the older version before the new one got installed, so it just needed time to recover. This has nothing to do with the add-on itself.

**Comment by dunxd** [comment]
I think it might have been something like that. I haven't encountered with any previous updates. The issue did persist between HA reboots, but perhaps it just requires more patience on my part.
Thanks for assistance.
