### ISSUE TITLE
Vimar 14592.0

### ISSUE THREAD

**Issue by legolas0802** [danielwelch/hassio-zigbee2mqtt#408]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
Can you add ti device.js?
{
    zigbeeModel: ['2_Way_Switch_v1.0', 'On_Off_Switch_v1.0'],
    model: '14592.0',
    vendor: 'Vimar',
    description: '2-way switch IoT connected mechanism',
    supports: 'on/off',
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {configureKey: 3},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(10);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
},
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
<!--

**Description of problem:**

Can you add ti device.js?
{
    zigbeeModel: ['2_Way_Switch_v1.0', 'On_Off_Switch_v1.0'],
    model: '14592.0',
    vendor: 'Vimar',
    description: '2-way switch IoT connected mechanism',
    supports: 'on/off',
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {configureKey: 3},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(10);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
},
**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// Can you add this device.js?
{
    zigbeeModel: ['2_Way_Switch_v1.0', 'On_Off_Switch_v1.0'],
    model: '14592.0',
    vendor: 'Vimar',
    description: '2-way switch IoT connected mechanism',
    supports: 'on/off',
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {configureKey: 3},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(10);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
},


**Your logs from Home Assistant**

**Comment by ciotlosm** [comment]
@legolas0802 This repository is for the add-on specific changes and problems. You would need to go here: https://github.com/Koenkk/zigbee2mqtt/issues/new/choose and use **New device support request**
