### ISSUE TITLE
RFC: Migrate from pm2 to integrated watchdog

### ISSUE THREAD

**Issue by ciotlosm** [danielwelch/hassio-zigbee2mqtt#422]
As Home Assistant released `watchdog` functionality for add-ons, I'm opening up for discussion if we should drop pm2 and adopt the integrated `watchdog`. 

**Watchdog** was added here: https://github.com/home-assistant/supervisor/pull/1970 as part of Supervisor `236`

**Comment by Dinth** [comment]
Are there any benefits of pm2 over built in watchdog?

**Comment by ciotlosm** [comment]
I've not investigated a side by side comparison. We've introduced `pm2` before watchdog was available and before z2m became more stable to avoid the add-on dying. 

I've raised this issue to discuss options with more people, as there might be some benefits to one solution over the other. 

One plus for using watchdog is removal of a process (pm2) that is not usually used in any other system except the add-on. This could have side effects (we haven't noticed any as of yet), that no one else would experience.

**Comment by ciotlosm** [comment]
I will test this out on a fork here: https://github.com/Zigbee2mqtt/hassio-zigbee2mqtt as removing pm2 will reduce complexity.

**Comment by danielwelch** [comment]
Would love to remove pm2 in favor of built-in watchdog if possible.

**Comment by ciotlosm** [comment]
It is now possible, as the container is built with base  which has integrated [s6-overlay](https://github.com/just-containers/s6-overlay#writing-a-service-script). That has its own service management as well, so including watchdog it's double resilience. 

I've migrated scripts to [this model](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/dev/common/rootfs/etc/) thanks to @scootec and I'm still testing proper service management for socat.
