### ISSUE TITLE
can't install new update 1.15

### ISSUE THREAD

**Issue by heizie** [danielwelch/hassio-zigbee2mqtt#428]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
None

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
Raspberry pi 3 running Home Assistant image 

**Description of problem:**
I've added our repository, but when i click install, then it said
`20-10-01 15:34:06 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armv7:1.15.0 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armv7:1.15.0 not found: manifest unknown: manifest unknown").`
I've saw you update the 1.15 version before few minutes. Might be some issues of the naming

**Comment by ciotlosm** [comment]
Build is still ongoing (see: https://dev.azure.com/danielwelch2101/hassio-zigbee2mqtt/_build/results?buildId=506&view=logs&j=dd1c38ba-a38b-54e6-47f3-80caee1bb8fb&t=de30a05a-fcaf-5a3b-671f-2bf0948816e9). To fix people trying to download the version too early is in progress with https://github.com/danielwelch/hassio-zigbee2mqtt/issues/399. 

Please be patient, it should be there in around 20 more minutes :-)
