### ISSUE TITLE
Use zigbee2mqtt dev branch in edge version

### ISSUE THREAD

**Issue by dzungpv** [danielwelch/hassio-zigbee2mqtt#43]
Please add more branch or add option for edge version use dev branch from zigbee2mqtt. I want to use this https://github.com/Koenkk/zigbee2mqtt/commit/85be7b44a0c9e311698d29d973443ab27049f2dd  but could not now.

**Comment by dzungpv** [comment]
And you can also use auto cloud build for docker image with trig by a push to dev branch.

**Comment by danielwelch** [comment]
@dzungpv see https://github.com/Koenkk/zigbee2mqtt/pull/251

Back in the pre-0.1 days of `zigbee2mqtt`, we used the `trigger-downstream.sh` script to automate Docker image builds for the add-on, which just tracked the master branch. But looks like now most of the action has moved over to `dev`, but the script is still tracking `master`. I submitted a PR over there to fix that, and I've changed the edge version of the add-on over to the `dev` branch (building now, should be done soon).

**Comment by dzungpv** [comment]
@danielwelch so if dev branch is the edge version, so master branch is release version?
Is this right @Koenkk ? if master is the release, just config your release version with master branch, and auto build when a merge or push to master.

**Comment by danielwelch** [comment]
Nope, wrong. Edge version now tracks the dev branch. The non-edge, or “stable” version of the add-on uses releases versions of zigbee2mqtt. It is updated whenever a new version of zigbee2mqtt comes out.

**Comment by dzungpv** [comment]
@danielwelch zigbee2mqtt release version 1.3.0  13 hour ago but I am not see the update. What is the problem?
