### ISSUE TITLE
Unable to start zigbee2mqtt 1.15.0 addon if using external converter

### ISSUE THREAD

**Issue by dinhchinh82** [danielwelch/hassio-zigbee2mqtt#434]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
Z2m addon version: 1.15.0
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

Raspberry Pi3, HASSIO version 0.115.6

**Description of problem:**
I've just upgraded new 1.15.0 Z2M add on version and it is unable to start if using the external converter like below:
```zigbee_shepherd_devices: true

Without adding the customized external converter above, z2m started without error.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: aaaa
  password: bbbb
serial:
  port: /dev/ttyUSB0
advanced:
  rtscts: false
  pan_id: 6754
  channel: 15
  network_key:
    - 1
    - 3
    - 51
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_shepherd_devices: true
```

**Your logs from Home Assistant**
Here is the log from docker:
https://pastebin.com/tvmNSGnA

**Comment by ciotlosm** [comment]
Your `devices.js` might not be compatible with the new version. This was always a workaround that probably should only be used for short periods until your device got into `master` for converters.

You can however fix you problem in two ways (see: https://github.com/danielwelch/hassio-zigbee2mqtt#adding-support-for-new-devices) 

- You can get a new `devices.js` as described in the documentation - which is a way to make sure it's compatible with your z2m setup
- You can use the newer and better method that is much future proof using `external_converters`.

**Comment by dinhchinh82** [comment]
> Your `devices.js` might not be compatible with the new version. This was always a workaround that probably should only be used for short periods until your device got into `master` for converters.

That's correct. I use new version of device.js and that's the reason. Just rollback to the version which is compatible with z2m 1.15.0 (3 days ago) and it works.

Thank you so much.
