### ISSUE TITLE
Unable to set the invert_cover option in the configuration.yaml

### ISSUE THREAD

**Issue by dinhchinh82** [danielwelch/hassio-zigbee2mqtt#435]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
HASSIO addon version 1.15.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

**Description of problem:**
Here are the steps to reproduce the procedure:
Step 1: Set the "invert_cover" option to be "true" under "device_options"
Step 2: Restart the addon

Step 3: check the detail content of configuration.yaml via SSH and the invert_cover option above is also not saved.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: u1
  password: p1
serial:
  port: /dev/ttyUSB0
advanced:
  rtscts: false
  log_level: info
  pan_id: 6754
  channel: 15
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 91
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options:
  invert_cover: true
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```
**Your logs from Home Assistant**

```20-10-03 14:07:11 WARNING (MainThread) [supervisor.addons.validate] Unknown options invert_cover
20-10-03 14:07:13 INFO (SyncWorker_0) [supervisor.docker.interface] Stop addon_7ad98f9c_zigbee2mqtt application
20-10-03 14:07:13 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_7ad98f9c_zigbee2mqtt application
20-10-03 14:07:13 WARNING (MainThread) [supervisor.addons.validate] Unknown options invert_cover
20-10-03 14:07:15 INFO (SyncWorker_2) [supervisor.docker.addon] Start Docker add-on dwelch2101/zigbee2mqtt-armv7 with version 1.15.0
```

**Expected**

The 'invert_cover' option can be saved to the configuration.yaml file without error.

Thank you.

**Comment by ciotlosm** [comment]
This option is not part of the config for the add-on. It needs to be added and a new version released. I will add this in the next release

**Comment by dinhchinh82** [comment]
> This option is not part of the config for the add-on. It needs to be added and a new version released. I will add this in the next release

Great. When do you plan to release new version?
Thank you.

**Comment by ciotlosm** [comment]
I've tried to find `invert_cover` option in z2m docs, but I'm unable to find it. Can you point me to where it was implemented? I found [something]() but it was not under `device_options`.

Also found that you can use this in the current version like this:
```json
device_options_string: '{"invert_cover": true}'
```

**Comment by dinhchinh82** [comment]
@ciotlosm you can check the document below:
https://www.zigbee2mqtt.io/devices/TS0601_curtain.html

**Comment by dinhchinh82** [comment]
> device_options_string: '{"invert_cover": true}'

I confirm this configuration works well so it's fine to close this issue.
Thank you so much.
