### ISSUE TITLE
I cant add again a device after i erased it

### ISSUE THREAD

**Issue by Gulivert** [danielwelch/hassio-zigbee2mqtt#437]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 
1.15.0 

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
Raspberry Pi 4

I connected a siren to zigbee2mqtt, it give my problem, i erased it **checking the button to be able to connect again later** but now i cant connect it again

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.0.29:1883'
  user: mqtt
  password: mqtt
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

```

**Your logs from Home Assistant**

Logs didnt show anything relevant

**Comment by ciotlosm** [comment]
Any logs available? Best to use edge with debug enabled to be able to help

**Comment by Gulivert** [comment]
I have tried to put it in debug mode, but the only traces that the log shows me are those of the devices that I already have connected. There is some file where it saves the devide it refuse to connect? I saw a blocklist property in the config but is empty.

**Comment by ciotlosm** [comment]
To have proper debug (for now) is to use Edge version unfortunately using the `zigbee_herdsman_debug` option

**Comment by Gulivert** [comment]
I install the edge version with the option, but the only new thing that show me is:
File /share/zigbee2mqtt/devices.js not found! Starting with default devices.js

The device will be:
https://www.zigbee2mqtt.io/devices/SZ-SRN12N.html

**Comment by ahonxxx** [comment]
After deleting a device, you cannot add a device. After installing zigbee2mqtt again, you cannot add a device

**Comment by Gulivert** [comment]
So what options do I have? Is there a file with the deleted devices that I can modify?

**Comment by ahonxxx** [comment]
I encountered the same situation as you, I am not proficient in English, translation seems to have a little problem, my operating environment is running on synoogy Hass.io 。Waiting for a solution

**Comment by ciotlosm** [comment]
@ahonxxx don't worry about english. If i can't understand something from translation I will ask for more details. 

@Gulivert Can you provide exact steps? I don't know how you `erased` a device. Was it through the built-in frontend? What options did you click?

![Screenshot 2020-10-10 at 09 56 00](https://user-images.githubusercontent.com/7738048/95648305-d8212380-0ade-11eb-9614-c0e32bda19d5.png)

**Comment by ahonxxx** [comment]
@ciotlosm  Thank you. After I updated to 1.15.0, through the built-in front-end interface, I checked forced deletion when deleting devices. After deleting, I could not add devices. I have 5 ZigBee devices in total. After deleting the remaining 4 devices, I can no longer add devices. I unloaded the hass.io After the deployment, ZigBee devices can not be added.

**Comment by ciotlosm** [comment]
@ahonxxx I assume you are putting your coordinator in pairing mode from the UI. Do you have any active router in your setup or just end devices?

**Comment by Aerallo** [comment]
I have the same problem, I even tried pairing new devices on a different RPi but after this update I cannot add anything. To answer the latest question, I have about 10 devices mixed with active and end

**Comment by ciotlosm** [comment]
What kind of stick / firmware do you use? What is your startup debug message? Are you putting it in pairing mode?

**Comment by Gulivert** [comment]
> @ahonxxx don't worry about english. If i can't understand something from translation I will ask for more details.
> 
> @Gulivert Can you provide exact steps? I don't know how you `erased` a device. Was it through the built-in frontend? What options did you click?
> 
> ![Screenshot 2020-10-10 at 09 56 00](https://user-images.githubusercontent.com/7738048/95648305-d8212380-0ade-11eb-9614-c0e32bda19d5.png)

In my case i use the "force remove" but not the "block from joining again". After that whe i put the device on pairing, it didnt show mup.

**Comment by ciotlosm** [comment]
@Gulivert make sure you also put the coordinator in pairing mode.

**Comment by Aerallo** [comment]
I solved it by reflashing my CC2531 stick, changing the zigbee channel and reinstalling zigbee2mqtt.

**Comment by Gulivert** [comment]
> @Gulivert make sure you also put the coordinator in pairing mode.

Yes i did

**Comment by ciotlosm** [comment]
@Gulivert the only other solution I can see is what @Aerallo is suggesting, a re-flashing for the coordinator.

**Comment by ahonxxx** [comment]
@Gulivert I changed the ZigBee channel, channel: 14 everything is OK

**Comment by Gulivert** [comment]
> @Gulivert I changed the ZigBee channel, channel: 14 everything is OK

I see that maybe is that the only solution. I tried to refrash it but didnt work, now the problem of change the channel is add it again all the device...

**Comment by Gulivert** [comment]
In fact, after i change the channel, even caming back to the previous channel all the device are erased. I'm not sure if this is the normal behaviour.

**Comment by ciotlosm** [comment]
Changing a channel requires reconnection of devices from previous channel. I'm not sure why changing it back doesn't work.

**Comment by lazou** [comment]
I have the same sort of issue with my Home Assistant installation running in a VM using a ConBee II stick. I installed the MQTT Broker add-in and the zigbee2mqtt add-in. The integration of the mqtt broker within Home Assistant is successful, including an enabled discovery. In the logs of the mqtt broker I can see that zigbee2mqtt and Home Assitant are conected. Now I tried to add two xiaomi devices (temperature sensor and window/door sesnsor). The zigbee2mqtt frontend shows that both devices are connected, I can also see that mqtt messages got published with sensor values. But nevertheless, both devices are not auto discovered by Home Assistant.

I have a fresh installation with the following versions:
Home Assistant 0.116.4 (HassOS 4.14)
Zigbee2mqtt: 1.15.0

Since I am new to the whole Home Assistant stuff, I tried for the last three days to get it working, but without luck (including several restarts 😉 )

My last hope, it is not a problem on my side but rather an issue of the plugin in the newest.

**Comment by lazou** [comment]
I solved my issue, it was independent from the reported one.

If someone is interested, here a short summary:
- mqtt broker allowed anonymous access - not recommended
- zigbee2mqtt config was invalid (`username` instead of `user`)
- zigbee2mqtt did connect and publish to the broker but anonymously, therefore the discovery of home assistant did not work

**Comment by KixMan28** [comment]
I had the same issue. I changed the channel to 14 and I reconnected everything. I think there is a bug in the integration, it would be nice if would be corrected. I needed to reconnect only 7 devices but those who have couple of dozens, they are in trouble.

**Comment by ciotlosm** [comment]
I recommend opening issues here: https://github.com/Koenkk/zigbee2mqtt/issues/new/choose
This issue tracker is only for the add-on and it's functionality. The add-on just wraps `zigbee2mqtt` so most of the inner workings, including the firmware for the USB stick can't be handled here. 

I will close this issue as people were able to restore pairing, but make sure you raise issues on the other repo to get more support.

**Comment by mglatz** [comment]
I had the same issue and solved it:
I have HA in VM thus the coordinator never powered down upon reboot. I disabled zigbee2mqtt, disconnected the coordinator for few seconds, reconnected, started zigbee2mqtt and I could reconnect all devices that I previously removed.

**Comment by altacoon** [comment]
Thank you, @mglatz, your answer helped me to solve the same issue, I had.

I am running HA on a pi, just make my first steps with zigbee2mqtt. Deleted a device in Z2M, and failed to reconnect it again.
Your solution worked for me!

**Comment by some-guy-23** [comment]
@mglatz very old thread, but your fix worked for me too, thank you!

I had (force) removed a device and couldn't get it added back, even after a soft reboot (via Web UI) of my zigbee coordinator. What ended up fixing it was totally disconnecting the coordinator from power for a while, like you suggested, thanks!

**Comment by aldoushx** [comment]
Hello,
It did not work for me... I tried the solution described above, but it fails to re-discover the devices that were deleted by a physical press on the pairing button :
I stopped the Z2MQTT container on Proxmox, unplugged the coordinator for 4seconds then plugged it back and restarted the container : nothing new happens when i try to pair again my devices...
Any idea where the history of the previous devices is stored in Z2MQTT ?
