### ISSUE TITLE
Unable to start the add-on

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [danielwelch/hassio-zigbee2mqtt#439]
**zigbee2mqtt add-on version:** 
1.15.0

**Operating environment:**
HassOS 4.13

**Description of problem:**
I am unable to start the add-on because the image does not exist.

**Your logs from Home Assistant**
```
ERROR (SyncWorker_0) [supervisor.docker] Image dwelch2101/zigbee2mqtt-armv7 not exists for addon_7ad98f9c_zigbee2mqtt
```

**Comment by ciotlosm** [comment]
The image is there: https://registry.hub.docker.com/r/dwelch2101/zigbee2mqtt-armv7/tags The only other reasons you might get this error is lack of available space on your HassOS installation.

**Comment by JavierSegoviaCordoba** [comment]
@ciotlosm I just updated to `1.15.0` when it started to fail

Currently, my System Metrics report this: Used space 10.3%

**Comment by ciotlosm** [comment]
Try to backup your add-on config and do a full uninstall / reinstall and restore your config after.

**Comment by JavierSegoviaCordoba** [comment]
I am getting a timeout when I try to install it

**Comment by JavierSegoviaCordoba** [comment]
After rebooting I could reinstall it, and it starts now, thank you!
