### ISSUE TITLE
BTicino living now - Device doesn't expose anything

### ISSUE THREAD

**Issue by theoden9017** [danielwelch/hassio-zigbee2mqtt#444]
Hi,
Last week I bought the BTicino smart switch K4003C without its Gateway.
using **zigbee2mqtt-edge 1.15.0-dev (commit #a132094)** add-on with my conbee2 I have discovered the device, but unfortunatly no action was expose 

```
0x0004740000b18711
Device doesn't expose anything
```

so i set zigbee_shepherd_devices to true
and added to my data_path the folder for supporting new devices (**v12.0.208**):
- https://github.com/danielwelch/hassio-zigbee2mqtt#adding-support-for-new-devices
- https://github.com/Koenkk/zigbee-herdsman-converters/releases/tag/v12.0.208

Once i restarted i get this error:

```
Zigbee2MQTT:info  2020-10-11 10:11:45: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-11.10-11-45' filename: log.txt
/app/node_modules/zigbee-herdsman-converters/devices.js:1641
        device.exposes = device.exposes.concat([exposes.numeric('linkquality').withUnit('lqi')]);
                                                        ^
TypeError: exposes.numeric is not a function
    at /app/node_modules/zigbee-herdsman-converters/devices.js:1641:57
    at Array.map (<anonymous>)
    at Object.<anonymous> (/app/node_modules/zigbee-herdsman-converters/devices.js:1630:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/zigbee-herdsman-converters/index.js:3:17)
npm
 ERR! code ELIFECYCLE
npm
 ERR! errno 1
npm ERR! zigbee2mqtt@1.15.0-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.15.0-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-11T08_11_46_517Z-debug.log
```

I tryed the device list using just Philips and BTicino, and commenting this line
`// device.exposes = device.exposes.concat([exposes.numeric('linkquality').withUnit('lqi')]);`

once i commented it start, but I still have no action exposed on Bticino switch discovered by zigbee2mqtt.

lurking for the same problem i found something similar here: 
https://github.com/Koenkk/zigbee2mqtt/issues/2626
but I'm not sure he is working with the zigbee2mqtt-edge add-on

Maybe the problem its related with the firmware version of BTicino switch:
![Untitled](https://user-images.githubusercontent.com/6663915/95674312-9ca25a00-0baf-11eb-851f-391208952d5b.jpg)

did you have any clue of what could cause this issue?

**Comment by ciotlosm** [comment]
Unfortunately your problem is within z2m code (or herdsman converters) which I don't have enough knowledge to assist. I recommend you raise an issue here: https://github.com/Koenkk/zigbee2mqtt/issues/new/choose

I would have recommended to avoid using the `devices.js` approach, but using `external_converters` unfortunately is not yet an option, as it has a bug (#438).

**Comment by theoden9017** [comment]
> 
> 
> Unfortunately your problem is within z2m code (or herdsman converters) which I don't have enough knowledge to assist. I recommend you raise an issue here: https://github.com/Koenkk/zigbee2mqtt/issues/new/choose
> 
> I would have recommended to avoid using the `devices.js` approach, but using `external_converters` unfortunately is not yet an option, as it has a bug (#438).

Ok thanks for the tip, i reposted the problem here:
https://github.com/Koenkk/zigbee2mqtt/issues/4638
