### ISSUE TITLE
502: Bad Gateway on Start-up

### ISSUE THREAD

**Issue by Toinieboy** [danielwelch/hassio-zigbee2mqtt#446]
Hi,

got the add-on installed, but getting an 502: Bad Gateway when trying to run the add-on. 
Home Assistant 0.116 on RBpi4 in docker.
Got 8099 allowed in the ufw rules.

8099 ssl:default [Connection refused] though

What am i doing wrong?

**Comment by ciotlosm** [comment]
Can you post your config? Why are you not just using ingress? Did you setup your `new_api` property? Usually the built-in frontend takes up to 5 minutes to start from the time the add-on started. Also this is influenced on the number of automations or if you have other stuff like Zigbee2mqttAssistant

**Comment by Toinieboy** [comment]
Hi,

Not too much automation running yet and no other stuff installed. Even going through ingress i am getting the same error.

I'm fairly new to MQTT so i might be missing something. Installed Mosquitto broker.

Adding the new-api: experimental code for example the config-check fails.

**Comment by ciotlosm** [comment]
Can you post your z2m config? Did you wait for 5 minutes?

**Comment by Toinieboy** [comment]
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: my_user
  password: my_password
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

And yes, waited 30 minutes;)

**Comment by ciotlosm** [comment]
Where do you see `8099 ssl:default [Connection refused]` ?

**Comment by Toinieboy** [comment]
![2020-10-12 15_10_19-Window](https://user-images.githubusercontent.com/66773265/95750321-427fc280-0c9d-11eb-91fb-5d255f7623c1.png)

**Comment by ciotlosm** [comment]
If you boot the add-on and go directly to the tab in the side bar, you will see this error. Can you get debug logs from the add-on?

**Comment by Toinieboy** [comment]
}Debug information end
./run.sh: line 24: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-10-12T16:23:34: PM2 log: Launching in no daemon mode
2020-10-12T16:23:35: PM2 log: App [npm:0] starting in -fork mode-
2020-10-12T16:23:35: PM2 log: App [npm:0] online
> zigbee2mqtt@1.15.0-dev start /app
> node index.js
Zigbee2MQTT:info  2020-10-12 16:23:39: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-12.16-23-38' filename: log.txt
Zigbee2MQTT:info  2020-10-12 16:23:40: Starting Zigbee2MQTT version 1.15.0-dev (commit #ebdf4bb)
Zigbee2MQTT:info  2020-10-12 16:23:40: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-10-12 16:23:40: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-12 16:23:40: Failed to start zigbee
Zigbee2MQTT:error 2020-10-12 16:23:40: Exiting...
Zigbee2MQTT:error 2020-10-12 16:23:40: Error: Error while opening serialport 'Error: Error: Resource busy, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12

**Comment by ciotlosm** [comment]
Your add-on is crashing, as your serial port setup is incorrect: "Error: Error while opening serialport 'Error: Error: Resource busy, cannot open /dev/ttyACM0'. Make sure you don't have any other add-on using the serial port and that the serial port is the correct one. 

You can use the documentation to find out the serial port: https://github.com/danielwelch/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/DOCS.md#notes

**Comment by Toinieboy** [comment]
I have deconz running that is look at a conbee II stick? Might that be the issue?

**Comment by Aerallo** [comment]
I had this problem too and solved it by reinstalling zigbee2mqtt if it helps anything

**Comment by ciotlosm** [comment]
If you have deconz with conbee stick you should still use the documentation to find out the serial port, however you need an extra setting:

```yaml
serial:
  port: /dev/ttyACM0
  adapter: deconz
```

This is part of the documentation here: https://www.zigbee2mqtt.io/information/supported_adapters.html#conbee-ii

**Comment by Toinieboy** [comment]
Okay, slowly getting there, still bad gate-way but also:

Zigbee2MQTT:error 2020-10-13 16:46:39: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

**Comment by ciotlosm** [comment]
Make sure you also have firmware updated with the proper one.

**Comment by Toinieboy** [comment]
Conbee is in the latest firmware. System just fully rebooted and deconz is stopped. Still same error:(

Port is correct:
13 16:00 usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2213029-if00 -> ../../ttyACM0

**Comment by ciotlosm** [comment]
Did you update the config with the `adapter` setting?

**Comment by Toinieboy** [comment]
![afbeelding](https://user-images.githubusercontent.com/66773265/95888756-cb702a00-0d81-11eb-8932-a66d41bb878a.png)

**Comment by Toinieboy** [comment]
![afbeelding](https://user-images.githubusercontent.com/66773265/95891334-3cfda780-0d85-11eb-8292-8ae8528e41c0.png)

Still same error on the config. and still   Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

**Comment by ciotlosm** [comment]
The config goes in your add-on config, not in your home assistant config.

**Comment by Toinieboy** [comment]
Feels stupid.....

So now we're at:

Zigbee2MQTT:info  2020-10-13 19:08:06: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-13.19-08-05' filename: log.txt
Zigbee2MQTT:info  2020-10-13 19:08:06: Starting Zigbee2MQTT version 1.15.0-dev (commit #24188a3)
Zigbee2MQTT:info  2020-10-13 19:08:06: Starting zigbee-herdsman...
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2020-10-13 19:08:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-13 19:08:18: Failed to start zigbee
Zigbee2MQTT:error 2020-10-13 19:08:18: Exiting...
Zigbee2MQTT:error 2020-10-13 19:08:18: undefined

**Comment by ciotlosm** [comment]
Can you add to the zigbee2mqtt add-on the option:
```
zigbee_herdsman_debug: true
```

And send what you get ?

**Comment by Toinieboy** [comment]
I think we did it! Thank you very very much!

![afbeelding](https://user-images.githubusercontent.com/66773265/95893410-31f84680-0d88-11eb-8698-d882abfe9b02.png)

**Comment by Uncaged77** [comment]
> The config goes in your **zigbee2mqtt add-on** config, not in your **home assistant** config.

How do you edit the yaml of the addon, and not the config of HA?  I am using HA/OS on a VM in Virtualbox on a windows 10 machine.

**Comment by ciotlosm** [comment]
You just use the add-on config in the Supervisor, no need to edit yaml file on disk.

**Comment by survivorak47** [comment]
> You need both like I said in [#446 (comment)](https://github.com/danielwelch/hassio-zigbee2mqtt/issues/446#issuecomment-707183517)
> 
> ```yaml
> serial:
>   port: /dev/ttyACM0
>   adapter: deconz
> ```

thanks buddy... you save me. lucky i found an answer for it...! it works.

**Comment by barcelona92** [comment]
Hi, i add these commands

`serial:
  port: /dev/ttyACM0
  adapter: deconz`

But appear the same error

**Comment by EDelsman** [comment]
The config gets overwitten every time Zigbee2mqtt starts, and I read elsewhere I'm supposed to edit that using the GUI. But the GUI won't start until I change it. Catch 22....

**Comment by BenjaminOe** [comment]
Hi everyone, i am completly new to Homeassistant but already have a first problem. I hope someone here can help me.

I have the same issue: When starting zigbee2mqtt i see only "Bad gateway"

This is my configuration:
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  user: xxxx
  passsword: xxxxxx
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
    - x
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true


An this is the log:
Zigbee2MQTT:error 2022-01-19 19:13:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-19 19:13:32: Failed to start zigbee
Zigbee2MQTT:error 2022-01-19 19:13:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-19 19:13:32: Exiting...
Zigbee2MQTT:error 2022-01-19 19:13:32: undefined
[19:13:32] INFO: Zigbee Herdsman debug logging enabled
[19:13:32] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
2022-01-19T18:13:39.067Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2022-01-19T18:13:39.075Z zigbee-herdsman:deconz:driver Set delay to 0
CREATED DECONZ ADAPTER
2022-01-19T18:13:39.079Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[XXXXXXXXXXXXXXXXXXXXXXXX],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0","adapter":"deconz"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-01-19T18:13:39.080Z zigbee-herdsman:deconz:driver Opening with /dev/ttyACM0
2022-01-19T18:13:39.093Z zigbee-herdsman:deconz:driver Serialport opened
2022-01-19T18:13:39.095Z zigbee-herdsman:controller:log Started with result 'resumed'
2022-01-19T18:13:39.095Z zigbee-herdsman:controller:log Injected database: true, adapter: true
2022-01-19T18:13:39.103Z zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 1 paramId: 1
