### ISSUE TITLE
expose fronted port

### ISSUE THREAD

**Issue by DJJo14** [danielwelch/hassio-zigbee2mqtt#448]
in hassio-zigbee2mqtt 1.5.0 the new fronted is added, but no expose port is added.

home assistant version 0.114.4
hassio Operating System 4.12

My fronted does not load

**Comment by ciotlosm** [comment]
The frontend uses ingress feature. Use the show in sidebar option. 

The frontend starts in up to 5 minutes. 

If you have a loading loop, make sure you have the "new_api" option set to true

**Comment by DJJo14** [comment]
The new "new_api" was the trick
