### ISSUE TITLE
Dev version

### ISSUE THREAD

**Issue by Baseje** [danielwelch/hassio-zigbee2mqtt#45]
Is it possible to create an addon of the DEV version of Zigbee2MQTT.

There is something solved (https://github.com/Koenkk/zigbee2mqtt/issues/198) wich i needed quickly.
Please let me know!

**Comment by danielwelch** [comment]
Is the edge version not what you’re looking for? It tracks the dev branch.

**Comment by ohmer1** [comment]
I wonder if the dev version should use the master of zigbee-shepherd-converters instead of a static one? I made a PR and I would like to be able to use it with the hassio addon. https://github.com/Koenkk/zigbee-shepherd-converters/pull/58

**Comment by danielwelch** [comment]
@ohmer1 How to handle the devices.js in a way that allows what you want (as well as just modifying the `devices.js` file via the add-on in general) is kind of an ongoing discussion. See https://github.com/danielwelch/hassio-zigbee2mqtt/issues/35.

It will likely require changes to `zigbee2mqtt` itself before we can make this possible via the add-on.

**Comment by danielwelch** [comment]
also see https://github.com/Koenkk/zigbee2mqtt/issues/232

**Comment by ohmer1** [comment]
Thanks. Great to know this may be possible in a near future. In the mean time, I build a small VM for my custom zigbee2mqtt instead of the addon. Will switch back to the addon later.
