### ISSUE TITLE
zigbee2mqtt group not reflected in HA

### ISSUE THREAD

**Issue by thomasgermain** [danielwelch/hassio-zigbee2mqtt#451]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 1.15.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

HassOS 4.13

**Description of problem:**
I created a group inside zigbee2mqtt (two bulbs that are actually in the same lamp). And I would expected the addon to reflect that group creation inside HA by creating a "fake" light entity (like the addon is doing when adding a new device, it's creating a new entity). So I can use that entity and abstracting the fact that they are actually 2 bulbs.

Am I expecting too much from the addon ?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration
```

**Your logs from Home Assistant**

**Comment by vlavrynovych** [comment]
+1, I do not know why, but when I've found groups on UI I expected to create groups and see them in HA

**Comment by ASNNetworks** [comment]
You need to read the docs, it's all explained and pretty straight forward: https://www.zigbee2mqtt.io/integration/home_assistant.html

This is about groups:: https://www.zigbee2mqtt.io/integration/home_assistant.html#groups

_Groups are not auto-discovered. With the configuration below, grouped devices in Zigbee2MQTT will be exposed as a single device in Home Assistant. The following example will show you how to add a group of lights to Home Assistant. It has to be added to the Home Assistant configuration.yaml._

I use zigbee2mqtt since 2 days, coming from deCONZ. Groups work fine if you follow the steps in the link 👍

**Comment by thomasgermain** [comment]
This is exactly why my request is here, you stated the doc of zigbee2mqtt, not the of the hassio addon.

You should have read that: `NOTE 2: If you are using the Zigbee2MQTT Hass.io add-on use their documentation`. For me it means: if you are using the Zigbee2MQTT Hass.io add-on, stop reading here and go the the addon doc.

And I didn't say it was not working. I created the mqtt manually and it's working fine.

**Comment by ciotlosm** [comment]
@thomasgermain I will try to clarify a bit the expectations here:

`zigbee2mqtt add-on` is only packaging `zigbee2mqtt` for easier usage within Home Assistant by making it an add-on that can be managed by their Supervisor. 

Any functionality like discovery integration (which is usually done through mqtt) is core functionality within `zigbee2mqtt` code and the add-on little to do with how things are handled. 

The add-on usually provides:
- Configuration to work with HassOS/Supervisor
- Watchdog functionality
- Socat support by using a fork process
- Ability to use strings for some settings so you can use `!secret` functionality in Home Assistant

The note `NOTE 2: If you are using the Zigbee2MQTT Hass.io add-on use their documentation` refers to the fact that you're on Home Assistant integration page (zigbee2mqtt can work with a lot of other home automation software), and the best way to understand how to install this is by using the more specific documentation on the add-on docs. 

I do agree that maybe that text can be a bit ambiguous, especially for new people, but you can help us make it better by suggesting changes through Pull Requests. 

I hope this makes things a bit more clear.

**Comment by thomasgermain** [comment]
Well yeah, you're right. Actually I'm expecting too much from the addon, but it doesn't mean the addon is not doing what is supposed to do.

The solution (to have the group entity created in HA) could be to have a zigbee2mqtt `integration`, but then it sounds weird (and out of scope here) to have this integration doing "something" so some entities can be discovered by mqtt.

**Comment by ciotlosm** [comment]
Maybe no `integration` is required, as long as there is enough functionality in the mqtt auto discovery to support this.
