### ISSUE TITLE
dev/ttyACM0 not found and other errors

### ISSUE THREAD

**Issue by igiul667** [danielwelch/hassio-zigbee2mqtt#454]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
```
version 1.15.0-dev (commit #fee6310)
```

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

Supervised install on an intel nuc running Ubuntu

**Description of problem:** 
When starting the addon reutrns some errors. If I try to restart it the error changes and becomes "dev/ttyACM0 not found. However if i unplug the CC stick and plug it back in again it appears in the listed serial devices, and if I try to start the addon it seems to start but still gives errors

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "external_converters": [],
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.0.210",
    "user": "mqttusername",
    "password": "mqttpassword"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": true
  },
  "advanced": {
    "log_level": "info",
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {
    "new_api": true
  },
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1.0,
    "initialdelay": 1.0,
    "options": "-d -d",
    "log": false
  }
}
```

**Your logs from Home Assistant**

if it finds the adapter after it has been replugged: https://pastebin.com/PDU8rcu7
if I restart it after (the adapter doens't show up anymore in the serial devices): https://pastebin.com/NURTaBC0

**Comment by ciotlosm** [comment]
@igiul667 I'd recommend you try and use the named serial port: ` Supervisor → System → Host system → ⋮ → Hardware`. It should look something like: ` /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0`

Also try using the add-on from: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt as it has a few startup improvements (to test things out).

**Comment by igiul667** [comment]
Thanks for the reply, I'll try what you're telling me soon

**Comment by igiul667** [comment]
Using the release version of zigbee2mqtt everything seems to start correctly however I'm unable to send commands to the zigbee devices. Using the edge version addon it also starts no problem, but as soon as i try pressing a button on a zigbee remote the addon crashes with error:
Zigbee2MQTT:error 2020-11-03 08:26:47: Adapter disconnected, stopping
Zigbee2MQTT:info  2020-11-03 08:26:47: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
Zigbee2MQTT:info  2020-11-03 08:26:47: Disconnecting from MQTT server
Zigbee2MQTT:error 2020-11-03 08:26:47: Failed to stop zigbee
I was thinking maybe I need to reflash the coordinator, do you think that would help?

**Comment by ciotlosm** [comment]
Might be that you need to do so. From the looks of it you either have:
- adapter problem 
- virtualization problem - if you have some sort of passthrough for the serial adapters
- driver problems ? unsure how your intel nuc setup is on this part

**Comment by igiul667** [comment]
I think I'll have to reflash the adapter, since it was working, but after a reboot it stopped, so I wouldn't think the issue is with the host. I'll let you know how that goes

**Comment by igiul667** [comment]
Fixed everything by reflashing the coordinator. I've had some prolems binding new items but I managed to do it.
