### ISSUE TITLE
Permit Join don't start.

### ISSUE THREAD

**Issue by mrIngrid** [danielwelch/hassio-zigbee2mqtt#455]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
Zigbee2mqtt Bridge 1.15.0
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

Raspberry Pi4 4GB
Home Assistant Supervised 116.4
HassOS 5.4 Developement boot on SSD
GeekWorm x857 mSata adapter.
CC2530+CC2592 & USB TO TTL CH340C.

**Description of problem:**
Permit Join start correctly without errors but don't happened nothing when i put in pair mode the devices.

If previously paired from another module, like cc2530 + cc2591 with usb to ttl CP2102, all sensors works perfectly (excluse Join Mode and Map)

On the previous version of z2m it worked without any problem .

Have opened an issue on HassOS 5.x Developement session 
https://github.com/home-assistant/operating-system/issues/902

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// 
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: ****
  password: *****
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: true
​
```

**Your logs from Home Assistant**

Nothing

**Comment by agners** [comment]
The driver for CH340C seems to use `/dev/ttyUSBX` as device names. It seems that the add-on is specifying `ttyACM0` only?

https://github.com/danielwelch/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/config.json#L43

**Comment by ciotlosm** [comment]
@agners the config.json you linked, is just the default. You can specify whichever serial port you need. See Notes [here](https://github.com/danielwelch/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/DOCS.md#notes) on how to identify the correct serial port. 

@mrIngrid How do you enable permit_join? Can you post some logs from the add-on?

**Comment by agners** [comment]
@ciotlosm ah I see, that is what I end up configuring in the Configuration tab. Just checked again on my RPi4 using a zzh! CC2652R Multiprotocol RF Stick. The host OS seems to detect the USB device correctly:

```
[ 4018.001262] usb 1-1.1: new full-speed USB device number 3 using xhci_hcd
[ 4018.115672] usb 1-1.1: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.63
[ 4018.124268] usb 1-1.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[ 4018.131741] usb 1-1.1: Product: USB2.0-Serial
[ 4018.158130] usbcore: registered new interface driver ch341
[ 4018.163916] usbserial: USB Serial support registered for ch341-uart
[ 4018.170557] ch341 1-1.1:1.0: ch341-uart converter detected
[ 4018.181034] usb 1-1.1: ch341-uart converter now attached to ttyUSB0
```

And I can join a Zigbee device successfully, so there seems to be no general problem with the OS.

@mrIngrid is the log really empty? E.g. in the Zigbee2mqtt Add-On, in the Log tab, after pressing refresh, its not showing anything?

**Comment by ciotlosm** [comment]
@agners I found out that RPI4 has pretty big interference with the zzh! and I had to add the USB extension cord and move the stick further away from the unit to have it work consistently.
