### ISSUE TITLE
xiaomi zigbee smart plug ZNCZ02LM not report voltage

### ISSUE THREAD

**Issue by faronov** [danielwelch/hassio-zigbee2mqtt#47]
xiaomi zigbee smart plug ZNCZ02LM not report voltage
but his report correctly in original branch https://github.com/Koenkk/zigbee2mqtt/
I already try the edge

**Comment by faronov** [comment]
info: MQTT publish, topic: 'zigbee2mqtt/0x00158d0001db01d9', payload: '{"state":"ON","power":0,"voltage":null,"consumption":157.53,"temperature":27,"linkquality":89}'

**Comment by ciotlosm** [comment]
This is not related to the addon. Might be related to: https://github.com/Koenkk/zigbee2mqtt/issues/373 which probably got fixed in a more recent release.
