### ISSUE TITLE
Frontend UI (via Ingress) never loads any data

### ISSUE THREAD

**Issue by thibmaek** [danielwelch/hassio-zigbee2mqtt#470]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

1.16.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

- Debian 10, Supervised, latest stable HA, Docker, Texas Instruments Zigbee USB coordinator
- Safari latest stable, Chrome latest stable

**Description of problem:**

Using HA Ingress, the frontend is loaded but never displays any data. Map does not load.

Addon does not display any error logs when loading the frontend, browser console neither. Seems like the addon config is not properly loaded in the frontend web UI

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/6213695/99392610-3f9b7180-28dc-11eb-926b-8f6bc13c2329.png">

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt_addon
  password: *****
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001949EBDF-if00
  disable_led: false
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**

**Comment by baldfox** [comment]
I also have this issue.... (running HA 0.117.6 / z2m 1.16.1)

data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://homeassistant'
  user: *******
  password: ********************
serial:
  port: /dev/ttyACM0
  disable_led: true
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  availability_timeout: 300
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

**Comment by baldfox** [comment]
![image](https://user-images.githubusercontent.com/32448665/99628999-7cdd3c00-2a61-11eb-91e2-87d20e4bf101.png)

**Comment by ciotlosm** [comment]
You guys are missing:

```yaml
experimental:
  new_api: true
```

**Comment by baldfox** [comment]
> You guys are missing:
> 
> ```yaml
> experimental:
>   new_api: true
> ```

Legend. This fixed me up! I haven't dealt with amending the {} so I deleted them after experimental and just added 
  new_api: true.

thank you for your help! I'm good.
