### ISSUE TITLE
Door sensor not presenting correct value in hass

### ISSUE THREAD

**Issue by taugusti** [danielwelch/hassio-zigbee2mqtt#473]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.16.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
RPI4
HassOS 4.17
Hass 0.117.6

**Description of problem:**
Have 2 pcs door/window sensors Xiaomi MCCGQ11LM
both work fine and reports as expected in the exposes section of the zigbee2mqtt sidebar ui
current state of the door is in the value "contact" (true/false)
Now the problem: in the hass developer view the state of "*_contact" is allways "off"
looking at the data of the device, the "contact" attribute reflects the correct value of the contact
So - my impression is that the contact attribute is not copied to the device state correctly.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: 
  password: 
serial:
  adapter: deconz
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1997293-if00
advanced:
  log_level: info
  pan_id: 6754
  channel: 15
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

```

**Your logs from Home Assistant**
Let me know if you need anything
attached a screenshot from the developer view
![image](https://user-images.githubusercontent.com/15052792/99769776-275b6a80-2b07-11eb-8fcd-88c864562637.png)

**Comment by ciotlosm** [comment]
Could you please raise this issue here https://github.com/Koenkk/zigbee2mqtt/issues/new/choose ?

**Comment by taugusti** [comment]
Sure. But be fore I do it, please note that the value comming from zigbee2mqtt is correct. It is just mapped wrong in hass.
Is that not the task of the plugin?

**Comment by ciotlosm** [comment]
The "plugin/add-on" just does the docker wrapping and some option setup for you. In your case the "discovery" which is an integration between z2m and mqtt is done by the add-on. 

It might be that the messages showing the device look correct, but maybe the discovery message sent is wrong.

**Comment by taugusti** [comment]
ahh ok - thanks for explaining!
I will post in the z2m repo
