### ISSUE TITLE
Updating lib/extension/homeassistant.js

### ISSUE THREAD

**Issue by lymereJ** [danielwelch/hassio-zigbee2mqtt#477]
**zigbee2mqtt add-on version (if edge, please report commit hash):** Edge (not sure how I can get the commit hash from the UI).

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
HassOS

**Description of problem:** I've added a new device to `devices.js` and just like #264, while the device is paired and published to the zigbee2mqtt log, it does not show up in HA. I believe that it is because I need to go through [this step](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#5-optional-add-home-assistant-configuration-for-your-device), however, I can't seem to be able access and modify this file with my setup. I found #280 which seems to provide a solution to that problem but has been closed. How can I modify `lib/extension/homeassistant.js` with my current setup?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: *****
  password: ****
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014B93C5E-if00
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_shepherd_devices: true

```

**Your logs from Home Assistant**
```
Zigbee2MQTT:info  2020-11-23 09:37:30: MQTT publish: topic 'zigbee2mqtt/0x0017880108f9d6ba', payload '{"update_available":true}'
Zigbee2MQTT:info  2020-11-23 09:37:35: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x0017880108f9d6ba"},"type":"device_announced"}'
```

**Comment by ciotlosm** [comment]
@lymereJ is the option not available when using `external_converter` method?

**Comment by lymereJ** [comment]
@ciotlosm I have not yet tried `external_converter`. What I added to `devices.js` was extremely simple so I was hoping to stick with this approach if it was possible to modify `lib/extension/homeassistant.js` as well with my current setup. If not possible, I'll give the `external_converter` method a try.

**Comment by nurikk** [comment]
> @ciotlosm I have not yet tried the `external_converter` method. What I added to `devices.js` was extremely simple so I was hoping that I could stick with this approach if it is possible to modify `lib/extension/homeassistant.js` as well with my current setup. If not possible, I'll give the `external_converter` method a try.

Using external converter you can specify `homeassistant` property and this is how you achieve HA discovery, but nowdays this method is going to be deprecated in favour of new `exposes` property.

Kindly take a look on this converter https://github.com/diyruz/AirSense/blob/master/converters/DIYRuZ_AirSense.js#L168

https://github.com/Koenkk/zigbee2mqtt.io/blob/new_api/docs/information/exposes.md

**Comment by ciotlosm** [comment]
@lymereJ Were you able to try the recommended approach and see if that works for you?

**Comment by lymereJ** [comment]
@ciotlosm - Not yet! I got caught up with other stuff. I'll try this week.

**Comment by lymereJ** [comment]
I noticed that the latest version of edge now support my device so I don't need to use external converters or `devices.js` anymore.
