### ISSUE TITLE
Moes TRV ZigBee3.0 causes an error in Home Assistant's log

### ISSUE THREAD

**Issue by eromanenko** [danielwelch/hassio-zigbee2mqtt#478]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.16.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

**Description of problem:**
Moes TRV ZigBee3.0 (TS0601_thermostat) causes of a lot of repeated errors in Home Assistant's log
`ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: manual`

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: xxxxxx
  password: xxxxxx
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
2020-11-24 18:00:09 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: manual
2020-11-24 18:00:09 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: manual
2020-11-24 18:00:18 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: manual
2020-11-24 18:00:19 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: manual
2020-11-24 18:00:19 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: manual
2020-11-24 18:00:19 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: manual

**Comment by PaulAnnekov** [comment]
I have the same device branded as `Tuya` (https://www.aliexpress.com/item/1005001453602222.html) and it reports exactly the same error.

**Comment by ARNik** [comment]
The same issue.

**Comment by djhalun** [comment]
The same problem, after some debugging it comes out that if you set preset for example to manual, also system_mode change to manual. And in config file state for system_mode is only "auto" and because of this, conflict pops up in log. This issue is with all types of presets (eco, complex, away). I think that only schedule works OK. Can You do something about this?

**Comment by oopiicaa** [comment]
I can also confirm this - been seeing these errors in HA logs for some time now (TS0601_thermostat - latest OTA (also present before), Zigbee2MQTT 1.16.2, HA Core 0.118.0).
Everything seems to work fine though.

`ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: off`
`ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: complex`

**Comment by ciotlosm** [comment]
This looks to be a problem in zigbee2mqtt. Can you please open an issue on the main issue tracker there please? This repo is just for the add-on functionality (integration with the Supervisor) and configuration, the main code & functionality (device handling & such) are not affected by changes here.

**Comment by groenmarsmannetje** [comment]
This has been solved in dev/edge version
