### ISSUE TITLE
Zigbee device is not added HA

### ISSUE THREAD

**Issue by tpbillund** [danielwelch/hassio-zigbee2mqtt#479]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
NODE_VERSION | 12.19.0
YARN_VERSION | 1.22.5

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
Docker 18.09.0-0513 on Synology DS1618+ with DSM 6.2.3-25426 Update 2.
Home Assistant Core 0.119.0.dev20201127
Supervisor 2020.11.0
HACS 1.6.2

**Description of problem:**
I have installed zigbee2mqtt and MQTT, when i add devices zigbee is detecting em and add em too MQTT
(This is some data from my log inside portainer, for zigbee2mqtt)

```
> Zigbee2MQTT:info  2020-11-28 08:40:54: MQTT publish: topic 'zigbee2mqtt/Temp_stue', payload '{"battery":100,"device":{"applicationVersion":5,"dateCode":"20191205","friendlyName":"Temp_stue","hardwareVersion":30,"ieeeAddr":"0x00158d00030b7984","manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ11LM","networkAddress":1715,"powerSource":"Battery","softwareBuildID":"3000-0001","stackVersion":2,"type":"EndDevice","zclVersion":1},"humidity":48.52,"linkquality":68,"pressure":1018.6,"temperature":22.15,"voltage":3015}'

> Zigbee2MQTT:info  2020-11-28 08:40:54: MQTT publish: topic 'zigbee2mqtt/Temp_stue', payload '{"battery":100,"device":{"applicationVersion":5,"dateCode":"20191205","friendlyName":"Temp_stue","hardwareVersion":30,"ieeeAddr":"0x00158d00030b7984","manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ11LM","networkAddress":1715,"powerSource":"Battery","softwareBuildID":"3000-0001","stackVersion":2,"type":"EndDevice","zclVersion":1},"humidity":48.52,"linkquality":68,"pressure":1018,"temperature":22.15,"voltage":3015}'
```
So the data from the devices is ok, but when i then open HA then I can't find em as sensor, can someone help me?
Say if you need some files provided...

**Comment by tpbillund** [comment]
No one that can help here ?

**Comment by ciotlosm** [comment]
@tpbillund This repo is just for the add-on wrapper. The discovery & other mqtt functionality are not handled here. You can try the main zigbee2mqtt repo for issue report. Might be worth checking if any existing similar issues exist. 

https://github.com/Koenkk/zigbee2mqtt/issues

**Comment by tpbillund** [comment]
thx :-)
