### ISSUE TITLE
Zigbee2Mqtt not reading state from Feibit 1/2/3/Dimmer gang switch

### ISSUE THREAD

**Issue by mfmgold** [danielwelch/hassio-zigbee2mqtt#480]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
version 1.16.1, commit has 6b32f30
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
HassOS 5.3, Virtual Machine - false Home Assistant 0.118.4, Raspberry AARCH 64 

**Description of problem:**
Home Assistant ZigbeeMQTT integration does not fetch device state for the following devices. 
FB56+ZSC05HG1.0 - Dimmer Switch
FB56+ZSW1GKJ2.5 - 1 Gang Switch
FB56+ZSW1HKJ2.5 - 2 Gang Switch
FB56+ZSW1IKJ2.5 - 3 Gang Switch
FB56-ZCW11HG1.2 - Downlight
FB56-ZCW08KU1.1 - Bulb
FB56-ZCW11HG1.2 - Bulb

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: password
serial:
  port: /dev/ttyAMA0
  adapter: deconz
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_shepherd_devices: true
```

**Your logs from Home Assistant**

> zigbee2mqtt@1.16.1 start /zigbee2mqtt-1.16.1
> node index.js
/zigbee2mqtt-1.16.1/node_modules/zigbee-herdsman-converters/devices.js:265
            exposes.enum('effect', exposes.access.SET, ['blink', 'breathe', 'okay', 'channel_change', 'finish_effect', 'stop_effect']),
                                                  ^
TypeError: Cannot read property 'SET' of undefined
    at Object.<anonymous> (/zigbee2mqtt-1.16.1/node_modules/zigbee-herdsman-converters/devices.js:265:51)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/zigbee2mqtt-1.16.1/node_modules/zigbee-herdsman-converters/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm 
ERR! zigbee2mqtt@1.16.1 start: `node index.js`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.16.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR!

**Comment by juslex** [comment]
Dear,

I have the some issue.

I have opened a issue: check it:

Koenkk/zigbee2mqtt#4461

**Comment by ciotlosm** [comment]
I will close this as the repo here is just for the add-on. Please continue to discuss this on Koenkk/zigbee2mqtt#4461
