### ISSUE TITLE
Can't add repository in Home Assistant.

### ISSUE THREAD

**Issue by frso80** [danielwelch/hassio-zigbee2mqtt#482]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
None
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

HassOS 4.17 running on Raspberry Pi 4 4GB.

**Description of problem:**
Can't add the repo in Home Assistant.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
Not relevant.
```

**Your logs from Home Assistant**
```
20-12-02 17:18:53 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-02 17:18:53 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
```

**Comment by yabbah** [comment]
I was just about to create an issue. Have the same issue here ..

**Comment by mangant** [comment]
I have same issue too.

**Comment by Mr-Groch** [comment]
I've added earlier, but can't reload and update, supervisor logs:

```
20-12-02 18:44:33 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-02 18:44:33 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-02 18:44:34 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-02 18:44:34 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
```

**Comment by rickyoleary** [comment]
Same issue, finally got everything delivered and ran into the issue first off, glad I'm not the only one. :)

**Comment by LaurentMicrotec** [comment]
Same issue!
`20-12-02 19:10:20 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-02 19:10:20 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'`

**Comment by ciotlosm** [comment]
This is a problem with the new release of the add-on. You can use https://github.com/zigbee2mqtt/hassio-zigbee2mqtt until we get this fixed here as well. 

Issue was raised now as well here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues/483

**Comment by SzemiSun** [comment]
I have same issue too.

**Comment by andriej** [comment]
@ciotlosm will there be some kind of hand-over of repos?

**Comment by ciotlosm** [comment]
@andriej I'll try to outline here the steps that I had in mind:
1. Keep both repos on at the same time until enough people test out `zigbee2mqtt/hassio-zigbee2mqtt` version to iron out potential problems
1. Merge back to `danielwelch/hassio-zigbee2mqtt` all changes: at this stage, docker images would get consumed from dockerhub `zigbee2mqtt` org
1. Reset `zigbee2mqtt/hassio-zigbee2mqtt` repo so it is no longer a fork of `danielwelch/hassio-zigbee2mqtt`
1. Update `zigbee2mqtt` documentation (not the add-on) to reflect `zigbee2mqtt/hassio-zigbee2mqtt` repo as main
1. Cleanup  `danielwelch/hassio-zigbee2mqtt` code to allow only `configs` pointing to dockerhub `zigbee2mqtt` org
1. Keep `danielwelch/hassio-zigbee2mqtt` as a lightweight `config only version to store `previous/older` version in case there are severe bugs that are not solved in time (to avoid people getting problems with their significant other)

**Comment by LaurentMicrotec** [comment]
Wow, that's a lot of work, isn't it? I don't understand everything, I don't have the level. But we can hope with a new functional add on in how long?

**Comment by ciotlosm** [comment]
@LaurentMicrotec would think in around 1 month we should be able to have a transition. Maybe sooner if I get more time.

**Comment by wafprotocol** [comment]
> Wow, that's a lot of work, isn't it? I don't understand everything, I don't have the level. But we can hope with a new functional add on in how long?

@LaurentMicrotec the handover doesn't have much to do with the state of _this_ addon, when this issue is fixed `danielwelch/hassio-zigbee2mqtt` should work again. Methinks for home assistant supervisor users it should just be a change in repositories and get the new version and stop the old. (although some entities changed when I switched from `danielwelch` to `zigbee2mqtt`)

**Comment by rickyoleary** [comment]
> This is a problem with the new release of the add-on. You can use https://github.com/zigbee2mqtt/hassio-zigbee2mqtt until we get this fixed here as well.
> 
> Issue was raised now as well here: #483
> 
> Update: New PR created in #484

Hi, I am using this as suggested and I can download the repo and install the addon. But it just won't seem to go past:

> zigbee2mqtt@1.16.1 start /app
> node index.js

in the logs. Everything I'm looking at online, after this line it should launch zigbee-shephard etc. But mine just stops and it's not working, is it related to the add on that has been suggested? I am using Home Assistant, version: 2020.12.2 and version 1.16.1-1 of Zigbee2mqtt as per above repo URL.

Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[10:55:18] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[10:55:19] INFO: MQTT available, fetching server detail ...
[10:55:19] INFO: MQTT credentials not configured, trying to auto-discovering ...
[10:55:20] INFO: Configuring'addons' mqtt user
[10:55:20] INFO: Previous config file found, checking backup
[10:55:20] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[10:55:20] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:55:21] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.16.1 start /app
> node index.js

Nothing further here.

**Comment by ciotlosm** [comment]
@rickyoleary That is normal as you have no errors. If you want more logs you need to use `info` or `debug` in your config for `log_level` here:

```
advanced:
  log_level: warn
```
