### ISSUE TITLE
Update homeassistant addon manually?

### ISSUE THREAD

**Issue by jamiekris** [danielwelch/hassio-zigbee2mqtt#485]
I can see that 1.16.2 has been released, yet homeassistant does not show me the option to update the addon. Is there a way to manually do this? or force an update check?

**Comment by Ryanmt2** [comment]
You are just waiting for this to be merged in first, then it will update.
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/14

**Comment by ciotlosm** [comment]
This should now be fixed.
