### ISSUE TITLE
Can't update to 1.16.2.1

### ISSUE THREAD

**Issue by Mr-Groch** [danielwelch/hassio-zigbee2mqtt#486]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.16.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

HassOS

**Description of problem:**
Can't update to 1.16.2 release - addon does not show available update, when I try to reload repository data, supervisor logs shows warning (see below)

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: *****
  password: *****
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  report: true
  pan_id: 6755
  channel: 25
  network_key:
    - 1
    - 2
    - 5
    - 7
    - 9
    - 10
    - 13
    - 15
    - 0
    - 2
    - 4
    - 7
    - 8
    - 10
    - 11
    - 13
  availability_timeout: 300
  availability_blocklist:
    - '0x00158d00038e48fa'
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
```
20-12-03 11:31:25 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-03 11:31:25 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
```

**Comment by xpavli44** [comment]
Same here `20-12-03 11:44:06 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-03 11:44:06 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'`

**Comment by ciotlosm** [comment]
I'll try to release a tested patch soon. Sorry for the inconvenience. You can try using https://github.com/zigbee2mqtt/hassio-zigbee2mqtt if you're in a rush. It works with the same config.

**Comment by Falconpage** [comment]
If I can help, the error I've got when I tried to update from 1.16.1 to  1.16.2.2 :

[supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-amd64:1.16.2.2 -> 404 Client Error for http+docker://localhost/v1.40/images/create?tag=1.16.2.2&fromImage=dwelch2101%2Fzigbee2mqtt-amd64: Not Found ("manifest for dwelch2101/zigbee2mqtt-amd64:1.16.2.2 not found: manifest unknown: manifest unknown").

**Comment by ciotlosm** [comment]
@Falconpage yes, that is a problem with the release process on this repo and how it handles tags and building of stable releases. That error will only go away on the new repo where a dev branch exists and where were can release new versions on the dev branch, build them and only when it works, publish in `master`.

**Comment by Falconpage** [comment]
Ok, if I understand well, we just have to  wait ?
You are working on a new repo ?

**Comment by ciotlosm** [comment]
There are two repos:
- https://github.com/danielwelch/hassio-zigbee2mqtt (this one)
- https://github.com/zigbee2mqtt/hassio-zigbee2mqtt (a new fork that will become default in the future)

Currently the `new` one has no bugs as version 1.16.2 was not released there, so you can use https://github.com/zigbee2mqtt/hassio-zigbee2mqtt  safely. 

I'm working on a fix that would fix problems on  https://github.com/danielwelch/hassio-zigbee2mqtt and release a patched version, and if that works I will release 1.16.2 also on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt. 

Basically we're trying at the moment to keep https://github.com/danielwelch/hassio-zigbee2mqtt  and https://github.com/zigbee2mqtt/hassio-zigbee2mqtt  in sync with version for a smooth transition soon (~1 month if all goes well). 

Steps for the transition should be:
1. Keep both repos on at the same time until enough people test out `zigbee2mqtt/hassio-zigbee2mqtt` version to iron out potential problems
1. Merge back to `danielwelch/hassio-zigbee2mqtt` all changes: at this stage, docker images would get consumed from dockerhub `zigbee2mqtt` org
1. Reset `zigbee2mqtt/hassio-zigbee2mqtt` repo so it is no longer a fork of `danielwelch/hassio-zigbee2mqtt`
1. Update `zigbee2mqtt` documentation (not the add-on) to reflect `zigbee2mqtt/hassio-zigbee2mqtt` repo as main
1. Cleanup  `danielwelch/hassio-zigbee2mqtt` code to allow only `configs` pointing to dockerhub `zigbee2mqtt` org
1. Keep `danielwelch/hassio-zigbee2mqtt` as a lightweight `config` only version to store `previous/older` version in case there are severe bugs that are not solved in time (to avoid people getting problems with their significant other)

**Comment by jamiekris** [comment]
I am currently on the `danielwelch` branch and hassio detects that there is a new version (16.2.2) available, however, does not seem to do anything when I hit the update button. I have tried to restart the machine/addon with no effect still. Am I missing something?

**Comment by ciotlosm** [comment]
@jamiekris you're not missing anything. The problem is with the release process. I'm working on testing 1.16.2.2 before i publish it to docker hub, but there is no easy way to do this without version upgrade in the config file, which resulted in 1.16.2.2 being made visible to home-assistant (as it uses `master` branch) 

I'm trying to get this tested as soon as possible and released, but if it's an inconvenient you can use https://github.com/zigbee2mqtt/hassio-zigbee2mqtt.

**Comment by wafprotocol** [comment]
I see both `zigbee2mqtt` and `danielwelch` have a release for 1.6.2 now but both give the same error on installing:

`20-12-03 16:08:33 ERROR (SyncWorker_6) [supervisor.docker.interface] Can't install zigbee2mqtt/zigbee2mqtt-armv7:1.16.2 -> 404 Client Error for http+docker://localhost/v1.40/images/create?tag=1.16.2&fromImage=zigbee2mqtt%2Fzigbee2mqtt-armv7: Not Found ("manifest for zigbee2mqtt/zigbee2mqtt-armv7:1.16.2 not found: manifest unknown: manifest unknown").`

**Comment by shirou93** [comment]
> @jamiekris you're not missing anything. The problem is with the release process. I'm working on testing 1.16.2.2 before i publish it to docker hub, but there is no easy way to do this without version upgrade in the config file, which resulted in 1.16.2.2 being made visible to home-assistant (as it uses `master` branch)
> 
> I'm trying to get this tested as soon as possible and released, but if it's an inconvenient you can use https://github.com/zigbee2mqtt/hassio-zigbee2mqtt.

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt. url not working. Error when install. old url work.

**Comment by ciotlosm** [comment]
@shirou93 https://github.com/zigbee2mqtt/hassio-zigbee2mqtt should work now. It seems Home Assistant for some reason broke the clean release process there by fetching the `dev` version of config.json (Even if stated differently in the docs). You were just unlucky to catch also the package in between builds. Try a new install and it should work. 

Now both repos have 1.16.2 (org) & 1.16.2.2 (daniel) built and ready to be consumed, and hopefully work without problem.

**Comment by ciotlosm** [comment]
I'm still investigating how ttps://github.com/zigbee2mqtt/hassio-zigbee2mqtt got version 1.16.2 announced as the master version (https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/config.json) still shows 1.16.1-1

**Comment by shirou93** [comment]
Working now.
