### ISSUE TITLE
Can't install 1.16.2.2

### ISSUE THREAD

**Issue by wafprotocol** [danielwelch/hassio-zigbee2mqtt#488]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
None (removed version 1.14 and now running on `zigbee2mqtt/hassio-zigbee2mqtt` 1.16.1-1)
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

HassOS 4.17
supervisor 2020.12.2

**Description of problem:**
Can't install 1.16.2.2

I don't see any release of 1.16.2.2 yet in github, yet that's the version supervisor wants to install.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
Not relevant
```

**Your logs from Home Assistant**
```
20-12-03 12:02:41 INFO (SyncWorker_6) [supervisor.docker.interface] Downloading docker image dwelch2101/zigbee2mqtt-armv7 with tag 1.16.2.2.
20-12-03 12:02:43 ERROR (SyncWorker_6) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armv7:1.16.2.2 -> 404 Client Error for http+docker://localhost/v1.40/images/create?tag=1.16.2.2&fromImage=dwelch2101%2Fzigbee2mqtt-armv7: Not Found ("manifest for dwelch2101/zigbee2mqtt-armv7:1.16.2.2 not found: manifest unknown: manifest unknown").
```

**Comment by ciotlosm** [comment]
Please switch to using https://github.com/zigbee2mqtt/hassio-zigbee2mqtt for now, as the config is compatible. The release process here is a bit broken and there are bugs in 1.16.2 and 1.16.2.1. Apologies for this, I'm working on a fix but have to make sure it passes live tests this time.

**Comment by wafprotocol** [comment]
Thanks, I am already running that one because of the previous issues in 1.6.2 (just want to upgrade to 1.16.2 for christmas lights support 👍). 
Wanted to test updating and saw 1.16.2.2 is available from hassio/supervisor but has not been released on github yet.

**Comment by romlisrl** [comment]
Same issue here.

Will try to switch to another repository.

**Comment by ciotlosm** [comment]
Please switch for now. Once tested, I will release versions on both repos with 1.16.2 in working condition.

**Comment by bruvv** [comment]
This is still an issue, for both repo's. I tried removing it and reinstalling but that is giving me the same error and now I cannot control mine zigbee lights anymore, lol...
