### ISSUE TITLE
Question: How to build a forked version using the edge add-on?

### ISSUE THREAD

**Issue by mihalski** [danielwelch/hassio-zigbee2mqtt#49]
I've forked zigbee2mqtt to make a minor change and thought I'd be able to use your add-on as a local add-on and simply change the git clone line to:
```
git clone -b unique_id --single-branch --depth 1 https://github.com/mihalski/zigbee2mqtt.git /app
```
However it STILL seems to use a different branch (or possibly repository?) when I install from the local add-on repository. I have verified this by checking the contents of the offending file inside the docker container that is built.

Am I doing something obvious wrong?

**Comment by danielwelch** [comment]
If you’re using it as a local add-on, you’ll need to make changes to the config.json file as well. Without more info, I’d guess that the add-on isn’t actually building locally, but is using the image on docker hub published by me, consistent with the instructions of the configuration file.

**Comment by mihalski** [comment]
Ahh.. I suspected something like that after I couldn't get it to work.
Originally I thought that the Docker file gets built locally and the git clone is done as part of the install. Seems that's not the case?
Literally the only change I wish to make is to one of the files in lib/homeassistant.js.
Is there a way to force the build of the docker container locally? I have not yet tried but I assume it's not as easy as removing the `"image": "dwelch2101/zigbee2mqtt-edge-{arch}"` in the config.json?

**Comment by danielwelch** [comment]
Yes, your understanding is partially correct. That is what happens, unless the add-on is specifies an image in the config. But the good news is, yes, it’s that easy. You should just have to remove that line and, assuming everything is setup in the right location for local add-ons, it should build locally. You can always check the logs for some hints on what’s going on during installation.

**Comment by dzungpv** [comment]
I want this too, try to build from your config but not work. Can you provide detail step by step to build the image @danielwelch ?
Due to this feature not complete https://github.com/Koenkk/zigbee2mqtt/issues/232, pull request accept slow , i want to build my own image for testing hassio

**Comment by mihalski** [comment]
I tried the suggested approach and after an extended wait the build/run failed with the following error:
```
18-09-11 07:57:37 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/local_zigbee2mqtt-edge
18-09-11 07:57:37 INFO (SyncWorker_0) [hassio.docker.addon] Start build local/armhf-addon-zigbee2mqtt-edge:test
18-09-11 08:05:54 ERROR (SyncWorker_0) [hassio.docker.addon] Can't build local/armhf-addon-zigbee2mqtt-edge:test: COPY failed: stat /var/lib/docker/tmp/docker-builder581565988/run.sh: no such file or directory
```
Here are the files I used: [zigbee2mqtt-unique_id.zip](https://github.com/danielwelch/hassio-zigbee2mqtt/files/2370035/zigbee2mqtt-unique_id.zip)

Any ideas what happened here?

**Comment by mihalski** [comment]
And the solution.. Surely obvious if you know what you're doing...

Copy `run.sh` and `set_config.py` from the `zigbee2mqtt` directory to the `zigbee2mqtt-edge` directory (then the `zigbee2mqtt-edge` directory to the local addon directory).

Now when you build it will succeed, and use the repository specified in the `Dockerfile`.

**Comment by danielwelch** [comment]
Great, glad you got it working. @dzungpv I recommend reading the homeassistant dev docs on creating and add-on, particularly the first bit on local add-on testing and development in this case. Without knowing more details, it’s difficult to help. Logs are usually helpful; in the case above they pointed out the step in the Dockerfile that caused a problem.

**Comment by Iv4nS** [comment]
I'm having this issue, no matter what I do or change it still pulls from the original repository: https://github.com/Koenkk/zigbee2mqtt

I tried replacing the repository specified in the Dockerfile and getting rid of the image in config.json but still it pulls it somehow.  IAny don't see anything usefull in hassio's log (System tab).

Do you happen to have any instructions in terms of modifications for it to pull my own repository?
Thanks!
