### ISSUE TITLE
Last seen not saved

### ISSUE THREAD

**Issue by Maurotb** [danielwelch/hassio-zigbee2mqtt#490]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

1.16.2.2

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

Hassos 0.118.4

**Description of problem:**

If i change lastseen from none to another value in frontend, it work but if i restart zigbee2mqtt it return to "none"

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration
```

**Your logs from Home Assistant**

**Comment by ciotlosm** [comment]
This is not a problem of the add-on. Try and post an issue on z2m issue tracker list for this. We won't be able to help you here.
