### ISSUE TITLE
Failed to start addon after upgrade supervisor

### ISSUE THREAD

**Issue by hoattt1** [danielwelch/hassio-zigbee2mqtt#491]
**zigbee2mqtt add-on version (if edge, please report commit hash): 1.16.2.2

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):
- HassOS
- Raspery Pi 3b+
- Supervisor 2020.12.6

**Description of problem:**
After I upgraded supervisor to 2020.12.6 and restarted HassOS, Zigbee2mqtt addon cann't start. When i tried to start addon, it showed a message: "- 404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_110c40b1_zigbee2mqtt: Not Found ("No such image: dwelch2101/zigbee2mqtt-armv7:1.16.2.2")"

**Your logs from Home Assistant**
20-12-08 14:43:49 WARNING (MainThread) [supervisor.addons.validate] Unknown options include_device_information
20-12-08 14:43:49 WARNING (MainThread) [supervisor.addons.validate] Unknown options include_device_information
20-12-08 14:43:49 ERROR (SyncWorker_4) [supervisor.docker] Image dwelch2101/zigbee2mqtt-armv7 not exists for addon_110c40b1_zigbee2mqtt
20-12-08 14:44:08 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-12-08 14:44:08 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
20-12-08 14:44:08 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
20-12-08 14:45:50 WARNING (MainThread) [supervisor.addons.validate] Unknown options include_device_information
20-12-08 14:45:51 WARNING (MainThread) [supervisor.addons.validate] Unknown options include_device_information
20-12-08 14:45:51 ERROR (SyncWorker_3) [supervisor.docker] Image dwelch2101/zigbee2mqtt-armv7 not exists for addon_110c40b1_zigbee2mqtt
20-12-08 14:48:35 INFO (MainThread) [supervisor.snapshots] Found 5 snapshot files

Anyone can help me?

**Comment by ciotlosm** [comment]
Can you uninstall / reinstall ? Just save your config. Looks like the supervisor cleaned up local images. it must try to re-take from the docker hub.

**Comment by hoattt1** [comment]
> Can you uninstall / reinstall ? Just save your config. Looks like the supervisor cleaned up local images. it must try to re-take from the docker hub.

Thank so much, after uninstall/reinstall it didn't work. So i tried ty restore some snapshot, After 3-4 times and then uninstall/reinstall, it worked.
Thanks so much

**Comment by szaracz** [comment]
Hi. I am experiencing the same issue. Is any solution available?

**Comment by hoattt1** [comment]
> Hi. I am experiencing the same issue. Is any solution available?

Just uninstall and reinstall many times
