### ISSUE TITLE
Tradfri Test server option support - ikea_ota_use_test_url option missing

### ISSUE THREAD

**Issue by dreimer1986** [danielwelch/hassio-zigbee2mqtt#493]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
6126ead

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

HassOS 5.6

**Description of problem:**
https://github.com/Koenkk/zigbee2mqtt/issues/2921#issuecomment-741977661 this setting can't be added right now.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://homeassistant'
  user: CENSOR
  password: CENSOR
  include_device_information: true
  version: 5
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: CENSOR
  channel: CENSOR
  network_key:
    - CENSOR
  availability_blocklist: []
  availability_passlist: []
  availability_timeout: 60
  report: true
  last_seen: ISO_8601
  rtscts: true
  **ikea_ota_use_test_url: true**
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
  transmit_power: 14
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**

**Comment by groenmarsmannetje** [comment]
Just a question because I am interested. Why does the configuration of the addon does not use a scheme in the zigbee2mqtt source to validate the Json or just pass the configuration? It does not make sense to me that for a configuarational change a whole new build and release is needed.

**Comment by ciotlosm** [comment]
@groenmarsmannetje The config for the add-on is based on the requirements from Home Assistant Supervisor. This allows only for a 2 layer config and no more:

```
layer1:
  layer2:
```

In many cases the configuration from Zigbee2mqtt has multiple layers, so this has to be adapter to work with the Supervisor. We do want to have the configuration editable from the Add-on UI as in the future, with the right "schema" we will get better UI for this.

Imagine booleans being toggle switches, ranges to be sliders & such. While this is painful at times to keep in sync, and new features have to be added by hand, it does give a lot of benefit for users that will get to use an easier workflow to maintain their configuration.

**Comment by dreimer1986** [comment]
TBH I prefer the UI configurable way like we have it right now. HA tries to become more and more user friendly with every new version and switching back to a config file to edit sounds like a big step back. So I fully support the current way to go. And most important... It does not happen very often that a new parameter is added to the config of z2m. So no problem from my side to wait a bit until things sum up until a update is really worth the effort. Just wanted to be sure that it's on the todo list, that's why I made the report ^^

**Comment by KRISUUUU** [comment]
1.17 the same... [supervisor.addons.validate] Unknown options ikea_ota_use_test_url :(

**Comment by ciotlosm** [comment]
I will try to include this in 1.17.0.1 on this repo and in 1.17.0-1 on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt soon.

**Comment by filewalker1** [comment]
still missing in 1.17.0.1

by the way? is there a guide on how to change from this repo to the new one without loosing config/zigbee devices?

**Comment by KRISUUUU** [comment]
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt

This is new repo ?

**Comment by ciotlosm** [comment]
@filewalker1 unfortunately I forgot there was a pending PR on this one, so the release version for this will be 1.17.0.2
The new repo works out of the box with your old config and will reuse your config/ database & all data for devices, so you can swap seamlessly. There are two options removed from `socat` section that you will see as warning on startup.

@KRISUUUU yes, that will become the new official repo once all the docs changes are complete and merged (https://github.com/Koenkk/zigbee2mqtt.io/pull/544 and https://github.com/Koenkk/zigbee2mqtt/pull/5546)

**Comment by filewalker1** [comment]
@ciotlosm thank you very much! so no need to backup and manually restore anything (except configuration) - that is great. Keep up the good work :)

**Comment by ciotlosm** [comment]
@filewalker1 Thanks. The original repo will also remain for quite a few months in parallel, but will drop all code and adopt the new versioning scheme by just reusing the built artefacts from the new one. In time we will delay updates to the original one (by a week or so) to allow people to rollback in case new one is problematic for them. 

I'm not sure how long we will run them in parallel in the long run, but I guess we will see in time how the community adapts to this new flow.

**Comment by KRISUUUU** [comment]
@ciotlosm Thank you for your answer! Great job

**Comment by jd1900** [comment]
> @KRISUUUU yes, that will become the new official repo once all the docs changes are complete and merged ([Koenkk/zigbee2mqtt.io#544](https://github.com/Koenkk/zigbee2mqtt.io/pull/544) and [Koenkk/zigbee2mqtt#5546](https://github.com/Koenkk/zigbee2mqtt/pull/5546))

@ciotlosm I've swapped to that repo, but I still get the error:
21-01-23 15:44:03 WARNING (MainThread) [supervisor.addons.validate] Unknown options ikea_ota_use_test_url

Wasn't the new repo supposed to be updated with the OTA option?

BTW, in the new repo there is no v1.17.1 or v1.17.0-1, just v1.17.0. Why is that?

**Comment by dreimer1986** [comment]
Well, ppl will hate me for making them think the report got an update, buuuut.... I understood that he wanted to make this one the more recent experimental one ad the other the final official one. Correct me if I am wrong here.

**Comment by KRISUUUU** [comment]
Working on 1.17.1 ?

**Comment by dreimer1986** [comment]
Easy to check: https://github.com/danielwelch/hassio-zigbee2mqtt/commit/3793c6cb4c19ae6b5a7d4cb164b8b2cf6507fc93 Nope

**Comment by mgiebels** [comment]
OTA Update still not working 
```
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'Switch.1' failed (Image is truncated: not long enough to contain a valid tag)","meta":{"device":"Switch.1","status":"update_failed"},"type":"ota_update"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Switch.1"},"error":"Update of 'Switch.1' failed (Image is truncated: not long enough to contain a valid tag)","status":"error","transaction":"8sjj9-1"}
```

I have the test url in my configuration.yaml

serial:
  adapter: deconz
  port: /dev/ttyACM0
advanced:
  ikea_ota_use_test_url: true
  lpog_level: info
  pan_id: 6754
  channel: 11
  network_key:

Zigbee2mqtt
Current version: 1.17.1

**Comment by ciotlosm** [comment]
This was now added in 1.17.1-1 and edge for https://github.com/zigbee2mqtt/hassio-zigbee2mqtt. Version 1.17.1-1 is not yet published, but it should be soon.

**Comment by car1ox** [comment]
I just installed 1.17.1-1 and ikea ota is working fine with the test server.
Now updating one of my Ikea lights.
Thanks!

**Comment by mgiebels** [comment]
How can i install 1.17.1-1?

**Comment by ciotlosm** [comment]
From https://github.com/zigbee2mqtt/hassio-zigbee2mqtt

**Comment by mgiebels** [comment]
Ah i installed it from : https://github.com/danielwelch/hassio-zigbee2mqtt

**Comment by jerkovicl** [comment]
Any guide for upgrade to other Repo?

**Comment by ciotlosm** [comment]
copy config, install new one, paste config

**Comment by mgiebels** [comment]
Still can not update :(

```
info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'Switch.1' failed (Image is truncated: not long enough to contain a valid tag)","meta":{"device":"Switch.1","status":"update_failed"},"type":"ota_update"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Switch.1"},"error":"Update of 'Switch.1' failed (Image is truncated: not long enough to contain a valid tag)","status":"error","transaction":"4hm5m-1"}'
Error Update of 'Switch.1' failed (Image is truncated: not long enough to contain a valid tag)
```

**Comment by mgiebels** [comment]
I installed it from that other repo and put my old config back but then it looks at the old share again.
When I look in the log it says 1.17.1 is starting.
While I installed 1.17.1-1 from: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt

I'll wait for it to be on my other repo: https://github.com/danielwelch/hassio-zigbee2mqtt

**Comment by stanvv** [comment]
New repo works to me!

**Comment by jerkovicl** [comment]
> copy config, install new one, paste config

Do i need to repair devices after switching?

**Comment by mgiebels** [comment]
For me is copy config install new one en past config not working.
It says installed 1.17.1-1 but in the log he says starting 1.17.1 and by about is also says 1.17.1

**Comment by ciotlosm** [comment]
@mgiebels it will say 1.17.1 at startup because that's the z2m version. You don't need to repair devices, and now the current repo will show 1.17.1-1 available because we're deprecating the old repo so the images are common, configs are just copied over.

**Comment by mgiebels** [comment]
> it will say 1.17.1 at startup because that's the z2m version. You don't need to repair devices, and now the current repo will show 1.17.1-1 available because we're deprecating the old repo so the images are common, configs are just copied over.

Yes it just doesn't work.
Ikea update in advanced is not shown and the updates do not work either.
Then what am I doing wrong?

**Comment by ciotlosm** [comment]
Did you add `ikea_ota_use_test_url` in advanced and it doesn't let you save?

**Comment by mgiebels** [comment]
> Did you add `ikea_ota_use_test_url` in advanced and it doesn't let you save?

I do not know where to enter this, I cannot find an option for this

**Comment by ciotlosm** [comment]
@mgiebels if you are using HassOS add-on you should find it under Supervisor > Dashboard > Zigbee2mqtt > Configuration. Just add the option there.

**Comment by mgiebels** [comment]
this is also still visible in my change log state: Removed transmit_power from experimental
but this is still visible to me.
Looks like it hasn't been updated then.

**Comment by mgiebels** [comment]
> @mgiebels if you are using HassOS add-on you should find it under Supervisor > Dashboard > Zigbee2mqtt > Configuration. Just add the option there.

I have copied de config file from my old zigbee2mqtt and add it to the new one but it doesnt work

**Comment by mgiebels** [comment]
It is working :D

**Comment by ciotlosm** [comment]
@dreimer1986 is the update working for you? Can we close this issue?

**Comment by mgiebels** [comment]
Update is working for me! you me close it

**Comment by dreimer1986** [comment]
Oh, you are waiting for me... Sorry. ^^ Update installed, test server option working, no updates for my bulbs though, but that was quite expected. I close it then :D Thanks for fixing!
