### ISSUE TITLE
Moes MS-104Z-1 "unsupported" after 1.16.2.2

### ISSUE THREAD

**Issue by Gio-dot** [danielwelch/hassio-zigbee2mqtt#497]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.16.2.2
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
Supervisor
Version
2020.12.7
Operating System
Home Assistant OS 5.8

**Description of problem:**
Some day ago i was on 1.16.1 version of this addon and i added succesfully this device https://zigbee.blakadder.com/Moes_MS-104Z-1.html. Yesterday i updated to 1.16.2.2 and that device now is declared "unsupported" (see log below). WHich can be the problem? I have other devices (Xiaomi and Osram) all working even after last update.. Tried to repeat pairing, but is say "unsupported" again.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration
```

**Your logs from Home Zigbeetomqtt addon**
```
Zigbee2MQTT:warn  2020-12-17 09:00:32: Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_zmy1waw6'
```
![image](https://user-images.githubusercontent.com/55327160/102468703-2c520200-4052-11eb-8489-e90f637bf04c.png)

![image](https://user-images.githubusercontent.com/55327160/102468859-599eb000-4052-11eb-9dd0-a82eac427da5.png)

**Comment by Gio-dot** [comment]
Ok, solved restoring a plugin snapshot from Hassio snapshot. Restored version 1.16.1 and now this device work again. I can confirm it doesn't work on 1.16.2.2

**Comment by ciotlosm** [comment]
@Gio-dot can you please report this bug on the main `zigbee2mqtt` issue tracker? This repo here is just for the add-on. Most changes here cover just packaging that code to work with Home Assistant Supervisor.
