### ISSUE TITLE
adapter_delay option missing

### ISSUE THREAD

**Issue by andriej** [danielwelch/hassio-zigbee2mqtt#499]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 0.16.2

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):** HA Supervised Debian 10

**Description of problem:**
Please add support of `adapter_delay` so it can be passed through to z2m as in Conbee thread: https://github.com/Koenkk/zigbee-herdsman/issues/72#issuecomment-748683612

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
advanced:
  adapter_delay: 
(should work)
```

**Your logs from Home Assistant**
`20-12-20 23:01:22 WARNING (MainThread) [supervisor.addons.validate] Unknown options adapter_delay`

**Comment by andriej** [comment]
@ciotlosm any chance to have it faster implemented in your-new repo? :-)

**Comment by ciotlosm** [comment]
@andriej I will look to add it to both for now. Just been a bit busy period.

**Comment by andriej** [comment]
Yeah, I understand. Urgency is called by dropped WAF-facotr, as integration started to go haywire. ;-)

**Comment by kind3r** [comment]
@andriej, until the PR is accepted you can test the edge version from my repo https://github.com/kind3r/hassio-zigbee2mqtt.
I have not noticed a significant improvement, z2m feels a bit slower than deConz, but there are some other delays involved as mentioned in https://github.com/Koenkk/zigbee-herdsman/issues/273

**Comment by ciotlosm** [comment]
This is now part of https://github.com/zigbee2mqtt/hassio-zigbee2mqtt 1.17.0
I'll also accept the PR on this as soon as I get sometime to rebase it for 1.17.0

**Comment by andriej** [comment]
Are you sure?
I still see `WARNING (MainThread) [supervisor.addons.validate] Unknown options adapter_delay` in Supervisor logs on 1.17.0 addon

**Comment by ciotlosm** [comment]
@andriej it's part currently only of https://github.com/zigbee2mqtt/hassio-zigbee2mqtt  1.17.0 which is a different repo (that we're trying to switch to this month)

https://github.com/danielwelch/hassio-zigbee2mqtt still does not have it in 1.17.0 and will have to be part of 1.17.0.1  as https://github.com/danielwelch/hassio-zigbee2mqtt/pull/504 will have to get rebased.

**Comment by andriej** [comment]
Right. I've moved to this repo and it seems supported right now.
Thus, those two are not in my config but showed up in supervisor log:
```
21-01-04 12:13:24 WARNING (MainThread) [supervisor.addons.validate] Unknown options restartdelay
21-01-04 12:13:24 WARNING (MainThread) [supervisor.addons.validate] Unknown options initialdelay
```

**Comment by ciotlosm** [comment]
restartdelay and initialdelay are configs that are no longer needed, as those were used for a process hack that is no longer needed as we now use s6-overlay

Those options are nowhere in the repo code, so they must be somewhere in `socat` section in your config.

**Comment by andriej** [comment]
You're right, it was socat. Thanks.

**Comment by liuk84** [comment]
please, i have alredy problem, is presente the warning restart relay... is present in socat.. i do delete this?whaat i do delete?
![Schermata 2021-03-06 alle 18 15 33](https://user-images.githubusercontent.com/75086206/110215043-f7fb1e80-7ea7-11eb-8aff-8051e8152764.png)

**Comment by ciotlosm** [comment]
@liuk84 just remove `restartdelay` and initialdelay` options from your socat config. Those are no longer required.

**Comment by liuk84** [comment]
> @liuk84 just remove `restartdelay` and initialdelay` options from your socat config. Those are no longer required.

yes, thanck for answer i have deleted it, but i'm not able to eliminate  experimental: new_api true

**Comment by ciotlosm** [comment]
Just put in experimental: {}
