### ISSUE TITLE
Support cache_state in configuration

### ISSUE THREAD

**Issue by deskoh** [danielwelch/hassio-zigbee2mqtt#50]
To support `advanced.cache_state` in addon configuration. See [here](https://github.com/Koenkk/zigbee2mqtt/wiki/Configuration) for more details on the option.

This option fixes the issue mentioned [here](https://github.com/Koenkk/zigbee2mqtt/issues/70).

**Comment by danielwelch** [comment]
I’ll work on this as a part of refactoring the options more completely. There are several that have been changed or added and the add-on hasn’t caught up.

**Comment by danielwelch** [comment]
This is supported as of 0.1.3.1
