### ISSUE TITLE
[FATAL tini (6)] exec /init failed: Exec format error

### ISSUE THREAD

**Issue by jnpetersen** [danielwelch/hassio-zigbee2mqtt#500]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

Running HassOS on Raspberry Pi 4 Supervised. Its running on Raspbian (buster)

**Description of problem:**

I tried installing the addon, I adjusted the configuration for my MQTT settings, and I get the error listed in the title of this post when I try to start the addmon.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json

data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.230:1883'
  user: myuser
  password: mypassword
serial:
  port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2254373-if00
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false


```

**Your logs from Home Assistant**

[FATAL tini (7)] exec /init failed: Exec format error

**Comment by ciotlosm** [comment]
Can you try installing from here: http://github.com/zigbee2mqtt/hassio-zigbee2mqtt ?
