### ISSUE TITLE
device no longer working, no logs or whatever since latest hass.io version under synology

### ISSUE THREAD

**Issue by dummys** [danielwelch/hassio-zigbee2mqtt#501]
Hi, 
Since latest version of hass.io and synology my zigbee2mqtt is not working anymore. Before I was using the special version from another repositories that I can't remember from now But when trying to use this version, I got mqtt connected, I see my sensor but the state of the sensor is not updated. Is there a way to debug what is going on ? I checked inside the docker image, and my /dev/ttyACM0 for my CC2531 is there, so it should be not the problem. Anyone having same problem as me ? I'm using mosqitto server addon too.

**Comment by dummys** [comment]
I tried to use zigbee2mqtt on the computer directly and it works. I can see the pairing device. But not on synology.

**Comment by ciotlosm** [comment]
You can try looking in hassio system hardware to see how the serial port in named o your synology.
