### ISSUE TITLE
Lidl E14 'has left the network' ...for good

### ISSUE THREAD

**Issue by Fridolin34** [danielwelch/hassio-zigbee2mqtt#502]
Greetings,

I've added a new Osram Switch to my network and had to start the pairing process a couple of times. While trying to pair the new device, I've seen something like 'xyz has left the network'. I didn't pay attention, but now I see that one of my Lidl lights is no longer available. The rest of the network is just fine, but this one is missing. 
It has been registered somehow similar to "TuYa | TS0502A" (this one is the E27, which is still connected)

I've restarted the system, the light bulb, I run touchlink, I switched the light off/on like 20 times, but this E14 device seems to be gone.

What might have happend and what should I do now?

Thanks,
Fridolin

**Comment by ciotlosm** [comment]
To help with device support you should use the z2m issue repo, this is the add-on only "chrome". I can recommend you try a force remove of the device and try re-pairing after.

**Comment by Fridolin34** [comment]
Thanks for the reply. I freshly installed everything from scratch and it works. Unfortunately I've forgotten about this issue here.
