### ISSUE TITLE
zigbee2mqtt 1.17.0 released

### ISSUE THREAD

**Issue by artkrz** [danielwelch/hassio-zigbee2mqtt#506]
Are you planning to bump z2m to 1.17.0 anytime soon?

**Comment by artkrz** [comment]
https://github.com/danielwelch/hassio-zigbee2mqtt/commit/8a6aa58d003364090f2e4a2f86faec0cb6bf1479

**Comment by KRISUUUU** [comment]
I can't wait for a new release :) 

Is the edge version also being developed ? I only see the master

**Comment by artkrz** [comment]
It's out.
