### ISSUE TITLE
Upgrade to 1.17.0.1 fails - Manifest unknown

### ISSUE THREAD

**Issue by andyshilton** [danielwelch/hassio-zigbee2mqtt#508]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
Upgrading from 1.16.2.2 to 1.17.0.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

Home Assistant 2020.12.2 on Home Assistant Blue

**Description of problem:**
Attempted to upgrade via the interface and it fails, placing the following in the log:

21-01-04 13:50:06 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-aarch64:1.17.0.1 -> 404 Client Error for http+docker://localhost/v1.40/images/create?tag=1.17.0.1&fromImage=dwelch2101%2Fzigbee2mqtt-aarch64: Not Found ("manifest for dwelch2101/zigbee2mqtt-aarch64:1.17.0.1 not found: manifest unknown: manifest unknown").

Rebooted and tried again and the same error happens.

**Comment by ciotlosm** [comment]
Can you try switch to using https://github.com/zigbee2mqtt/hassio-zigbee2mqtt 1.17.0? This will become soon the official add-on. We will check what is wrong with 1.17.0.1. Usually the error specified happens when we publish the add-on and the users get notified before the build completes (workflow problem with current one). This is fixed in the new one. 

Later edit: It seems the build didn't start as I forgot to publish the tag. It should complete in around 30 minutes.

**Comment by andyshilton** [comment]
@ciotlosm  Thank you. I'll hang on as I'm not really sure how to force a version via the supervisor. It just appears and I click update usually :)

![image](https://user-images.githubusercontent.com/16556349/103545124-0a051480-4e99-11eb-963d-b1eafbb464ed.png)

**Comment by ciotlosm** [comment]
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt it's a new repo (compared to current: https://github.com/danielwelch/hassio-zigbee2mqtt/ ) As we're moving the add-on to an org and publish the images to a docker hub org. 

If you're in no rush you can also wait, the current repo will be available for some time after the migration, but in the form of configs only consuming images with the new versioning system from the new docker hub org.

You can follow the build job here: https://dev.azure.com/danielwelch2101/hassio-zigbee2mqtt/_build/results?buildId=834&view=results

Make sure to close the issue once you are happy that it works.

**Comment by andyshilton** [comment]
@ciotlosm Thanks for the info. I wasn't aware it was now available that way too. I will have to look into migrating across.

Yes, will make sure I close this issue. Thanks for your help, very much appreciated.

**Comment by andyshilton** [comment]
Build complete and I'm now upgrading successfully. Thanks 👍
