### ISSUE TITLE
Failed to start addon (1.17.0.1)

### ISSUE THREAD

**Issue by domosgabor** [danielwelch/hassio-zigbee2mqtt#509]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
Upgrading from 1.16.x to 1.17.0.1

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
Home Assistant 2020.12.1

**Description of problem:**
Failed to start addon
404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_7ad98f9c_zigbee2mqtt: Not Found ("No such image: dwelch2101/zigbee2mqtt-armv7:1.17.0.1")

I've just upgraded to the latest version, don't remember whether there was an error message or not during the upgrade but the addon failed to start. After a reboot the situation is the same, manual add-on start throws the error message above.

**Comment by frauhottelmann** [comment]
It's published. If you get the error above just do a
`docker pull dwelch2101/zigbee2mqtt-armv7:1.17.0.1` and then start the addon from the supervisor. You do need to adjust `armv7` to your platform!

**Comment by domosgabor** [comment]
Thanks, issue is solved.
