### ISSUE TITLE
Addon fails to store persistent data in host's filesystem

### ISSUE THREAD

**Issue by garethhowell** [danielwelch/hassio-zigbee2mqtt#512]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 1.17 but applies to all

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

docker supervised install on Pi3 running raspbian

**Description of problem:**
Persistent data (e.g. database.db) is stored in `/usr/share/zigbee2mqtt` but this folder is not mapped from a host folder. Most other addons store persistent data in a folder that is accessible outside of the container and is thus accessible even if the container is not running.

**Comment by ciotlosm** [comment]
You can switch to https://github.com/zigbee2mqtt/hassio-zigbee2mqtt that uses `/config` by default however you can switch where z2m stores the config from the add-on UI. it's up to you to decide where you want to store data about it.

**Comment by garethhowell** [comment]
Thanks, @ciotlosm. I'll switch over to that.
