### ISSUE TITLE
Addon does not start after restarting Raspberry

### ISSUE THREAD

**Issue by vyalekseev** [danielwelch/hassio-zigbee2mqtt#515]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
Raspberry Pi 2, Home Assiatant in Docker
TI CC2531 USB CDC

**Description of problem:**
After updating to version 1.17.0, the addon stopped starting.
If you reconnect the CC2531 stick in USB and restart the Raspberry, then the addon starts.
After the next Raspberry reboot, the addon won't start again.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: mqtt
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

```

**
2021-01-15T17:35:55: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2021-01-15T17:35:55: PM2 log: App [npm:0] starting in -fork mode-
2021-01-15T17:35:55: PM2 log: App [npm:0] online
> zigbee2mqtt@1.17.0 start /zigbee2mqtt-1.17.0
> node index.js
Zigbee2MQTT:info  2021-01-15 17:36:15: Logging to console and directory: '/share/zigbee2mqtt/log/2021-01-15.17-36-09' filename: log.txt
Zigbee2MQTT:info  2021-01-15 17:36:16: Starting Zigbee2MQTT version 1.17.0 (commit #1.17.0)
Zigbee2MQTT:info  2021-01-15 17:36:16: Starting zigbee-herdsman (0.13.46)
Zigbee2MQTT:error 2021-01-15 17:36:43: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-01-15 17:36:43: Failed to start zigbee
Zigbee2MQTT:error 2021-01-15 17:36:43: Exiting...
Zigbee2MQTT:error 2021-01-15 17:36:43: Error: SRSP - SYS - osalNvRead after 6000ms
    at Timeout._onTimeout (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.17.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.0 start script.
npm ERR!
 This is probably not a problem with npm. There is likely additional logging output above.
npm 
ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-15T14_36_43_720Z-debug.log
**

**Comment by kraen** [comment]
Got almost the same error

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
Home Assistant Supervised in Docker
TI CC2531 USB CDC

> Zigbee2MQTT:info  2021-01-16 23:29:08: Logging to console and directory: '/share/zigbee2mqtt
> /log/2021-01-16.23-29-06' filename: log.txt
> Zigbee2MQTT:info  2021-01-16 23:29:08: Starting Zigbee2MQTT version 1.17.0 (commit #1.17.0)
> Zigbee2MQTT:info  2021-01-16 23:29:08: Starting zigbee-herdsman (0.13.46)
> Zigbee2MQTT:error 2021-01-16 23:29:20: Error while starting zigbee-herdsman
> Zigbee2MQTT:error 2021-01-16 23:29:20: Failed to start zigbee
> Zigbee2MQTT:error 2021-01-16 23:29:20: Exiting...
> Zigbee2MQTT:error 2021-01-16 23:29:20: Error: AREQ - ZDO - activeEpRsp after 10000ms
>     at Timeout._onTimeout (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7)
> npm
>  ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR!
>  zigbee2mqtt@1.17.0 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the zigbee2mqtt@1.17.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-01-16T22_29_20_190Z-debug.log
> 2021-01-16T23:29:21: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
> 2021-01-16T23:29:21: PM2 log: App [npm:0] starting in -fork mode-
> 2021-01-16T23:29:21: PM2 log: App [npm:0] online

**Comment by berta24** [comment]
```
Zigbee2MQTT:debug 2021-01-20 11:38:58: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00193B3AF5-if00"}}'
Zigbee2MQTT:error 2021-01-20 11:39:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-01-20 11:39:18: Failed to start zigbee
Zigbee2MQTT:error 2021-01-20 11:39:18: Exiting...
Zigbee2MQTT:error 2021-01-20 11:39:18: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
 zigbee2mqtt@1.17.0-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.0-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-20T11_39_18_733Z-debug.log
2021-01-20T11:39:21: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2021-01-20T11:39:21: PM2 log: App [npm:0] starting in -fork mode-
2021-01-20T11:39:21: PM2 log: App [npm:0] online
> zigbee2mqtt@1.17.0-dev start /app
> node index.js
```
Same error after upgrading my HA installation, sometimes it still reads the temp but idk how if it's not even recognizing the adapter

**Comment by greyskul2005** [comment]
I have the same problem, but it has been at the root of changing to ssd, modifying EPROM and installing HA 64bits...

**Comment by vyalekseev** [comment]
@danielwelch 

what can be done? or how can you roll back to the previous version?

**Comment by zzzanuda** [comment]
Do you enable integration  Zigbee Home Automation? If yes, delete it and z2m will start with no error.

**Comment by greyskul2005** [comment]
What is the automation that you tell me?

**Comment by zzzanuda** [comment]
ZHA (Zigbee Home Automation) https://www.home-assistant.io/integrations/zha/, look at your integrations.

**Comment by greyskul2005** [comment]
Oh yeah, no, I don't have the integration "Zigbee Home Automation", just MQTT Broker, and zigbee2mqtt, and so far everything has worked fine.
The only change I have made is to boot from an SSD and change from HASSIO 32bit to 64bit

I have no idea what could happen ...

**Comment by stittel** [comment]
![2021-01-31_14-08-28](https://user-images.githubusercontent.com/63233867/106384960-fd0f0e80-63cd-11eb-9e3d-38a26a3aebf4.png)

Pi4
core-2021.1.5
supervisor-2021.01.7
Home Assistant OS 5.10

All updates version of the MQTT broker and Zigbee2MQTT are running. The same for ZHA.

**Comment by dlabanec** [comment]
Zigbee2MQTT:info  2021-01-31 22:38:51: Logging to console and directory: '/share/zigbee2mqtt/log/2021-01-31.22-38-49' filename: log.txt
Zigbee2MQTT:info  2021-01-31 22:38:51: Starting Zigbee2MQTT version 1.17.0 (commit #1.17.0)
Zigbee2MQTT:info  2021-01-31 22:38:51: Starting zigbee-herdsman (0.13.46)
Zigbee2MQTT:error 2021-01-31 22:39:03: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-01-31 22:39:03: Failed to start zigbee
Zigbee2MQTT:error 2021-01-31 22:39:03: Exiting...
Zigbee2MQTT:error 2021-01-31 22:39:03: Error: AREQ - ZDO - activeEpRsp after 10000ms
    at Timeout._onTimeout (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
 zigbee2mqtt@1.17.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm 
ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-31T21_39_03_391Z-debug.log
2021-01-31T22:39:05: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2021-01-31T22:39:05: PM2 log: App [npm:0] starting in -fork mode-
2021-01-31T22:39:05: PM2 log: App [npm:0] online
> zigbee2mqtt@1.17.0 start /zigbee2mqtt-1.17.0
> node index.js

same problem, PI4, 32bit,  CC2531 :( Stoped work today, before work well. Please help me, after five hours finding solution Im totaly lost :(

**Comment by ciotlosm** [comment]
Usually the error is not due to the add-on version, but something between the z2m app and the stick which does not respond.  Sometimes a reset works, sometimes you need to do a re-flash. Sometimes it's just a problem as someone suggested when some other process takes over the usb port.
