### ISSUE TITLE
cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory

### ISSUE THREAD

**Issue by nexustp** [danielwelch/hassio-zigbee2mqtt#516]
**zigbee2mqtt add-on version 1.17.0:**

**Operating environment Hassio on Debian GNU/Linux 10 (buster), Docker version
19.03.13**

**Description of problem:**
I have problem similar to case #246 but I try install edge version - not help

after set: zigbee_shepherd_devices: true
and put devices.js file in data_path location, add-on not start

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://xxx.xxx.xxx.xxx'
  user: xxxx
  password: xxxxx
serial:
  port: /dev/ttyACM1
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 9
    - 5
    - 7
    - 9
    - 14
    - 13
    - 15
    - 0
    - 3
    - 4
    - 7
    - 6
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_shepherd_devices: true
```

**Your logs from Home Assistant**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing...
[18:19:38] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing...
[18:19:38] INFO: MQTT available, fetching server detail ...
[18:19:38] INFO: Previous config file found, checking backup
[18:19:38] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[18:19:38] INFO: File devices.js found, copying to ./node_modules/zigbee-herdsman-converters/
cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory
[cont-init.d] zigbee2mqtt.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by ciotlosm** [comment]
I recommend switching to using https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/DOCS.md#adding-support-for-new-devices 

This version will not be supported in the add-on as it's complicated to keep devices.js in sync between version updates.

**Comment by AHH4485** [comment]
I've been struggling the same issue here, 
unfortunately the links to the dummy converter files are not working.
The reason I am trying to set up an external converter is to make the ' https://www.zigbee2mqtt.io/devices/ZB003-X.html ' working, which officially should be supported, but doesn’t work after being added to the network.

**Comment by ciotlosm** [comment]
@AHH4485 I've updated the docs on `dev`: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/dev/zigbee2mqtt/DOCS.md#adding-support-for-new-devices to fix the broken links
