### ISSUE TITLE
advanced -> legacy_api option not exposed

### ISSUE THREAD

**Issue by y0ast** [danielwelch/hassio-zigbee2mqtt#517]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.17.0.1

**Description of problem:**
```
advanced:
    legacy_api: true
```
This option was added in 1.17.0 (as the new_api became default), but is not yet exposed in the addon.

Description here: https://www.zigbee2mqtt.io/information/configuration.html

**Comment by ciotlosm** [comment]
This was now added in 1.17.1-1 and edge for https://github.com/zigbee2mqtt/hassio-zigbee2mqtt. Version 1.17.1-1 is not yet published, but it should be soon.

**Comment by y0ast** [comment]
Thanks! That’s great :)

Is this repo going to be deprecated in favor of the one you linked?

**Comment by ciotlosm** [comment]
Yes (see: https://github.com/Koenkk/zigbee2mqtt.io/pull/544). We're going to keep `danielwelch` repo as an option, but images will be taken from the z2m org and the code and fixes will go in the other repo. The advantage is that it will allow multiple admins in case someone isn't available for a period
