### ISSUE TITLE
Question: setup after add-on installation?

### ISSUE THREAD

**Issue by vinhdizzo** [danielwelch/hassio-zigbee2mqtt#518]
Hi,

I just installed this add-on as described in the README. I have a cc2531 USB stick flashed with the firmware to work with zigbee2mqtt.

After I install the add-on, so I have to edit any config file to specify my mosquito server and credentials? Or does this add-on figure all this out on HassOS? I figure I need to sort this out before attempting to add devices. Appreciate any guidance, thank you.

**Comment by ciotlosm** [comment]
@vinhdizzo if you use https://github.com/zigbee2mqtt/hassio-zigbee2mqtt (different repo) you will get mqtt auto detection. 
If you want to use this add-on, you will need to create a user in your home assistant (if you use the integrated mqtt addon) and use those credentials in the config file for the add-on (no file editing on disk, just the regular config in the UI).
