### ISSUE TITLE
zigbee_herdsman_debug option

### ISSUE THREAD

**Issue by protyposis** [danielwelch/hassio-zigbee2mqtt#519]
Hi,

I am trying to enable `zigbee_herdsman_debug` logging (v1.17.0). 

 1. Am I right in assuming that those logs are showing up in `HA` -> `Supervisor` -> `Zigbee2mqtt` -> `Log`, but not within the `Logs` view of the https://github.com/nurikk/z2m-frontend (`HA` -> `Zigbee2mqtt` -> `Logs`)? 
 2. What is the recommended way to consume these logs in "realtime" for debugging purposes, ideally a merged log of `zigbee-herdsman` and `zigbee2mqtt`? (in contrast to the `Log` view which needs to be manually refreshed via the `Refresh` button)

Also I am reading conflicting information about this flag. In https://github.com/danielwelch/hassio-zigbee2mqtt/issues/494#issuecomment-748978550 it says that this flag was removed. In https://github.com/danielwelch/hassio-zigbee2mqtt/issues/272#issuecomment-564714998 it says that the flag is called `zigbee_shepherd_debug` for historical reasons. In https://github.com/danielwelch/hassio-zigbee2mqtt/issues/272#issuecomment-564784456 someone suggests to support both (which makes sense, with deprecating the old one), but there's no linked PR/commit suggesting that this was implemented. Looking into the current config schema, both seem to be supported: https://github.com/danielwelch/hassio-zigbee2mqtt/blob/59f34467e6b1aedd0ba1c49fa6bc54fcd8146bd4/zigbee2mqtt/config.json#L75-L76. Could you please clarify?

**Comment by ciotlosm** [comment]
`zigbee_herdsman_debug` is the correct one. The other flag was not cleaned probably not to break people's config. It will probably be removed in a later release. 

I can't comment on the best way to see debug logs in real time.
