### ISSUE TITLE
Pairing Legrand 067775

### ISSUE THREAD

**Issue by stanislavmerts** [danielwelch/hassio-zigbee2mqtt#523]
Hello! I don't understand how pair Legrand 067775 with Netatmo socket. No instructions
mqtt discovery: true
permit join: true
There are no buttons on the device
Please help me!

**Comment by Giancky79** [comment]
https://docdif.fr.grpleg.com/general/MEDIAGRP/NP-FT-GT/F02486FR-00.pdf
