### ISSUE TITLE
Difference between two hassio addon repos

### ISSUE THREAD

**Issue by Erelen-Laiquendi** [danielwelch/hassio-zigbee2mqtt#526]
What is the difference between:
1) https://github.com/danielwelch/hassio-zigbee2mqtt
2) https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
?

**Comment by KRISUUUU** [comment]
The second repo will be official

https://github.com/danielwelch/hassio-zigbee2mqtt/issues/493#issuecomment-754112374

**Comment by Erelen-Laiquendi** [comment]
Thanks for link.
Second will be official, but it's not _same_ repos - content is different :)
