### ISSUE TITLE
Connection drops

### ISSUE THREAD

**Issue by xicoxicao** [danielwelch/hassio-zigbee2mqtt#527]
Hey guys.

So I'm running  on the following environment

zigbee2mqtt add-on version: 1.17.1
Operating environment: HassOS

and for the couple of days I've had my zigbee connections drop.

Looking at the log I get the follwing messages that keep repeating.

"> zigbee2mqtt@1.17.1 start /zigbee2mqtt-1.17.1
> node index.js
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            READ THIS CAREFULLY
Refusing to start because configuration is not valid, found the following errors:
- friendly_name shoud atleast be 1 char long
If you don't know how to solve this, read https://www.zigbee2mqtt.io/information/configuration.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
npm
 
ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
 zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-02T18_21_06_406Z-debug.log
2021-02-02T18:21:07: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2021-02-02T18:21:07: PM2 log: App [npm:0] starting in -fork mode-
2021-02-02T18:21:07: PM2 log: App [npm:0] online"

Initially I changed the serial port from "/dev/ttyACM0" to "/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD47DFA-if00" and it worked for a while but it dopped off overnight.

I tried looking for a device name but couldn't find it,

Pls advise

**Comment by skipper79** [comment]
Same issue here

and also others; https://community.home-assistant.io/t/zigbee2mqtt-web-ui-not-opening-502-bad-gateway/270283/17

**Comment by xicoxicao** [comment]
Hey. Solved the problem by going back to the previous version and cleaning up the config.

Updated again and it now works.
