### ISSUE TITLE
Feature - unsupported devices wizard/report tool

### ISSUE THREAD

**Issue by chrisrock1984** [danielwelch/hassio-zigbee2mqtt#528]
Hi,

I love this add-on so much and really appreciate your work!

I was wondering if it would be possible to create a reporting mechanism for unsupported but connectable devices which sends all the needed information automatically to the "new devices support request".
This would make adding new devices in a later version much easier.

Also a kind of wizard within the add-on, where a new device can be configured by using templates from similar devices would be, in my opinion a great improvement for setting up new devices.

BR,
Chris

**Comment by ciotlosm** [comment]
@Koenkk This might be a good feature, to somehow allow "auto-generate" external converters "dummy" for devices that are unsupported, and allow users to edit those files with just the minimum to get them working. 

Unsure about linking in the logs directly to the new device support issue.

**Comment by Koenkk** [comment]
@ciotlosm the converter configuration varies a lot, I think the easiest to copy a device that is very similar.

**Comment by chrisrock1984** [comment]
I am trying to add following device -> https://de.aliexpress.com/item/1005001383340876.html?spm=a2g0s.9042311.0.0.27424c4dSd7hvD

The device can be paired and it is reporting linkquality
![image](https://user-images.githubusercontent.com/22988621/112293952-fcd71500-8c92-11eb-9868-202fe866c473.png)
![image](https://user-images.githubusercontent.com/22988621/112294035-124c3f00-8c93-11eb-9267-6d5e3a056339.png)


It would be easier, as @ciotlosm mentioned, that a file is generated automatically within the share folder (I am using HASSOS) where I can add the converters myself.

At the moment, I do not know how or where to start adding this device myself as some documentation/community entries are old or not working

**Comment by ciotlosm** [comment]
Closing this issue as it didn't have much traction and there are other more pressing issue that require dev work. Feel free to start a PR or discussion on the core z2m repo: https://github.com/Koenkk/zigbee2mqtt/issues
