### ISSUE TITLE
Switching from Z-Stack 3.0.x to 1.2 returns error  "Backup is only supported for Z-Stack 3" and zigbee2mqtt doesn't start

### ISSUE THREAD

**Issue by kokuo81** [danielwelch/hassio-zigbee2mqtt#532]
zigbee2mqtt 1.17.1 Coordinator

Hassio (Raspberry Pi 3B)

I was using a CC2531 with Z-Stack 3.0.x firmware as coordinator, conneting to several devices, also using Aqara D1 switches as routers.
Since some days the connection of some devices stopped working for no specific reason.
I decided then to flash my CC2531 with the 1.2 firmware to see if things were getting better but since then, I always get the issues at starting:

Erros: Backup is only supported for Z-Stack 3

This is the log:

> zigbee2mqtt@1.17.1 start /zigbee2mqtt-1.17.1
> node index.js
Zigbee2MQTT:info  2021-02-07 14:34:18: Logging to console and directory: '/share/zigbee2mqtt/log/2021-02-07.14-34-15' filename: log.txt
Zigbee2MQTT:info  2021-02-07 14:34:18: Starting Zigbee2MQTT version 1.17.1 (commit #1.17.1)
Zigbee2MQTT:info  2021-02-07 14:34:18: Starting zigbee-herdsman (0.13.59)
Zigbee2MQTT:error 2021-02-07 14:34:20: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-07 14:34:20: Failed to start zigbee
Zigbee2MQTT:error 2021-02-07 14:34:20: Exiting...
Zigbee2MQTT:error 2021-02-07 14:34:20: Error: Backup is only supported for Z-Stack 3
    at Object.<anonymous> (/zigbee2mqtt-1.17.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/backup.js:174:19)
    at Generator.next (<anonymous>)
    at fulfilled (/zigbee2mqtt-1.17.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/backup.js:24:58)

Tried to reflash the stick, to uninstall and reinstall the Add-on, to restart Hassio, to unplug and plug back the stick, nothing changes.

Thanks!

**Comment by ciotlosm** [comment]
@Koenkk is this something we can handle in the add-on?

**Comment by Koenkk** [comment]
Can be fixed by deleting the `coordinator_backup.json` file. Not an addon issue.
