### ISSUE TITLE
friendly_name shoud atleast be 1 char long

### ISSUE THREAD

**Issue by andrey80nik** [danielwelch/hassio-zigbee2mqtt#537]
The web interface does not open: 502: Bad Gateway

There is such an error in the log;

Refusing to start because configuration is not valid, found the following errors:
- friendly_name shoud atleast be 1 char long

If you don't know how to solve this, read https://www.zigbee2mqtt.io/information/configuration.html

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-12T03_42_07_577Z-debug.log
[06:42:08] INFO: Handing over control to Zigbee2mqtt Core ...
```

Please help me understand how to fix it?
Before the update, everything worked fine

**Comment by ciotlosm** [comment]
> The web interface does not open: 502: Bad Gateway
> 

This is because the add-on is not starting

> There is such an error in the log;
> 
> Refusing to start because configuration is not valid, found the following errors:
> 
> * friendly_name shoud atleast be 1 char long

Can you post your config with the sensitive information masked out?

> 
> If you don't know how to solve this, read https://www.zigbee2mqtt.io/information/configuration.html
> 
> ```
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-02-12T03_42_07_577Z-debug.log
> [06:42:08] INFO: Handing over control to Zigbee2mqtt Core ...
> ```
> 
> Please help me understand how to fix it?
> Before the update, everything worked fine

**Comment by andrey80nik** [comment]
> Can you post your config with the sensitive information masked out?

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user:  [masked]
  password:  [masked]
serial:
  port: /dev/ttyAMA0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
 [masked]
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

**Comment by ciotlosm** [comment]
@andrey80nik maybe you have some invalid entried in `zigbee2mqtt/devices.yaml`. Can you check there?

**Comment by andrey80nik** [comment]
> @andrey80nik, может быть, у вас есть какой-то инвалид, записанный сюда `zigbee2mqtt/devices.yaml`. Вы можете проверить там?
[https://i.imgur.com/ivmptEn.png](url) there is no such file

**Comment by ciotlosm** [comment]
You can create one I guess, it would get created if you use the frontend as well. 

![Screenshot 2021-02-12 at 15 21 20](https://user-images.githubusercontent.com/7738048/107773250-09885500-6d46-11eb-8ea6-1368fb1aa6d5.png)

**Comment by andrey80nik** [comment]
the source of the problems is `data_path: /share/zigbee2mqtt`
that's right - `data_path: /config/zigbee2mqtt`

**Comment by ciotlosm** [comment]
Can this be closed?
