### ISSUE TITLE
Ignore serial: section in configuration.yaml

### ISSUE THREAD

**Issue by ae-11** [danielwelch/hassio-zigbee2mqtt#538]
Zigbee2MQTT version 1.18.1

/etc/zigbee2mqtt/configuration.yaml
```
serial:
  port: /dev/ttymxc1
  adapter: zigate
```
start - debug:
Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)

OpenWRT over Xiaomi Lumi Gateway v2 (ARMv7) with Zigate firmware for JN5169 snapshot-20210103

Why zigbee2mqtt attempt connect to undeclared /dev/ttyACM0?

**Comment by ciotlosm** [comment]
Are you sure you are using the add-on? By your path (/etc/zigbee2mqtt/configuration.yaml) looks like you are using something else. The add-on (depending on the version) usually uses /share/zigbee2mqtt/configuration.yaml or /config/zigbee2mqtt/configuration.yaml

**Comment by ae-11** [comment]
> Are you sure you are using the add-on? By your path (/etc/zigbee2mqtt/configuration.yaml) looks like you are using something else. The add-on (depending on the version) usually uses /share/zigbee2mqtt/configuration.yaml or /config/zigbee2mqtt/configuration.yaml

Yes I'm sure because OpenWRT put default configuration file to /etc/zigbee2mqtt path. And OpeWRT on Lumi have not /config and /share path. Also in env ZIGBEE2MQTT_DATA=/etc/zigbee2mqtt/ set this path (it's from /etc/init.d/ziigbee2mqtt)...

**Comment by ciotlosm** [comment]
You might be using the raw container not the home assistant add-on. The Home Assistant add-on only runs on Home Assistant Supervisor

**Comment by ae-11** [comment]
> You might be using the raw container not the home assistant add-on. The Home Assistant add-on only runs on Home Assistant Supervisor

Sorry I made a wrong thread with my question. This question for zigbee2mqtt node for OpenWRT.
