### ISSUE TITLE
Not working the QBKG03LM Xiaomi wall switch double key switching

### ISSUE THREAD

**Issue by itanczos** [danielwelch/hassio-zigbee2mqtt#57]
Error log:
Cannot handle MQTT message with topic 'zigbee2mqtt/0x00158d00014a5ab2/left/set' and message 'ON'

**Comment by zen** [comment]
Where is this entry from?

**Comment by ciotlosm** [comment]
@itanczos This probably not related to the addon. Looks like the mqtt client had issues processing the message. As @zen mentioned, it would help to understand where the message was from.

**Comment by itanczos** [comment]
The bug was terminated after a zigbee2mqtt (v.0.1.6) version upgrade.
