### ISSUE TITLE
Addon reports wrong running srtate

### ISSUE THREAD

**Issue by zen** [danielwelch/hassio-zigbee2mqtt#58]
Hi,

Addon didn't start properly due to port changed:
"[Info] Configuration file found. Will overwrite configurable               fields with values from add-on configuration
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
[2018-09-29T19:48:02.905Z] PM2 log: Launching in no daemon mode
[2018-09-29T19:48:04.916Z] PM2 log: Starting execution sequence in -fork mode- for app name:npm id:0
[2018-09-29T19:48:05.274Z] PM2 log: App name:npm id:0 online
> zigbee2mqtt@0.1.6 start /zigbee2mqtt-0.1.6
> node index.js
  zigbee2mqtt:info 2018-9-29 19:48:42 Logging to directory: '/share/zigbee2mqtt/log/2018-09-29.19-48-41'
  zigbee2mqtt:info 2018-9-29 19:48:58 Starting zigbee2mqtt version 0.1.6 (commit #unknown)
  zigbee2mqtt:info 2018-9-29 19:48:58 Starting zigbee-shepherd
  zigbee2mqtt:info 2018-9-29 19:48:59 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
  zigbee2mqtt:info 2018-9-29 19:49:59 Starting zigbee-shepherd
  zigbee2mqtt:error 2018-9-29 19:49:59 Error while starting zigbee-shepherd!
  zigbee2mqtt:error 2018-9-29 19:49:59 Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 2018-9-29 19:49:59 Failed to start
	{"message":"Error: No such file or directory, cannot open /dev/ttyACM0","stack":"Error: Error: No such file or directory, cannot open /dev/ttyACM0"}"

But reports state "running"

**Comment by danielwelch** [comment]
Just curious, does “incorrect state” have any practical importance to you?
