### ISSUE TITLE
feature request: led control via services?

### ISSUE THREAD

**Issue by pejotigrek** [danielwelch/hassio-zigbee2mqtt#59]
we can turn off led via configuration - but what if we could turn on/off led via services also? it would be neat to have an automation which would turn on the led during pairing timer, and then turn off the led after timer finishes (and pairing mode is off).

**Comment by emouawad** [comment]
i agree - that would be useful.
Is that possible? 
thanks

**Comment by danielwelch** [comment]
I think the best way to implement this would be for zigbee2mqtt to make this configurable via MQTT (like permit_join and some other aspects of the configuration). Right now, I don't see that this is an option in the docs.

**Comment by pejotigrek** [comment]
MQTT implementation sounds good too - as long as we will be able to turn on/off led "on the fly", I'm good with everything ;)

**Comment by emouawad** [comment]
#https://github.com/Koenkk/zigbee2mqtt/issues/1442

**Comment by ciotlosm** [comment]
Considering there is no support for this for some time, I don't think this will get implemented soon. Also with the `boom` of possible [adapters](https://www.zigbee2mqtt.io/information/supported_adapters.html#supported-adapters) I don't think `led` is generic enough to get support anymore.
