### ISSUE TITLE
"Error: Resource busy, cannot open /dev/ttyACM0"

### ISSUE THREAD

**Issue by RonnyAL** [danielwelch/hassio-zigbee2mqtt#61]
When I initially set up and configured everything (using a CC2531 stick and the [latest firmware](https://github.com/Koenkk/Z-Stack-firmware/blob/fe965489f516ffc5c9c09f61dd869b8abca043e5/coordinator/CC2531/bin/CC2531ZNP-Prod.hex) as per today), I couldn't get things working using the zigbee2mqtt component. I got the one minute wait in the log and then a message about having to press the reset button. So I installed the zigbee2mqtt-edge version and it worked fine. Today things started acting up again. zigbee-sheperd was apparantly not running, and the log was full of messages about it. So I stopped the zigbee2mqtt-edge component and installed the now updated "regular" component. It too doesn't work for me now. This is what my log shows:

```
[Info] Configuration file found. Will overwrite configurable               fields with values from add-on configuration
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
[2018-10-03T17:38:00.452Z] PM2 log: Launching in no daemon mode
[2018-10-03T17:38:00.879Z] PM2 log: Starting execution sequence in -fork mode- for app name:npm id:0
[2018-10-03T17:38:00.918Z] PM2 log: App name:npm id:0 online
> zigbee2mqtt@0.1.6 start /zigbee2mqtt-0.1.6
> node index.js
  zigbee2mqtt:info 2018-10-3 17:38:04 Logging to directory: '/share/zigbee2mqtt/log/2018-10-03.17-38-04'
  zigbee2mqtt:info 2018-10-3 17:38:05 Starting zigbee2mqtt version 0.1.6 (commit #unknown)
  zigbee2mqtt:info 2018-10-3 17:38:05 Starting zigbee-shepherd
  zigbee2mqtt:info 2018-10-3 17:38:05 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
  zigbee2mqtt:info 2018-10-3 17:39:06 Starting zigbee-shepherd
  zigbee2mqtt:error 2018-10-3 17:39:06 Error while starting zigbee-shepherd!
  zigbee2mqtt:error 2018-10-3 17:39:06 Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 2018-10-3 17:39:06 Failed to start
	{"message":"Error: Resource busy, cannot open /dev/ttyACM0","stack":"Error: Error: Resource busy, cannot open /dev/ttyACM0"}
```

Thanks for reading.

**Edit:** After messing around with unplugging and replugging the stick, pressing the reset button - I ended up with an error saying there's no file or folder at /dev/ttyACM0. Noticed under Hass.io > Hardware that it had changed to /dev/ttyACM1, and changed the configuration accordingly. After that it started working again. After a later reboot it had changed back to ACM0 and I had to reconfigure, but things are still working.

Leaving the issue up in case you want to take a look at the error I initially had anyway!

**Comment by danielwelch** [comment]
For a related discussion, see https://github.com/danielwelch/hassio-zigbee2mqtt/issues/48

This unpredictability is a known problem and something I hope to solve soon.

**Comment by RonnyAL** [comment]
> For a related discussion, see #48
> 
> This unpredictability is a known problem and something I hope to solve soon.

Thanks for the link. Keep up the good work! :)
