### ISSUE TITLE
Xiaomi cube not working in hassio addon

### ISSUE THREAD

**Issue by lettore** [danielwelch/hassio-zigbee2mqtt#62]
I switched from Hassbian to Hassos and found that the Xiaomi Cube MFKZQ01LM that before worked now is not recognized.
This is the log:
```
 zigbee2mqtt:info 2018-10-3 23:12:40 Device incoming...
  zigbee2mqtt:info 2018-10-3 23:12:40 MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"pairing","message":"device incoming"}'
  zigbee2mqtt:warn 2018-10-3 23:13:27 Device with modelID '0x656275635f726f736e65732e696d756c' is not supported.
  zigbee2mqtt:warn 2018-10-3 23:13:27 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
```

**Comment by frostworx** [comment]
I recently installed hassio-zigbee2mqtt in a rpi3 docker, received my cube yesterday and can confirm this issue.

**Comment by ciotlosm** [comment]
If the cube previously worked and now it's not it's a version issue and probably a decoding bug. It should be reported here: https://github.com/Koenkk/zigbee2mqtt/issues

**Comment by frostworx** [comment]
looks like upstream bug is here:
https://github.com/Koenkk/zigbee2mqtt/issues/388

**Comment by frostworx** [comment]
thanks, lv-88! I can confirm as well that it works now with an up2date installation, after having removed the old entry from the database as described here: https://github.com/Koenkk/zigbee2mqtt/issues/388#issuecomment-430579690
