### ISSUE TITLE
when are commits received in edge addon

### ISSUE THREAD

**Issue by celeroll** [danielwelch/hassio-zigbee2mqtt#63]
I have a new device which is not supported in the "stable" version.
I saw that yesterday there was a merge commit about the support for this device [Commit for WXKG11LM](https://github.com/Koenkk/zigbee-shepherd-converters/pull/89).
When will this commit be inclueded in "edge" and when in "stable" version?

**Comment by danielwelch** [comment]
It will be included in stable when there is a new release of zigbee2mqtt, and the add-on is updated to reflect that.

The edge version, on the other hand, is updated automatically with new commits to the zigbee2mqtt dev branch. So it may already be available. You can check the add-on docker hub page to see when the most recent edge image was pushed.

**Comment by celeroll** [comment]
Sorry, I'm not aware of where to check "docker hub page".
So in this particulare case mentioned above, is it in the edge available or not?

**Comment by danielwelch** [comment]
https://hub.docker.com/r/dwelch2101/zigbee2mqtt-armhf/

I’ll try to add a link to the README.

The docker image was last updated 20 hours ago. Looks like the commit you linked was merged 22 hours ago. So yes, I assume it’s included.

**Comment by celeroll** [comment]
Unfortunatelly it is not included. 
I have uninstalled, removed repo and tried again, but no success. 
I even managed to edit the files in the docker image according the merged issue and it worked fine, until hass.io was restarted. 
So any suggestions for a solution?

**Comment by danielwelch** [comment]
I see the issue. The commit you linked to is in zigbee-shepherd-converters, not zigbee2mqtt. My bad. 

So the answer to your question is: whenever the dev branch’s zigbee-shepherd-converters dependency is updated to include a version that includes that commit. I’m less familiar with that release process, but a quick look shows the dev branch uses version 4.0.2, which was released 9 days ago according to npm.
