### ISSUE TITLE
Hassio error: zigbee2mqtt not supported on aarch64

### ISSUE THREAD

**Issue by Stephan296** [danielwelch/hassio-zigbee2mqtt#64]
I get the error in hassio when i want to install this addon on a Odroid C2: 7ad98f9c_zigbee2mqtt not supported on aarch64.
Earlier this month i could succesfully install this add-on.

**Comment by emouawad** [comment]
So Did u get working no problems?
Interested in knowing if it works - i am on OrangePi Win+ but same architecture as the Odroid
