### ISSUE TITLE
cache_state not working in 0.1.7 edge build ?

### ISSUE THREAD

**Issue by davidsig** [danielwelch/hassio-zigbee2mqtt#68]
I switched to the edge build for new device compatibility but then my sensors stopped working correctly.
I have xaomi tem/hum/press sensors and they only show the latest state reported:
so when zigbee2mqtt log shows:
MQTT publish, topic: 'zigbee2mqtt/0x00158d000534207653, payload: '{"temperature":20.19,"linkquality":44,"humidity":40.31}' 
Only the temp and humidity are displayed in home assistant and pressure would be empty

**Comment by davidsig** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/485 seems to be a bug in the orginal branch

**Comment by KaiboshOz** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/468#issuecomment-430886343 
Looks like it's been fixed in dev branch so should be in the edge build soon (if not already)

**Comment by mario-g0** [comment]
when will the fix be released for the stable version?

**Comment by mario-g0** [comment]
any news?
