### ISSUE TITLE
battery level and voltage on RTCGQ01LM

### ISSUE THREAD

**Issue by ghiglie** [danielwelch/hassio-zigbee2mqtt#69]
Hi there! I'm using a template to manage battery stats. I've just found that on Aqara and Mija motion / human body sensors I have this data on illumination sensor card, and only on that - so the ones that haven't it, they can't show. Hope I explained well myself.

Marco

**Comment by danielwelch** [comment]
This belongs in the [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt) issue tracker.

**Comment by ghiglie** [comment]
Oh, sorry! Thanks for your reply, always a bad idea opening issues at 2am :(
Thanks again for your great work!
