### ISSUE TITLE
Addon turns off after some time

### ISSUE THREAD

**Issue by naitsimp** [danielwelch/hassio-zigbee2mqtt#70]
Hi,

I have installed the zigbee2mqtt Addon to my Hassio.
It starts  and runs normal but after a while it just turns off and stops working.
This is the last entry of the Log:
`./run.sh: line 25:    11 Segmentation fault      (core dumped) ZIGBEE2MQTT_DATA="$DATA_PATH" pm2-runtime start npm -- start`
Can someone help?

Thank you

**Comment by danielwelch** [comment]
Sorry about the error. Could you provide some more information? Perhaps your add-on config and your device for starters. Is it consistently reproduced?

**Comment by danielwelch** [comment]
I wonder if running on a 1 is to blame. Would be interesting to see your system resources utilization when this is happening. I’ve seen reports of problems running Hassio on a raspberry pi 1 on the forums, unrelated to this.

**Comment by naitsimp** [comment]
It might be my pi 1.
Since I posted here I haven't had a stop of the addon, might be because I uninstalled the motionEye addon, I also restarted the whole system very often, because I worked on my configuration and I might be not enough time to stop. I had to reinstall my Hassio setup as well. I will keep you updated.

How would I get my system resources utilization?

**Comment by danielwelch** [comment]
The easiest way to do this from directly within home assistant is probably the system monitor component: https://github.com/danielwelch/hassio-zigbee2mqtt/issues/70#issuecomment-439031742

There are other ways as well from the command line, a quick google should help.

**Comment by danielwelch** [comment]
The easiest way to do this from directly within home assistant is probably the system monitor component: https://www.home-assistant.io/components/sensor.systemmonitor/

There are other ways as well from the command line, a quick google should help.

**Comment by naitsimp** [comment]
I already have memory_use_percent and processor_use as a sensor. Are these enough ?

**Comment by naitsimp** [comment]
It still happens.
The log, shows me a new error.
`Zigbee2mqtt requires node version >=8.11 10, you are running v8.11.4!`

Might this be the reason?

Does the addon need a certain amount of free disk space to work properly?

Might it help if I reflash the CC2531 with the current version? 
I am running on `Coordinator firmware version: '20180815'`

**Comment by danielwelch** [comment]
What does your memory use look like when it’s happening? 

Nah, I don’t think that’s to blame.

Yes it needs “some” amount of disk space, but that also shouldn’t be the problem since you’re pulling the image and initiating without a problem. 

Your question on re-flashing could be better answered in the zigbee2mqtt repo.

**Comment by naitsimp** [comment]
My Pi's CPU is running at around 40-70% at all times, there are some 100% spikes.
When the addon turns on, the CPU goes like that: at turn off the CPU is around 80-90%, the next couple of seconds after that it is at 90-100%.

For the moment I wrote an automation which starts the addon when the mqtt message "offline" gets published. With this I am only without the addon for around a minute.

**Comment by naitsimp** [comment]
After upgrading my system to a RPi3B+ and a faster SD card the Addon doesn't turn off anymore.

**Comment by marinoraffaele** [comment]
Hi,
I have installed the zigbee2mqtt Addon to my Hassio version 1.2.1 and Mosquitto broker (4.1) all working for some time.
It starts and runs normal but after a while it just turns off and stops working.

Here is my my configuration.yaml:


advanced:
  log_level: debug
devices:
  '0x00158d00027ac1f2':
    friendly_name: '0x00158d00027ac1f2'
    retain: false
  '0x00158d0002b5fa1a':
    friendly_name: '0x00158d0002b5fa1a'
    retain: false
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  password: password
  server: mqtt://my_ip:1883
  user: username
permit_join: false
serial:
  port: /dev/ttyACM0

This is my log I get:

zigbee2mqtt:debug 3/12/2019, 6:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 6:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 6:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 6:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:00:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:05:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:10:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:15:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:20:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:25:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:30:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:35:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 7:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:00:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:05:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:10:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:15:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:20:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:22:00 AM Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"65281":{"1":2955,"3":23,"4":5032,"5":31,"6":[0,1],"8":516,"10":0,"100":0}}}' of device 'lumi.sensor_wleak.aq1' (0x00158d00027ac1f2)
  zigbee2mqtt:info 3/12/2019, 8:22:00 AM MQTT publish: topic 'zigbee2mqtt/0x00158d00027ac1f2', payload '{"water_leak":false,"linkquality":70,"battery":74,"voltage":2955}'
  zigbee2mqtt:debug 3/12/2019, 8:22:00 AM Received zigbee message of type 'devChange' with data '{"cid":"genBasic","data":{"65281":[null,2955,null,23,5032,31,[0,1],null,516,null,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0]}}' of device 'lumi.sensor_wleak.aq1' (0x00158d00027ac1f2)
  zigbee2mqtt:debug 3/12/2019, 8:25:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:30:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:35:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 8:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:00:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:05:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:10:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:15:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:20:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:25:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:30:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:35:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 9:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:00:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:05:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:10:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:15:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:20:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:25:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:30:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:35:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:40:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:45:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:50:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 10:55:25 AM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 3/12/2019, 11:00:25 AM Saving state to file /share/zigbee2mqtt/state.json


can someone help me?
