### ISSUE TITLE
can't access /dev/tty*

### ISSUE THREAD

**Issue by kiwijunglist** [danielwelch/hassio-zigbee2mqtt#72]
zigbee2mqtt for hass.io gives the following error:

  zigbee2mqtt:error 2018-12-4 12:53:16 Failed to start
	{"message":"Error: No such file or directory, cannot open ../../ttyACM0","stack":"Error: Error: No such file or directory, cannot open ../../ttyACM0"}

I get a similar error with /dev/ttyACM0 etc...

I have intel NUC running ubuntu running hass.io in a docker
If I ssh into hass.io I can see that hass.io can't access /dev/tty*
If i ssh into ubuntu I can access /dev/tty*

**Comment by danielwelch** [comment]
sounds like a problem mapping dev into Hassio, the add-on, or into the ssh service container. I have no experience running Hassio as a docker container (or, I guess, series of containers) on another OS.

**Comment by kiwijunglist** [comment]
this is no longer an issue for me because
a) i'm now using docker rather than hass.io
b) i'm using a server rather than a nuc.
