### ISSUE TITLE
Prevent automatic sensor publishing

### ISSUE THREAD

**Issue by virhonestum** [danielwelch/hassio-zigbee2mqtt#73]
Hey,

currently whenever my aquara switch has connected, an MQTT message is published setting the device up as a sensor:
```
zigbee2mqtt:info 2018-12-7 00:50:05 MQTT publish, topic: 'homeassistant/sensor/0x001a8f0012b60d2f/click/config', payload: '{"icon":"mdi:toggle-switch","value_template":"{{ value_json.click }}","json_attributes":["linkquality","battery","voltage","action","duration"],"force_update":true,"state_topic":"zigbee2mqtt/wall_switch","availability_topic":"zigbee2mqtt/bridge/state","name":"wall_switch"}'
```
Could there be a way to prevent that, so that I can add a sensor manually via the configuration.yaml if needed, and not have it show up automatically?

Thanks

**Comment by danielwelch** [comment]
This is a zigbee2mqtt question and belongs in the zigbee2mqtt repository.
