### ISSUE TITLE
Timeout on Allow to Join

### ISSUE THREAD

**Issue by matisaul** [danielwelch/hassio-zigbee2mqtt#74]
Hi all, 

This is my first time configuring a zigbee device.
I bought a Zigbee CC2531 Sniffer from [Aliexpress](https://www.aliexpress.com/item/diymore-Wireless-Zigbee-CC2531-Sniffer-Bare-Board-Packet-Protocol-Analyzer-Module-USB-Interface-Dongle-Capture-Packet/32855873520.html?spm=2114.13010708.0.0.7f2e4c4d3E2UB9), and installed the custom firmware from [Koenkk Wiki](https://github.com/Koenkk/zigbee2mqtt/wiki/Getting-started).

The addon connect to MQTT broker without problem, but I get this error when I tried to allow new devices to join:

```
zigbee2mqtt:info 2018-12-13 12:13:04 Logging to directory: '/share/zigbee2mqtt/log/2018-12-13.12-13-03'
  zigbee2mqtt:info 2018-12-13 12:13:08 Starting zigbee2mqtt version 0.2.0 (commit #unknown)
  zigbee2mqtt:info 2018-12-13 12:13:08 Starting zigbee-shepherd
  zigbee2mqtt:info 2018-12-13 12:13:10 zigbee-shepherd started
  zigbee2mqtt:info 2018-12-13 12:13:10 Coordinator firmware version: '20180815'
  zigbee2mqtt:info 2018-12-13 12:13:10 Currently 0 devices are joined:
  zigbee2mqtt:info 2018-12-13 12:13:10 Zigbee: disabling joining new devices.
  zigbee2mqtt:info 2018-12-13 12:13:10 Connecting to MQTT server at mqtt://192.168.0.11:1883
  zigbee2mqtt:info 2018-12-13 12:13:10 zigbee-shepherd ready
  zigbee2mqtt:info 2018-12-13 12:13:10 Connected to MQTT server
  zigbee2mqtt:info 2018-12-13 12:13:10 MQTT publish, topic: 'zigbee2mqtt/bridge/state', payload: 'online'
  zigbee2mqtt:info 2018-12-13 12:22:33 Zigbee: allowing new devices to join.
  zigbee2mqtt:info 2018-12-13 12:22:36 
	{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/zigbee2mqtt-0.2.0/node_modules/cc-znp/lib/ccznp.js:255:22)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at CcZnp.emit (events.js:211:7)\n    at Timeout.<anonymous> (/zigbee2mqtt-0.2.0/node_modules/cc-znp/lib/ccznp.js:234:18)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"}
  zigbee2mqtt:info 2018-12-13 12:32:34 Zigbee: disabling joining new devices.
  zigbee2mqtt:info 2018-12-13 12:32:34 Zigbee: disabling joining new devices.
  zigbee2mqtt:info 2018-12-13 12:32:37 
	{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/zigbee2mqtt-0.2.0/node_modules/cc-znp/lib/ccznp.js:255:22)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at CcZnp.emit (events.js:211:7)\n    at Timeout.<anonymous> (/zigbee2mqtt-0.2.0/node_modules/cc-znp/lib/ccznp.js:234:18)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"}
  zigbee2mqtt:info 2018-12-13 12:32:40 
	{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/zigbee2mqtt-0.2.0/node_modules/cc-znp/lib/ccznp.js:255:22)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at CcZnp.emit (events.js:211:7)\n    at Timeout.<anonymous> (/zigbee2mqtt-0.2.0/node_modules/cc-znp/lib/ccznp.js:234:18)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"}
```

My addon config is:

```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.X.X:1883",
  "serial_port": "/dev/ttyACM0"
}


```

Anyone with the same problem?

Thanks in advance

**Comment by janssi** [comment]
The same problem here 
`[Info] Configuration file found. Will overwrite configurable               fields with values from add-on configuration
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
2019-01-19T15:13:31: PM2 log: Launching in no daemon mode
2019-01-19T15:13:31: PM2 log: App [npm:0] starting in -fork mode-
2019-01-19T15:13:32: PM2 log: App [npm:0] online
> zigbee2mqtt@1.0.1 start /zigbee2mqtt-1.0.1
> node index.js
  zigbee2mqtt:info 2019-1-19 15:13:46 Logging to directory: '/share/zigbee2mqtt/log/2019-01-19.15-13-45'
  zigbee2mqtt:info 2019-1-19 15:14:00 Starting zigbee2mqtt version 1.0.1 (commit #unknown)
  zigbee2mqtt:info 2019-1-19 15:14:00 Starting zigbee-shepherd
  zigbee2mqtt:info 2019-1-19 15:14:04 zigbee-shepherd started
  zigbee2mqtt:info 2019-1-19 15:14:04 Coordinator firmware version: '20181024'
  zigbee2mqtt:info 2019-1-19 15:14:04 Currently 0 devices are joined:
  zigbee2mqtt:info 2019-1-19 15:14:04 Zigbee: disabling joining new devices.
  zigbee2mqtt:info 2019-1-19 15:14:04 Connecting to MQTT server at mqtt://192.168.8.108:1883
  zigbee2mqtt:info 2019-1-19 15:14:04 zigbee-shepherd ready
  zigbee2mqtt:info 2019-1-19 15:14:04 Connected to MQTT server
  zigbee2mqtt:info 2019-1-19 15:14:04 MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
  zigbee2mqtt:info 2019-1-19 16:06:48 Zigbee: allowing new devices to join.
  zigbee2mqtt:info 2019-1-19 16:06:51 
	{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/zigbee2mqtt-1.0.1/node_modules/cc-znp/lib/ccznp.js:255:22)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at CcZnp.emit (events.js:211:7)\n    at Timeout.<anonymous> (/zigbee2mqtt-1.0.1/node_modules/cc-znp/lib/ccznp.js:234:18)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"}
  zigbee2mqtt:info 2019-1-19 16:06:51 MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":true}'`

Hassio app settings 
`{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.xxx.xxx:1883",
  "serial_port": "/dev/ttyACM0"
}`

Config file
`homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  password: xxxx
  server: mqtt://192.168.xxx.xxx:1883
  user: xxxx
permit_join: false
serial:
  port: /dev/ttyACM0
`

Any ideas?

**Comment by matisaul** [comment]
@janssi I think I figured out what was the problem. It seems there are troubles with ResinOS (I had a Hassio on a Intel NUC Pc). I installed Hasssio over Ubuntu + Docker, and now It's working perfect.

**Comment by marinoraffaele** [comment]
I also have the same problem Error: request timeout n at CcZnp

zigbee2mqtt:error 3/18/2019, 9:37:49 PM Exiting...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm 
ERR! zigbee2mqtt@1.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-18T20_37_49_411Z-debug.log
2019-03-18T21:37:52: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-03-18T21:37:52: PM2 log: App [npm:0] starting in -fork mode-
2019-03-18T21:37:52: PM2 log: App [npm:0] online
> zigbee2mqtt@1.2.1 start /zigbee2mqtt-1.2.1
> node index.js
  zigbee2mqtt:info 3/18/2019, 9:37:55 PM Logging to directory: '/share/zigbee2mqtt/log/2019-03-18.21-37-55'
  zigbee2mqtt:info 3/18/2019, 9:37:57 PM Starting zigbee2mqtt version 1.2.1 (commit #unknown)
  zigbee2mqtt:info 3/18/2019, 9:37:57 PM Starting zigbee-shepherd
  zigbee2mqtt:info 3/18/2019, 9:37:58 PM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds)
  zigbee2mqtt:info 3/18/2019, 9:38:58 PM Starting zigbee-shepherd
  zigbee2mqtt:error 3/18/2019, 9:39:00 PM Error while starting zigbee-shepherd!
  zigbee2mqtt:error 3/18/2019, 9:39:00 PM Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 3/18/2019, 9:39:00 PM Failed to start
	{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/zigbee2mqtt-1.2.1/node_modules/cc-znp/lib/ccznp.js:261:22)\n    at Object.onceWrapper (events.js:273:13)\n    at CcZnp.emit (events.js:182:13)\n    at Timeout.<anonymous> (/zigbee2mqtt-1.2.1/node_modules/cc-znp/lib/ccznp.js:240:18)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
  zigbee2mqtt:error 3/18/2019, 9:39:00 PM Exiting...
npm
 ERR! code ELIFECYCLE
npm ERR!
 errno 1
npm ERR!
 zigbee2mqtt@1.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.2.1 start script.
npm
 ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!
     /root/.npm/_logs/2019-03-18T20_39_00_296Z-debug.log
2019-03-18T21:39:03: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-03-18T21:39:03: PM2 log: App [npm:0] starting in -fork mode-
2019-03-18T21:39:03: PM2 log: App [npm:0] online
> zigbee2mqtt@1.2.1 start /zigbee2mqtt-1.2.1
> node index.js
  zigbee2mqtt:info 3/18/2019, 9:39:06 PM Logging to directory: '/share/zigbee2mqtt/log/2019-03-18.21-39-06'
  zigbee2mqtt:info 3/18/2019, 9:39:07 PM Starting zigbee2mqtt version 1.2.1 (commit #unknown)
  zigbee2mqtt:info 3/18/2019, 9:39:07 PM Starting zigbee-shepherd
  zigbee2mqtt:info 3/18/2019, 9:39:09 PM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds)

Anyone with the same problem?

**Comment by alex1712** [comment]
Is there any news on this issue?
