### ISSUE TITLE
"platform": "mqtt_json" is deprecated, replace with "schema":"json" 

### ISSUE THREAD

**Issue by trwolff04** [danielwelch/hassio-zigbee2mqtt#78]
Seeing this error under my hassio log pretty frequently.  Posted under the main zigbee2mqtt  and they've already addressed the issue.  Can you fix this for hassio?

**Comment by danielwelch** [comment]
Just released v1.0.1, should be available after it's done building. I'll close this for now as it should be solved by the update but feel free to reopen.
