### ISSUE TITLE
TypeError: Cannot read property 'port' of undefined

### ISSUE THREAD

**Issue by nightcat91** [danielwelch/hassio-zigbee2mqtt#79]
Hi,

today I installed the zigbee2mqtt hassio addon but I am not able to successfully start it or use it.
Here is my addon config:

```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://localhost:1883",
  "serial_port": "/dev/ttyACM0",
  "log_level": "debug",
  "mqtt_user": "zigbee2mqtt",
  "mqtt_pass": "zigbee2mqttpass"
}
```

I also tried the default config, and I confirmed that my flashed CC2531 USB stick is connected to /dev/ttyACM0 according to the System Hardware page from hassio.

I am running hassio on a RPi 3b with hassio v. 0.84.6 and HassOS 1.13
Using the official hassio addon Mosquitto broker v.2.0 (update to v.4 not yet done)
zigbee2mqtt addon is v.1.0.1

I think this is the core part of the error message:
`TypeError: Cannot read property 'port' of undefined`
Full error message at the bottom

Furthermore I tried to play around with the mqtt_server setting. 
I tried the following things for the mqtt server, because of the error message I thought it had something to do with the port of the mqtt server or its adress... (but I think it actually has nothing to do with the mqtt server)
mqtt://hassio
mqtt://hassio:1883
mqtt://homeassistant
mqtt://homeassistant:1883
mqtt://192.168.10.150
mqtt://192.168.10.150:1883
mqtt://localhost
mqtt://localhost:1883

After some reading on other issues I found out that the "port" is talking about the serial port of the device...

Here is the full error message after I start the addon, it repeats itsself about every 5-10 seconds as it seems the addon is restarting all the time because of the error.

```
[Info] Configuration file found. Will overwrite configurable               fields with values from add-on configuration
Traceback (most recent call last):
  File "set_config.py", line 110, in <module>
    main(args.options_path, args.data_path)
  File "set_config.py", line 68, in main
    cfg.set_option('homeassistant')
  File "set_config.py", line 26, in set_option
    self.config[option_name] = self.options[option_name]
TypeError: 'NoneType' object does not support item assignment
2018-12-23T04:02:25: PM2 log: Launching in no daemon mode
2018-12-23T04:02:26: PM2 log: App [npm:0] starting in -fork mode-
2018-12-23T04:02:26: PM2 log: App [npm:0] online
> zigbee2mqtt@1.0.1 start /zigbee2mqtt-1.0.1
> node index.js
  zigbee2mqtt:info 2018-12-23 04:03:19 Logging to directory: '/share/zigbee2mqtt/log/2018-12-23.04-03-19'
  zigbee2mqtt:info 2018-12-23 04:03:21 Starting zigbee2mqtt version 1.0.1 (commit #unknown)
  zigbee2mqtt:info 2018-12-23 04:03:21 Starting zigbee-shepherd
/zigbee2mqtt-1.0.1/lib/zigbee.js:34
        this.shepherd = new ZShepherd(settings.get().serial.port, shepherdSettings);
                                                           ^
TypeError: Cannot read property 'port' of undefined
    at Zigbee.start (/zigbee2mqtt-1.0.1/lib/zigbee.js:34:60)
    at startupLogVersion (/zigbee2mqtt-1.0.1/lib/controller.js:132:25)
    at git.getLastCommit (/zigbee2mqtt-1.0.1/lib/controller.js:172:13)
    at /zigbee2mqtt-1.0.1/node_modules/git-last-commit/source/index.js:44:5
    at /zigbee2mqtt-1.0.1/node_modules/git-last-commit/source/index.js:14:4
    at ChildProcess.exithandler (child_process.js:283:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-23T03_03_36_585Z-debug.log
2018-12-23T04:03:36: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2018-12-23T04:03:36: PM2 log: App [npm:0] starting in -fork mode-
2018-12-23T04:03:36: PM2 log: App [npm:0] online
> zigbee2mqtt@1.0.1 start /zigbee2mqtt-1.0.1
> node index.js
  zigbee2mqtt:info 2018-12-23 04:03:40 Logging to directory: '/share/zigbee2mqtt/log/2018-12-23.04-03-40'
  zigbee2mqtt:info 2018-12-23 04:03:41 Starting zigbee2mqtt version 1.0.1 (commit #unknown)
  zigbee2mqtt:info 2018-12-23 04:03:41 Starting zigbee-shepherd
```

**Comment by nightcat91** [comment]
Any ideas?

**Comment by nightcat91** [comment]
![image](https://user-images.githubusercontent.com/31433650/50714857-bcbbf580-107a-11e9-95ba-6aeb72c9c613.png)
yes

**Comment by Iv4nS** [comment]
That was silly of me to ask that. I re-read your first post and noticed you mentioned checking that. Can you paste the contents of the file /share/zigbee2mqtt/configuration.yaml here?

**Comment by nightcat91** [comment]
The file is empty

and in the log folders there are a bunch of logs, some are empty and the others only show this:
```
2019-1-4 23:14:53 - info: Logging to directory: '/share/zigbee2mqtt/log/2019-01-04.23-14-53'
2019-1-4 23:14:55 - info: Starting zigbee2mqtt version 1.0.1 (commit #unknown)
```

**Comment by Iv4nS** [comment]
That file should not be empty. Delete that file and re install the add-on and see if it remains empty after pressing Start.

**Comment by nightcat91** [comment]
Now it seems to be all fixed... strange, I did a reinstall about 3 times last week...

Now this is inside the file:

> homeassistant: true
> mqtt:
>   base_topic: zigbee2mqtt
>   password: zigbee2mqttpass
>   server: mqtt://homeassistant
>   user: zigbee2mqtt
> permit_join: false
> serial:
>   port: /dev/ttyACM0
> 

dont worry about the mqtt user and pass, those are just for testing...

Now  the whole addon is running:

> [Info] Configuration file found. Will overwrite configurable               fields with values from add-on configuration
> [Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
> 2019-01-05T00:16:04: PM2 log: Launching in no daemon mode
> 2019-01-05T00:16:04: PM2 log: App [npm:0] starting in -fork mode-
> 2019-01-05T00:16:04: PM2 log: App [npm:0] online
> > zigbee2mqtt@1.0.1 start /zigbee2mqtt-1.0.1
> > node index.js
>   zigbee2mqtt:info 2019-1-5 00:16:08 Logging to directory: '/share/zigbee2mqtt/log/2019-01-05.00-16-08'
>   zigbee2mqtt:info 2019-1-5 00:16:10 Starting zigbee2mqtt version 1.0.1 (commit #unknown)
>   zigbee2mqtt:info 2019-1-5 00:16:10 Starting zigbee-shepherd
>   zigbee2mqtt:info 2019-1-5 00:16:10 zigbee-shepherd started
>   zigbee2mqtt:info 2019-1-5 00:16:10 Coordinator firmware version: '20181024'
>   zigbee2mqtt:info 2019-1-5 00:16:10 Currently 0 devices are joined:
>   zigbee2mqtt:info 2019-1-5 00:16:10 Zigbee: disabling joining new devices.
>   zigbee2mqtt:info 2019-1-5 00:16:10 Connecting to MQTT server at mqtt://homeassistant
>   zigbee2mqtt:info 2019-1-5 00:16:11 zigbee-shepherd ready
>   zigbee2mqtt:info 2019-1-5 00:16:11 Connected to MQTT server
>   zigbee2mqtt:info 2019-1-5 00:16:11 MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'

**Comment by Iv4nS** [comment]
Nice! Glad it works now. Maybe deleting the file did it, permission issue or something similar.

**Comment by nightcat91** [comment]
yeah I guess deleting the config file fixed it...

thanks!!

**Comment by Iv4nS** [comment]
You are welcome! Have fun!

**Comment by krishuang92** [comment]
By remove the empty /share/zigbee2mqtt/configuration.yaml, I successfully start the zigbee2mqtt and see the bridge online, pair a Aqara 2-rocker wall switch for temporary testing.
Now I can move on and start planing to migrate all my Aqara devices into Home Assistant.
Thank you.
