### ISSUE TITLE
initial_state: 'on' is required in configuration example

### ISSUE THREAD

**Issue by bartn** [danielwelch/hassio-zigbee2mqtt#84]
In a recent update Home Assistant requires every automation to have declared the initial state. When one follows the example integration for Home Assistant the `initial_state: 'on'` tags are missing the automations to _allow pairing_

**Comment by danielwelch** [comment]
Thanks for the comment. Can you reference the version that requires `initial_state` to be declared? I'm on version 0.84.6, don't have that requirement (my automations work just fine), and don't see any mention of this in the 0.85 release notes. According to the docs, if `initial_state` isn't defined, the automation will resume whatever state it had prior to shut down (on or off).

**Comment by bartn** [comment]
Hi Daniel, you might be right there. However I figured that they (most of my automation) didn't launch, so I've added the initial_state. Now I read the following: 

> If you don’t set this the previous state is restored. If you shut Home Assistant down before it finishes starting, the automation will be stored as being off, and your automations will be disabled at the next startup.

[Source](https://www.home-assistant.io/docs/automation/)
So probably it should go right in most cases, and I must have experience a improper shut down...

**Comment by danielwelch** [comment]
I’ll go ahead and close this if that’s ok.
