### ISSUE TITLE
remove device

### ISSUE THREAD

**Issue by justinw78** [danielwelch/hassio-zigbee2mqtt#87]
Good day,

First of all, thank you very much for this beautiful addon. I have a question about removing a device.
Can this also directly in hassio?
I tried something but unfortunately I'm doing something wrong probably? (see 

> attachment)

Greetings justin
![untitled](https://user-images.githubusercontent.com/8213938/51493099-6bb73b80-1db4-11e9-8b64-315f48a8a8d6.png)

**Comment by wimpie007** [comment]
![image](https://user-images.githubusercontent.com/33153228/55882241-778cef80-5ba4-11e9-957c-258b329dcc30.png)
