### ISSUE TITLE
[Release] update to 1.1.0 :)

### ISSUE THREAD

**Issue by SamJongenelen** [danielwelch/hassio-zigbee2mqtt#91]
Fresh update on the project: https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.1.0

It's only been released a couple of hours, but can't wait to get started with it :)

**Comment by SamJongenelen** [comment]
I suppose its just updating the dockerfile hassio-zigbee2mqtt/zigbee2mqtt/Dockerfile but I'm not sure you'd want it in the _edge_ version first

**Comment by d1slact0r** [comment]
Not really usefull to open an issue for this, rather open a PR like so: https://github.com/danielwelch/hassio-zigbee2mqtt/pull/92
and edge is the dev branch and not bound to any releases.

**Comment by danielwelch** [comment]
An issue is helpful just to bring it to my attention, although I do get alerts for new releases on the project as well. Thanks for reporting and for the PR, will look to have it available later today.

**Comment by d1slact0r** [comment]
let me know if anything needs changing, i am free today from work.

**Comment by danielwelch** [comment]
Just pushed v1.1.0 and images are being built now.
