### ISSUE TITLE
startup state

### ISSUE THREAD

**Issue by tonnie84** [danielwelch/hassio-zigbee2mqtt#93]
Hi is just installed the addon zigbee2mqtt and it works fine. Thanks for that!
I only noticed when i restart hassio that the state of my xiaomi door sensors are wrong. Is there a way to check the startup state?

all doorsensors are closed on startup even when they are open. When used they will switch to the right state and after one use the keep up-to-date. But its a little bit annoying when its not the right state at startup. With the Xiaomi Gateway this was no problem.

I hope its just a setting  many thanks

**Comment by Hertizch** [comment]
Same issue here. I flashed my coordinator to the latest version, and repaired all devices to add network_key. I need to restart zigbee2mqtt after a ha reboot to get the states working. Everything worked instantly before.

**Comment by skawt-tee** [comment]
What are you using for your MQTT broker? I had something similar - I'm using the Mosquito add-on, combined with the Integration. I'm pretty new to MQTT so I can't say I know exactly what is going on, but from my limited understanding, the combination of Mosquito & HA's integration isn't properly setting the birth and last will messages. 

I fixed this by adding the following to my main configuration.yaml (not z2m's config.yaml). My understanding is that this shouldn't be needed, but it does seem to work:

mqtt:
  broker: [HA IP]:1883 # IP of your HA if using the Mosquito add-on`
  username: [redacted]
  password: [redacted]
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    retain: true

* first post here and I have zero clue how to format the above properly. Look up the mqtt HA docs and crib the indentation from there. Big thing is the 'birth' and 'will' messages with the retain: true.

**Comment by imathijs** [comment]
@skawt-tee Thank you so much. I was struggling to get zigbee2mqtt working with Hass.io mosquitto addon for 3 days. I was wondering why was my bridge state sensor was giving me "Unavailable" state.
But setting up the mqtt birth_message and will_message in configuration.yaml did fix it. I'm so happy now.
