### ISSUE TITLE
Not starting since 1.1.0

### ISSUE THREAD

**Issue by noxhirsch** [danielwelch/hassio-zigbee2mqtt#94]
Hi,
since the update to version 1.1.0 the addon doesn't start any more. If I press "start" the button immediately blinks red. It seems like it doesn't accept the config anymore. Even if I reset it to defaults and try to safe it says: 

>not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'homeassistant': True, 'permit_join': False, 'mqtt_base_topic': 'zigbee2mqtt', 'mqtt_server': 'mqtt://homeassistant', 'serial_port': '/dev/ttyACM0', 'devices': []}

I checked the docs, but I can't find a solution for this. Did I miss something or is there a bug?
The log stays empty, because the addon doesn't even try to start.

Regards
Nico

**Comment by colonelflagg** [comment]
Nico,

I just found the same thing.

The config requires a "network_key". It will start if added to the config

But...I think you then have to re-pair everything....

**Comment by danielwelch** [comment]
Thanks for reporting, see https://github.com/danielwelch/hassio-zigbee2mqtt/issues/95
