### ISSUE TITLE
Zigbee2mqtt 1.1.0 new version not starting - requires "network_key"

### ISSUE THREAD

**Issue by colonelflagg** [danielwelch/hassio-zigbee2mqtt#95]
After updating via HASSIo today to zigbee2mqtt , the addon will not start.

It appears it now requires a compulsory "network_key": option in the config file.

It won't compile or start without this.

I did not have a "network_key" before the upgrade and don't really want to add it in as I will have to re-pair my 20 odd devices.

thanks again for a great addon !

**Comment by danielwelch** [comment]
thanks for reporting! This is a quirk of how Hass.io deals with nested configuration (kind of in the same way as the devices field is required to be an empty list). So it's required that the config include an empty list. I didn't think that would be an issue for zigbee2mqtt, but as I think about it more, maybe I'm wrongly assuming that zigbee2mqtt will just "ignore" an empty list. I'll add a check to the add-on code to prevent an empty list from being written for network key.

As a sidenote, if anyone knows a way to make these nested configs altogether optional (i.e., no entry rather than an empty list entry), please let me know.

**Comment by danielwelch** [comment]
As a workaround, you can start the add-on safely due to my incompetence, because I forgot to update the `set_config.py` script to even include network key. So it won't be passed to zigbee2mqtt anyway until I push a fix.

**Comment by colonelflagg** [comment]
The docs show 
"network_key": [7, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 11, 12, 13],
What would I add to the config as a Network key that won't break my device pairing ?

**Comment by danielwelch** [comment]
I've pushed [an update](https://github.com/danielwelch/hassio-zigbee2mqtt/releases/tag/v1.1.0.1) that fixes this. You can leave `"network_key": []` in your Hass.io frontend configuration, and the network_key field will not be added to your zigbee2mqtt configuration.

**Comment by colonelflagg** [comment]
Back up again !!

Thanks for your work :)

**Comment by noxhirsch** [comment]
@danielwelch 
I'm getting this error now:
```  zigbee2mqtt:info 2019-1-31 06:14:03 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
/zigbee2mqtt-1.1.0/node_modules/q/q.js:155
                throw e;
                ^
TypeError: Cannot read property 'close' of undefined
    at shepherd.start (/zigbee2mqtt-1.1.0/lib/zigbee.js:45:47)
    at /zigbee2mqtt-1.1.0/node_modules/q/q.js:2059:17
    at runSingle (/zigbee2mqtt-1.1.0/node_modules/q/q.js:137:13)
    at flush (/zigbee2mqtt-1.1.0/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)```

**Comment by StyxyDog** [comment]
> @danielwelch
> I'm getting this error now:
> 
> ```
> zigbee2mqtt:info 2019-1-31 06:14:03 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
> /zigbee2mqtt-1.1.0/node_modules/q/q.js:155
>                 throw e;
>                 ^
> TypeError: Cannot read property 'close' of undefined
>     at shepherd.start (/zigbee2mqtt-1.1.0/lib/zigbee.js:45:47)
>     at /zigbee2mqtt-1.1.0/node_modules/q/q.js:2059:17
>     at runSingle (/zigbee2mqtt-1.1.0/node_modules/q/q.js:137:13)
>     at flush (/zigbee2mqtt-1.1.0/node_modules/q/q.js:125:13)
>     at _combinedTickCallback (internal/process/next_tick.js:132:7)
>     at process._tickCallback (internal/process/next_tick.js:181:9)```
> ```

Hi, I'm getting this same error. After updating to 1.1.0 and adding "network_key": [] the addon-started without errors, however non of my devices were actually working in HA. Following a reboot I get the error as mentioned by @noxhirsch  when trying to start the add-on.
Not sure how to force an update to 1.1.0.1, if that would help.

**Comment by StyxyDog** [comment]
A complete shutdown and power off seems to have sorted it! Sorry to trouble you. :)

**Comment by hawaltie** [comment]
> A complete shutdown and power off seems to have sorted it! Sorry to trouble you. :)

For me this didn't work either
