### ISSUE TITLE
Issue after updating to 1.1.0: not a valid value for dictionary value @ data['options']. 

### ISSUE THREAD

**Issue by quantummobile** [danielwelch/hassio-zigbee2mqtt#96]
Hi Daniel,

v. 1.1.0 has an issue - after update add does not start and configuration can't  be saved.
Error shown:
not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'homeassistant': True, 'permit_join': False, 'mqtt_base_topic': 'zigbee2mqtt', 'mqtt_server': 'mqtt://homeassistant', 'serial_port': '/dev/ttyACM0', 'devices': []}

![screenshot 2019-01-31 at 13 12 58](https://user-images.githubusercontent.com/47085307/52052546-7796c080-255f-11e9-9303-d19291237916.png)

**Comment by danielwelch** [comment]
Try setting `"network_key": []` as described in https://github.com/danielwelch/hassio-zigbee2mqtt/issues/95. If that is the problem, upgrading to v1.1.0.1 will also solve the issue.

**Comment by quantummobile** [comment]
Upgraded to v 1.1.0.1 - all back to normal. 
Thanks!
