### ISSUE TITLE
Network key doesn't accept Hex values as indicated in docs

### ISSUE THREAD

**Issue by icouper** [danielwelch/hassio-zigbee2mqtt#98]
The add-on documentation for "network key" says to follow [this doc ](https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_secure_network.html) for network key usage. That doc states it can be decimal or hex values. I used the code on that page to generate a key, which ended up being hex values.

Through trial and error I found the add-on config only accepts decimal values for the network key.

Can we get clarification on the network key instructions to make this clearer or allow it to accept hex values?

**Comment by danielwelch** [comment]
Thanks for pointing this out. I’ll update the docs to make this more clear.

**Comment by danielwelch** [comment]
Done https://github.com/danielwelch/hassio-zigbee2mqtt/commit/71f09a8137f762209103aa8839e6eb9eae698e6d
